### ISSUE TITLE
Feature Request - manage dependencies

### ISSUE THREAD

**Issue by rmad17** [kennethreitz/pipenv#1]
This is one feature I desperately want. Many times after installing it becomes very difficult to find out dependencies installed by a package and they stay on. If this could be fixed it would be great.

**Comment by kennethreitz** [comment]
this would be solved

**Comment by kennethreitz** [comment]
Not a problem with pyenv — only things you explicitly install are added to `Pipfile`, and if there are sub-dependencies, they are added to `Pipfile.freeze` when `freeze` is run.
