### ISSUE TITLE
Consider using pew to activate virtual environments

### ISSUE THREAD

**Issue by ryanhiebert** [kennethreitz/pipenv#10]
I've been using it via the `pew` package, which fills roughly the same niche as virtualenvwrapper, but using the inve approach. My own experience finds it vastly superior to the script-sourcing approach. Explained simply, it starts a subshell instead of changing the current shell. That means de-activating an environment is as simple as the standard `exit` command in your shell.

https://gist.github.com/datagrok/2199506
https://github.com/berdario/pew

**Comment by kennethreitz** [comment]
Investigate pew https://github.com/berdario/pew

**Comment by kennethreitz** [comment]
i think we have all the benefits of this with the current `$ pipenv shell` command.

**Comment by kennethreitz** [comment]
i tried using pew, but `pew workon` does not work on my machine for some reason

**Comment by kennethreitz** [comment]
going to punt on this for now

**Comment by ryanhiebert** [comment]
That's cool, it's a different model, and it may not be worth the time Right Now.

I'd like to point out, for possible future reference, that the inve model doesn't require using pew, though. inve was originally designed as an `activate` replacement, that would live in the same place, but open a subshell instead. That concept can be really helpful. pew thought so, and made a virtualenvwrapper alternative built on it, and I think it works excellently.
