### ISSUE TITLE
Pipenv lock -r -d: option -d does not exist

### ISSUE THREAD

**Issue by varnion** [kennethreitz/pipenv#1006]
Can't create export a develpment requirements file (as explained [here](https://pipenv.readthedocs.io/en/latest/advanced.html#generating-a-requirements-txt))

##### Describe you environment

1. OS Type: Linux
1. Python version: Python 3.5.2
1. Pipenv version: pipenv, version 8.2.7

##### Expected result

output dev requirements;

##### Actual result

Error: no such option: -d

##### Steps to replicate

create a new folder and then, enter and then

```
pipenv install django
pipenv install django-extensions --dev

# finally

pipenv lock -r # this works
pipenv lock -rd # this don't

**Comment by nateprewitt** [comment]
@varnion this feature was added in 8.3.0. Please update your copy of pipenv.
