### ISSUE TITLE
Intelligently Warn when version is provided incorrectly

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#1010]
Message from a fan:

> I tried using pipenv and after pipenv install requests noticed it used version "*" in the pipfile. I edited that to "2.18.4" to fix it to an exact version but got an error Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies. After googling found that the exact format is supposed to be "==2.18.4".
> 
> I found pipenv because I was looking for something like npm or composer for Python, so I thought the version constraints would be similar. Maybe you can show an error when the version constrain format is wrong, or better yet, add it as an alias to the correct one?

I love this idea, and think we should implement it.

**Comment by nateprewitt** [comment]
@kennethreitz, could you clarify which approach you were leaning towards 😁? I think we can definitely warn, aliasing may be a bit murkier.

**Comment by kennethreitz** [comment]
Warning.

**Comment by techalchemy** [comment]
@nateprewitt @kennethreitz if we only find a valid version (we can parse as I am doing for pyenv right now) with no specifiers we can assume it should be a strict pin and also issue a warning, wouldn't that be the most elegant / user friendly?

**Comment by nateprewitt** [comment]
@techalchemy, the mantra we've adopted for a lot of the areas in Requests is "don't make assumptions for the user". Whenever we have, there's usually a vocal group who doesn't want the tool to behave in X way because it's not the correct assumption for use case Y.

By having a single standardized format there isn't ambiguity or additional code to guess what the user may have meant. The warning is a minimal change and guides the user in the right direction pretty quickly.

**Comment by techalchemy** [comment]
@nateprewitt That's totally valid.  I do agree with the user in question that including the specifier if you want to pin a specific version when we dont include a specifier for the wildcard case is kind of confusing though.  The change would be pretty substantial and touches a lot of moving parts so I agree a warning is easiest.

**Comment by erinxocon** [comment]
I added a warning to pip-tools if it can't try any version, to check the version number/specifier and look at PEP440 for any more information.  The warning message can probably be simplified for the end user.  That's just my initial take.

**Comment by erinxocon** [comment]
![image](https://user-images.githubusercontent.com/208567/32309947-a1451cfa-bf54-11e7-81e1-eb2245017555.png)

How it looks in the terminal.

**Comment by erinxocon** [comment]
This should be addressed in master currently.
