### ISSUE TITLE
Add flag to not load .env file and/or add command to reload .env file when inside a pipenv shell

### ISSUE THREAD

**Issue by rodxavier** [kennethreitz/pipenv#1015]
Currently, pipenv automatically reads the `.env` file when running either `pipenv run` or `pipenv shell`. It would be nice to have a way to prevent it from doing this. I know I can just do `PIPENV_DOTENV_LOCATION=.fake` but it seems a little hacky.

Moreover, when I edit the `.env` file inside a `pipenv shell`. I have to deactivate and activate the environment again for the changes to take place.

**Environment**
1. OS Type: OSX
2. Python version: 3.6.2
3. Pipenv version: 8.3.1

**Expected Result**
It would be nice to have a flag to make pipenv not automatically load the `.env` file. Also, it would be helpful to have a command to reload the `.env` file.

**Comment by nateprewitt** [comment]
@rodxavier, have you tried using PIPENV_DONT_LOAD_ENV? That should work for your use case.

**Comment by rodxavier** [comment]
@nateprewitt Thanks for replying. Yeah, I have tried using it but it seems a bit hacky.

**Comment by nateprewitt** [comment]
@rodxavier, in what way? By flag are you asking for an option to pass? If we added an option for every possible combination of environment settings we'd have a pretty unmanageable API.

**Comment by rodxavier** [comment]
@nateprewitt Sorry about that. I haven't tried that option and that seem to solve my issue. Is it mentioned somewhere in the docs?

**Comment by nateprewitt** [comment]
@rodxavier it *should* be under "Automatic Loading of .env" in the advanced section, but it's currently not.

This would be a good first PR for anyone looking 😉

**Comment by rodxavier** [comment]
@nateprewitt Thanks. I'm keen to add it in.
