### ISSUE TITLE
cannot import geopy in jupyter notebook after using pipenv in project repo

### ISSUE THREAD

**Issue by jillianhade** [kennethreitz/pipenv#1016]
I am using pipenv to create my virtual env within my project repo and then installing the packages I am using. I am having problems importing `geopy` from within jupyter notebook after installing it using pipenv. Using `pipenv graph` confirms that geopy is indeed installed, but then after opening a jupyter notebook from within the `pipenv shell` I get `ImportError: No module named geopy` when trying to import geopy. I was able to get it working by specifying the version of geopy to install. Now I am having the problem with `haversine` even though I tried doing what I did for geopy and I added a specific version to install.
-- | --

##### Describe your environment

1. macOS Sierra 10.12.5
1. python version: 2.7.13
1. Pipenv version: 8.2.7

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by techalchemy** [comment]
@jillianhade I have never used a jupyter notebook and I don't know how you open one, but I'm guessing you are opening the notebook with a system executable and not with an executable that is installed in your virtualenv. Can you please provide the following:

1. All of the commands you entered and their output
2. The contents of your `Pipfile`
2. Exit from the pipenv shell, then run `python --version && pipenv --version && pip --version && which python && which pip && which pipenv && env` and provide the output
3. After running `pipenv shell`, run the same commands as above and provide the output

**Comment by jillianhade** [comment]
Commands entered:
from within repo dir:
`pipenv install`
```Requirements.txt found, instead of Pipfile! Converting…
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches certifi==2015.4.28,>=2017.4.17
Tried: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 1.0.0, 1.0.1, 1.0.1, 14.5.14, 2015.4.28, 2015.4.28, 2015.9.6, 2015.9.6, 2015.9.6.1, 2015.9.6.1, 2015.9.6.2, 2015.9.6.2, 2015.11.20, 2015.11.20, 2015.11.20.1, 2015.11.20.1, 2016.2.28, 2016.2.28, 2016.8.2, 2016.8.2, 2016.8.8, 2016.8.8, 2016.8.31, 2016.8.31, 2016.9.26, 2016.9.26, 2017.1.23, 2017.1.23, 2017.4.17, 2017.4.17, 2017.7.27, 2017.7.27, 2017.7.27.1, 2017.7.27.1
```

`pipenv install --skip-lock` (because it cannot find the version of certifi that I specified)
```Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:07
To activate this project's virtualenv, run the following:
 $ pipenv shell```

`pipenv graph`
```creds==1.0.15
geolocation-python==0.2.2
  - requests [required: Any, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - setuptools [required: Any, installed: 36.6.0]
geopy==1.11.0
googlemaps==2.5.1
  - requests [required: <3.0,>=2.11.1, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
haversine==0.4.5
multiprocessing==2.6.2.1
progress==1.3
tqdm==4.11.2```

`pipenv shell`
`jupyter notebook`

Contents of `Pipfile`:
```[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]

certifi = "==2015.4.28"
creds = "*"
googlemaps = "*"
geolocation-python = "*"
geopy = "==1.11.0"
haversine = "==0.4.5"
multiprocessing = "==2.6.2.1"
numpy = "==1.12.1"
pandas = "==0.19.2"
progress = "==1.3"
requests = "*"
SQLAlchemy = "==1.0.6"
tqdm = "==4.11.2"
Versions in bash:
`python 2.7.13`
`pipenv 8.2.7`
`pip 9.0.1`
output for which:
python
`/usr/local/bin/python`
pipenv
/usr/local/bin/pipenv
pip
/usr/local/bin/pip```

Versions in `pipenv shell`
`python 2.7.13`
`pipenv 8.2.7`
`pip 9.0.1`

**Comment by techalchemy** [comment]
@jillianhade Thanks for providing that info with a quick turnaround! It looks like you aren't installing `jupyter` in your virtualenv.  We aren't setting `PYTHON_PATH` in the subshell or anything like that, so you will have to just include jupyter in your `Pipfile`, run `pipenv install` again, and then jump down into the shell and see if it works.

**Comment by jillianhade** [comment]
@techalchemy You were right! I needed to install jupyter inside of the virtualenv. Thanks so much for the help! 👍  🐍

**Comment by techalchemy** [comment]
Glad it helped!
