### ISSUE TITLE
Installing a local package with `pipenv install '-e .'` doesn't save dependencies

### ISSUE THREAD

**Issue by macbeth322** [kennethreitz/pipenv#1024]
##### Describe your environment

1. Linux
1. Python version: 3.4
1. Pipenv version: 8.2.7

##### Expected result

Installing a local package with `pipenv install '-e .'` should install the local package then install its dependencies, then save all of that in the Pipfile and Pipfile.lock.

##### Actual result

The first install command `pipfile install '-e .'` correctly installs all expected packages and saves the expected results into Pipfile, but the Pipfile.lock only contains the local package and non of its dependencies.

##### Steps to replicate

```
$ pipenv --three
Creating a virtualenv for this project…
Using /path/to/python/bin/python3 to create virtualenv…
⠋Already using interpreter /path/to/python/bin/python3
Using base prefix '/path/to/python'
New python executable in /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D/bin/python3
Also creating executable in /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D
Creating a Pipfile for this project…
chris $ pipenv install '-e .'
Installing -e .…
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒Obtaining file:///home/chris/demos/pipenv-local-lock-bug
Collecting Flask (from foobar==1.0.0)
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting click>=2.0 (from Flask->foobar==1.0.0)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask->foobar==1.0.0)
Collecting Jinja2>=2.4 (from Flask->foobar==1.0.0)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from Flask->foobar==1.0.0)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask->foobar==1.0.0)
Installing collected packages: click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, Flask, foobar
  Running setup.py develop for foobar
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 click-6.7 foobar itsdangerous-0.24

Adding -e . to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (e45bed)!
chris $ pipenv run pip freeze
click==6.7
Flask==0.12.2
foobar==1.0.0
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
Werkzeug==0.12.2
chris $ pipenv --three
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using /path/to/python/bin/python3 to create virtualenv…
⠋  Already using interpreter /path/to/python/bin/python3
Using base prefix '/path/to/python'
New python executable in /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D/bin/python3
Also creating executable in /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/chris/.local/share/virtualenvs/pipenv-local-lock-bug-l-tO7M9D
chris $ pipenv install
Installing dependencies from Pipfile.lock (e45bed)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:01
To activate this project's virtualenv, run the following:
 $ pipenv shell
chris $ pipenv run pip freeze
foobar==1.0.0
chris $ pipenv lock --verbose --clear
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Updated Pipfile.lock (e45bed)!
```

**Comment by macbeth322** [comment]
Relevant Files

Pipfile
```
[[source]]

verify_ssl = true
url = "https://pypi.python.org/simple"
name = "pypi"


[dev-packages]



[requires]

python_version = "3.4"


[packages]

"e1839a8" = {path = ".", editable = true}
```

Pipfile.lock
```
{
    "_meta": {
        "hash": {
            "sha256": "ab499050fd277d2e6eb0a8dc5a743672c2b43a1be18fe764bf1152d864e45bed"
        },
        "host-environment-markers": "REDACTED",
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.4"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "e1839a8": {
            "editable": true,
            "path": "."
        }
    },
    "develop": {}
}
```

setup.py
```
from setuptools import setup, find_packages

setup(
    name='foobar',
    version='1.0.0',
    author='macbeth322',
    package_dir={'': 'src'},
    packages=find_packages('src'),
    install_requires=[
        'Flask',
    ],
)
```

**Comment by techalchemy** [comment]
@macbeth322 I can see why you would expect this to work, but it's a bit more nuanced than it might look at first.  `Pipenv` does not parse requrements from `setup.py` and it doesn't traverse the installation requirements that `setuptools` calculates, which are determined completely independently of pip.  It can tell you, after they are installed, which ones exist, but it can't do any kind of dependency resolving.

>  should install the local package then install its dependencies, then save all of that in the Pipfile

This wouldn't really be possible since we only even know to install the local directory because it is in the `Pipfile`.  The point of a pipfile is to hold your top level dependencies, and let `pipenv` resolve the subdependencies when it installs and updates the top level ones.  In order for `pipenv` to be able to traverse a dependency graph, however, it has to be in a `requirements,txt`, `Pipfile`, or parseable by `pip` or `piptools` or available on pypi.  This functionality doesn't exist in `pip` or `pip-tools` so I don't really foresee us building it into `pipenv` in the near future, unfortunately.

Thanks for the report, and sorry this isn't behaving the way you want.  Believe me, I also wish we could capture these dependencies with ease and consistency :)

**Comment by macbeth322** [comment]
Thanks for the response @techalchemy, but I'm hoping you can give some more insight into the specific feature that is missing from `pip` that is preventing `pipenv` from working as I expected.

1. `pipenv install '-e .'` installs the dependencies, so something is looking at the `setup.py` at some point for its dependencies.
2. `pipenv run pip show foobar` shows `Flask` as a dependency so `pip` is able to understand that Flask` is a dependency of `foobar` even after install time
```
$ pip show foobar
Name: foobar
Version: 1.0.0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: macbeth322
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/chris/demos/pipenv-local-lock-bug/src
Requires: Flask
```

**Comment by vphilippon** [comment]
@techalchemy I'm a bit surprised here too. From `pip-tools` side, `Flask` would be added to the requirements.txt. There's no issue with getting the dependencies of "-e .".

I can't do much more right now (on my phone, far away from my computer), but I don't see why this wouldn't work.
You can compare with:
requirements.in
```
-e .
```
`pip-compile -v --rebuild`

Tell me if I've missed something.

**Comment by macbeth322** [comment]
I updated to pipenv==11.8.3 and this issue seems to have been fixed. I am able to install a local package and have its dependencies locked in Pipfile.lock and I am able to install from Pipfile.lock.

**Comment by techalchemy** [comment]
@macbeth322 thanks for the update! We've been working quite hard on a lot of this stuff, so thanks for your patience :)
