### ISSUE TITLE
pipenv is using system python instead of brew python

### ISSUE THREAD

**Issue by LW81** [kennethreitz/pipenv#1029]
Hi,

on my Mac i have installed python 2 using brew.
This has created a binary called python2 in /usr/local/bin.

I have now also installed pipenv using

`brew install pipenv`

When i now create a project like mentioned in the docs using:

`pipenv install requests`

I see the following output:

`
Creating a virtualenv for this project…
⠋Using real prefix /System/Library/Frameworks/Python.framework/Versions/2.7
`

So my virtualenv is created using the System Python instead of my brew python.
What do i need to do to change that ?

Many thx in advance !

**Comment by erinxocon** [comment]
Hi @LW81!  This could be due to the order of python executables found in your path.  Can you echo that out here?

**Comment by richardcooper** [comment]
Homebrew installed pipenv runs on system Python† to avoid having a dependency on homebrew's python or python3. If you don't explicitly tell pipenv which version of python to use in the virtualenv then it will use the same version that it is running on, i.e. system Python.

There are a few options for changing which version of Python in used in the virtualenv:
- `pipenv --two` # Finds python2 on your $PATH
- `pipenv --three` # Finds python3 on your $PATH
- `pipenv --python=2.7` # Finds python2.7 on your $PATH
- `pipenv --python=/usr/local/bin/python3` # Use that exact version of Python
- Set the `PIPENV_DEFAULT_PYTHON_VERSION` environment variable. e.g `PIPENV_DEFAULT_PYTHON_VERSION=3.6`

 † On any macOS >= 10.7

**Comment by LW81** [comment]
Awesome, thx @richardcooper  !

This works exactly as you described !

**Comment by erinxocon** [comment]
Thanks for the explanation @richardcooper!
