### ISSUE TITLE
Comments are dropped when installing new packages

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#1033]
I use comments in the `Pipfile` to help group and document related packages, but they are lost when installing new packages.

##### Describe your environment

pipenv 8.3.2

##### Expected result

New package is added to `Pipfile` at the bottom (or top) of the `[packages]` section, but the rest of the file is unchanged.

##### Actual result

The whole `Pipfile` is rewritten, dropping all my comments, whitespace, and ordering.

##### Steps to replicate

1. Copy this `Pipfile`: https://github.com/jacebrowning/template-django-demo/blob/fd4fb87ddb92601f435e333ae2e246b8af7462ef/Pipfile
2. `$ pipenv install django-export-action`

**Comment by techalchemy** [comment]
Hmm I thought we changed our entire approach to toml parsing in order to preserve comments in pipfiles

**Comment by kennethreitz** [comment]
yeah that's not how it works

**Comment by kennethreitz** [comment]
sorry for the issue, it works sometimes, other times it doesn't. we are doing our best.

**Comment by jacebrowning** [comment]
I'm not sure I understand this response. With pipenv 8.3.2, installing any package seems to drop all the comments. In which cases are comments maintained?

**Comment by kennethreitz** [comment]
it’s not going to get better than it is

**Comment by kennethreitz** [comment]
e.g TOML libraries are are partial and horrible
