### ISSUE TITLE
Alpine Linux Support

### ISSUE THREAD

**Issue by brunoalano** [kennethreitz/pipenv#104]
I'm using the `pipenv` in Docker (base: python:3.5-alpine), but when I try to use the `pipenv shell`, it gives:

"Windows is not currently supported."

Activating manually using `source .venv/bin/activate` works.

**Comment by nateprewitt** [comment]
@brunoalano would you be able to provide the value of $SHELL in your terminal on the docker instance?

This error occurs when we aren't able to find a "SHELL" variable in the os.environ dictionary.

**Comment by brunoalano** [comment]
It's empty. Should I set it as `bash`?

**Comment by brunoalano** [comment]
Setting it for `/bin/ash`, works. Thanks

**Comment by nateprewitt** [comment]
Happy to help! I'll look into making the exception message a little more informative. 

Feel free to reopen this is you find you're still having trouble.
