### ISSUE TITLE
Dead on delivery: unknown locale

### ISSUE THREAD

**Issue by wvxvw** [kennethreitz/pipenv#1044]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

```
$ uname -a
Linux linux-il-wvxvw 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release 
No LSB modules are available.
```
(it's Ubuntu 17)
```
$ dpkg -s python3-pip | grep Version:
Version: 9.0.1-2
```
```
$ python --version
Python 2.7.13
```
```
$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

After setting locale to en_US.UTF-8, I can also run this:
```
$ pipenv --version
pipenv, version 8.3.2
```

##### Expected result

`pipenv` runs using whatever locale it wants.

##### Actual result
```
$ pipenv --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.5/dist-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.5/dist-packages/pew/pew.py", line 42, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.5/dist-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_IL

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1728, in cli
    ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 630, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 334, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 388, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```

##### Steps to replicate
Set your locale to something `pipenv` doesn't recognize, for example:

```
export LANG=en_IL
```
then run any command.

**Comment by techalchemy** [comment]
Hi @Germione thanks for the report, sorry about the issue! I think this might relate to not having a Unicode specifier on your locale. If you run `locale -a`is there an `en_IL.UTF-8`? If so, does that work?

**Comment by wvxvw** [comment]
@techalchemy well, this is what this ticket is about... Of course virtually everything else written in Python works with this locale (I've been working with several Python projects on this machine for at least two months with these same settings).

Of course (as I already pointed out), I can change my environment to match `pipenv' requirements, but... what if I don't want to / cannot do it?

**Comment by techalchemy** [comment]
@wvxvw that wasn’t what I asked though, I just asked if you can add .UTF-8 to the locale you’re using. Pipenv is a command line application written in python 3 and it (unlike most day to day python software) requires you to configure your shell properly to support Unicode. If you don’t want to do that I’m not really sure what your options are... I’m not asking you to change your locale, I don’t know of any reason why you wouldn’t configure your shell with a locale that is UTF-8?

**Comment by joshfriend** [comment]
I'll leave my 2cents here since you also opened this issue against pyenv initially.

python 3.5 is not recognizing your locale, they have a list that they keep in sync with a specific version of glibc: https://github.com/python/cpython/blob/28ab3ce92402d86aa400960d38f0d69f498bb677/Lib/locale.py#L844

It was updated very recently to glibc 2.18, but that is still not the highest version. You could open a bug on python's tracker to ask for another update **HOWEVER** this will only help with new python versions (e.g. 3.7.0 when it comes out). I'd suggest setting `LC_ALL="en_US.utf8"` in your environment, or a similar (and compatible) locale.

If you look closely at the stacktrace, you will see that the error comes from `pew`:

```python
...
  File "/usr/local/lib/python3.5/dist-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_IL
```

their `_utils` module assumes incorrectly that `locale.getlocale()` will return `None` if your locale is not recognized, instead, it throws `ValueError`.

**Comment by techalchemy** [comment]
@joshfriend thanks for digging into that and clearing it up! @wvxvw unfortunately we can't do much about locales that are not supported by pyenv, python, or glibc.  Digging into this it seems like glibc only added the locale in version 2.24, see here: https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=146ffc146fe3bf97cd3bc1a649f1ffa8acfa4a0d

So unfortunately this fairly new locale isn't compatible.  I'm sympathetic to the frustration this must cause but I don't think there's much we can do here.  You can raise an issue with pyenv to properly handle `getlocale()` in the interim, but other than that I am going to go ahead and close this for now.  Sorry we can't be of more help!

**Comment by joshfriend** [comment]
The development branch for python 3.7 was just updated to glibc 2.18 (which is from 2013) a month ago, who knows how long it will take to get up to 2.24!

**Comment by wvxvw** [comment]
OK guys... you don't understand what this ticket is about. Should I file a new one, or will you re-read the description?

I'll rephrase, with some more explanation.

Whatever the value of `LANG` environment variable is **you should not fail!**.  At most, give a warning about the output of your program may be not readable to the user.  Understand that the value of this variable is advisory **only**.  So, how does it work?  Suppose your program can only output UTF-16 and ASCII in Latin1 but the user asked you for UTF-8 by setting this variable to `C.UTF-8`.  What do you do then?  You send a warning message to `stderr` saying something to the effect of "We apologize for not being able to conform to your locale specification, and will print our output assuming you can reinterpet Latin1, you can also force the output to be printed using UTF-16 encoding by providing this command-line option..."

Under no circumstance you should fail if you cannot find an exact match to user's locale!  The locale is there to inform a program about the user's choice, but it's understood that it's not possible to satisfy it precisely all the time.  In fact, if you ever had to deal with i18n, you'd know that there are rules and logistics about how to suggest from available locales to match the desired locale.

**Comment by nateprewitt** [comment]
@wvxvw, let's take a step back and review the thread.

You made a couple hyperbolic statements about "virtually everything" in Python working fine with your locale, and the others have taken the time to explain why that statement isn't true.

This is failure in the standard library from a call in a third party library that happens at import time. None of this is our code other than the import line. The fix really needs to be raised in the pew repository.

In the meantime, the best we can do is wrap the import of pew in a try/except and print a prettier message. The exception is pretty clear though and passing a default locale message for *any* ValueError raised here is likely to mask other issues.

**Comment by robinwo** [comment]
Same issue here.

**Comment by wvxvw** [comment]
As I had to return here one more time, why don't I spend some more time trying to explain this issue.  I don't use `pipenv` anymore, but it still may be useful to others.

So, here we go.

1. `LOCALE` environment variable means not what you think it means.  It tells you what the user's preference is.  It doesn't mean that if you cannot satisfy that preference exactly, you should give up on doing any work at all.  Furthermore, it tells you absolutely nothing about the actual encoding used by the shell in which the program is invoked, or the encoding used by another program which, say, pipes its output into your program's input.  Whatever it is set to should be at best taken as a hint, not as a mandatory requirement.

2. Python 3 has no real problems running in locales other than some UTF-8.  The problem is in the way it interprets what it reads from `stdin`.  Well, it was a bad decision by the Python core dev team to automatically treat that as if it was UTF-8, and so you need to use some strong magic to treat `stdin` correctly, as a stream of bytes (not impossible, just unnecessarily hard).  Furthermore, even if Python interpreter decided to treat input as UTF-8 encoded, there is a way to deal with bytes that don't translate into UTF-8 (remember those question marks inside rhombus? - that's the right way to do it). 

3. An alleged virtualization tool should minimize its dependencies on external factors, be as forgiving as possible to the external world, while creating sanitized environment for the programs that run in this virtual environment.  You did the opposite: you require from me, to create a virtual environment for you.  What's the point then for me to use your program, if I am already forced to do your work for you?

**Comment by nateprewitt** [comment]
Hey again @wvxvw, thanks for taking the time to reiterate your thoughts. We don’t have any major disagreements on what you’ve said. There is no good reason a user should have to muck with their `LOCALE` variable.

As said above though, we have very little we can do in pipenv itself other than rewriting `pew`, a third party library we do not own, in its entirety. That’s a significant amount of work that we’ve previously lacked the resources to do. Portions of the pew library are currently being rewritten and this may eventually get better. However, this is people’s free time doing a service to the community. We all have normal jobs and can’t give these projects we maintain all of our remaining time.

Hopefully we’ll be in a better state soon, but until that time comes, these are the constraints we are stuck with.
