### ISSUE TITLE
pipenv using wrong pip

### ISSUE THREAD

**Issue by hawkeyej** [kennethreitz/pipenv#1051]
pipenv is creating the environment using the old pip from /usr/bin instead of the newer pip from /usr/local/bin

##### Describe your environment

OS: Amazon Linux
Python: Python 2.7.12
pipenv: pipenv, version 8.3.2

##### Expected result

Expected pip 9.0.1

##### Actual result

Got pip 6.0.8

##### Steps to replicate

pipenv --python 2.7

**Comment by techalchemy** [comment]
You should configure your path so that the right one is first

**Comment by hawkeyej** [comment]
The path DOES have the right pip first in the path.

**Comment by hawkeyej** [comment]
/usr/local/bin
/bin
/usr/bin
/usr/local/sbin
/usr/sbin
/sbin

**Comment by techalchemy** [comment]
Please provide the output of the following:

`pip2 --version && python2 --version && which pip2 && which python2`

**Comment by hawkeyej** [comment]
```
sh-4.2$ pip2 --version && python2 --version && which pip2 && which python2
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
Python 2.6.9
/usr/local/bin/pip2
/usr/bin/python2
```

One problem with this test is that python2 is the wrong python
```
sh-4.2$ python -V && which python && pipenv run python -V
Python 2.7.12
/usr/bin/python
Python 2.7.12
```
So pipenv is using the correct python

**Comment by techalchemy** [comment]
@hawkeyej what about `python -m pip —version`?

**Comment by techalchemy** [comment]
Seems like you have done a `sudo python -m pip install —upgrade pip` while having pip installed by your distro package manager so python (and pipenv) are still preferring the original version in /usr/bin

**Comment by hawkeyej** [comment]
```
sh-4.2$ python -m pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

That is true that I have installed an upgrade to pip, but why doesn't pipenv respect the PATH environment?

It seems to me that pipenv should use the environment that it is running in (including PATH) and not just make assumptions based on specific locations.

**Comment by uranusjr** [comment]
Could this be avoided if Pipenv runs Pip with `python -m pip`, instead of `pip`? This is the most reliable way to find the right Pip AFAIK.
