### ISSUE TITLE
[proposal] reverse order of python versions when choosing an executable

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#1055]
hi all, currently when `pyenv versions` has multiple version of python 3, it deterministically chooses the lowest python version. i.e. `3.5.3` will be chosen over `3.6.3`. I think a reasonable default will be to reverse this order and use the latest version instead. when I'm not specifying the python version and just run `pipenv install` on a new project, I almost always mean to use the latest version installed.

happy to submit a PR if you think this is a good idea

thanks!

**Comment by techalchemy** [comment]
Hey, I actually noticed this recently myself when we started using the packaging version parser to eliminate prereleases, that might be a good place to put this logic (see https://github.com/kennethreitz/pipenv/pull/1000/files#diff-e1e68886e05fef92bb74ed1699e5179eR405)

I think this is a great idea and if you are willing I think a PR would be very welcome, although if there is some way to sort if we use the packaging parser that might be preferable to just reversing (?)

**Comment by kennethreitz** [comment]
@AlJohri please send a pr
