### ISSUE TITLE
pipenv shell fails using zsh: The command was not found or was not executable

### ISSUE THREAD

**Issue by bew** [kennethreitz/pipenv#1058]
Hello, I'm trying to use `pipenv shell` but I always get the error `The command was not found or was not executable: /tmp/test_pipenv/zsh`. I'm using zsh.

##### Describe your environment

1. OS Type: `Archlinux with kernel 4.13.1`
1. Python version: `Python 3.6.3`
1. Pipenv version: `8.3.2`

##### Expected result

Start a new shell with the pipenv environment.

##### Actual result

```
 /tmp/test_pipenv  % pipenv install --verbose
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /home/lesell_b/.local/share/virtualenvs/test_pipenv-th_PmQW6/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/lesell_b/.local/share/virtualenvs/test_pipenv-th_PmQW6
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (c23e27)!                                                                                                                Installing dependencies from Pipfile.lock (c23e27)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell

 /tmp/test_pipenv  % ls
Pipfile  Pipfile.lock

 /tmp/test_pipenv  % pipenv shell --verbose
Spawning environment shell (/tmp/test_pipenv/zsh). Use 'exit' to leave.
Traceback (most recent call last):
  File "/home/lesell_b/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/cli.py", line 2197, in shell
    do_shell(three=three, python=python, fancy=fancy, shell_args=shell_args)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/cli.py", line 2125, in do_shell
    terminal_dimensions.columns
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 198, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/home/lesell_b/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 271, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /tmp/test_pipenv/zsh.
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
```
$ # Using zsh
$ mkdir test_pipenv
$ cd test_pipenv
$ pipenv install
$ pipenv shell
```

**Comment by bew** [comment]
I've found my issue, I had the `SHELL` env variable to `zsh` and not `/bin/zsh`.

I always thought that was enough, and never had any issues with software using it. Maybe it would be interesting to add a note about that in the README ?

**Comment by techalchemy** [comment]
I think this just needs to be added to our list of places to properly find executables.  Thanks for reporting this, it seems like a legitimate bug -- it should work the way you had it

**Comment by nateprewitt** [comment]
@bew did you setup your zsh shell variable manually? It should be /bin/zsh out of the box and IEEE 1003.1 has the definition of the unix SHELL variable as a *pathname* to your shell.

**Comment by techalchemy** [comment]
@nateprewitt I closed the PR, closing this issue due to the reasons you stated

**Comment by bew** [comment]
Oh didn't know that (was probably a leftover from my early times with zsh)

Thank you!

**Comment by sallybananas** [comment]
Can you explain how to fix the error in detail? I too am having the issue and I'm not sure how to fix it based on what you wrote above.

**Comment by bew** [comment]
@sallybananas if you have set manually the environment variable `SHELL` in your zsh config to `zsh` (in your `~/.zshrc` or `~/.zshenv`), you should remove that line, as it should be automatically set by zsh (if ot's not for whatever reason, set `SHELL` to the full path of the zsh binary).

**Comment by sallybananas** [comment]
@bew I don't know why this is just not clicking for me. 
In my ~/.zshrc I see this-

`# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/sallybananas/.oh-my-zsh`

is this the issue? Is the export line not the correct path?
In my file, I don't see an environment variable SHELL like you mentioned.

Thanks so much for the help

**Comment by subokita** [comment]
@sallybananas 
Just add
`export SHELL=/bin/zsh`
into your .zshrc, open a new shell, and try pipenv shell again

**Comment by sjohnson540** [comment]
This still doesn't work for me. SHELL is set to `/usr/bin/zsh`, and still getting the error above.

**Comment by uranusjr** [comment]
Set `PIPENV_SHELL=/use/bin/zsh` to force it to use it.

**Comment by codethief** [comment]
I'm having the same issue as @sjohnson540 . 

@uranusjr I tried that but I'm getting:

```
$ export PIPENV_SHELL=/bin/zsh
$ pipenv shell                
Launching subshell in virtual environment…
~/.env:70: command not found: readlink # <-- .env is my dotfile where I set up environment variables like PATH and other things in a shell-independent way (which is why I'm not using `.profile` or `.zprofile`)
~/.env:87: command not found: pgrep
~/.env:90: command not found: ssh-agent
compaudit:133: command not found: getent
 . ~/.local/share/virtualenvs/myproject-oc5MXuJw/bin/activate
~/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
env_default:1: command not found: env
env_default:1: command not found: env
compaudit:133: command not found: getent

$ . ~/.local/share/virtualenvs/myproject-oc5MXuJw/bin/activate # <-- Note that this command gets executed automatically by `pipenv shell`. I.e. I didn't type this.
Command »basename« is available at »/usr/bin/basename«
The command could not be found because »/usr/bin« is not part of PATH
~/.local/share/virtualenvs/myproject-oc5MXuJw/bin/activate:61: command not found: basename
```

The thing is… my `PATH` *does* contain `/usr/bin`. It's only *after* running `pipenv shell` (despite the above errors I'm ending up in a new shell), that `/usr/bin` suddenly is not part of `PATH`, anymore. So since I seem to have set up everything correctly and it's still not working, I'm unsure what to do here…

**Comment by codethief** [comment]
Could we please reopen this?

**Comment by codethief** [comment]
So it seems the issue has been fixed somehow since the summer. I just upgraded from pipenv-2018.7.1 to pipenv-2018.11.26 and it works beautifully.

**Comment by jsrice7391** [comment]
I did the classic install and then re-install with homebrew and it worked marvelously.
```
brew uninstall pipenv
brew install pipenv
```
