### ISSUE TITLE
Package being ignored with pipenv 8.3

### ISSUE THREAD

**Issue by Djiit** [kennethreitz/pipenv#1064]
##### Describe your environment

1. OS Type **Ubuntu Xenial**
1. Python version: `$ python -V` **python 3.6.1**
1. Pipenv version: `$ pipenv --version` **pipenv, version 8.3.1**

##### Expected result

Assuming we have a pipfile containing `alembic = '*'`
The `alembic` package should be : 
* installed by the command `pipenv install`
* listed by the command `pipenv lock -r`

##### Actual result

`pipenv install` does not install `alembic`.
`pipenv lock -r --verbose` returns nothing.

##### Steps to replicate

```bash
pipenv --three
pipenv install alembic
pipenv lock -r
```

Theses steps are ok with pipenv 8.2.6 on my dev box.

**Comment by techalchemy** [comment]
@Djiit do you have a folder called 'alembic' off of your project root?

**Comment by Djiit** [comment]
Yep!

**Comment by smurail** [comment]
Same issue here, could workaround it by renaming alembic folder (and changing alembic.ini accordingly). Maybe an issue with alembic executable colliding in some way with alembic directory?

**Comment by techalchemy** [comment]
@smurail yes, it is an issue with that, which is why I asked.  It is fixed in #958 which will be out in our next release
