### ISSUE TITLE
Little problem with GitPython

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#1067]
Use case:
- install GitPython using `pipenv install GitPython`
- in `Pipfile`, the entry is set as `gitpython = "*"`

On clean environmnent, `pipenv install` is fine, but all modules that does a `import git` fails.

How to fix: simply set in `Pipfile` the entry as `GitPython = "*"`

**Comment by nateprewitt** [comment]
Thanks for opening this issue @Stibbons. This is actually fixed on master with #1034 and will be available in the next release. We'll probably try to have something out by the end of the week.

**Comment by nateprewitt** [comment]
Thanks for opening this issue @Stibbons. This is actually fixed on master with #1034 and will be available in the next release. We'll probably try to have something out by the end of the week.

**Comment by Stibbons** [comment]
@nateprewitt  I have a similar issue with "gitrepo" that does not even install and does not appear in `Pipfile.lock` even after `pipenv instal`. It should install a module named "repo". Does it needs to appear in https://github.com/kennethreitz/pipenv/blob/692387f70eccbadfa03bf278f094ef4c27524bf7/pipenv/vendor/pipreqs/mapping ?

**Comment by nateprewitt** [comment]
@Stibbons, this is fixed on our master branch and we have had to delay our release due to some breaking changes being merged. I'm working to get something out in the next few days. Thanks for your patience.

**Comment by Stibbons** [comment]
Hello. I confirm this is fixed in 9.0.1
