### ISSUE TITLE
install / uninstall API asymmetry

### ISSUE THREAD

**Issue by timofurrer** [kennethreitz/pipenv#107]
I was kind of confused that `pipenv uninstall` does not change the Pipfile at all. I'd expect that if the `pipenv uninstall requests` command removes the `requests` entry from the Pipfile then `pipenv uninstall` would do, too.

I'm aware that you might never want to remove *all* your dependencies from the Pipfile. However, a command like `pipenv clean` would be much more appropriate in my opinion to clean the environment.

I'd love to see that the `packages` argument for `pipenv uninstall` would be required and a separate `pipenv clean` command would exist.

**Comment by kennethreitz** [comment]
It should remove it from the pipfile, I will have to investigate. 

Was requests a dev dependency?

**Comment by jacebrowning** [comment]
Similarly, I was confused by [this review comment](https://github.com/kennethreitz/pipenv/pull/105#issuecomment-275490257) regarding the symmetry of `pipenv install --dev` vs. `pipenv uninstall --dev`.

Maybe the option should be divided into something like `pipenv install --include-dev` and `pip install --for-dev foobar`.

Just my two cents.

**Comment by kennethreitz** [comment]
A new release was just pushed which improves this functionality. 

https://github.com/kennethreitz/pipenv/pull/105

**Comment by timofurrer** [comment]
> It should remove it from the pipfile, I will have to investigate.

Okay, this would make sense, too.

> A new release was just pushed which improves this functionality.
>
> #105

I'm not quiet sure why you've linked #105 because it does not solve this asymmetry issue.
