### ISSUE TITLE
pipenv broken

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#1085]
![image](https://user-images.githubusercontent.com/2430381/32952777-45c9836e-cb7c-11e7-8fd0-ca42fb705b1e.png)

Occurred in 44053b52bbbda1884edd12baecbe7f3c4d251c98

could be because im on python 2 and FileNotFoundError doesnt exist? or maybe it just needs `from os import FileNotFoundError`

**Comment by henryiii** [comment]
I just got a similar error when trying to run on Python 2. I believe `FileNotFoundError` was introduced in Python 3.5 as a subclass of OSError.

**Comment by henryiii** [comment]
Another issue: `os.utime` needs a `None` second argument on Python 2.

**Comment by henryiii** [comment]
That patch fixes the problem for me on Python 2, CentOS 7.
