### ISSUE TITLE
.env file with values containing "\n" are wrongly loaded

### ISSUE THREAD

**Issue by francbartoli** [kennethreitz/pipenv#1087]
If a value of the .env file contains a new line string `\n` then the resulting variable is wrong with the value `\\n`

##### Describe your environment

1. Mac OS X 10.9
1. Python version: 2.7.13
1. Pipenv version: 8.3.2

##### Expected result

.env file
-------
PRIVATE_KEY=-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAJC1HiIAZAiIMA0GCSqGSIb3Df\nBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVx\naWRnaXRzIFB0eSBMdGQwHhcNMTExMjMxMDg1OTQ0WhcNMT\nA ....\nMANY LINES LIKE THAT ....\nJjyzfN746vaInA1KxYEeI1Rx5KXY8zIdj6a7hhphpj2E04\nC3Fayua4DRHyZOLmlvQ6tIChY0ClXXuefbmVSDeUHwc8Yu\nB7xxt8BVc69rLeHV15A0qyx77CLSj3tCx2IUXVqRs5mlSb\nvA==\n-----END CERTIFICATE-----

print os.environ['PRIVATE_KEY']
`-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAJC1HiIAZAiIMA0GCSqGSIb3Df\nBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVx\naWRnaXRzIFB0eSBMdGQwHhcNMTExMjMxMDg1OTQ0WhcNMT\nA ....\nMANY LINES LIKE THAT ....\nJjyzfN746vaInA1KxYEeI1Rx5KXY8zIdj6a7hhphpj2E04\nC3Fayua4DRHyZOLmlvQ6tIChY0ClXXuefbmVSDeUHwc8Yu\nB7xxt8BVc69rLeHV15A0qyx77CLSj3tCx2IUXVqRs5mlSb\nvA==\n-----END CERTIFICATE-----`

##### Actual result

`-----BEGIN CERTIFICATE-----\\nMIIDXTCCAkWgAwIBAgIJAJC1HiIAZAiIMA0GCSqGSIb3Df\\nBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVx\\naWRnaXRzIFB0eSBMdGQwHhcNMTExMjMxMDg1OTQ0WhcNMT\\nA ....\\nMANY LINES LIKE THAT ....\\nJjyzfN746vaInA1KxYEeI1Rx5KXY8zIdj6a7hhphpj2E04\\nC3Fayua4DRHyZOLmlvQ6tIChY0ClXXuefbmVSDeUHwc8Yu\\nB7xxt8BVc69rLeHV15A0qyx77CLSj3tCx2IUXVqRs5mlSb\\nvA==\\n-----END CERTIFICATE-----`

##### Steps to replicate

Simply print the value after setting it into an .env file

**Comment by techalchemy** [comment]
in what sense is this wrong exactly This is exactly what I would expect...

**Comment by francbartoli** [comment]
Sorry wrong copy and paste, I did not realize. Now it should be evident the double slash `\\n`

**Comment by techalchemy** [comment]
Special characters are escaped when loaded.  Wrap the string in double quotes

**Comment by francbartoli** [comment]
ok thanks @techalchemy

**Comment by francbartoli** [comment]
Set double quotes as below doesn't solve the issue:

`PRIVATE_KEY="-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAJC1HiIAZAiIMA0GCSqGSIb3Df\nBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVx\naWRnaXRzIFB0eSBMdGQwHhcNMTExMjMxMDg1OTQ0WhcNMT\nA ....\nMANY LINES LIKE THAT ....\nJjyzfN746vaInA1KxYEeI1Rx5KXY8zIdj6a7hhphpj2E04\nC3Fayua4DRHyZOLmlvQ6tIChY0ClXXuefbmVSDeUHwc8Yu\nB7xxt8BVc69rLeHV15A0qyx77CLSj3tCx2IUXVqRs5mlSb\nvA==\n-----END CERTIFICATE-----"`

**Comment by erinxocon** [comment]
@francbartoli I believe I fixed this.  Barring any issues with my fix, it should be merged into the next release!

**Comment by erinxocon** [comment]
@francbartoli you will have to quote your variable value still.
