### ISSUE TITLE
Invalid version installed on local editable

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#1093]
Hello.
I had an issue yesterday with an invalid version of my package being installed with `pipenv install --dev`, using editable line such as:
```
"e1839a8" = {path = ".", editable = true}
```
Even by cleaning everything, an old commit was used instead.

I fixed it by entering the egg name of my package in `Pipfile`:
```
mypackage = {path = ".", editable = true}
```

An, I find it more elegant instead of this sha-1-like name, to use the package name. It is more logic, since it is editable, there is no need to freeze a hash whatsoever.
What do you think of it?

I have opened a suggestion here: [pipfile#94](https://github.com/pypa/pipfile/issues/94)

**Comment by techalchemy** [comment]
This isn’t a commit,it’s a deterministic hash of the filesystem path you are installing. We used to use the path itself, but that resides in the attributes we include anyway so there wouldn’t be much point.

I’m going to close this since it’s not really applicable

**Comment by Stibbons** [comment]
Any idea why it installed an old version and why it has been fixed by changing this hash ?

**Comment by techalchemy** [comment]
The hash isn't relevant to anything, it's just the key that is used to represent the entry.  Changing it will never do anything,  The only thing that matters is the path in the entry, which is ".".  It will install whatever the current directory has, so not much pipenv has to do with that
