### ISSUE TITLE
Minimal or modular installation

### ISSUE THREAD

**Issue by xmedeko** [kennethreitz/pipenv#1099]
I would like to have minimalistic installation of pipenv to do it's main task - the pip and virtualenv orchestration, without the additional features (code checks - flake8, etc.) E.g. we use different code check tools, or we do not need it at all on the production.
The project may split to modules, like `pipenv, pipenv-codecheck, pipenv-...`, etc. So a user may install, what she wants.

**Comment by erinxocon** [comment]
Hi @xmedeko.  I can understand the need for this, but this isn't a priority at this time.  It would require a major refactor to pull out all of the individual parts, and we're still largely an in development project where things change a lot!  I'm not saying it won't happen, but I can't say that it will happen soon.

**Comment by xmedeko** [comment]
Ok, I understand.
Just a note: if you have flagged this issue as enhancement, future, then it's better to keep it open. So, the other users see it, may express their opinions, etc.
