### ISSUE TITLE
Pipenv chooses wrong project path

### ISSUE THREAD

**Issue by colde** [kennethreitz/pipenv#1102]
When creating a new environment with pipenv --python 3, it does not use the current directory as the project home, but instead chooses a directory two directories up from the current working directory, as illustrated here:
```
 ~/P/mpx-python-api    pwd
/Users/loke/Projects/mpx-python-api
 ~/P/mpx-python-api    pipenv --python 3
Creating a virtualenv for this project…
Using /usr/local/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/loke/.virtualenvs/loke-WdDiAoi-/bin/python3.6
Also creating executable in /Users/loke/.virtualenvs/loke-WdDiAoi-/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/loke/.virtualenvs/loke-WdDiAoi-
 ~/P/mpx-python-api    pipenv --where                                                                       (4s 524ms)
/Users/loke
 ~/P/mpx-python-api   
```

##### Describe your environment

1. OS Type
macOS High Sierra
1. Python version: `$ python -V`
Python 2.7.14 (default)
Python 3.6.3 (python3)
1. Pipenv version: `$ pipenv --version`
pipenv, version 8.3.2 (installed via brew)

##### Expected result
I expected a virtualenv be created for the path /Users/loke/Projects/mpx-python-api

##### Actual result
A virtualenv was created for /Users/loke

##### Steps to replicate
Simply create the virtualenv with pipenv

**Comment by mtt2p** [comment]
remove the Pipfile from your home directory like 
mv ~/Pipfile* /tmp

**Comment by erinxocon** [comment]
Hi @colde, do you have a pipfile anywhere above that folder in your directory structure.  Pipenv will search up through the directory tree for a pipfile and use that as the project root.  If you remove it, you should be able to create a venv for that directory.  If this isn't the case let me know!

**Comment by dangelsaurus** [comment]
> Hi @colde, do you have a pipfile anywhere above that folder in your directory structure. Pipenv will search up through the directory tree for a pipfile and use that as the project root. If you remove it, you should be able to create a venv for that directory. If this isn't the case let me know!

but why?

**Comment by hess8** [comment]
Thanks for the help!

**Comment by brennenhuang** [comment]
help me a lot, thank you.

**Comment by noelmcloughlin** [comment]
I had to do this.
```
 rm $(find ~/ | grep Pipfile)
 rm -fr ~/.local
 pip3 install --user pipenv
```

**Comment by snachman** [comment]
> remove the Pipfile from your home directory like mv ~/Pipfile* /tmp

THANK YOU!!!! This was it.

**Comment by brandon-fryslie** [comment]
Does this need to be filed as a separate bug report?  It's pretty terrible behavior, if you ever accidentally run a pipenv command in the wrong directory and a Pipefile gets created, pipenv will be effectively broken for every subdirectory.  I didn't notice this was even happening until I put my pipenv venv name in my shell prompt and noticed it was incorrect.
