### ISSUE TITLE
Hashes different between local and server?

### ISSUE THREAD

**Issue by wasabigeek** [kennethreitz/pipenv#1103]
Referencing an [older issue](https://github.com/kennethreitz/pipenv/issues/210#issuecomment-339703474), I understood lockfiles should be portable between different OSes now, but this doesn't seem to be the case.

As an example, I encountered the following error after running my deploy script:
```
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    oauthlib==1.0.3 from file:///usr/share/pip-wheels/oauthlib-1.0.3-py3-none-any.whl (from -r /tmp/pipenv-az9xn_nu-requirement.txt (line 1)):
Expected sha256 ef4bfe4663ca3b97a995860c0173b967ebd98033d02f38c9e1b2cbb6c191d9ad
Got        5454640e006c0eecce902638cd7a3fda384d083abf3f7412173fb075610e2256
```
I confirmed the hashes using `pip download` + `pip hash` on local and on the server, they're as above. Are there other factors that could contribute to this e.g. Python version? (In the end I did `pipenv install <package>` on the server itself, ugh).

##### Describe your environment

1. OS Type: 
    - [**WSL**](https://github.com/Microsoft/WSL) (local)
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
    - **PythonAnywhere** (server)
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
1. Python version: 3.5.2 (local), 3.4.3 (server)
1. Pipenv version: 8.3.1

**Comment by nateprewitt** [comment]
@wasabigeek can we get a look at your lockfile? Was it generated with 8.3.1?

This sounds like a possible regression if it's a new lockfile and you haven't edited the wheel.

**Comment by kennethreitz** [comment]
please share your lockfile and your pipfile

**Comment by wasabigeek** [comment]
@nateprewitt @kennethreitz sorry for the late post, my Pipfile/Pipfile.lock are [here](https://gist.github.com/wasabigeek/7604e8a33450973376fa477566b1f468).

If I recall correctly, Pillow and oauthlib failed, but I only have the error for oauthlib as above.

The lockfile was initially created with an earlier version. I just used `pipenv lock` after getting the new version though, and the hash for oauthlib looks the same (refer to gist above)
