### ISSUE TITLE
Add information about the used `Pipfile` when creating a new virtualenv

### ISSUE THREAD

**Issue by joaoqalves** [kennethreitz/pipenv#1106]
# Background

When generating a new _virtualenv_ in a new project, if you have a `Pipfile` in a parent directory, it will create a _virtualenv_ for that directory. 

# Problem

If people have a `Pipfile` that they are not aware of (e.g., at their `$HOME`, due to a `cp` error or whatever), they may start a witch hunt 😢 

# Goal / Feature request

Inform the user in a clear way about the `Pipfile` that's being read. 

PS: I can implement this myself and send a PR, but only if this idea looks good for the project 😄

**Comment by nateprewitt** [comment]
Hey @joaoqalves, I think a minimal update to the message including the location of the Pipfile seems fine. If you'd like to put together a PR for this, I'm happy to review it.

**Comment by kennethreitz** [comment]
no, we used to do this, and it was removed intentionally.

**Comment by joaoqalves** [comment]
@kennethreitz Do you have the link for this removal so I can understand the motivations?
