### ISSUE TITLE
.env file not working 

### ISSUE THREAD

**Issue by rajabiy** [kennethreitz/pipenv#1107]
1. Ubuntu 16.04
1. Python version: 3.5.2
1. Pipenv version: 8.3.2
in project dir I have .env file
$ cat .env
PIPENV_VENV_IN_PROJECT=1

when I run 
$ pipenv shell
amin@amin-Aspire-E1-572G:~/**/self-s/kurs/djinv$ source /home/amin/.local/share/virtualenvs/djinv-eVTiZKZ_/bin/activate

but if I 
run 
$ export PIPENV_VENV_IN_PROJECT=1
$ pipenv shell
Loading .env environment variables…
Spawning environment shell (/bin/bash). Use 'exit' to leave.
amin@amin-Aspire-E1-572G:~/**/self-s/kurs/djinv$ source /home/amin/**/self-s/kurs/djinv/.venv/bin/activate

I have expected getting virtualenv in .venv directory in project directory just with .env file with containing  PIPENV_VENV_IN_PROJECT=1

**Comment by kennethreitz** [comment]
run `env` inside the shell to see your environment variables.

**Comment by marcin-derlukiewicz** [comment]
same here

launching as:
`PIPENV_VENV_IN_PROJECT=1 pipenv install` works as expected, but setting `PIPENV_VENV_IN_PROJECT=1` in .env file does nothing

**Comment by uranusjr** [comment]
This is a result of #902. `.env` is only loaded for `shell` and `run`, not `install`. This is wrong if you ask me, but the way things are.

**Comment by kennethreitz** [comment]
`.env` is used for code-specific environment variables, not system ones. Pipenv is configured by your system, not your code.

**Comment by marcin-derlukiewicz** [comment]
@kennethreitz, are you are saying, that this particular venv option should be rather configurable in Pipfile to achieve desired effect?

**Comment by kennethreitz** [comment]
no, it should be in your `~/.bashrc` (or equivalent). It's a developer's preference. 

If you want to enable it per-project, for some reason, I recommend checking out [direnv](https://direnv.net)

**Comment by marcin-derlukiewicz** [comment]
ok, but direnv is not making life easy.
Human way would be, add additional switch or config option to fix this, 
Install additional program so it will automate setting env option that would allow changing behavior when switching between projects is somewhat Borg.

**Comment by kennethreitz** [comment]
thanks for your opinion

**Comment by ludoleg** [comment]
Hi I am on OSX and still can't get my env variables loaded with .env when I launch pipenv shell.
>pipenv --version
pipenv, version 10.0.0
Was there a fix I missed?

**Comment by alukach** [comment]
A 🤦 moment for me: **Verify that both `.env` and `Pipfile` are located in the same directory.** Somehow I setup my pipenv my the parent directory, causing this issue.
