### ISSUE TITLE
pipenv main page docs don't recommend --user, install section does.

### ISSUE THREAD

**Issue by jlitzingerdev** [kennethreitz/pipenv#1108]
The install instructions on the main pipenv page specify a non-user install of pip [1] while the separate installation docs [2] specify a user install, is the difference intentional, or should a --user install always be recommended?

Its likely on some platforms (e.g. most Linux variants) that attempts to install without --user will present the user with a Permission denied traceback.

Sorry if this is noise, but I didn't see an alternate forum for asking a question before opening an issue (I also didn't find an identical issue with a quick issue search).

[1] https://docs.pipenv.org/index.html#install-pipenv-today
[2] https://docs.pipenv.org/install.html#installing-pipenv

**Comment by kennethreitz** [comment]
thanks for the feedback

**Comment by jlitzingerdev** [comment]
No problem, thanks for the tool, it is outstanding!
