### ISSUE TITLE
feature request: add name tag to environment creation

### ISSUE THREAD

**Issue by rgalbo** [kennethreitz/pipenv#1119]
This is something that I am not sure if feasible but anaconda environments allow for the name of the environment to be set using a name flag `-n`. This would be useful for something like scientific computing where you will use an environment for a specific taskt (simulation, data science, statistics) and would like it to be named as such without creating a specific place for it to live on your computer.

**Comment by erinxocon** [comment]
Hi @rgalbo!  The name of the environent gets created based on the name of the folder with a hash added on to ensure it's unique.  If you wish for the environment to be named something else, you can manually create it and then use pipenv within that (it will use the venv's python), or just change the name of the folder.  I do not believe we will be supporting this at this time.  Thanks for using pipenv!
