### ISSUE TITLE
pipenv uninstall doesn't remove dependencies from virtualenv

### ISSUE THREAD

**Issue by wasabigeek** [kennethreitz/pipenv#1123]
I'm not sure if this is intentional, but `pipenv uninstall` only removes the package, not it's dependencies from the venv. I would have expected it to be removed.

##### Describe your environment

1. OS Type: Windows 10, WSL
1. Python version: 3.5.2
1. Pipenv version: 8.3.2

##### Steps to replicate

```
$ pipenv install requests
$ pipenv shell
$ pip freeze
certifi==2017.11.5
chardet==3.0.4
idna==2.6
requests==2.18.4
urllib3==1.22
$ pipenv uninstall requests
certifi==2017.11.5
chardet==3.0.4
idna==2.6
urllib3==1.22
```

##### Expected result

`requests` and it's dependencies are removed.

##### Actual result

only `requests` is removed.

**Comment by chenull** [comment]
@wasabigeek i think this is intentional. at least `pip` uninstall something did the same. whenever i want to `refresh` my virtualenv, i do `pipenv update`. from the help text:

```
Commands:
...
  uninstall  Un-installs a provided package and removes it from Pipfile.
  update     Uninstalls all packages, and re-installs package(s) in [packages]
             to latest compatible versions.
```

**Comment by wasabigeek** [comment]
Thanks @chenull, I glossed over the `update` command. It still feels a unexpected to me, but I guess I'm used to npm.

**Comment by atmragib** [comment]
```
pipenv --rm
pipenv install
```

This process will work but very slow as it delete the full virtual environment and reinstall all the main dependencies.

**Comment by Flimm** [comment]
The correct command in Pipenv 2020.11.4 is:

```
pipenv clean
```

The command `pipenv update` does not work.
