### ISSUE TITLE
Pipenv fails to install from github by ref and tag

### ISSUE THREAD

**Issue by BeyondEvil** [kennethreitz/pipenv#1126]
Trying to install from github using ref and tag fails, because pipenv "destroys" the format of the url removing `git:` from the reference.

##### Describe your environment

1. OS Type OSX 10.12.6
1. Python version: `$ python -V` 3.6.3
1. Pipenv version: `$ pipenv --version` 8.3.2

##### Expected result

The reference in `Pipfile` looks like this (which is correct)
`pytest-tags = {git = "git://github.com/Projectplace/pytest-tags.git", editable = true, ref = "1.5"}`

But in the `Pipfile.lock` file, it's
`"git": "//github.com/Projectplace/pytest-tags.git"`

Workaround is to re-add `git:` to the pipfile.lock manually.

##### Actual result

```Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (24ab2e)!
Installing dependencies from Pipfile.lock (24ab2e)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 19/19 — 00:00:05
An error occurred while installing -e git+//github.com/Projectplace/pytest-tags.git@c8cf057c03a1fa30769c0328efa41d4826e03bcf#egg=pytest-tags! Will try again.
Installing initially–failed dependencies…
Obtaining pytest-tags from git+//github.com/Projectplace/pytest-tags.git@c8cf057c03a1fa30769c0328efa41d4826e03bcf#egg=pytest-tags
  Cloning github.com/Projectplace/pytest-tags.git (to c8cf057c03a1fa30769c0328efa41d4826e03bcf) to /Users/jimbrannlund/.local/share/virtualenvs/dpo-automation-NuB7OARD/src/pytest-tags
fatal: repository 'github.com/Projectplace/pytest-tags.git' does not exist

Command "git clone -q github.com/Projectplace/pytest-tags.git /Users/jimbrannlund/.local/share/virtualenvs/dpo-automation-NuB7OARD/src/pytest-tags" failed with error code 128 in None```

**Comment by techalchemy** [comment]
@BeyondEvil I can reproduce this for editable installs, will look into it

**Comment by BeyondEvil** [comment]
I have to say, I'm really impressed by the short turnaround (4 hours) from reported issue to merged fix! @techalchemy
