### ISSUE TITLE
pipenv find a newer dependencies ,but actully

### ISSUE THREAD

**Issue by Jasonsey** [kennethreitz/pipenv#1131]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type
1. Python version: `$ python -V`
1. Pipenv version: `$ pipenv --version`

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by vphilippon** [comment]
Looks like a missclick (see #1132)
