### ISSUE TITLE
pipenv shell is corrupting .bash_history

### ISSUE THREAD

**Issue by hyperknot** [kennethreitz/pipenv#1164]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

Whenever I run `pipenv shell` it corrupts my `.bash_history` file.

##### Describe your environment

1. OS Type: OS X 10.12.6
1. Python version: `$ python -V` Python 2.7.14 (pipenv uses Python 3.6.3)
1. Pipenv version: `$ pipenv --version` pipenv, version 8.3.2

##### Expected result
`.bash_history` should not get destroyed upon entering `pipenv shell`

##### Steps to replicate

1. original `.bash_history` is quite large, almost 1 MB.
2. run `pipenv shell`
3. by the time the shell is created, my `.bash_history` is super small, like 15 KB. 

It happens on a clear folder (no Pipfile or anything), both with no args, `--two` and `--three`.

My bash_profile has these lines:

```
shopt -s histappend
HISTSIZE=100000
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignoredups:erasedups:ignorespace
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
```

**Comment by techalchemy** [comment]
@hyperknot your `.bash_profile` doesn't affect pipenv shells, since `.bash_profile` is for login shells only.  You need to put any settings in your `.bashrc` if you want them to be loaded in an interactive shell

Would you mind providing the contents of that as well?

**Comment by hyperknot** [comment]
I do not have any `.bashrc`, only `.bash_profile`. So by your logic I should move the bash_history related block to `.bashrc`? Or I should even rename my `.bash_profile` to `.bashrc`?

**Comment by hyperknot** [comment]
OK, in OS X every terminal tab is a login shell, so I had to do the following.

1. renamed `.bash_profile` to `.bashrc`
2. made `.bash_profile` contain the following: 
```
if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi
```

Now it works.

**Comment by hyperknot** [comment]
BTW, every command line tool / homebrew instruction for OS X always puts everything in `.bash_profile` and `.bashrc` isn't really used, so other users might run into this.

Wouldn't it be possible to source `.bash_profile` automatically on `pipenv shell`?

**Comment by techalchemy** [comment]
@hyperknot you could try, but you're running somewhere that doesn't have a `Pipfile` or a pipenv-managed virtualenv you said? I have no real idea what the consequences of that would be, to be honest.

Since you are on OS X i assume you have your locale set somewhere since everything isn't broken, but you might want to add the lines

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Since things can break if those are set incorrectly and whatnot

Glad this was a simple one! Thanks for your patience and for the bug report, I'm sure this will be helpful in the future

**Comment by hyperknot** [comment]
@techalchemy running `pipenv shell` in an empty dir creates a pipenv for me first, so it's actually in a pipenv by that time. Shouldn't it be like this?

Ah, that locale thing in OS X. It's quite crazy about that, actually. If it recognises a Preferred Language - Region pair as a valid location string, it exports `LANG=en_GB.UTF-8` or whatever is set, so I don't need those lines. But yes, many users might need it.

**Comment by techalchemy** [comment]
@hyperknot pipenv itself doesn't actually handle any of the calls after creating a subshell, it just uses either your `$SHELL` environment variable or `pew` (the tool we use to manage virtualenvs) to spawn a subshell and the subshell process itself handles whatever happens at load time.  

You can do the inverse of what you did, which is to leave everything in `.bash_profile` and put this in your `.bashrc`:

```bash
if [ -f $HOME/.bash_profile ]; then
    source $HOME/.bash_profile
fi
```

**Comment by hyperknot** [comment]
@techalchemy I'll be testing this solution now, so far seems to work fine. At least this could be added as a non-intrusive solution for all users running into problems with `pipenv shell`.

Even if out of the scope of this project, the most friction-free behaviour in the future would be to modify pew to load `.bash_profile` `.bashrc` is not present.
