### ISSUE TITLE
1+ second overhead with 'pipenv run'

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#120]
I would like to be able to use `pipenv run` as part of my automation tooling, but currently it adds about a second of overhead on my machine:

```
$ pipenv --version
pipenv, version 3.2.4

$ time .venv/bin/python --version
Python 3.6.0
.venv/bin/python --version  0.00s user 0.00s system 28% cpu 0.020 total

$ time pipenv run python --version
Python 3.6.0
pipenv run python --version  1.03s user 0.20s system 36% cpu 3.399 total
```

While one second is not long, it is enough to discourage me from using pyenv as a task runner for tests, linters, etc.

Can anything be done about this overhead?

**Comment by nateprewitt** [comment]
Thanks for bringing this up @jacebrowning, we were parsing the Pipfile every time a command was run, causing the slow down. I just merged a patch (#122) that should help with this considerably.

**Comment by jacebrowning** [comment]
Thanks! I'll test this when the `v3.2.5` is out.

**Comment by jacebrowning** [comment]
This is working much better! 💥
