### ISSUE TITLE
Support global requirements

### ISSUE THREAD

**Issue by sblask** [kennethreitz/pipenv#124]
This tool looks great and it's kind of doing what I set up manually in my dotfiles/projects. One thing seems to be missing though: global requirements - something that I want to have installed in all my virtual environments. This is what I do now: https://github.com/sblask/dotfiles/blob/e40fa3928ba6a4419480faee2f052505099447db/zshrc.dotfile#L299 every time I encounter a `.venv` directory: https://github.com/sblask/dotfiles/blob/e40fa3928ba6a4419480faee2f052505099447db/zshrc.dotfile#L305 I do this to have certain packages available without having to install them globally, mostly for checking code in vim : https://github.com/sblask/dotfiles/blob/e40fa3928ba6a4419480faee2f052505099447db/.virtualenvs/requirements.txt.symlink I guess the best way to implement it in pipenv would be a `.pipfile` in a user's home that is included when doing `pipenv install`.

**Comment by kennethreitz** [comment]
not going to happen
