### ISSUE TITLE
Autocomplete for zsh/bash/fish?

### ISSUE THREAD

**Issue by lk-geimfari** [kennethreitz/pipenv#125]
What do you think about autocomplete plugin for zsh/bash/fish? Does it exist?

**Comment by timofurrer** [comment]
This would be really easy to implement by using https://github.com/click-contrib/click-completion

**Comment by lk-geimfari** [comment]
@timofurrer Actually we can just rewrite existed pip plugin for zsh. As i can judge `pip` and `pipenv` are similar tools.

**Comment by timofurrer** [comment]
With `click-completion` you'd only have to add it as a dependency and initialize it. Nothing about writing anything.

**Comment by lk-geimfari** [comment]
@timofurrer Oh, that's cool!

**Comment by kennethreitz** [comment]
click-completion looks cool!

**Comment by kennethreitz** [comment]
open to a README update for ZSH and BASH!

**Comment by lk-geimfari** [comment]
@kennethreitz That's great!

**Comment by gregplaysguitar** [comment]
Any tips on adding this to zsh?

**Comment by kennethreitz** [comment]
same way it is for fish!
