### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by vadimadr** [kennethreitz/pipenv#142]
Shouldn't temporary files be deleted after successful installation?

**Comment by nateprewitt** [comment]
@vadimadr Could you clarify which temp files you're referring to? The downloads directory?

**Comment by vadimadr** [comment]
The ones that are being fed to `pip install -r`  command (`/tmp/tmp*-requirements.txt`)

**Comment by nateprewitt** [comment]
Ah, yes, while those will eventually get cleaned up, I don't see a reason not to do it earlier. We'll work on getting that into the next release unless you'd like to provide a PR :)

**Comment by kennethreitz** [comment]
i think they're useful for debugging.

**Comment by kennethreitz** [comment]
but yes, it would be good to delete them
