### ISSUE TITLE
Add list command

### ISSUE THREAD

**Issue by vadimadr** [kennethreitz/pipenv#144]
Why not add `list` command? It should list all required dependencies considering lock file.

I think it is in scope of this package because reading json file is not very pleasing for eye and occupy a lot of space in terminal output. Moreover, I suppose this is assumed to replace pip command in the future, so it should provide all the functionality that vanilla pip does.

**Comment by kennethreitz** [comment]
`install --list` does this. we want to avoid adding more commands if at all possible. the fewer commands, the better.
