### ISSUE TITLE
Why lockfile is not created by default?

### ISSUE THREAD

**Issue by vadimadr** [kennethreitz/pipenv#146]

**Comment by kennethreitz** [comment]
it is?

**Comment by vadimadr** [comment]
@kennethreitz No lockfile created after initialising project:
```(pipenv)vadim@vadim-K56CB /t/workdir-0129-0005-lockfile> pipenv --three
Creating a Pipfile for this project...
Creating a virtualenv for this project...
Running virtualenv with interpreter /tmp/workdir-0128-2240-pipenv-hash/pipenv/.venv/bin/python3
Using real prefix '/usr'
Path not in prefix '/tmp/workdir-0128-2240-pipenv-hash/pipenv/.venv/include/python3.5m' '/usr'
New python executable in /tmp/workdir-0129-0005-lockfile/.venv/bin/python3
Also creating executable in /tmp/workdir-0129-0005-lockfile/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /tmp/workdir-0129-0005-lockfile/.venv
(pipenv)vadim@vadim-K56CB /t/workdir-0129-0005-lockfile> pipenv install requests
Installing requests...
Collecting requests
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.13.0

Adding requests to Pipfile's [packages]...
P.S. You have excellent taste! ✨🍰✨
(pipenv)vadim@vadim-K56CB /t/workdir-0129-0005-lockfile> ls -al
total 4
drwxrwxr-x  3 vadim vadim   80 Jan 29 00:05 .
drwxrwxrwt 47 root  root  1380 Jan 29 00:05 ..
-rw-rw-r--  1 vadim vadim   95 Jan 29 00:05 Pipfile
drwxrwxr-x  5 vadim vadim  140 Jan 29 00:05 .venv
(pipenv)vadim@vadim-K56CB /t/workdir-0129-0005-lockfile> 
```

Is it desired behaviour? What are reasons behind that?

**Comment by nateprewitt** [comment]
@vadimadr, the install command by default will only update the Pipfile and install them in your virtualenv. If you'd like to update your lock file each time you add a dependency you can use the --lock parameter to do so.

**Comment by jpadilla** [comment]
@nateprewitt I'm wondering what if anything we can do to make `--lock` the default behavior. According to https://github.com/kennethreitz/pipenv/issues/50#issuecomment-274637993

> the only downside is that currently locking is a rather expensive (time-wise) operation.

Does this still hold true?

**Comment by nateprewitt** [comment]
@jpadilla, locking is still not a fast action.

I believe the default of not locking is the correct one. If the user is playing around with adding one package at a time, we don't want to wait for a whole lock rebuild every time they add or delete a dependency. Especially since the environment is already updated for them.

When they're ready to lock it, the user can use `pipenv lock`, or if they know they definitely want the dependencies, they can tell pipenv to make it permanent with `pipenv install <dependencies> --lock`.
