### ISSUE TITLE
Add an option to disable colored output

### ISSUE THREAD

**Issue by FooBarQuaxx** [kennethreitz/pipenv#152]
Some colored output (particularly blue) makes the text non legible in my terminal. I think it's trivial just to add a global --no-color flag.

**Comment by kennethreitz** [comment]
fix your terminal :)

**Comment by kennethreitz** [comment]
maybe via environment variable.

**Comment by kennethreitz** [comment]
in master, you can now set `export PIPENV_COLORBLIND=1` and no colors will be produced
