### ISSUE TITLE
Allow `check` option to report on multiple mismatches between 508 & Pipfile 

### ISSUE THREAD

**Issue by m-charlton** [kennethreitz/pipenv#160]
Say the 508 requirements file contains the following:

```
{ ...,
  'python_version': '3.5',
  'os_name': 'posix',
  ...
}
```

And our Pipfile:

```
...
[requires]
python_version = '2.7'
os_name = 'windows'
```

As it stands, you will only see the first mismatch:

```
Specifier python_version does not match 2.7.
```

All subsequent errors will be ignored. Ideally we'd want to see:

```
Specifier python_version does not match 2.7.
Specifier os_name does not match windows.
Failed!
```
Might be useful to include a `Failed!` message as well.

In addition would it be useful to include the *actual* value that was found?
Example:

```
Specifier python_version does not match 2.7 - Actual 3.5.
Specifier os_name does not match windows - Actual posix.
Failed!
```

I've already made and tested the changes and can submit a pull request.

Also if the Pipfile contains the following entry

```
...
[requires]
platform: 'Darwin'
...
```

And the 508 requirements file is:

```
{ ...,
  'platform_machine': 'x86_64',
  'platform_python_implementation': 'CPython',
  'platform_release': '15.0.0',
  'platform_system': 'Darwin',
  ...
}
```

Then would it be useful to issue a warning along the lines:

```
Warning - unable to find specifier platform.
```

As the specifier could have been misspelt in the Pipfile. Would we want to
fail the check in this case?

Again I can submit this change in a PR.

**Comment by kennethreitz** [comment]
I think it's reasonable to only fail once, but i'll see what I can do.

**Comment by kennethreitz** [comment]
added!
