### ISSUE TITLE
Support for running commands directly in the pipenv shell?

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#162]
I would like the ability to specify a command to run in the pipenv shell so that I can simulate my production environment locally with a single call:

```
$ pipenv shell heroku local

# or alternate syntax:

$ pipenv shell -c "heroku local"
```

Would you support this use case?

**Comment by kennethreitz** [comment]
Not at this time.

**Comment by kennethreitz** [comment]
added in master!

**Comment by nateprewitt** [comment]
Resolved with 85049ba.

**Comment by metakermit** [comment]
I see that `pipenv shell -c` has been deprecated in 7.5. How come? This seemed to be the only way to [run honcho in pipenv](https://github.com/pypa/pipenv/issues/249)

**Comment by uranusjr** [comment]
Does `pipenv run` replace this feature?

**Comment by metakermit** [comment]
OK, it seems this was a [honcho issue](https://github.com/nickstenning/honcho/issues/136) I was experiencing. I manage to get decent results with pipenv + honcho for running multiple processes (postgres, redis, django, celery) by using:

```
PYTHONUNBUFFERED=1 pipenv run honcho start
```

So you're right @uranusjr 🙂

**Comment by uranusjr** [comment]
Glad it’s working for you 😃  I wonder what `PYTHONUNBUFFERED=1` is affecting in this example 🤔 `pipenv run` actually uses `os.exec*` to _replace_ the current process, so there shouldn’t be buffering issues there… I hops someone would be interested to sort this out someday.

**Comment by metakermit** [comment]
No, it's got nothing to do with pipenv from what I see, it's just that Django's runserver is buffering output, so unless if you add this flag there would be no output coming from this process (which got me confused about why is the server not starting).
