### ISSUE TITLE
support more shells (fish / csh / bash / powershell)

### ISSUE THREAD

**Issue by aisk** [kennethreitz/pipenv#17]
I'm using fish and looks pipenv works fine without shell command:

```
❰/private/tmp/asd❱✔≻ pipenv shell
Spawning virtualenv shell (/usr/local/bin/fish).
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
/private/tmp/asd/.venv/bin/activate (line 23):     if [ -n "${BASH-}" ] || [ -n "${ZSH_VERSION-}" ] ; then
                                                                         ^
from sourcing file /private/tmp/asd/.venv/bin/activate
	called on line 194 of file /usr/local/Cellar/fish/2.4.0/share/fish/config.fish

in function '.'
	called on standard input

source: Error while reading file '/private/tmp/asd/.venv/bin/activate'
```

Seems it is trying to active the virtualenv with `bin/active`, but virtualenv also support fish via `bin/active.fish`, i think we can source it while detected current shell is fish.

And also, i think pipenv dose not support csh / cmd.exe now...

**Comment by ryanhiebert** [comment]
FWIW, this is what inve is all about (#10), and is the reason that I was suggesting it.

**Comment by kennethreitz** [comment]
adding fish support should be easy enough!

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/24bbe10bafd49f3216f85e9129b9fe29f21222d9

**Comment by kennethreitz** [comment]
released!

**Comment by kennethreitz** [comment]
i don't have the ability to test powershell at the moment

**Comment by kennethreitz** [comment]
csh supported, bash supported, fish supported

**Comment by uranusjr** [comment]
Powershell support would be much involved because there are no environment variables to test. Testing `sys.platform == 'win32'` is not enough since Powershell and the Command Prompt uses different activate scripts. And aside from that Pexpect doesn’t even support `spawn` on Windows, so it won’t work anyway…

**Comment by kennethreitz** [comment]
We may have to not support powershell then.

**Comment by jessebraham** [comment]
One option, although I'm not sure how I feel about it, would be to first determine the system, and if `win32` is detected do feature detection to determine whether the shell was Command Prompt or Powershell.

**Comment by jessebraham** [comment]
I've found a reasonable method of determining whether Python has been executed by `powershell.exe` or `cmd.exe` using [psutil](https://github.com/giampaolo/psutil).  

```python
import psutil
import sys

if sys.platform == 'win32':
    me = psutil.Process()
    parent = psutil.Process(me.ppid())

    # Prints "powershell.exe" or "cmd.exe"
    print(parent.name())
```

The lack of support for `pexpect.spawn` on Windows is the limiting factor at this point.

**Comment by jessebraham** [comment]
@uranusjr It is possible to detect the difference between Powershell and Command Prompt, for example using the [psutil](https://github.com/giampaolo/psutil) module:  

```python
import psutil
import sys

if sys.platform() == 'win32':
    me = psutil.Process()
    parent = psutil.Process(me.ppid())

    # Prints 'powershell.exe' or 'cmd.exe'
    print(parent.name())
```

However as you mentioned, `pexpect.spawn` is *not* supported on Windows, and [there are no plans for it ever to be](https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows).

**Comment by kennethreitz** [comment]
going to drop windows support for now.
