### ISSUE TITLE
Support for ~/.virtualenvs folder instead of .venv in project folder

### ISSUE THREAD

**Issue by tylerwince** [kennethreitz/pipenv#173]
I think it would be great if there could be a choice between adding the `.venv/` folder to the repo directly and having a central `~/.virtualenvs` folder - similar to virtualenvwrapper. 

@kennethreitz, what do you think about adding support for this? I would be willing to take a stab at it if it is something you want to pursue.

**Comment by kennethreitz** [comment]
if anything we'd support `pew`. there's a branch for that.

**Comment by tylerwince** [comment]
Sounds great! Thanks

**Comment by kennethreitz** [comment]
integrated!

**Comment by kennethreitz** [comment]
also added `PIPENV_VENV_IN_PROJECT` mode for classic operation.

**Comment by tylerwince** [comment]
👍 works like a charm! Thanks @kennethreitz
