### ISSUE TITLE
Problem installing pymorphy2

### ISSUE THREAD

**Issue by jungornti** [kennethreitz/pipenv#180]
Hello, i have just create project environment with `pipenv install` with this Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[dev-packages]
django-debug-toolbar = "*"
pytest = "*"
pytest-django = "*"
coverage = "*"
tox = "*"
mock = "*"

[packages]
Django = "*"
django-allauth = "*"
django-ckeditor = "*"
django-cleanup = "*"
django-cmstemplates = "*"
django-codemirror-widget = "*"
django-el-pagination = "*"
django-widget-tweaks = "*"
easy-thumbnails = "*"
envvars = "*"
hiredis = "*"
ipython = "*"
lxml = "*"
psycopg2 = "*"
pymorphy2-dicts-ru = "*"
pytils = "*"
redis = "*"
rules = "*"
dj_database_url = "*"
Pillow = "*"

[packages.pymorphy2]
extra = [ "fast",]
```

Then i launched django project (manage.py) and got an error that pymorphy2 is not installed, but it is declared in Pipfile.

Then i tried to install it with `pipenv install pymorphy2` being inside in virtual environment and got this error: `Error: 2`.

**Comment by kennethreitz** [comment]
make sure you're using the latest version!

**Comment by jungornti** [comment]
I updated, now it is working, thanks, but now `pymorphy2 extras section` is replaced in Pipfile with `pymorphy2 = "*"`, instead of `pymorphy2 = {extras = '[fast'}`, so i can not install fast version of pymorphy2 anymore. I think this is a bug.

**Comment by nateprewitt** [comment]
@jungornti, and anyone stumbling onto this issue later, you've used the word "extra" instead of "extras" which will not work. Fixing the name in your Pipfile should work fine.

**Comment by jungornti** [comment]
@nateprewitt thank you, sorry for bothering you because of this stupid problem. :)
