### ISSUE TITLE
Depth of Pipfile recursive search

### ISSUE THREAD

**Issue by spiliopoulos** [kennethreitz/pipenv#183]
There is a default depth of 3 for the recursive search of a Pipfile. For projects with a deeper file hierarchy it's difficult/confusing to use pipenv. For example I have already created a virtualenv on the root dir, then I move 4 directories down, and I do pipenv install Something and I end up with a new virtualenv in that directory. This behavior should be documented and it would be nice to be able to configure the depth (for example with a flag). I can create a PR if this is desirable.

**Comment by kennethreitz** [comment]
what depth do you think it should be set at?

**Comment by kennethreitz** [comment]
I'd like to avoid configuration if at all possible.

**Comment by spiliopoulos** [comment]
Well, there is no one size fits all option here. If you want to avoid configuration then it should at least be very clearly documented. Preferably on the first run of pipenv output too.

**Comment by kennethreitz** [comment]
I'm looking for data here: what depth do *you* need?

**Comment by spiliopoulos** [comment]
Well, the project I am working at now has a max depth of 10 I think.

**Comment by kennethreitz** [comment]
yeah, we're not going to support that i don't think. perhaps via environment variable...

**Comment by spiliopoulos** [comment]
Sure. Would you like two seperate prs one for the documentation (that there is a maximum depth) and one for the environmental variable, so you could accept one or the other or both?

**Comment by kennethreitz** [comment]
one for both — add it to the advanced section

**Comment by spiliopoulos** [comment]
:+1:

**Comment by kennethreitz** [comment]
this is now configurable!

**Comment by kennethreitz** [comment]
`PIPENV_MAX_DEPTH`

**Comment by spiliopoulos** [comment]
Thanks.

**Comment by fossum** [comment]
This is the fix I need, but there is no link here... Now I have to continue Googling.

Can someone link the commit that added PIPENV_MAX_DEPTH or link a documentation page?

**Comment by uranusjr** [comment]
@fossum WHat do you mean? Set the environment variable, and it will change the search depth.

**Comment by fossum** [comment]
I guess I missed, "Would you like two seperate prs one for the documentation (that there is a maximum depth) and one for the environmental variable, so you could accept one or the other or both?" while skimming.

I still don't know what version this was fixed in or what "add it to the advanced section" ment. I did find the advanced documentation after Googling "PIPENV_MAX_DEPTH", but my point is there was no linkage to a fix.

The issue was just, closed.

**Comment by techalchemy** [comment]
@fossum issues are not documentation. They are a place for us to triage problems

**Comment by codeskyblue** [comment]
@fossum Found in code https://github.com/pypa/pipenv/blob/76d6fcc5c595a4e12a7d54ed848241fe41a316c9/pipenv/environments.py#L190
