### ISSUE TITLE
'pipenv install' does not honor --three option when auto generate the virtualenv

### ISSUE THREAD

**Issue by xwk** [kennethreitz/pipenv#186]
Steps to reproduce the problem:
1. create a new project folder
2. cd to the folder
3. run 'pipenv --three install rx'
4. run 'pipenv shell'
5. run 'python'

Expected outcome: 
The python version should be 3.x

Actual outcome:
The python version is 2.x

In comparision, if you use 'pipenv --three' command to explicitly create the virtualenv, it will correctly create a python3 virtualenv.

**Comment by nateprewitt** [comment]
@xwk, this isn't quite that pipenv install --three isn't being honored, but that pipenv shell had a functionality change. We're already discussing this in #184, and it's been patched on master.

Going to close this in favor of the other issue. Thanks for taking the time to open this!
