### ISSUE TITLE
Only pipenv shell  -c works on my zsh

### ISSUE THREAD

**Issue by douglasmiranda** [kennethreitz/pipenv#188]
I'm using zsh, and `pip shell` only works with the `--compat` flag.

So, in this case, what "misconfigured shells" means?

```
github-douglas/demo/dfu-demo
▶ pipenv shell --help                                     
Usage: pipenv shell [OPTIONS] [SHELL_ARGS]...

  Spawns a shell within the virtualenv.

Options:
  --three / --two  Use Python 3/2 when creating virtualenv.
  --python TEXT    Specify which version of Python virtualenv should use.
  -c, --compat     Run in shell compatibility mode (for misconfigured shells).
  --help           Show this message and exit.

github-douglas/demo/dfu-demo
▶ pipenv shell       
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

github-douglas/demo/dfu-demo
▶ ./manage.py --version
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

github-douglas/demo/dfu-demo
▶ pipenv shell -c                                         
Spawning environment shell (/bin/zsh).
source /Users/douglas/.virtualenvs/dfu-demo/bin/activate

github-douglas/demo/dfu-demo
▶ source /Users/douglas/.virtualenvs/dfu-demo/bin/activate
(dfu-demo) 
github-douglas/demo/dfu-demo
▶ ./manage.py --version                                   
1.10.5
(dfu-demo) 
github-douglas/demo/dfu-demo
▶ 
```

pipenv==3.3.4

**Comment by kennethreitz** [comment]
that means you don't have your shell configured properly!

**Comment by kennethreitz** [comment]
and that's why compatibility mode is there. you can make it permanent by setting `PIPENV_SHELL_COMPAT=1`

**Comment by frgtn** [comment]
@kennethreitz could you expand a little (or post a link) on what is considered properly configured shell in this case? For people who stumble to this via Google. Thanks!

**Comment by hershal** [comment]
I'm stumbling across this issue and I still don't know *what* is misconfigured in my shell that makes a straight `pipenv shell` not work for me. What is misconfigured in my shell such that "regular" mode does not work, but compatibility mode does? What is considered a properly configured shell? For reference, I'm using zsh.
Thanks.

**Comment by kennethreitz** [comment]
check this out for more information https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated
