### ISSUE TITLE
Removal of --requirements

### ISSUE THREAD

**Issue by jdno** [kennethreitz/pipenv#189]
Hello,

I am in dire need of the `--requirements` flag and was wondering why it was removed. Especially after seeing the very recent discussion in #163.

We currently experiment with both `pipenv` and `pip` in our development pipeline. Local development is done with `pipenv` (thanks btw!), but to deploy our servers, we fall back to plain ol' `pip`. More specifically, we build Docker images from our code. And in those containers there is absolutely no need for virtual environments.

Up until now, we used `pipenv install --requirements` to generate a `requirements.txt` file during the build, copy that into the image and used `pip` to install all requirements.

As long as `pip` does not support the Pipfile format, I think `pipenv` should offer some way to export the requirements as a `requirements.txt` file.

Cheers,
JD

**Comment by nateprewitt** [comment]
Hey @jdno, the functionality wasn't removed but rather relocated to a more sensible place. Calling `pipenv install --requirements` only printed the requirements list, while not installing anything. This lead to some confusion when running commands like `pipenv install Django --requirements`.

The `requirements.txt` functionality now resides on the `lock` function with the command `pipenv lock -r`. This probably could have been documented better in the change log. Let us know if you encounter any further issues. Thanks!

**Comment by jdno** [comment]
Epic stuff! 👍 Thanks for the quick update.

**Comment by kennethreitz** [comment]
✨🍰✨
