### ISSUE TITLE
Subcommand(?) issue while bootstrapping a new environment

### ISSUE THREAD

**Issue by JacobOscarson** [kennethreitz/pipenv#190]
Hello,

First, thanks a lot for this project! It certainly fills in a missing piece of functionality in the Python ecosystem.

However, I just ran into an issue when running with a combination of:
```
Python 2.7.10 (brew installed on OS X 10.12.2 (16C67))
pip 9.0.1
pipenv, version 3.3.4
```

aiming to create an environment using Python 3.6.0 (findable via `$PATH`)

I try to install from scratch /w a new Pipfile like this:

```shell
[..]$ rm -rf Pipfile* && LC_ALL='en_US.UTF-8' pipenv --three install
Creating a Pipfile for this project...
No package provided, installing all dependencies.
Pipfile found at /Users/jacob/src/oss/components/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Installing dependencies from Pipfile.lock...
An error occured while installing!

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --require-hashes
```

**Comment by nateprewitt** [comment]
@JacobOscarson could you supplying us with a few more pieces of information?

* `virtualenv --version`
* `pew version`
* `pipenv run pip --version`
* `pipenv run python --version`

**Comment by JacobOscarson** [comment]
```
virtualenv --version
13.1.2
~/src/plexical/env/ve/2.7/bin/pew version
0.1.26
```

Running both `pipenv run pip --version` and `pipenv run python --version` raises `OSError` complaining about missing local files, originally from the `subprocess` stdlib module.

**Comment by nateprewitt** [comment]
@JacobOscarson This is leading me to think there's an installation issue of some kind with your pipenv instance. My first suggestion would be to uninstall pipenv, run the `pipenv` command again to verify you don't have an additional install somewhere else, and then reinstall it.

If that doesn't fix it, we'll need the traceback from that OSError to keep moving forward.

**Comment by kennethreitz** [comment]
make sure you're using the latest pip!

``$ pip install pip --upgrade``
