### ISSUE TITLE
Hashes do not match on CircleCI

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#191]
I am getting the following failure on CircleCI with pipenv 3.3.4:

```
An error occured while installing!
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    coverage==4.3.4 from https://pypi.python.org/packages/d4/26/ff939bccb1406bb139dedefcbdca850d208c47f5bef32a5b391267b13023/coverage-4.3.4-cp36-cp36m-manylinux1_x86_64.whl#md5=c71e253f56a4ac0cc07cabe8df0863d5 (from -r /tmp/tmp1rtbwrxp-requirements.txt (line 21)):
        Expected sha256 8b282292973a1dc4eccfcc0776e0fde75b5b3de2e35164c2d854f7dd80149e4b
             Got        2f5a8bf29bdc69976d0913745daab11f8265e46ec41153f5e1e1794088019dad
```

Using the same version `pipenv install --dev` succeeds on my machine.

How do I go about debugging this?

**Comment by nateprewitt** [comment]
@jacebrowning this is an issue of wheels vs binaries. CircleCI is downloading `coverage-4.3.4-cp36-cp36m-manylinux1_x86_64.whl` and I'm assuming you're on macOS or getting a source archive on your local system.

This is a known issue that is typically caused by generating a lock file in Python 2 and then trying to use it with Python 3 (and vice versa).

Have you tried uploading this to your CI without a precompiled Pipfile.lock in the project? This isn't advice on how to solve this, I'm just curious if this is a Pipfile.lock issue, or an environment issue on Circle-CI.

**Comment by jacebrowning** [comment]
@nateprewitt `rm Pipfile.lock && pipenv install --dev` succeeds on CircleCI.

**Comment by nateprewitt** [comment]
Yeah, so this is a conflict of either default python versions (or pip environment settings; see #147) between your local system and CircleCI. As long as we allow wheels, there will be hash differences on different system configurations. While this does defeat some of the purpose of the hashes, I think it's the best solution we can provide at the moment.

Glad this worked for you, and thanks for letting us know about this.

**Comment by nateprewitt** [comment]
@jacebrowning, ignore my previous advice of deleting the lock file. I'd forgotten the prescribed solution from the [docs](http://docs.pipenv.org/en/latest/advanced.html#testing-projects) is to run `pipenv lock` before running `pipenv install --dev` on a CI environment.

**Comment by shadow-light** [comment]
@nateprewitt Running `pipenv lock` seems to not only discard the hashes but also the versions in the lock file. Is it possible to recreate a lock file on another platform that maintains the same version numbers for all the packages? If not, I'd love to request this as a feature.

**Comment by techalchemy** [comment]
Implementation will be a bit slower in pipenv but you can test out the resolver we are working on - [passa](https://github.com/sarugaku/passa) and you should be able to do more granular manipulation of your lockfile

**Comment by shadow-light** [comment]
Ok, thanks. Glad it's being worked on.
