### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#194]
see if this is even possible. May have to just print output to tell users what to do if they are on windows.

**Comment by kennethreitz** [comment]
spinner doesn't work on windows. not even worth it.

**Comment by MyrionPhoenixmoon** [comment]
So just to be clear - there is no windows support for pipenv at all?

Or is this about some sub-functionality?

**Comment by nateprewitt** [comment]
@MyrionPhoenixmoon we currently don't officially support Windows. You may be able to get certain features to work on Windows, but their function has no guarantee to continue in future versions. Hopefully when we have a more stable build we can start entertaining Windows support.

**Comment by MyrionPhoenixmoon** [comment]
Thank you. I hope that day comes soon :)

**Comment by jacebrowning** [comment]
Would you consider setting up AppVeyor to include Windows as a CI target. At the time of this comment, pipenv doesn't work on AppVeyor's Windows machines and produces [the following error](https://ci.appveyor.com/project/jacebrowning/template-python/build/1.0.263/job/afj57ycmlouxqcfb):

```
$ pipenv install
Creating a virtualenv for this project...
New python executable in C:\projects\.venv\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Virtualenv location: C:\projects\.venv
No package provided, installing all dependencies.
Fixing package names in Pipfile...
Pipfile found at C:\projects\template-python/Pipfile. Considering this to be the project home.
Pipfile.lock out of date, updating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock!
Installing dependencies from Pipfile.lock...
An error occured while installing!
The system cannot find the path specified.
```

**Comment by nateprewitt** [comment]
Since pipenv currently [doesn't support Windows](https://github.com/kennethreitz/pipenv#caveats) I'm not sure what the benefit of setting up AppVeyor would be, since the build will always fail. We have a lot of linux based assumptions baked into how pipenv works in its current state.

**Comment by savovs** [comment]
Pipenv is awesome. Windows support would make it even easier to share projects with people, much like npm in Node.js.

**Comment by nateprewitt** [comment]
@savovs, we added windows support about 7 months ago 😊

**Comment by uranusjr** [comment]
@nateprewitt Which is broken in a weekly basis. I’ve wanted to introduce Pipenv to many people but can’t do it responsibly at its current state. :(

**Comment by kennethreitz** [comment]
our tests are working now :)
