### ISSUE TITLE
Activate .venv on install?

### ISSUE THREAD

**Issue by skovmand** [kennethreitz/pipenv#196]
Hi Kenneth. 

I think this package is brilliant. As a newcomer to the Python Community, I think pip needs many improvements, and that whole virtualenvironment process was a pain to understand in the beginning. Pipenv solves a lot of them.

Two suggestions: 
- Adding a shortcut command for `source .venv/bin/activate`
- Activating the virtual environment automatically after installing it with e.g. `pipenv --three`

**Comment by nateprewitt** [comment]
Hey @skovmand, thanks for opening this issue.

The shortcut for activating your virtualenv already exists. `pipenv shell` should activate your virtualenv for you inside a new shell process.

As for automatically activating, the typical workflow with pipenv should actually allow you to skip activating the environment in most cases. Instead, using `pipenv run` to execute commands from inside the environment. This allows you to toggle directories with different environments without having to worry about which virtualenv you're in as well.

Hopefully this helps, and please let us know if you have any further thoughts :)

**Comment by skovmand** [comment]
Thanks Nate. 

Sorry for being ignorant about these things. Now I get the idea!
Thanks for your good work on this.

**Comment by nateprewitt** [comment]
You're not being ignorant at all, this is a slightly different paradigm and takes some adjustment. Questions are always good because this will likely help others in the future :)

Glad you're enjoying it!
