### ISSUE TITLE
spinner breaks pipenv on Python 2.6

### ISSUE THREAD

**Issue by wong2** [kennethreitz/pipenv#197]
```
➜  ~ git:(master) ✗ pipenv install flask
Installing flask...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/blindspin/__init__.py", line 31, in init_spin
    sys.stdout.write(next(self.spinner_cycle))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u280b' in position 0: ordinal not in range(128)
```

according to [blindspin README](https://github.com/kennethreitz/blindspin#install):

> Supports Python 2.7 and 3.

So I think we should either make blindspin support Python 2.6, or don't use blindspin in pipenv on Python 2.6

**Comment by kennethreitz** [comment]
@nateprewitt let's automatically disable the spinner for 2.6 for now, then try to fix the library.

**Comment by nateprewitt** [comment]
#200 is merged and disables the spinner for 2.6. Unless you have issues with kennethreitz/blindspin#1 @kennethreitz, the fix should be ready to go there when you feel like pushing a release.

**Comment by egorf** [comment]
I've experienced the same issue on Python 2.7.3 as well

**Comment by nateprewitt** [comment]
Ok, that's what I thought. We need @kennethreitz to merge the patch on blindspin and things should be fixed for Python 2.

**Comment by kennethreitz** [comment]
merged!

**Comment by nateprewitt** [comment]
Alright, this should be fixed with the next release of `blindspin`. Closing this out as fixed.
