### ISSUE TITLE
How to use pipenv + developing?

### ISSUE THREAD

**Issue by waynew** [kennethreitz/pipenv#198]
My typical workflow involves installing my package with pip's editable mode, i.e.

    /path/to/my/project$ pip install -e .

Which is how I get my dependencies - from my setup.py `install_requires` section. Mainly because I have console scripts setup.

Is this orthogonal to pipenv, or is there any (planned) support for this type of workflow?

**Comment by nateprewitt** [comment]
So the short answer is no, we don't really have a way to do this workflow right now.

We had the ability to support this to an extent with remote repositories on a version control system, but it looks like this has actually been regressed in a recent version.

I think we can at least look into supporting something like this if you can give me a more detailed breakdown of your use case. What part of your scripts need access to `install_requires` and for what purpose? Won't these already be installed via pip?

**Comment by kennethreitz** [comment]
We will likely grow this ability, as the pipfile project does.

**Comment by kennethreitz** [comment]
currently you would do the following:

```
$ pipenv shell
$ pip -e .

**Comment by waynew** [comment]
That's the approach I took - though I wasn't able to figure out how I'm supposed to get the requirements from my setup.py into a Pipfile... I could do it manually of course, that just seemed like it was contrary to the designs of pipenv 😄

**Comment by waynew** [comment]
Ah-hah! I figured out how to do what I was expecting:

    pipenv install $(pip freeze | grep -v git)

You'd have to replace `git` with whatever VCS you're using for your editable packages, but I guess this command probably does a better way of explaining the feature that I was expecting to be available.

Presumably from there there's a nice way to gather the requirements from the Pipfile into setup.py? Or is that something in the works by the distutils team?
