### ISSUE TITLE
Double (pipenv) added to shell?

### ISSUE THREAD

**Issue by illume** [kennethreitz/pipenv#20]
Notice the shell decoration gets overwritten with pipenv? However if I manually activate from the .venv it works as expected.

```
17:40:24-rene~/tmp/pipenv$ pipenv shell
Spawning environment shell (/bin/bash).
(pipenv)source /Users/rene/tmp/pipenv/.venv/bin/activate
(pipenv)(pipenv)exit
17:40:35-rene~/tmp/pipenv$ . ./.venv/bin/activate
(pipenv)17:40:47-rene~/tmp/pipenv$ 
```

The line:
```
(pipenv)(pipenv)exit
```
Should be:
```
(pipenv)17:40:47-rene~/tmp/pipenv$ 
```

I guess it could be something to do with my setup. Not sure. (osx, homebrew python 3.6).

**Comment by kennethreitz** [comment]
I noticed that with Bash as well. Not sure why it's happening.

**Comment by kennethreitz** [comment]
Ah, I think I know the source of this.

**Comment by kennethreitz** [comment]
fixed!
