### ISSUE TITLE
Feature request: Cleanup unused venvs

### ISSUE THREAD

**Issue by xi** [kennethreitz/pipenv#202]
As far as I can see I have to use the lower level `pew ls` and `pew rm {name}` to find and remove unused venvs. It would be nice if this was included in pipenv itself.

**Comment by jacebrowning** [comment]
I'm strongly in favor of the virtual environments being created in the same directory as the project for this reason. There's less "magic" and it's trivial to delete a whole project including its virtual environment.

**Comment by nateprewitt** [comment]
So to be clear @jacebrowning, the functionality you're describing is still readily available with the`PIPENV_VENV_IN_PROJECT` environment variable.

@xi I think we could introduce this kind of functionality, but I'm not sure @kennethreitz is looking to add new commands to the API. Previously, when the virtualenv directory was located with the project by default, the user could use `rm` to delete the directory and start fresh. I think the `pew` commands are somewhat analagous to that, but it does require knowledge of some of the inner workings of pipenv.

At the very least, this should be documented, but perhaps Kenneth will have some thoughts on how to he'd like to see this best addressed.

**Comment by jacebrowning** [comment]
@nateprewitt Thanks! I haven't actually read through the docs since they went up.

**Comment by abitrolly** [comment]
`pipenv` now creates `~/.local/share/virtualenvs/.../.project` file with the name of directory in it.
