### ISSUE TITLE
git autocomplete not working in subshell

### ISSUE THREAD

**Issue by chhantyal** [kennethreitz/pipenv#207]
Thanks a lot for this awesome project 👍 

I am trying out for the first time. I have git autocomplete enabled, using this https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

When I activate virtualenv using `pipenv shell`, git autocomplete doesn't work anymore

**Comment by nateprewitt** [comment]
Hey @chhantyal, could you tell me what shell you're using and what the value of `$SHELL` is in your terminal? Thanks!

**Comment by kennethreitz** [comment]
this is a side-effect of the way your shell is configured. I'd recommend getting more familiar with how your shell and its best practices.

**Comment by chhantyal** [comment]
@nateprewitt I am using `bash`.

This is default configuration on OSX. I have only added this line in ~/.profile
`source ~/.git-completion.bash`
to enable git completion. I thought it was bug because activating venv doesn't affect it.

Anyway, not big of an inconvenience. I will try to figure out what `pipenv shell` does.

**Comment by nateprewitt** [comment]
@chhantyal by default `pipenv shell` will run the command `pew workon <project_name>` where `project_name` is the directory you are using `pipenv` in. There may be restrictions in `pew` that are not playing well with your use of `source` to activate git-completion.

As Kenneth said, you'll either need to work out the conflict between `pew` and your shell setup, or you can use the `PIPENV_SHELL_COMPAT` environment variable to use a simpler `$SHELL -i` command for activation.

**Comment by alexjolly28** [comment]
> @nateprewitt I am using `bash`.
> 
> This is default configuration on OSX. I have only added this line in ~/.profile
> `source ~/.git-completion.bash`
> to enable git completion. I thought it was bug because activating venv doesn't affect it.
> 
> Anyway, not big of an inconvenience. I will try to figure out what `pipenv shell` does.

try this for Mac terminals ... 

source ~/.bash_profile

to solve the auto completion in Pipenv subshell ,Thank you

**Comment by BeyondEvil** [comment]
> > @nateprewitt I am using `bash`.
> > This is default configuration on OSX. I have only added this line in ~/.profile
> > `source ~/.git-completion.bash`
> > to enable git completion. I thought it was bug because activating venv doesn't affect it.
> > Anyway, not big of an inconvenience. I will try to figure out what `pipenv shell` does.
> 
> try this for Mac terminals ...
> 
> source ~/.bash_profile
> 
> to solve the auto completion in Pipenv subshell ,Thank you

@alexjolly28 Right, but that's a workaround and not a fix.

I'm curious to understand what the actual problem is. I'm using bash on macos.

**Comment by atkinsg** [comment]
By moving `source ~/.git-completion.bash` into `~/.bashrc` then git autocompletion is restored.
