### ISSUE TITLE
pipenv uninstall --dev xxx uninstall all packages by mistake

### ISSUE THREAD

**Issue by guyskk** [kennethreitz/pipenv#208]
pipenv 3.3.6, python 3.6
```
(validr) [guyskk@localhost validr]$ pipenv uninstall -d numpy
Un-installing [dev-packages]...
Un-installing beeprint...

Un-installing schema...

Un-installing jsonschema...

Un-installing schematics...

Un-installing voluptuous...

Un-installing pytest...

Un-installing pytest-cov...

Un-installing flake8...

Un-installing numpy...
Uninstalling numpy-1.12.0:
  Successfully uninstalled numpy-1.12.0

(validr) [guyskk@localhost validr]$ cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[dev-packages]
beeprint = "*"
schema = "*"
jsonschema = "*"
schematics = "*"
voluptuous = "*"
pytest = "*"
pytest-cov = "*"
flake8 = "*"
numpy = "*"
(validr) [guyskk@localhost validr]$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.1.10)
setuptools (34.1.1)
six (1.10.0)
wheel (0.29.0)
```

**Comment by nateprewitt** [comment]
This looks like a legacy bit of documentation that we forgot to cleanup. `pipenv uninstall --dev` removes *ALL* packages in `dev-packages` and doesn't actually process any further args. This is matching the behaviour of `--all` which will remove everything. It's intended to allow you to easily clean up dev dependencies if you no longer want them.

You can simply use `pipenv uninstall numpy` and it will remove it from the `[dev-packages]` section for you if it's listed there.

Apologies for the confusion, I'll get the argument help string updated.

**Comment by mhubig** [comment]
This is not working. And the behavior is strange and unexpected ...

```
$ pipenv install --dev green
Installing green...
...
Adding green to Pipfile's [dev-packages]...

$ cat Pipfile|rg green
green = "*"

$ pipenv uninstall green
Successfully uninstalled green-2.7.3
...
Removing green from Pipfile's [packages]...

$ cat Pipfile|rg green
green = "*"

$ pipenv uninstall --dev green
Un-installing [dev-packages] ...
```

**Comment by nateprewitt** [comment]
Thanks for pointing this out @mhubig! This was definitely an oversight and I'm surprised it's gone this long unnoticed. I've opened #325 to start the discussion on the best solution here. That should lead to a resolution for this in the next release.

**Comment by jerome-diver** [comment]
pipenv uninstall doesn't worsk at all, it doesn't remove any package from virtual site-package directory. Need to force by use pip uninstall instead. pipenv is bugged.

**Comment by frostming** [comment]
@jerome-diver you are not kind to say such a word without providing any information about what you encountered. Most users can use uninstall correctly.

**Comment by jerome-diver** [comment]
ho yes, sorry, i will be back, no time now.

**Comment by wangsha** [comment]
I'm experiencing same behavior as described in https://github.com/pypa/pipenv/issues/3529
my package is gunicorn
