### ISSUE TITLE
pipenv install failure doesn't exit with failure code

### ISSUE THREAD

**Issue by frankh** [kennethreitz/pipenv#211]
Currently if pipenv fails to install (in my case due to hashes not matching the lock file, possibly also for other reasons), the error message is pushed off the screen by normal `Collecting ...` messages and the exit code is 0, despite the fact nothing has been installed at all.

It should return an error code and finish with a big red error message

To reproduce: Remove the virtualenv, change one of the hashes in Pipfile.lock and run `pipenv install`

**Comment by nateprewitt** [comment]
Thanks for this @frankh, this is now resolved in 85d2b2e.
