### ISSUE TITLE
pipenv install removes comments from Pipfile

### ISSUE THREAD

**Issue by singleton11** [kennethreitz/pipenv#212]

**Comment by nateprewitt** [comment]
Hmm, this shouldn't be happening. It's likely part of how we're handling normalizing the Pipfile. I'll take a look into this, thanks @singleton11!

**Comment by nateprewitt** [comment]
This looks to be a limitation of our upstream `toml` library. We'll need to raise an issue there and have them implement support for comments. We could probably implement this ourselves, but it would be nicer to get this support integrated at the source.

**Comment by nateprewitt** [comment]
This is being tracked in the upstream project at uiri/toml#77. If anyone would like to take this on, that'd be super helpful! Otherwise, I'll try to start poking at this in the coming week or two.

**Comment by kennethreitz** [comment]
not anymore! 

It does remove some comments, sometimes, but it mostly preserves them now.
