### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by jungornti** [kennethreitz/pipenv#214]
Hello, it will be nice to the community, if we can know, when stable release is planned. Current version is 3.x, but current product is highly unstable and bugged. This is confusing a lot. I know, that your team want to iterate step by step and release early, that's why we are asking about stable release date.

Thank you.

**Comment by nateprewitt** [comment]
@jungornti, we're currently working on getting more of the API thoroughly tested in the CI environment. Hopefully once we have that in place the number of regressions we've recently experienced will be reduced. Please bear in mind this is an experimental project that's still less than a month old.

Is there a particular issue you're encountering in the latest version, that doesn't already have an issue open?

**Comment by jungornti** [comment]
Thank you for clarifying the situation, @nateprewitt
