### ISSUE TITLE
Configurable virtualenv location

### ISSUE THREAD

**Issue by hobarrera** [kennethreitz/pipenv#23]
As an `mkvirtualenv` user, there's one must-have feature that's become really important to me, and that's having a configurable (env variable?) default location for virtualenvs. Personally, I used `.local/share/virtualenvs`, but that's just a matter of preference.

Having them inside projects (repositories) is a bit annoying since lots of tools won't ignore them, disk-usage is harder to track, and a few other nitpicks.

---

Note: I'm aware that it may not be the most popular option. I don't mind keeping the current default, but just think that configurability would be nice.

**Comment by kennethreitz** [comment]
i'm definitely open to it in the future, but at the moment, i plan to keep the current implementation.

**Comment by hobarrera** [comment]
Are you open to PRs for this at least?

**Comment by kennethreitz** [comment]
i doubt i'll accept them, but i'll definitely take a close look at them!
