### ISSUE TITLE
Cannot execute pipenv shell properly

### ISSUE THREAD

**Issue by apollo13** [kennethreitz/pipenv#234]
See the following output:
```
➜  test-pipenv pipenv --three
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/florian/.virtualenvs/test-pipenv/bin/python3
Also creating executable in /home/florian/.virtualenvs/test-pipenv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/florian/.virtualenvs/test-pipenv
➜  test-pipenv pipenv install Django
Installing Django...
Collecting Django
  Using cached Django-1.10.5-py2.py3-none-any.whl
Installing collected packages: Django
Successfully installed Django-1.10.5

Adding Django to Pipfile's [packages]...
➜  test-pipenv pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
/home/florian/.virtualenvs/test-pipenv/bin/python: Error while finding module specification for 'virtualenvwrapper.hook_loader' (ImportError: No module named 'virtualenvwrapper')
virtualenvwrapper.sh: There was a problem running the initialization hooks. 

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/home/florian/.virtualenvs/test-pipenv/bin/python and that PATH is
set properly.
➜  test-pipenv env|grep VIRTUAL
VIRTUALENVWRAPPER_SCRIPT=/home/florian/.local/bin/virtualenvwrapper.sh
VIRTUALENVWRAPPER_PROJECT_FILENAME=.project
VIRTUALENVWRAPPER_WORKON_CD=1
VIRTUALENVWRAPPER_HOOK_DIR=/home/florian/.virtualenvs
VIRTUAL_ENV=/home/florian/.virtualenvs/test-pipenv
➜  test-pipenv which python
/home/florian/.virtualenvs/test-pipenv/bin/python

```
As you can see VIRTUAL_ENV is set properly and `which python` returns the one from the venv, but it looks like as if the executed shell is sourcing my profile again.

I am using virtualenv-wrapper manually without problems. My .zshrc has
```
source ~/.local/bin/virtualenvwrapper.sh
```
Is the anything I can do to get around this error? Please tell me if (and which) information you need.

**Comment by apollo13** [comment]
```
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
```
before sourcing the wrapper script did help -- not sure if that is a bug at all, or in which component it is :)

**Comment by nateprewitt** [comment]
@apollo13 could you verify for me that `virtualenvwrapper` is installed inside your pipenv environment with the command `pipenv run pip freeze`? I'm pretty sure this is an issue of the script you're sourcing assuming that virtualenvwrapper is already installed when it hasn't been added to that environment.

We don't officially support `virtualenvwrapper` right now and there's a possibility there's conflicting functionality, but I'm happy to take a look if the above isn't true.

**Comment by apollo13** [comment]
@nateprewitt Yes, virtualenvwrapper is not installed in the pipenv venv. The virtualenvwrapper zsh hook tries to find it's python via this: https://bitbucket.org/virtualenvwrapper/virtualenvwrapper/src/cee707f128e39623718568b47b6038e8d62c5f34/virtualenvwrapper.sh?at=master&fileviewer=file-view-default#virtualenvwrapper.sh-47:51 -- which obviously breaks for venvs.

**Comment by nateprewitt** [comment]
Yeah, so given this startup script in your profile, you'll either need to install virtualenvwrapper inside your pipenv environment before running the shell. I think that's the only advice we can give at this point since I wouldn't consider this a bug in popenv

**Comment by nhanb** [comment]
FWIW I worked around this by only sourcing `virtualenvwrapper.sh` if pipenv is not currently active, because if I'm using pipenv I'm probably not going to need virtualenvwrapper anyway. My `.zshrc` now goes like this:

```bash
if [ "$PIPENV_ACTIVE" != '1' ]; then
    [ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh
fi
```
