### ISSUE TITLE
Pipenv lock changes order of develop and default keys

### ISSUE THREAD

**Issue by singleton11** [kennethreitz/pipenv#235]
This is very painful to track it in VCS. I'd like to get more granular diff what was changed from previous lock

**Comment by nateprewitt** [comment]
This currently requires changes to how the Pipfile project API works, but is something I'd personally like to see supported. We had an older ticket for this that was closed before things were fully resolved, so we'll leave this one open for now to track.

**Comment by kennethreitz** [comment]
closing for now
