### ISSUE TITLE
Recursive use of pipenv shell

### ISSUE THREAD

**Issue by OrkoHunter** [kennethreitz/pipenv#239]
We would have to use `pipenv shell` while building a CLI project. So, once we switch to the new shell and suppose if we forgot and executed `pipenv shell` again it then creates a new shell once again and we have to exit two times to get back to the default shell.

It'd be great if we have already used `pipenv shell`, the next time it maybe gives a message saying "You're already in the pipenv shell".

**Comment by nateprewitt** [comment]
Hey @OrkoHunter, could you tell me which shell you're using?

I currently get a warning in standard bash saying `Be aware that this environment will be nested on top of 'your-project-name'` when I try to activate the shell more than once. I believe most prompts are modified to also include the virtualenv name that pipenv is using after `pipenv shell` is used once. Is this not behaviour you're seeing?

**Comment by OrkoHunter** [comment]
Hey @nateprewitt

I am using oh-my-zsh shell and I am not seeing any messages. :-/

**Comment by nateprewitt** [comment]
Ok, we can look into trying to detect if the shell has been activated and raising a message. If we go down that route I'm almost wondering if we should just prohibit running pipenv shell from inside the shell. I'm not sure if there's a real use case for allowing that in the first place.
