### ISSUE TITLE
Provide a pipenv temp command

### ISSUE THREAD

**Issue by sametmax** [kennethreitz/pipenv#24]
Testing package is a something a Python dev do quite often. But you don't want to install it on your system, so you usually create a virtualenv for that, then discard it.

pew (yes again, sorry to bother you with it) has a command to create a temporary virtualenv. We would do:

`pipenv temp`

To get into a temporary virtualenv (you and the env being move automatically in the temp dir of your OS), so you can make tests quickly and it get discarded at the next reboot or when you deactivate.

**Comment by kennethreitz** [comment]
i think that's out of scope for this project. you can still use those other tools, of course!
