### ISSUE TITLE
Comparison of package names must be case insensitive

### ISSUE THREAD

**Issue by jdno** [kennethreitz/pipenv#240]
Hi,

when trying to uninstall a package, I noticed that it stayed in the `Pipfile` even though the command output told we it would be removed. I started to dig into this thinking I discovered a bug in the uninstall command, but it seems it's a more general problem related to the way `pipenv` compares package names.

See this example:

     $ pipenv install pyyaml
     $ pipenv uninstall PyYAML

These commands successfully install and uninstall the Python package. But, the package won't be removed from the `Pipfile`, because the comparison in [project.remove_package_from_pipfile](https://github.com/kennethreitz/pipenv/blob/ed6b73c84f16e44488473c5d461b2ddfe3df6eb3/pipenv/project.py#L179) is case sensitive.

This seems to be a violation of [PEP-426](https://www.python.org/dev/peps/pep-0426/#name), which states that

> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.

The easiest way to handle this seems to be to transform the package name with something like `package_name.lower()` and `package_name.replace('-', '_')` into a "known" format, but it might also be worth it to look how `pip` deals with this. Sadly, my time is limited right now, otherwise I would have already looked into this myself.

Let me know how you want to solve this, and I'll see if I can prepare a pull request. :)

**Comment by nateprewitt** [comment]
Hey @jdno, thanks for opening this ticket! We've been battling with getting this working consistently for the last few minor versions and have open issues regarding how this affects the code in other places in #229 and #206. I'm currently in the process of redoing how we handle both Pipfile and the lockfile internally which will give us a model consistent with pep426 so we're only doing one transform before writing. We're hoping to see this land in the next week in 3.5.0.

**Comment by jdno** [comment]
Damn it, I didn't check the existing issues well enough. But I'm glad to hear you're spending more time on it than I would have, to properly fix the issue... 😉 

Should we close this then?

**Comment by nateprewitt** [comment]
@jdno, let's leave it open for now as a reminder to make sure we have proper testing in place for this kind of case. I'll wrap it into the issues we'll close out with 3.5.0.

**Comment by nateprewitt** [comment]
This should be resolved in #242 and will be released in 3.5.0.
