### ISSUE TITLE
"pipenv lock --requirements" includes dev requirements

### ISSUE THREAD

**Issue by blueyed** [kennethreitz/pipenv#245]
It should behave like `pipenv install`, where you have to specify `--dev` to install development packages explicitly.

My use case it `pip install -r <(pipenv lock --requirements) -t build/upload` to generate a directory with the packages required for the app - that should not include development packages (by default).

**Comment by nateprewitt** [comment]
This should be simple to set up, we currently have `dev` hardcoded to True for the lock command. I think this was Kenneth's original intent to just do a simple dump of everything for requirements.txt.

If @kennethreitz signs off on adding the `--dev` option to `pipenv lock` that will fix everything with a one line change. We can look into a PR at that point.

Thanks for bringing this up, @blueyed :)

**Comment by kennethreitz** [comment]
I think it should remain as is, for now.

**Comment by kennethreitz** [comment]
i might change my mind later.

**Comment by blueyed** [comment]
So what would be the recommended way to achieve a clean install without dev deps then currently?

**Comment by nateprewitt** [comment]
In the current version of pipenv, you'd need to run the command on a Pipfile without dev dependencies. That's unfortunately the only way at the moment.

I did think some more on the `--dev` parameter yesterday though and don't think that's the right approach if we ever decide to address this. A `--dev` parameter without the accompanying `--requirements` param has confusing semantics. The use of `--dev` in other situations would imply we're locking dependencies **including** dev. This suggests `pipenv lock` without `--dev` only locks the default section which isn't, and likely won't ever be, the case. There's nothing to tie that param directly to requirements without creating a secondary param specifically for dev-requirements which is also undesirable.

If maintaining the requirements.txt backwards compatibility is fundamental for your project right now, I'd suggest using something like the script below.

```python
from pipenv.project import Project
from pipenv.utils import convert_deps_to_pip

# Create pip-compatible dependency list
packages = Project().parsed_pipfile.get('packages', {})
deps = convert_deps_to_pip(packages, r=False)

with open('requirements.txt', 'w') as f:
    f.write('\n'.join(deps))
```

**Comment by blueyed** [comment]
Yes, I came to the same conclusion.

There should be a separate command for it (generating a requirements file/output) probably.

**Comment by Stibbons** [comment]
+1 to get 2 commands: `-r` for `requirements.txt` and `-d` for `requirements-dev.txt`

**Comment by blueyed** [comment]
Sorry to be deconstructive, but this is surely not happening through commenting on an issue that has been ignored from the beginning: I've even digged into the code and created a PR IIRC - but this project is just a bit too confusing.

**Comment by jcox-dev** [comment]
For those that find your way here, this seems to have been addressed in https://github.com/kennethreitz/pipenv/pull/972
