### ISSUE TITLE
Custom lock file names

### ISSUE THREAD

**Issue by jontonsoup** [kennethreitz/pipenv#248]
Is there a way to have custom lock file names? We have several dockerfile builds which have different requirements for the same repo. 

Thanks!

**Comment by nateprewitt** [comment]
Hey @jontonsoup, thanks for taking the time to start this discussion :)

At this point in time I don't believe we have any plans to allow for custom lockfile naming.

That said if you could help me better understand your project structure, I may be able to provide some advice on how to handle this. The use of subdirectories for example would allow partitioning of the Pipfiles but I'm not sure how that would interact with your overall codebase.

**Comment by jontonsoup** [comment]
Hey @nateprewitt -- thanks for responding quickly! 

We have  a jupyter notebook that runs in a Dockerfile that allows for analysis using our codebase. Our production system does not need all of anaconda (which is almost 2 gigs and makes our docker deploys a nightmare). 

We currently have two separate Dockerfiles already, and have different requirement.txt files. I'm wondering how we would make this migration?

**Comment by nateprewitt** [comment]
So I don't know if we have an elegant way to handle this situation. I see two possible solutions for the moment.

You could maintain the two separate Pipfile copies and use `pipenv lock --requirements` to generate the requirements.txt which is pretty unideal.

The other is creating a directory associated with each dockerfile and moving the Pipfile/Pipfile.lock into the top directory during the docker deploy. This is also clunky but as I said, Pipfile hasn't really been designed to handle a case like this. This may be a longer running discussion that may be worth raising in [that repository](https://github.com/pypa/pipfile).

**Comment by jontonsoup** [comment]
@nateprewitt I think we have a work around where we use pip for one and Pipenv for the other... extremely not ideal, but at least we have our day to day using sane dependency management :)

**Comment by nateprewitt** [comment]
Glad you've got something working. I'm reading up on what other package management utilities are doing in this case. It seems Ruby has handled this in a single file with platform/group definitions. I'm still unclear on how Cargo.toml would handle a case like this though.

**Comment by jontonsoup** [comment]
Thanks! Hopefully more people can input on whether this is a common use case -- but for use mission critical.

**Comment by kennethreitz** [comment]
closing for pypa/pipfile#70
