### ISSUE TITLE
Honcho Issues

### ISSUE THREAD

**Issue by jontonsoup** [kennethreitz/pipenv#249]
It appears that honcho (https://github.com/nickstenning/honcho) does not work with `pipenv run`.

Here is the example: 

```
[jonathan]: docker run -it test /bin/bash                                                                                            [~/src/consulting/eoch/test]:master
root@6047f1099378:/app# pipenv run honcho start
20:13:56 system               | server.1 started (pid=16)
20:13:56 server.1             | /bin/sh: 1: gunicorn: not found
20:13:56 system               | server.1 stopped (rc=127)
``` 

`pip shell` & `honcho start` works, but I'm not sure how to do that not interactively 

To clarify -- I have installed gunicorn properly, as it works via `shell`.

**Comment by jacebrowning** [comment]
I think you will have to run honcho via `pipenv shell` because the commands honcho will call (`gunicorn`) only exist in the virtual environment.

In my project, I had to do:

```
$ pipenv shell -c "honcho start; exit $?"
```

**Comment by jontonsoup** [comment]
@jacebrowning ah -- I didnt realize I could call `-c` like a normal shell. 

I also just prepended the PATH in the docker ENV with the virutalenv path. 

Thanks!

**Comment by nateprewitt** [comment]
So @jacebrowning is correct that this seems to be the best approach for Honcho.

This isn't ideal but it's a conflict of the both `pipenv`'s and `honcho`'s subprocess functionality. `pipenv run` is kicking off a new process with the virtualenv activated and running `honcho` which is in turn kicking off a new shell that is now back to using the standard bash environment. This is why it can't find gunicorn.

It looks like you've found some solutions though, so we'll leave this at that. Thanks for getting this information recorded @jacebrowning and @jontonsoup!

**Comment by metakermit** [comment]
`pipenv shell -c` is deprecated since 7.5.0. Any other ideas how to use honcho with it?

**Comment by metakermit** [comment]
OK, it seems this was a [honcho issue](https://github.com/nickstenning/honcho/issues/136) I was experiencing. I manage to get decent results with pipenv + honcho for running multiple processes (postgres, redis, django, celery) by using:

```
PYTHONUNBUFFERED=1 pipenv run honcho start
```
