### ISSUE TITLE
pipenv run/shell and commands that auto-reload

### ISSUE THREAD

**Issue by anlutro** [kennethreitz/pipenv#257]
I tried using pipenv with flask yesterday, and ran into an issue when running it in debug mode (which enables auto-reloading of the application when a module's code changes).

```
% pipenv run python -m myapp
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/andreas/dev/myapp/myapp/__main__.py", line 1, in <module>
    from myapp import app
ImportError: No module named 'myapp'
```

It looks like the subprocess doesn't start inside the virtualenv. It doesn't seem to make a difference if I run this with `pipenv run` or inside a `pipenv shell`. Running it inside a manually activated virtualenv works fine.

**Comment by nateprewitt** [comment]
Hey @anlutro, thanks for taking the time to open this issue. We've had similar issues with apps spawning subprocesses before (such as `honcho`) that have been solved with `pipenv shell -c honcho start`. Could you try `pipenv shell -c flask run` or `pipenv shell python -m myapp`, and see if that works? Thanks!

**Comment by anlutro** [comment]
Aha, I figured there'd be duplicate issues but wasn't sure what to search for to find them.

`pipenv shell` and `pipenv shell -c` didn't seem to make a difference:

```
$ pipenv shell python -m myapp             
python -m myapp
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
$ python -m myapp
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/andreas/dev/myapp/myapp/__main__.py", line 1, in <module>
    from myapp import app
ImportError: No module named 'myapp'

$ pipenv shell -c python -m myapp
Spawning environment shell (/usr/bin/zsh).
source /home/andreas/.local/share/virtualenvs/myapp-TkRi09Xi/bin/activate
$ source /home/andreas/.local/share/virtualenvs/myapp-TkRi09Xi/bin/activate
(myapp-TkRi09Xi) $ python -m myapp
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/andreas/dev/myapp/myapp/__main__.py", line 1, in <module>
    from myapp import app
ImportError: No module named 'myapp'
```

However, `pipenv shell flask run` seems to work.

```
$ pipenv shell FLASK_APP=myapp/__main__.py flask run
FLASK_APP=myapp/__main__.py flask run
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
$ FLASK_APP=myapp/__main__.py flask run
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
```

As does `FLASK_APP=myapp/__main__.py pipenv run flask run`. This is a bit tedious to write, though.

**Comment by nateprewitt** [comment]
I'll try to take a peek at what virtualenv is doing in flask's case v.s. what we're doing with `pipenv run` and see if there's a way to make venv persistence better with subprocesses.

This is probably the best approach for the time being though.

**Comment by nateprewitt** [comment]
Also for records purposes, the issue I was referencing above is #249.
