### ISSUE TITLE
Pipenv is not playing nice with virtualenvwrapper?

### ISSUE THREAD

**Issue by ArthurPBressan** [kennethreitz/pipenv#258]
I installed pipenv as a test, and, until now, I was using virtualenvwrapper to manage my venvs. For some reason, pipenv couldn't open a shell apparently because of virtualenvwrapper, though I'm not 100% sure.

Here's the gist:
https://gist.github.com/ArthurPBressan/681f781a875d629ecaba3c97ea1a513b

Besides pipenv not entering the shell, now every time (even after uninstalling and reinstalling virtualenvwrapper and uninstalling pipenv) I `workon` and `deactivate` a virtualenv, it shows some errors on the console, and I don't know how to fix those.

Here's a gist with the errors:
https://gist.github.com/ArthurPBressan/87a469c3201483abf7880782905e8f1b

**Comment by nateprewitt** [comment]
Hey @ArthurPBressan, this looks like it may be a duplicate of #234.

As for the continued errors, are you sure you're not still inside a pipenv shell? Do these still occur in a new terminal session?

**Comment by ArthurPBressan** [comment]
Oh, I missed that one when I looked over the issues.

And I just checked, and apparently I *was* inside a pipenv shell! I'm using the default Ubuntu terminal, but I had no indication whatsoever. 

I `exit`ed my terminal expecting to close it, but it just dumped me to the previous directory I was testing pipenv, and the errors went away.

Thanks!

**Comment by nateprewitt** [comment]
Glad it worked out, thanks for taking the time to check in on this!
