### ISSUE TITLE
pipenv .venv folder inside project root

### ISSUE THREAD

**Issue by SergeyPirogov** [kennethreitz/pipenv#259]
When I use command `pipenv --three` to create virtualenv, it init env to folder `$USER_HOME/.venvs/<name>`. Is it possible to set virtual env folder path to `$PROJECT_ROOT/.venv`

In docs I see that there is some env variable `PIPENV_VENV_IN_PROJECT` but i can't find example how to activate it.

Thanks

**Comment by kennethreitz** [comment]
In bash, `export PIPENV_VENV_IN_PROJECT=1`
