### ISSUE TITLE
Run as a module with python -m pipenv

### ISSUE THREAD

**Issue by illume** [kennethreitz/pipenv#26]
This is something you can do with virtualenv and pip. pipenv is just missing the __main__.py file to do so.

```
python3.6 -m venv anenv
. ./anenv/bin/activate
python -m pip install pygame
```

However pipenv can't run as a module.
```
$ python3.6 -m pipenv install
/usr/local/opt/python3/bin/python3.6: No module named pipenv.__main__; 'pipenv' is a package and cannot be directly executed
```

This is useful for running the script with different python interpreters in build scripts and such which use different python versions, or on different platforms where things like "pip3.6" do not exist.

**Comment by kennethreitz** [comment]
i like this idea.

**Comment by kennethreitz** [comment]
open to a PR!

**Comment by illume** [comment]
Cooking something up then...
