### ISSUE TITLE
six dependency error in vendor packages

### ISSUE THREAD

**Issue by KhasanovBI** [kennethreitz/pipenv#267]
![image](https://cloud.githubusercontent.com/assets/8990821/23836426/f89259fc-0788-11e7-8f58-385f04625428.png)

**Comment by nateprewitt** [comment]
Thanks @KhasanovBI, looks like we need to get six included in our vendored dependencies.

**Comment by kennethreitz** [comment]
fixed in master

**Comment by KhasanovBI** [comment]
Can you upload to pypi, please?
