### ISSUE TITLE
pipenv install pyupio hangs

### ISSUE THREAD

**Issue by browniebroke** [kennethreitz/pipenv#273]
I tried today to use pipenv to start a new project based on the [pyup command line](https://github.com/pyupio/pyup), but I was unable to install this package, pipenv hangs for ever. I left it running for 30 mins, where pip installs it in less than 1 min.

```bash
09:07:27 Bruno@Bruno-3.local:/Users/Bruno/pipenv_test> pipenv --two
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/Bruno/.virtualenvs/pipenv_test-efB41TrZ/bin/python2.7
Also creating executable in /Users/Bruno/.virtualenvs/pipenv_test-efB41TrZ/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/Bruno/.virtualenvs/pipenv_test-efB41TrZ
09:07:41 Bruno@Bruno-3.local:/Users/Bruno/pipenv_test> pipenv install pyupio
Installing pyupio...
⠸
```

I'm using pipenv 3.5.3, installed under python 2.7.13. Creating the virtualenv under python 2 or 3 doesn't help.

I've tried to add a print statement in my `delegator.run()` function, and the command which is hanging is 
`"/Users/Bruno/.virtualenvs/pipenv_test-efB41TrZ/bin/pip" install  "pyupio" -i https://pypi.python.org/simple`

As and alternative, I've tried both of the below which worked, but did not update my Pipfile nor Pipfile.lock:
```
pipenv shell
pip install  "pyupio" -i https://pypi.python.org/simple
```

```
pipenv run pip install  "pyupio" -i https://pypi.python.org/simple
```
Is that a known incompatibility with pyupio or [one of its dependencies?](https://github.com/pyupio/pyup/blob/master/setup.py#L17) Thanks

**Comment by browniebroke** [comment]
In case that matters, I'm on OSX.

**Comment by nateprewitt** [comment]
Hey @browniebroke, I'm unable to reproduce this on mac OS Sierra with your specified configuration. `pipenv install pyupio` seems to finish in under a minute without issue.

The only odd things I'm noticing is they have setuptools pinned to a significantly lower version (<=26.1.1) for some reason. The only other possibly conflicting package with pipenv is click but I don't see that being a problem either.

Which version of OSX are you on and could you upgrade to 3.5.4 before testing again to verify this isn't fixed?

Could you also provide the output for the following commands?

* `pipenv run python --version`
* `pipenv run pip --version`
* `pipenv run pip freeze`

Thanks!

**Comment by browniebroke** [comment]
Humm, strange, maybe something to do with my environment... I'm under El Capitan 10.11.6. 

I've tried to upgrade to pipenv 3.5.4, but the problem seems to persist.

```
17:37:50 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv run python --version
Python 3.5.2
17:45:49 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv run pip --version
pip 9.0.1 from /Users/Bruno/.virtualenvs/pipenv-test--zWB5BHt/lib/python3.5/site-packages (python 3.5)
17:45:57 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv run pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
six==1.10.0
```

**Comment by nateprewitt** [comment]
Just to clarify, other packages do install quickly/correctly?

**Comment by browniebroke** [comment]
I've tried to re-install `pipenv` under my python 3.5.2 installation, but I have a similar behaviour:
```
17:53:56 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv install pyupio
Creating a virtualenv for this project...
⠋Using base prefix '/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/Bruno/.virtualenvs/pipenv-test--zWB5BHt/bin/python3.5
Also creating executable in /Users/Bruno/.virtualenvs/pipenv-test--zWB5BHt/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/Bruno/.virtualenvs/pipenv-test--zWB5BHt
Installing pyupio...
⠋^C
Aborted!
17:57:50 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
```
And your the commands:
```
> pipenv --version
pipenv, version 3.5.4
> pipenv run python --version
Python 3.5.2
> pipenv run pip --version
pip 9.0.1 from /Users/Bruno/.virtualenvs/pipenv-test--zWB5BHt/lib/python3.5/site-packages (python 3.5)
> pipenv run pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
six==1.10.0
```

**Comment by browniebroke** [comment]
Yes that's fast:
```
17:58:45 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv install requests
Installing requests...
Collecting requests
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.13.0

Adding requests to Pipfile's [packages]...
P.S. You have excellent taste! ✨ 🍰 ✨
18:00:04 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
```

**Comment by browniebroke** [comment]
I'll try to install pyup's dependencies one by one and let you know.

**Comment by browniebroke** [comment]
I've managed to install all dependencies except one, [PyGithub](https://pypi.python.org/pypi/PyGithub). I initially thought about case sensitivity, but that's been fixed recently (#240), and it doesn't help to spell with the correct case:

```
18:07:04 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
> pipenv install PyGithub
Fixing package names in Pipfile...
Installing PyGithub...
⠧^C
Aborted!
18:09:45 Bruno@Bruno-3.local:/Users/Bruno/Desktop/pipenv-test
```

**Comment by browniebroke** [comment]
Let me know if you want more information from me. 
Otherwise, feel free to close this if no one else is able to reproduce.

**Comment by nateprewitt** [comment]
@browniebroke, yeah I can't reproduce any of this unfortunately and since this seems to be a specific package outside of the purview of pipenv I'm not sure we can do much. If you're able to reproduce this on another system, or with other packages, let us know and we can investigate further.

Thanks again for taking the time to open this ticket!

**Comment by browniebroke** [comment]
No problem, thanks for taking the time to assist and try to reproduce 👍
