### ISSUE TITLE
pipenv lock --requirements --no-hashes outputs hashes

### ISSUE THREAD

**Issue by patrick91** [kennethreitz/pipenv#274]
I was trying to run pipenv in a Dockerfile and in order to install the deps globally I use this code:

```
ADD Pipfile /src/Pipfile
ADD Pipfile.lock /src/Pipfile.lock
RUN pipenv lock --requirements --no-hashes > /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
```

since I'm developing on a mac the hashes will be different, so I'm using the `--no-hashes` option.
Unfortunately this still outputs the hashes when using `--requirements`.

Is this the intended behaviour? If so how I can properly use pipenv in a Dockerfile? I don't really need a virtualenv in this case

**Comment by nateprewitt** [comment]
Hey @patrick91, thanks for spotting this! It looks like `--no-hashes` works as expected with `pipenv lock --requirements --no-hashes` when the Pipfile.lock *doesn't* exist but not when it does. I'll try to get this patched this morning.

For the time being, I would suggest removing the `ADD Pipfile.lock /src/Pipfile.lock` requirement from your Dockerfile for now and things should work as expected.

**Comment by patrick91** [comment]
@nateprewitt thanks! That's what I did at the end :)

I'm wondering if there should be a way to install stuff globally (like `npm install -g`),
using `pipenv lock --requirements` sounds a bit like a workaround :)

**Comment by nateprewitt** [comment]
@patrick91 I haven't spent a ton of time in the Node.js realm, so forgive any ignorance here. A quick scan of the docs seems to read that this installs packages for use from any directory on the OS.

You can accomplish this with `pipenv install --system` which will use the system default `pip` installation. I wouldn't suggest this, but it does seem analogous to `npm install -g`.

If you're looking to install packages without hash checking (i.e. for any system configuration), you can use `pipenv install --ignore-hashes`. The `--requirements` option was definitely an after thought and isn't *really* a first-class option in `pipenv`. It's more of a hack to allow people to use a requirements.txt if they absolutely have to. This option may end up phased out in the future.

**Comment by patrick91** [comment]
Oh, I have missed that command. So with:

`RUN pipenv install --system --ignore-hashes`

It totally works! Thanks :) 

You're right, it is not a good practise to install packages globally, but inside a docker container is fine

**Comment by nateprewitt** [comment]
Alright, we're all tidied up with 86ef9b8. I'm going to wait a few days to cut the hotfix since this isn't in the critical path. That will give some time for any other bugs in 3.5.4 to float in and hopefully get wrapped up.

Thanks again @patrick91! Glad you've got things working now.

**Comment by patrick91** [comment]
No worries :) 

The only usecase I see is when using Amazon elasticbeanstalk with the default python configuration, it requires a `requirements.txt` file.
