### ISSUE TITLE
How do we install packages like troposphere[policy]?

### ISSUE THREAD

**Issue by nikolay** [kennethreitz/pipenv#277]

**Comment by nateprewitt** [comment]
Hey @nikolay, you can specify this in the format:

```troposphere = { extras = ['policy'] }```

**Comment by nikolay** [comment]
Great! If possible, add this to your examples!

**Comment by nikolay** [comment]
@nateprewitt Sorry, but what if I want to specify a version?

**Comment by nateprewitt** [comment]
For a version, you can specify additional values inside the table.

`troposphere = { extras = ['policy'], version = '1.5.6' }`

You can find more information on the Pipfile syntax in the [official Pipfile repository](https://github.com/pypa/pipfile).
