### ISSUE TITLE
Installing packages from git repositories

### ISSUE THREAD

**Issue by jeeyoungk** [kennethreitz/pipenv#279]
I couldn't find instructions on installing packages from git repositories. https://github.com/pypa/pipfile seem to suggest that the spec is:

```
pinax = { git = 'git://github.com/pinax/pinax.git', ref = '1.4', editable = true }
```

but i'm not sure whether this is supported or implemented.

I wouldn't mind making a pull request if it's not done yet.

**Comment by nateprewitt** [comment]
Hey @jeeyoungk, thanks for taking the time to check in on this. Version Controlled dependencies were implemented in 3.5.0, so it should be working fine now. Please let us know if you're encountering problems.
