### ISSUE TITLE
rm flag fails without Pipfile

### ISSUE THREAD

**Issue by ryanwilsonperkin** [kennethreitz/pipenv#283]
When I create a virtualenv for my current environment, but then remove the Pipfile/Pipfile.lock, the command `pipenv --rm` will fail.

```bash
pipenv install  # instantiate
rm Pipfile Pipfile.lock
pipenv --rm  # fails
```

I'm running:
- pip 9.0.1
- Python 2.7.13
- pipenv 3.5.4

See full output below:
<details>

```
~  pipenv install
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋New python executable in /Users/ryan/.virtualenvs/ryan-a3k9euAf/bin/python2.7
Also creating executable in /Users/ryan/.virtualenvs/ryan-a3k9euAf/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/ryan/.virtualenvs/ryan-a3k9euAf
No package provided, installing all dependencies.
Pipfile found at /Users/ryan/Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
⠸Locking [packages] dependencies...
⠴Updated Pipfile.lock!
Installing dependencies from Pipfile.lock...
⠦
⠴
To activate this project's virtualenv, run the following:
 $ pipenv shell
~  rm Pipfile*
~  pipenv --rm
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 713, in cli
    loc = project.virtualenv_location
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 76, in virtualenv_location
    c = delegator.run('pew dir "{0}"'.format(self.virtualenv_name))
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 57, in virtualenv_name
    sanitized = re.sub(r'[ $`!*@"\\\r\n\t]', '_', self.name)[0:42]
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 32, in name
    self._name = self.pipfile_location.split(os.sep)[-2]
AttributeError: 'NoneType' object has no attribute 'split'
```

</details>

**Comment by nateprewitt** [comment]
Hey @ryanwilsonperkin, thanks for taking the time to open this. We're definitely making an incorrect assumption here that the Pipfile will always exist with the standard cli commands. The virtualenv location that ``--rm`` is trying to remove is bound to the name of the directory the Pipfile resides in. Without that information, we won't be able to run remove reliably.

Since we don't really have a way to store this kind of information without the user navigating to the project directory, it's probably best to raise an exception when a Pipfile can't be found. I'll try to throw this together today or tomorrow, but PRs are welcome as well.

**Comment by ryanwilsonperkin** [comment]
@nateprewitt I'd be happy to take a crack at a PR this evening. Anything in particular I should know about contributing?

**Comment by nateprewitt** [comment]
@ryanwilsonperkin, nothing particular for contribution. If you open the PR, we'll take a look and see if anything needs tweaking and then should be ready to merge it.

On second glance, I think simply printing a message with click should do the trick. We only want to run `rm` if the Pipfile exists. If not, we should just tell the user we can't find the project.

**Comment by ryanwilsonperkin** [comment]
@nateprewitt from a UX perspective would you prefer that `virtualenv_exists` returns `False` when no Pipfile can be found? That would cause the error
```No virtualenv has been created for this project yet!```
to be printed, which isn't technically true and might confuse a user.

We could choose instead to first check `project.pipfile_exists` and print a different error, but that might not be helpful to the user either, who just wants to delete the virtualenv they expect to be related to the current directory.

Side note: as a user, it was my impression that the virtualenv was based on the directory, not the Pipfile in the directory.

**Comment by nateprewitt** [comment]
So this is slightly complicated and I don't know if there's a perfect solution with the given architecture for how we handle "projects".

A project is the combination of a directory containing the Pipfile, the exact path of that directory (in a default configuration at least), and the location of the virtualenv (either placed with `pew` or a local `.venv` directory).

The Pipfile location is the basis all of these pieces are built around, so a lack of Pipfile actually means we don't know what the user is asking. The user doesn't have to be in the project directory to access the project, any subdirectories to depth `n` where `n` is the value of `PIPENV_ENV_MAXDEPTH` or a default of 3. If the virtualenv is located in `.venv` it's based on the exact directory of the Pipfile, and if it's run by `pew` it's the Pipfile's current directory name + a hash of the file path. While we could assume the user is trying to act on their current directory, Pipenv has semantics that mean this may not be the case. It may also lead to accidentally deleting a virtualenv they didn't mean to.

For those reasons, I'm thinking simply adding the Pipfile check is the least intrusive solution for now. If we can't find a Pipfile, we don't know which virtualenv the user is referring to, and can't do anything. Technically, the no-name virtualenv doesn't "exist" in this case, so I don't think the original error is completely wrong. Specificity doesn't hurt though, so I think we can print an error that the "project isn't initialized" when there isn't a Pipfile present.

**Comment by nateprewitt** [comment]
Sorry, to directly answer your question, checking `project.pipfile_exists` first is what I'm referring to here. We want to check that and print an appropriate error message if necessary, before running `--venv` or `--rm`.
