### ISSUE TITLE
Set default python version (--two/--three) based on requires.python_version

### ISSUE THREAD

**Issue by urbaniak** [kennethreitz/pipenv#286]
So you don't need to care which python version project requires, if it's specified in the Pipfile.

It may go further and use specified there python version (instead of just `--two/--three` switch).

if it's possible to get that upstream I'm happy to work on PR.

**Comment by nateprewitt** [comment]
Thanks for opening this @urbaniak, I think adding support for some of the `[requires]` options could be useful but have some concerns. If we did implement something like this, it may be difficult to detect where a certain python version lives on the system. We can hope that `pythonX.X` is symlinked from /usr/bin but I don't know if that's going to be guaranteed.

I also think we'll definitely need an "opt-out" setting for this. A user who wants to install a package from Pipfile with their own options/requirements shouldn't be required to change the Pipfile or move outside of `pipenv` to install.

I'm going to tag @kennethreitz to get his thoughts before you start working on anything.

**Comment by kennethreitz** [comment]
we could special case `requires_python`and infer "3.6" to == `--three`.

**Comment by kennethreitz** [comment]
That's what I'm dong on Heroku, currently,

**Comment by dahlia** [comment]
> If we did implement something like this, it may be difficult to detect where a certain python version lives on the system. We can hope that `pythonX.X` is symlinked from /usr/bin but I don't know if that's going to be guaranteed.

Tox's approach might work for Pipenv as well.  Tox simply shows an error when it fails to find the interpreter.

**Comment by iandanforth** [comment]
For anyone coming here from a search the official docs now describe how this functionality can be used - [Specifying Versions of Python](http://pipenv.readthedocs.io/en/latest/basics/#specifying-versions-of-python)
