### ISSUE TITLE
Provide a way to find required deps from the code

### ISSUE THREAD

**Issue by sametmax** [kennethreitz/pipenv#29]
You will not always start with a fresh project. Sometime you will have a project that works but is not cleanly structured and you want to convert it.

Tools like [pipreqs](https://github.com/bndr/pipreqs) allow you to scan your project, find the import of 3rd party tools and turn them into a requirements.txt file.

We can imagine use case for pipenv:

- `pipenv finddeps` which does what pipreqs do, but only output it instead of saving it. Using `--save` would save it in the toml file.
- `pipenv init`, which takes a non pipenv project, run findeps in it and then create the toml file with it.

**Comment by kennethreitz** [comment]
No.

**Comment by piccolbo** [comment]
Is this kind of terse answer covered in https://www.kennethreitz.org/essays/be-cordial-or-be-on-your-way ?
