### ISSUE TITLE
Support Arbitrary Environments

### ISSUE THREAD

**Issue by pbdeuchler** [kennethreitz/pipenv#291]
`pipenv` supports the `--dev` option to create a separate environment. It would be awesome to be able to support arbitrary environments with something like `--env dev` or `--env prod`. Until then, I can't use this for sufficiently complex apps that have separate testing, dev, and prod dependencies

**Comment by kennethreitz** [comment]
not happening!

**Comment by pbdeuchler** [comment]
Dang, can I ask why not? this would allow me to use pipenv globally, instead of having to revert to my old virtualenvwrapper workflow for work/complex side projects

**Comment by kennethreitz** [comment]
this was an explicit design decision.
