### ISSUE TITLE
pipenv shell loses history

### ISSUE THREAD

**Issue by myoung34** [kennethreitz/pipenv#297]
it seems as though the launch into a new shell causes a weird history chain.

For example:

```
$ pip
-bash: fab: command not found
$ pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
$ history | tail -n 5 | grep fab
500  history | tail -n 5 | grep fab
$ exit
exit
$ history | tail -n 5 | grep fab
 1406  fab
 1408  history | tail -n 5 | grep fab
$ pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
$ history | tail -n 5 | grep fab
  497  history | tail -n 5 | grep fab
  500  history | tail -n 5 | grep fab
```

**Comment by nateprewitt** [comment]
Hey @myoung34, thanks for taking the time to open this issue! So this is unfortunately a side effect of spawning a new shell process. The best option for launching these commands is using the `subprocess` module so I'm not sure if we have a clear way to preserve bash history here.

**Comment by myoung34** [comment]
Yea, I'm not sure either. It's just annoying and sets a weird expectation
