### ISSUE TITLE
Support for editable installs

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#3]
Currently, we cannot convert a `pip install -e ....` to `Pipfile`'s format.

**Comment by kennethreitz** [comment]
Done!

**Comment by abdulhaq-e** [comment]
Is there a way to use it with `pipenv install`?

**Comment by wkretzsch** [comment]
@abdulhaq-e: It appears this feature has regressed. 
 See https://github.com/kennethreitz/pipenv/issues/313

**Comment by kennethreitz** [comment]
working on master

**Comment by ericfrederich** [comment]
What about installing the project you're working on as editable, like `pip install --editable .` would do?  Is this possible?

**Comment by wkretzsch** [comment]
`python setup.py develop` appears to work for me?

**Comment by ericfrederich** [comment]
@wkretzsch, would you run that as `pipenv run python setup.py develop`?

**Comment by wkretzsch** [comment]
Right.  I run it from inside a pipenv shell

```
pipenv shell 
# wait for virtualenv to load
python setup.py develop
```

**Comment by wkretzsch** [comment]
I think the develop command is only supported by `setuptools`.

Here is the head of my `setup.py`
```
#!/usr/bin/env python
from setuptools import setup, find_packages

setup (
# ...
 ```

**Comment by exhuma** [comment]
What about adding a `-e/--editable` flag to `pipenv install`? The flag seems to be currently free. At least in version 8.3.2

**Comment by techalchemy** [comment]
@exhuma 9.0.1 has been out for some time and editable installs have been supported via `-e` for some time

**Comment by immunochomik** [comment]
I have version 9.1.0 and  -e option is not there, it does not appear in pip install -h and it does not work. So @techalchemy I do not understand is it there or not ?

**Comment by techalchemy** [comment]
It is not an argument to the command line any more than the name of a package would be considered an argument, which is why it doesn’t appear in help. It is passed as a part of a requirement, not as an option to pipenv. So yes, as stated, it remains supported, please attempt to use it and file an issue if you find a problem with it.
