### ISSUE TITLE
--three doesn't work

### ISSUE THREAD

**Issue by msztolcman** [kennethreitz/pipenv#30]
I have empty directory:

> % ls -la
> total 0
> drwx------   2 mysz  staff  -  68 23 sty 08:28 ./
> drwxr-xr-x  24 mysz  staff  - 816 23 sty 08:25 ../

So install some module that requires Py3:

> % pipenv --three install fileperms
> Creating a Pipfile for this project...
> Creating a virtualenv for this project...
> New python executable in /Users/mysz/tmp/asd/.venv/bin/python2.7
> Also creating executable in /Users/mysz/tmp/asd/.venv/bin/python
> Installing setuptools, pip, wheel...done.
> 
> Virtualenv location: /Users/mysz/tmp/asd/.venv
> Installing fileperms...
> Collecting fileperms
>   Using cached fileperms-1.0.4-py2.py3-none-any.whl
> Installing collected packages: fileperms
> Successfully installed fileperms-1.0.4
> 
> Adding fileperms to Pipfile's [packages]...

Above is line:

> New python executable in /Users/mysz/tmp/asd/.venv/bin/python2.7

And in fact, there is virtualenv with python2 instead of python3.

My python3 version:

> % python3 --version
> Python 3.6.0

**Comment by kennethreitz** [comment]
just `$ pipenv --three`, no other arguments.
