### ISSUE TITLE
Setting exact version is not intuitive.

### ISSUE THREAD

**Issue by lunemec** [kennethreitz/pipenv#302]
Hi, I wanted to freeze my versions in Pipfile, and I just wanted to point out, that there is no doc (that I could find) how to do this.

Say I want version of maya 0.1.8, so I created Pipfile:
```
[packages]
maya = "0.1.8"
```
This however gives error: `can't install maya0.1.8`. After going through the code of pipenv, it just concats the package name + version inside "". 

To fix the problem, I had to edit "0.1.8" to "==0.1.8". I get why this is there, because of comparison operators "=<>". But there could be at least mention of this in readme, or it could be smart about exact match version - when there is no * or =<>.

Thanks for awesome project!

**Comment by kennethreitz** [comment]
we should add this to the docs
