### ISSUE TITLE
Zsh shell give error when sourcing pipenv for completion purposes

### ISSUE THREAD

**Issue by thepreacher** [kennethreitz/pipenv#304]
I have the following in my .zshrc
`eval "(env _PIPENV_COMPLETE=source pipenv)"`

on starting the shell I get the error

`Traceback (most recent call last):
  File "/Users/me/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/me/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 692, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/Users/me/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click_completion.py", line 297, in _shellcomplete
    echo(get_code(prog_name=prog_name, env_name=complete_var))
  File "/Users/me/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click_completion.py", line 385, in get_code
    from jinja2 import Template
ModuleNotFoundError: No module named 'jinja2'`

How do I resolve this? BTW I'm using Conda to manage my python installations. Thanks for a great tool.

**Comment by nateprewitt** [comment]
Hey @thepreacher,  `jinja2` should be included in our vendored dependencies as of the latest release (3.5.5).  If you're still experiencing this in the latest release, please let us know and we can look into this further. Thanks for taking the time to look open this issue and hopefully upgrading solves things.

**Comment by thepreacher** [comment]
Thanks @nateprewitt, to the response. So what I tried was uninstall pipenv using `pipsi uninstall pipenv` then I reinstalled it with `pipsi install pipenv`. I restared iterm and still had the error above poping up. Bellow is the log from the install of pipenv. I've checked and pipenv is definately version (3.5.5)

`➔ pipsi install pipenv`
`  Running virtualenv with interpreter /Users/me/.local/venvs/pipsi/bin/python3.6`
` Using real prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6'`
 ` New python executable in /Users/me/.local/venvs/pipenv/bin/python3.6`
  `Also creating executable in /Users/me/.local/venvs/pipenv/bin/python`
 ` Installing setuptools, pip, wheel...done.`
  `Collecting pipenv`
  `Collecting virtualenv (from pipenv)`
  `Using cached virtualenv-15.1.0-py2.py3-none-any.whl`
  `Collecting pew>=0.1.26 (from pipenv)`
  `Using cached pew-0.1.26-py2.py3-none-any.whl`
  `Requirement already satisfied: pip in ./.local/venvs/pipenv/lib/python3.6/site-packages (from   pipenv)`
  `Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)`
  `Using cached pythonz_bd-1.11.4-py3-none-any.whl`
  `Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)`
  `Requirement already satisfied: setuptools>=17.1 in ./.local/venvs/pipenv/lib/python3.6/site-  packages (from pew>=0.1.26->pipenv)`
  `Collecting resumable-urlretrieve; python_version == "3.6" (from pythonz-  bd>=1.10.2->pew>=0.1.26->pipenv)`
  `Using cached resumable_urlretrieve-0.1.5-py2.py3-none-any.whl`
  `Requirement already satisfied: appdirs>=1.4.0 in ./.local/venvs/pipenv/lib/python3.6/site-  packages (from setuptools>=17.1->pew>=0.1.26->pipenv)`
  `Requirement already satisfied: packaging>=16.8 in ./.local/venvs/pipenv/lib/python3.6/site-  packages (from setuptools>=17.1->pew>=0.1.26->pipenv)`
  `Requirement already satisfied: six>=1.6.0 in ./.local/venvs/pipenv/lib/python3.6/site-packages   (from setuptools>=17.1->pew>=0.1.26->pipenv)`
   `Collecting requests (from resumable-urlretrieve; python_version == "3.6"->pythonz-bd>=1.10.2->pew>=0.1.26->pipenv)`
   ` Using cached requests-2.13.0-py2.py3-none-any.whl`
  ` Requirement already satisfied: pyparsing in ./.local/venvs/pipenv/lib/python3.6/site-packages   (from packaging>=16.8->setuptools>=17.1->pew>=0.1.26->pipenv)`
  ` Installing collected packages: virtualenv, requests, resumable-urlretrieve, pythonz-bd, virtualenv-clone, pew, pipenv`
`
   Successfully installed pew-0.1.26 pipenv-3.5.5 pythonz-bd-1.11.4 requests-2.13.0 resumable-  urlretrieve-0.1.5 virtualenv-15.1.0 virtualenv-clone-0.2.6
    Linked script /Users/me/.local/bin/pipenv`
`
   Done.
`

Hope this gives you a bit more info for you to help me.
Cheers.

**Comment by nateprewitt** [comment]
Have you tried installing pipenv with pip instead of pipsi? I'm unfortunately unable to access a terminal right now to do any testing but I wasn't able to reproduce this in initial tests this morning.

**Comment by thepreacher** [comment]
No I haven't tried that. I'll do a update asap. Thanks.

**Comment by thepreacher** [comment]
I uninstalled the version installed by `pipsi` and did a `pip install pipenv` into the root miniconda site-packages. Unfortunately the error still persist. The only way to get rid of the error is to comment it out for now.

**Comment by nateprewitt** [comment]
I'll try to give this a closer look on Monday and see if we can get any more info. Thanks for letting us know about this @thepreacher.
