### ISSUE TITLE
execute `pipenv shell` into virtualenv , but there is no change terminal

### ISSUE THREAD

**Issue by mingmings** [kennethreitz/pipenv#307]
execute pipenv shell into virtualenv , but there is no change terminal

![image](https://cloud.githubusercontent.com/assets/3365500/24793429/98981ab0-1bb4-11e7-8831-9d79d399f093.png)

I don't know what happened ...

**Comment by nateprewitt** [comment]
Hey @mingmings, thanks for opening this. This is actually a dup of #269. The issue you're encountering is related to `pew` and more information can be found in berdario/pew#77.

If you'd prefer to not use `pew` to manage your shell, `pipenv shell -c` should function as you expect.

**Comment by mingmings** [comment]
@nateprewitt `pipenv shell -c` works well, tks

**Comment by studiozandra** [comment]
"pipenv shell -c" unfortunately doesn't work for me on Windows (and I just discovered the docs confirm this). But, at least VS Code's shell selector display which shell you are in currently. 
![pipenv-Capture](https://user-images.githubusercontent.com/17014512/113238919-659b3000-9245-11eb-9fd3-8def961a7e9b.PNG)
