### ISSUE TITLE
No documentation for how to install specific versions of dependencies

### ISSUE THREAD

**Issue by XenGi** [kennethreitz/pipenv#308]
I want to have django 1.x in my project because the 2.x release could break things. I can't find any docs on how to do this. I tried `pipenv install django<=2.*` or `pipenv install django=='<2.*'` but it doesn't work.
`pipenv install django==1.*` seems to work but my Pipfile then has the line `Django = "==1.*"` which looks wrong.

Any docs on this would be nice.

**Comment by nateprewitt** [comment]
Hey @XenGi, thanks for checking in on this. I'm able to run both of your commands in the format `pipenv install 'django<=2.*'`. This is the same format you would have to use with pip as well. 

If you specify a wildcard minor version like `django==1.*` we really can't be any more specific than `Django = "==1.*"`. If the question was about the formatting of `Django = "==1.*"` looking wrong, that's correct and our TOML representation of dependencies.

You can find docs for the Pipfile project which cover these cases [here](https://github.com/pypa/pipfile). 

Feel free to let us know if you have any further questions.

**Comment by XenGi** [comment]
Thx this helped me alot.
