### ISSUE TITLE
pipenv unistalls dev-packages on pipenv update

### ISSUE THREAD

**Issue by gregorias** [kennethreitz/pipenv#309]
In pipenv version 3.5.6, 'dev-packages' are not considered during the update operation.

Steps to reproduce:

    mkdir project && cd project
    pipenv install
    pipenv install --dev flake8
    pipenv update

Pipenv installs flake8 and adds it to Pipfile as a dev-package (as expected).

However `pipenv update` purges flake8. Also, `pipenv update --dev` purges and reinstalls flake8. The expected behavior is that pipenv does not delete dev-packages on any update operation.

**Comment by nateprewitt** [comment]
Hey @gregorias, thanks for taking the time to open this. So the help message for `pipenv update --help` seems pretty clear, and seems consistent with your observed behaviour. The `update` command "Updates pip to latest version, uninstalls all packages, and re-installs them to latest compatible versions."

Just like install, you'll only get dev packages when you specify `--dev`. This was a design decision made by Kenneth so he'd have to weigh in on change, but the current design seems reasonable to me.

**Comment by gregorias** [comment]
Hi @nateprewitt, thank you very much for quick response! I have one left-over question and remark so as to make the point of contention more explicit. 

My gripe is that the dev packages are just removed without the `--dev` flag. I believe that this makes sense when you think about it, but documentation is ambiguous on that issue. The line (emphasis mine):

> uninstall all packages and re-installs **them** to latest compatible version.

suggests that all packages that are uninstalled are reinstalled. So pipenv should either not touch the dev-packages at all, or remove and re-install them. I suspect that the former might lead to some Python environment consistency problems, and that is why it is not done this way. Anyway, it might be just a tiny bit more helpful if docs made this case clear. I can do the change and a PR if a maintainer agrees.

Hope this issue doesn't waste too much of anybody's time.

**Comment by nateprewitt** [comment]
Thanks for clarifying @gregorias. I'm more than happy to review a PR with documentation/help message clarifications if you feel like putting one together :)

**Comment by nateprewitt** [comment]
Resolved with better help message in #317.
