### ISSUE TITLE
Non-public package not installing

### ISSUE THREAD

**Issue by isaacsanders** [kennethreitz/pipenv#311]
Hey all,

I am working with a package that isn't in `https://pypi.org/simple` and when the CLI tries to `proper_case(package_name)` the package, my installation fails erroneously, as the package is in a different source that I have listed in my Pipfile. The error below:

```
Error:  Unable to find package <package-name> in PyPI repository.
```

Led me to the culprit. The `proper_case` function in the `util` module only statically checks the `https://pypi.org/simple` repo. It is not immediately obvious to me how to fix this, but it is not correct behavior.

**Comment by nateprewitt** [comment]
Hey @isaacsanders, do you have your other repository listed under `[sources]` in your Pipfile? You are correct that `pipenv` will only verify package names against `pypi.org/simple` and that's intentional. We are only using this as a best effort method and proper casing from 3rd party repos who aren't adhering to PEP423 cause problems.

Could you provide the traceback you're getting (if any) and the format you've used to declare your third-party dependency in your Pipfile?

**Comment by isaacsanders** [comment]
It is listed as a source, and the Pipfile.lock has interpreted it correctly. I copied the format used to declare the pypi repo, and the was able to install a package with pip and `-i`.

My dependency isn't in my pipfile, but one I was trying to install from the command line with the lock flag.

There was no traceback.

**Comment by nateprewitt** [comment]
So I'm a little confused about how you were originally trying to accomplish this.

My current understanding is you listed the source in your Pipfile, tried `pipenv install --lock package`, and then received the error? I can't reproduce this locally, so I'm going to need more information on how you're attempting to install the package, and what you're expecting the end result to be.

**Comment by isaacsanders** [comment]
I added the remote pypi source under [[source]]. I then tried to install and lock the version of my remote package. I the. Received the error.

**Comment by isaacsanders** [comment]
Let me try this again.

1. I start with a Pipfile with two sources:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
url = "https://a-real-pypi-interface.not-pypi-org.com/simple"
verify_ssl = true

[packages]
foo = "*"
bar = "*"
```

2. I `pipenv install --lock`.
3. The Pipfile.lock has both sources portly generated in it.
4. I `pipenv install --lock third-party-package` which exists in "https://a-real-pypi-interface.not-pypi-org.com/simple".
5. I get:

```
Error:  Unable to find package third-party-package in PyPI repository.
```

**Comment by isaacsanders** [comment]
I was expecting `third-party-package` to be installed from the other source and its version locked in the lockfile.

**Comment by isaacsanders** [comment]
My goal in using pipenv is that I want to be able to reliably clone a repository with a Pipfile, maybe not necessarily know which python version to use (but that would be a nice feature for the Pipfile folks), and install the set of packages it contains at the version with which I developed in the repository on another machine.

**Comment by nateprewitt** [comment]
I'm confused as to how this error could be bubbling up. We only use `proper_case` in one place which has a try/except block around it to catch this exception. There shouldn't be a case where this exception actually touches anything. Could you provide the version of pipenv you're using?

**Comment by isaacsanders** [comment]
I just saw this comment.
