### ISSUE TITLE
Missing LICENSE in the tar.gz file

### ISSUE THREAD

**Issue by junaruga** [kennethreitz/pipenv#321]
There is no `LICENSE` file in the tar.gz archive file.

```
https://pypi.python.org/pypi/pipenv
  pipenv-3.5.6.tar.gz
```

```
$ tar tzvf pipenv-3.5.6.tar.gz
...
-rw-r--r-- kennethreitz/staff   8856 2017-04-03 14:12 pipenv-3.5.6/PKG-INFO
-rw-r--r-- kennethreitz/staff   6490 2017-03-15 22:08 pipenv-3.5.6/README.rst
-rw-r--r-- kennethreitz/staff     59 2017-04-03 14:12 pipenv-3.5.6/setup.cfg
-rw-r--r-- kennethreitz/staff   2536 2017-03-15 22:08 pipenv-3.5.6/setup.py
```

I want you to include the license file in it.

Thanks.

**Comment by nateprewitt** [comment]
Thanks for pointing this out @junaruga! I've added 3b2fb4c which introduces a MANIFEST.in to add the necessary files. Things should be fixed in the next release.

As for back porting the LICENSE, I'm not sure what our options are there. @kennethreitz?

**Comment by junaruga** [comment]
@nateprewitt oh quick! Thanks!
