### ISSUE TITLE
Proposal: pipenv install with --path

### ISSUE THREAD

**Issue by junaruga** [kennethreitz/pipenv#322]
Hello,

Right now `pipenv install` installs the `vritualenv` environment to the directory `$HOME/.local/share/virtualenvs`.
I want to specify the the directory path with command line option.

```
$ pipenv install
Creating a virtualenv for this project...
...
Virtualenv location: /home/jaruga/.local/share/virtualenvs/pipenv-E-4hsA7t
...
```

It is like this.

```
$ pipenv install --path vendor/venv
```

I think that setting the `path` is a typical workflow for Ruby's same kind of tool Bundler (the command is `bundle`) [1].
So, I want the feature for `pipenv` too.

```
$ bundle install --path vendor/bundle 
```

How do you think?

By the way, I am really happy to find `pipenv` today.
I knew this kind of the tool to create clean environment for Ruby's Bundler, Perl's Carton, PHP's Composer. However I did not know it for Python.
Thank you for `pipenv`.

[1] http://bundler.io/

**Comment by nateprewitt** [comment]
Hey @junaruga, thanks for opening this issue. We've discussed this option in the past and I believe the conclusion from Kenneth is we won't support something like this right now. Ideally, we'd want to store this kind of information with the project like Bundler does so users don't have to type `--path` with every command. You can find the discussion on that in #252.

**Comment by nateprewitt** [comment]
As a side note, setting the environment variable `PIPENV_VENV_IN_PROJECT` will store the virtualenv with the project in a directory called `.venv` relative to the project path. That's the closest option we have currently.

**Comment by junaruga** [comment]
@nateprewitt oh okay, the environment variable is good enough. Thanks.

```
$ PIPENV_VENV_IN_PROJECT=1 pipenv install
Creating a virtualenv for this project...
...
Virtualenv location: /home/jaruga/git/pipenv/.venv
...
```
