### ISSUE TITLE
Emojis in Appveyor

### ISSUE THREAD

**Issue by nateprewitt** [kennethreitz/pipenv#331]
There's an issue somewhere in the stack when we run `delegator.run('pipenv install requests')` in appveyor but we're getting no useful feedback from std_err. I've tracked it down to the emojis in `easter_egg()` but I don't know if this is a problem in the subprocess or appveyor itself not supporting emojis being written to std_out. This needs further investigation which I'd welcome anyone to look into. Otherwise we'll try to get this fixed in the next few days.

As of 3.6.0 (4703650), the tests run cleanly if we bypass the `easter_egg` call. Anything after that won't be verifiable on Windows until this is resolved.

**Comment by kennethreitz** [comment]
well let's just change the test to install install something else other than requests

**Comment by nateprewitt** [comment]
@kennethreitz, that was my original thought but I wanted to see if we can at least understand why this is happening before settling for that change. Maybe I'm being too much of a purist 😜

**Comment by nateprewitt** [comment]
So it's something to do with emojis in subprocess on Windows but I can't determine why it's failing. There isn't a traceback and it just seems to die when you try to write to std_out.

I've replaced `requests` with `werkzeug` in the test and things seems to be operating as intended now.
