### ISSUE TITLE
Production-only dependencies

### ISSUE THREAD

**Issue by dahlia** [kennethreitz/pipenv#335]
I've used the practice of having dev-requirements.txt, requirements.txt, and prod-requirements in my work. While the former two can be replaced by Pipfile's `[dev-packages]` and `[packages]`, but it seems I can't find any correspondents for Pipfile.

The usual purpose of prod-requirements.txt is, for example, installing packages related to AWS or [raven][] to record server-side exceptions.

I want to sweepingly introduce Pipenv to my work, but the lack of `[prod-packages]` (or whatever we call it) prevent it from leave a single list of packages.  I need to have both Pipenv and prod-requirements.txt which share the many common items, and also need to edit both files when I change dependencies.  It's also hard to keep deployment scripts straightforward.

So I suggest Pipfile to have `[prod-packages]` list and `pipenv install` to have `-p`/`--prod` option.  Do this suggestion make sense?

[raven]: https://pypi.python.org/pypi/raven

**Comment by nateprewitt** [comment]
Hey @dahlia, thanks for taking the time to open this. This is more of a question for the [Pipfile](https://github.com/pypa/pipfile) project which is where the Pipfile specification lives. I know that when this has been asked previously Kenneth has expressed disinterest in supporting any more sections at this time. I'd take a look at issues there and possibly open one if you can't find satisfactory information.

I'd say this is unlikely to be implemented at this time unless Kenneth has changed his mind.

**Comment by dahlia** [comment]
Thanks for your answer.

I wonder how Pipenv users currently workaround this problem.  Is maintaining both Pipfile and prod-requirements.txt is the convention?

**Comment by kennethreitz** [comment]
[dependencies] should be your prod dependencies.

**Comment by kennethreitz** [comment]
[dev-dependencies] should be everything else.

**Comment by tony** [comment]
Until pipenv, I kept a `requirements/production.txt` file.

I don't use gunicorn or django-redis-cache on my local environment, but I do on prod.

I'll probably bite the bullet use [dependencies] for now. I also had to merge my ``requirements/test.txt`` into [dev-dependencies].

**Comment by MzHub** [comment]
Maybe if `pipenv` had a parameter for specifying the Pipfile name/path (and the resulting .lock would be based on that)?

Or is it against the design of pipenv?

**Comment by nateprewitt** [comment]
@MzHub, we technically have a PIPENV_PIPFILE environment variable which will allow you to specify a path for a Pipfile. I wouldn't advise using this for the above scenario though. Unfortunately, it's highly unlikely we'll add any support for additional sections or multiple Pipfiles for a single project.

**Comment by uranusjr** [comment]
@tony There’s nothing stopping you from keeping `requirements/production.txt`. I still keep it (but remove the `-r` part), and do this in production:

```
$ pipenv install --skip-lock
$ pipenv run pip install -r requirements/production.txt
```

This issue has been raised quite some times now (mine is #620, there are a few more), and I still think the current approach is not good enough. I don’t know how the Composer community make things work, but all package managers I work with (Bundler, Cargo, NPM) have some sort of ability to achieve this. Given how Python packaging ecosystem works, it would be impossible for Pipfile to replace requirements.txt, but become [another thing to learn](https://xkcd.com/927/) besides it.

**Comment by lorinkoz** [comment]
@kennethreitz 

> [dependencies] should be your prod dependencies.
> [dev-dependencies] should be everything else.

Question, every time I need to `pipenv install <package>` what should I do (best practice to comply with your statement) if:

1. <package> is dev only -> assumed `pipenv install <package> --dev`
2. <package> is production only -> assumed `pipenv install <package>`
3. <package> is both dev and production -> run both commands????

**Comment by nateprewitt** [comment]
Hi @lorinkoz, if a package is required in “both” sections, it’s a production package. `packages` will always be installed and `dev-packages` are additive for when you need to do development tasks. You only need to place the package in one section depending on whether it will be needed for the final deployment. Hopefully that clears things up.

**Comment by techalchemy** [comment]
As a small point of additional interest, if you _do_ put it in both sections, the one in `dev-packages` will just be overriden by the one in `packages`

**Comment by lorinkoz** [comment]
@nateprewitt @techalchemy Thanks for both replies :)

I still have a question. I have some production-only packages (not harmful in development but neither required.) Is there a way to flag production-only packages? Quick example: I don't use `django-redis` in all development environments because some team members are on Windows and somehow installing it is a pain?

This is just an example, I know local environments should resemble as much as possible production environments but sometimes you need to bend the rules a little bit. In those cases we can always resort to temporarily remove the package from the Pipfile, but I was hoping for a permanent solution.

Thanks again!

**Comment by kennethreitz** [comment]
There is not.

**Comment by techalchemy** [comment]
However you can use the following to only install it if not using windows:

`django-redis = {version = "*", markers = "os_name != 'nt'"}`

**Comment by petarGitNik** [comment]
@techalchemy How to skip package if production and development OS are the same (same Python version, etc)? I've looked into env markers in [PEP508][1] but I don't see any custom markers that could be used. Something like the following would be very nice to have:

`mod_wsgi = { version = "*", my_custom_env_var = "== 'production'" }`

[1]: https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by techalchemy** [comment]
The `packages` section is meant for production dependencies while `dev-packages` is meant for dev dependencies

**Comment by hjwp** [comment]
+1 for the ability to specify production-only dependencies.  for small projects, i don't want to use postgres (+ install `psycopg2`) on my dev environment. i can have it in CI if I really want.

**Comment by hjwp** [comment]
for now, using `platform_release` might work, since that's different in dev and prod:
```
"psycopg2" = { version = "*", platform_release = "==4.4.0-1065-aws" }
```

**Comment by gotexis** [comment]
@hjwp 

Hey, if I were about to do that, how should I know my `platform_release`? Isn't that susceptible to change?

**Comment by hjwp** [comment]
¯\_(ツ)_/¯

really depends on your circumstances I'm afraid.

**Comment by waketzheng** [comment]
@gotexis 
This worked for me:
```
python -c 'import platform;print(platform.release())'
# 3.10.0-693.2.2.el7.x86_64
```
And in Pipfile:
```
sentry-sdk = {version="*", platform_release ="=='3.10.0-693.2.2.el7.x86_64'"}
```

**Comment by f4z3k4s** [comment]
Any updates on this? This still seems a relevant question and @trew has a good point about `--dev` flag installing production dependencies also.

**Comment by venteto** [comment]
Agree with @trew and @f4z3k4s, and am wondering if there is an update. This is just one of a couple of issues (which seem to have been raised for years now) that prevents me from using `pipenv`.

**Comment by matteius** [comment]
@venteto I cannot say there are current PRs, but there seems to be a number of tickets around supporting named groups -- I wonder if that would be a better effort than just adding another third category that may not be sufficient for all use cases.   Also named groups broke lock generation last November, meaning if you had an alternate named category in the Pipfile that locking for the supported `[packages]` group would not generate.  (there is an open issue in the backlog about this).  There is also this ticket which is what I think we should be pursuing support for:  https://github.com/pypa/pipenv/issues/4745

If anyone has the bandwidth and ambition, @oz and myself are active enough that it should be possible to get a PR fully across the line.
