### ISSUE TITLE
requirements.txt are not installed

### ISSUE THREAD

**Issue by kakulukia** [kennethreitz/pipenv#342]
Hi! 

Some package(s) in my requirements obviously confuse pipenv so that nothing gets installed.
I end up with an empty Pipfile when executing _pipenv install_ with this requiremtens file present:

    appdirs==1.4.3
	appnope==0.1.0
	asn1crypto==0.22.0
	autopep8==1.3.1
	backports.shutil-get-terminal-size==1.0.0
	beautifulsoup4==4.5.3
	cffi==1.10.0
	cryptography==1.8.1
	decorator==4.0.11
	Django==1.10.7
	django-appconf==1.0.2
	django-bootstrap3==8.2.2
	django-compressor==2.1.1
	django-crispy-forms==1.6.1
	django-csp==3.0
	django-debug-toolbar==1.7
	django-extensions==1.7.8
	django-gravatar2==1.4.0
	django-imagekit==4.0
	django-libsass==0.7
	django-livereload-server==0.2.3
	django-modelcluster==3.1
	django-modeltranslation==0.12.1
	django-redis==4.8.0
	django-rosetta==0.7.13
	Django-Select2==5.10.0
	django-silk==1.0.0
	django-taggit==0.22.1
	django-treebeard==4.1.0
	django-undeletable==0.4.2
	django-webpack-loader==0.4.1
	djangorestframework==3.6.2
	easy-thumbnails==2.4.1
	Fabric3==1.13.1.post1
	flake8==3.3.0
	gnureadline==6.3.3
	google-api-python-client==1.6.2
	html5lib==0.999999999
	httplib2==0.10.3
	idna==2.5
	ipdb==0.10.3
	ipython==6.0.0
	ipython-genutils==0.2.0
	jedi==0.10.2
	Jinja2==2.9.6
	libsass==0.12.3
	MarkupSafe==1.0
	mccabe==0.6.1
	microsofttranslator==0.8
	oauth2client==4.0.0
	olefile==0.44
	packaging==16.8
	paramiko==2.1.2
	path.py==10.3.1
	pep8==1.7.0
	pexpect==4.2.1
	pickleshare==0.7.4
	pilkit==2.0
	Pillow==4.1.0
	polib==1.0.8
	prompt-toolkit==1.0.14
	psycopg2==2.7.1
	ptyprocess==0.5.1
	pyasn1==0.2.3
	pyasn1-modules==0.0.8
	pycodestyle==2.3.1
	pycparser==2.17
	pyflakes==1.5.0
	Pygments==2.2.0
	-e git+https://github.com/syrusakbary/pyjade.git@d8cf1d9404c759c6a2430c9a900874ab0e970cd8#egg=pyjade
	pyparsing==2.2.0
	python-dateutil==2.6.0
	pytz==2017.2
	rcssmin==1.0.6
	redis==2.10.5
	requests==2.13.0
	rjsmin==1.0.12
	rsa==3.4.2
	safety==1.4.0
	simplegeneric==0.8.1
	simplejson==3.10.0
	six==1.10.0
	sorl-thumbnail==12.3
	sqlparse==0.2.3
	tornado==4.5.1
	traitlets==4.3.2
	Unidecode==0.4.20
	uritemplate==3.0.0
	wagalytics==0.6
	wagtail==1.9.1
	wagtail-modeltranslation==0.6.0rc1
	wagtailapi==1.0rc3
	wagtailfontawesome==1.0.6
	wcwidth==0.1.7
	webencodings==0.5.1
	Willow==0.4

**Comment by kakulukia** [comment]
And the order of the status messages is weird:
    
    Requirements file found, instead of Pipfile! Converting...
    Installing dependencies from 'requirements.txt'...
    Creating a virtualenv for this project...

It should create a virtualenv first and then install stuff in it. Its done that way, but the messages say something different. :)

**Comment by nateprewitt** [comment]
Thanks for this @kakulukia, this is a problem with the order we're performing actions here. When a project isn't initialized, the Pipfile is created *after* we do these conversions, so everything gets erased.

We can fix that fairly easily, but there are some other issues with writing to the Pipfile excessively that are causing problems here too. I have most of a PR together but am trying to parse out what is required to fix this specifically and then optimizing the writes separately. I'll try to get something up tomorrow some time that will be available in the next release.

**Comment by kakulukia** [comment]
Nice!

**Comment by nateprewitt** [comment]
This should be resolved in the next release via #347. Thanks again for pointing this out @kakulukia!
