### ISSUE TITLE
Public/Private Dependency issues

### ISSUE THREAD

**Issue by isaacsanders** [kennethreitz/pipenv#343]
Hey all,

I am back with a bug, and I have already checked that I am on the latest version of Pipenv ;)

__The Problem__

We have a couple of private dependencies and plenty of public dependencies.

When trying to install with `pipenv install` with no package, we always fail to install in a clean environment.

The issue is that no matter which source is used, the underlying `pip install -r <requirements>` command fails. Either the public dependencies don't exist in the private repo, or the private dependencies don't exist in the public repo, causing either command to fail.

I have found the part of the code that causes this. In the `pip_install` function in the `cli` module, the sources are tried until they succeed, and if all sources fail, only the last is reported. For awhile, it just looked like my installation couldn't find `Flask` and `gunicorn`, an error that I thought was strange, but could deal with by scripting in anger.

__A Solution__

One way of fixing this might be to store the source used for a package in the lockfile (or somewhere) and during install create separate `requirements.txt` files for each source to install from.

If that isn't possible/simple or there is an obviously better way to do this, I would be happy to help/write code for this.

__A Note__

I would also prefer it if every unsuccessful command could be logged, preferably in the format of command-followed-by-error. While it might be more information than others want, I might have figured out this bug weeks ago if I had seen one more error message, rather than just the last one. (This may be part of a PR, if I happen to be the one who writes it)

– Isaac

**Comment by nateprewitt** [comment]
Hey @isaacsanders, thanks for opening this. Could you clarify a few things for me really quickly. Are you installing from a `Pipfile` or `requirements.txt`? Could you provide the contents of that file, and if you need to remove any sensitive data just make sure the structure of the requirement is preserved?

I'm not entirely sure how this would fail to find those packages since it *should* check every source before throwing an error. I'm particularly interested in the values of your sources again this time.

**Comment by isaacsanders** [comment]
I am installing from a `Pipfile`, but `pipenv` appears to internally generate a `requirements.txt` tempfile.

**Comment by nateprewitt** [comment]
@isaacsanders, it does create one, installs from it, and then deletes the file. Could you provide the contents of the Pipfile?

**Comment by isaacsanders** [comment]
It does check every source, but either repo doesn't mirror every package in the `requirements.txt`, so it fails for both, each for missing a package that the other source has.

**Comment by isaacsanders** [comment]
This is in the pattern of our `Pipfile`

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[[source]]
url = "https://packages.example.com/pypi/simple"
verify_ssl = true

[packages]
requests = "*"
private-package = "*"
```

**Comment by isaacsanders** [comment]
There are two distinct sets, and instead of unioning the sources, `pipenv` only succeeds on installing when the intersection satisfies the `requirements.txt`.

**Comment by nateprewitt** [comment]
@isaacsanders, thanks for the clarification, I see what you're saying now. So we need to eliminate what's been installed from one source before moving onto the next, or create a way to detect what's already been installed. I'm open to reviewing PRs for this or I'll try to take a look at this as soon as I can.

**Comment by isaacsanders** [comment]
I have a fix. `pip` has a `--extra-index-url` option. Instead of looping over the sources, I will just create a list of these `--extra-index-url` options and append them to the list of options.

**Comment by isaacsanders** [comment]
@nateprewitt @kennethreitz There is a question however.

If the package is in two repositories, which one will it install?

**Comment by nateprewitt** [comment]
@isaacsanders, we currently default to the order they are written into the Pipfile. You would need to place your internal source before the external to achieve your desired behaviour.

In the event you have mixed requirements (multiple packages in both repos with different precedence), we don't have a good solution for that. We *could* store a package by package requirement, or an extra variable for an inline table which allows optional explicit definitions for sources. I'm not sure if we're at a point to entertain that yet though. @kennethreitz, any thoughts here?

**Comment by kennethreitz** [comment]
we can't support every use case.
