### ISSUE TITLE
Allow pipenv configuration from environment variables

### ISSUE THREAD

**Issue by akalipetis** [kennethreitz/pipenv#345]
Currently, all the options of Pipenv commands are taken as flags. This is pretty cool for most cases, but there are some cases where one might prefer to have configuration from environment variables:

* When using in a build system
  * For example, let's say that you have a Dockerfile, which when built with `DEBUG=1` or similar will tell `pipenv` to install `--dev` dependencies, while normally it would not
* When using the same option in multiple commands
  * For example, let's say that for some reason I want to work using the system installation, I have to use `--system` in every command

If this is something we would like to see included, I could draft a PR with variables being `PIPENV_*`, ie `PIPENV_SYSTEM`. [This should be fairly easy since the project is using click](http://click.pocoo.org/5/options/#values-from-environment-variables).

**Comment by nateprewitt** [comment]
Hey @akalipetis, thanks for taking the time to open this issue! We do currently support a limited set of environment variables that can be found [here](http://docs.pipenv.org/en/latest/advanced.html#configuration-with-environment-variables) in our advanced documentation section.

While I could understand certain environments where you may want `--dev` or `--system` appended to all commands, I believe that's unlikely to be the common case. It also seems like it could be a frustrating feature on system with long running shells where users have forgotten this setting.

The current approach of adding `pipenv install --dev` into your docker file seems to be a reasonable solution to me that requires no added infrastructure. Is there a specific reason you feel a global environment variable is a better option in this case?

**Comment by akalipetis** [comment]
Thanks for getting back to me @nateprewitt!

My use case is the following one:

```Dockerfile
# Dockerfile
FROM python:3.6
ARG PIPENV_DEV
ENV PIPENV_DEV=$PIPENV_DEV
ENV PIPENV_SYSTEM=true

COPY Pipfile* /usr/src/app/
WORKDIR /usr/src/app
RUN pip install -U pipenv && pipenv install
```

The above Dockerfile will produce an image with development packages installed if `--build-arg=PIPENV_DEV=true` is supplied, while normally it will build the image without them. This allows for the same Dockerfile being using both while developing and deploying an application.

The only workaround I see here is something like:


```Dockerfile
FROM python:3.6
ARG PIPENV_ARGS

COPY Pipfile* /usr/src/app/
WORKDIR /usr/src/app
RUN pip install -U pipenv && pipenv install --system $PIPENV_ARGS
```

and then building this with `--build-arg='PIPENV_ARGS=--dev'`, which is Ok, but not optimal IMO.

Your counter-arguments are pretty valid too though, so I won't insist on this one. Feel free to close this if it's out of scope 😄

**Comment by nateprewitt** [comment]
@akalipetis Yeah, I agree the `$PIPENV_ARGS` isn't optimal but I think it's a sufficient solution for accomplishing the task. We've tried to keep the env args to a minimum because there's so many possibilities people could want. For that reason, I don't think we'll be supporting this feature at this time, but thanks so much for reaching out!

Please let us know if you have any more thoughts or feature requests 😄
