### ISSUE TITLE
reverse --no-hashes

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#346]
they seem to be more problematic (or perhaps *educational*) than anything.

I like the idea of switching this to `--include-hashes` or simply `--hashes` and having them off by default.

**Comment by kennethreitz** [comment]
@nateprewitt thoughts?

**Comment by nateprewitt** [comment]
@kennethreitz, I agree. I was trying to find a conversation @jacebrowning and I had a month or two ago before we added --no-hashes but can't find it. The short of my thoughts are hashes are nice but have become incredibly combersome for cross platform. While I'm usually "secure by default", this has been enough of a blocker that it's probably more useful as an opt-in.

**Comment by jacebrowning** [comment]
@nateprewitt https://github.com/kennethreitz/pipenv/issues/210 and https://github.com/kennethreitz/pipenv/issues/250 contain relevant discussion to requiring hashes.

**Comment by nateprewitt** [comment]
I started a v4.0.0 branch (we can rename if you want to try that new version scheme @kennethreitz). 93316b6 converts --ignore-hashes and --no-hashes into an inverse --require-hashes option.

**Comment by nateprewitt** [comment]
Resolved in #351.
