### ISSUE TITLE
Specifying the name for the virtualenv

### ISSUE THREAD

**Issue by jochenhebbrecht** [kennethreitz/pipenv#348]
Hi,
I was able to create a virtualenv using pipenv ($pipenv install --three --dev) and I've noticed a new virtualenv was created in ~/.virtualenvs/deploy-HshZVj8N.

However, I was wondering if I could specify the name for the virtualenv using pipenv so I could give it a more human-friendly name. Is that possible?

Jochen

**Comment by kennethreitz** [comment]
Not at this time.

**Comment by jochenhebbrecht** [comment]
Ok, thanks. But from where does it get the hashcode? And the 'deploy' word?

**Comment by nateprewitt** [comment]
Hey @jochenhebbrecht, "deploy" is the directory your project is located in, and the hash is a unique identifier for the absolute path of the project. This is to prevent accidental environment collisions.

**Comment by jochenhebbrecht** [comment]
Ok, thnx!

**Comment by toejough** [comment]
Since this issue was closed with a "Not at this time", is there a proper way/place to request something like a `--venv-name` option?  I use pyenv-virtualenv right now, and I really appreciate the ability to name my venvs.
