### ISSUE TITLE
for adoption, consider supporting pip-tools files too, controlled by environment variable (or auto detected)

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#352]

**Comment by JonasGroeger** [comment]
It would be great to be able to incorporate `requirements.in` files from pip-tools

**Comment by erinxocon** [comment]
@kennethreitz is this supported with the new pip-tools dependency? Or was it closed for other reasons/

**Comment by kennethreitz** [comment]
closed because it's not happening :)
