### ISSUE TITLE
Does not warn or error on conflicting version requirements

### ISSUE THREAD

**Issue by Diggsey** [kennethreitz/pipenv#354]
For example, if the `pipfile` specifies a dependency with version `<=2.5.1`, while the same package also occurs as a transitive dependency with version `>=2.6.0`, then both `pipfile` and `pipfile.lock` will agree that the version is `2.5.1`, but it will silently install `2.6.0` in the virtualenv, without showing any warnings or errors about the conflicting requirements.

**Comment by nateprewitt** [comment]
Hey, thanks for checking in on this. We're currently aware of this and tracking the progress in #298. We have an open PR that will attempt to make this a little less subtle, but there are a couple snags that still haven't been resolved. `pip` itself doesn't actually handle the transitive dependency problem, but `pipenv`'s behaviour is currently even more out of line than `pip`. We'll hopefully have this sorted in a future release.
