### ISSUE TITLE
`pipenv run --no-interactive` suppresses stdout

### ISSUE THREAD

**Issue by mrlamroger** [kennethreitz/pipenv#360]
`pipenv run --no-interactive -- python -c 'print("hi")'` doesn't print to stdout. Is this expected?

I'm not familar with no interactive mode.

**Comment by nonylene** [comment]
--no-interactive was removed at https://github.com/kennethreitz/pipenv/pull/320 . 

What if updating pipenv ( `pip install -U pipenv` )?

**Comment by nateprewitt** [comment]
@mrlamroger, @nonylene is correct. `--no-interactive` is no longer a supported option in the latest versions of pipenv. The point of `--no-interactive` was to suppress output to devices that didn't have or properly support a TTY. The behaviour you're experiencing is to be expected.

Please let us know if you have any further questions. Thanks!
