### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by tardyp** [kennethreitz/pipenv#362]
Trying to use pyenv with pypy, and pyenv does not install anything.

Looks like the travis.yml comments out pypy in the matrix.

Opening this Issue to track status for pypy.

**Comment by kennethreitz** [comment]
$ pipenv --python pypy

**Comment by nateprewitt** [comment]
@kennethreitz, there's definitely something broken in pypy. It runs the install command almost instantly but doesn't install anything or raise any errors. For some reason, opening the generated requirements.txt in pypy works but `read()` returns an empty string, despite the file having contents. I have no idea why that's happening but it's consistently happening in pypy.

Does anyone else have background here, the default version of pypy on travis is pypy-2.5.0.

**Comment by tardyp** [comment]
@nateprewitt thanks for confirming issue

Here are two reference docker builds

Based on python:2-slim:
https://hub.docker.com/r/forestscribe/gitlab-create-hook/builds/bmumke7tgbfavs55ywzflrw/
Based on pypy:2-slim: (with --python pypy)
https://hub.docker.com/r/forestscribe/gitlab-create-hook/builds/bvk8hr9gqzer6stgztczvcm/

here is the diff in dockerfile:
https://github.com/Forestscribe/gitlab-create-hook/pull/2/files

first installs correctly the dependencies:
```
Successfully installed bson-0.4.7 click-6.7 kafka-python-1.3.3 pytz-2017.2 requests-2.14.2
```

second just do nothing at install phase
```

Virtualenv location: /app/.venv
No package provided, installing all dependencies.
[0m
[91mPipfile found at /app/Pipfile. Considering this to be the project home.
[0m
Installing dependencies from Pipfile.lock...





To activate this project's virtualenv, run the following:
 $ pipenv shell
```

**Comment by nateprewitt** [comment]
Hmm, so for some reason pypy acknowledges the file exists but `os.stat` on the file path returns a size of 0 when we run pipenv with pypy. However, running `os.stat` on the same file path in the pypy interpreter returns what we'd expect.

**Comment by kennethreitz** [comment]
sounds like a bug in pypy
