### ISSUE TITLE
Support for multiple virtual environments (tox)

### ISSUE THREAD

**Issue by iScrE4m** [kennethreitz/pipenv#368]
If I'm maintaining a package that needs to run under multiple python versions, I'd like to be able to `pipenv install` multiple times, so that I can do: `pipenv run --python=python2.7 py.test tests` or `pipenv run --three py.test tests` or ->

Tox. I copied and edited `tox.ini` from here http://docs.pipenv.org/en/latest/advanced.html#tox-automation-project but all the tests in every tox instance were running under the virtualenv of pipenv, instead of it's own created one. So I went 'oldschool' with tox, running outside of pipenv, but it's a shame it doesn't work as the docs say.

**Comment by kennethreitz** [comment]
I don't think pipenv is the right tool for this. 

I'll think about if we can be accommidating, though. I certianly have this use case.

**Comment by kennethreitz** [comment]
maybe make `pipenv --two` actually change the current virtualenv, and two are created, one for two, one for three!

**Comment by nateprewitt** [comment]
We definitely should be able to support this, I have previously used pipenv with tox without issue. If you're specifying your envlist, the system default python should be whatever you're expecting the build to run. That means `pipenv  --python=python` should build the correct environment. Then you'll need to run `pipenv run py.test tests` afterwards.

Is that not working for you @iScrE4m?

**Comment by nateprewitt** [comment]
I can see how the docs may need to be updated here. The `--three` default for `pipenv install` is likely what's causing the issue for you.

**Comment by iScrE4m** [comment]
So I ran `pipenv --python=python` to recreate virtualenv, then added to tox pipenv as dep and testenv commands `pipenv install --dev` and `pipenv run py.test tests` -> Everything ran under 2.7

**Comment by nateprewitt** [comment]
To clarify, you ran `pipenv --python=python` once, outside of the tox workflow? If that's the case, that won't work.

You'll need to add the line `pipenv --python=python` before `pipenv install --dev` for your testenv commands. This will choose the python version that tox has currently bound to python and create a new environment for it.

**Comment by nateprewitt** [comment]
I should also note, the `pipenv --python=python` line is only a requirement when running tox locally. Deploying to a CI platform should containerize each envlist variable, meaning this is handled automatically.

**Comment by iScrE4m** [comment]
Well, gitlab CI doesn't, but that doesn't really matter. Here's my output locally:

```
py36 recreate: /home/david/PycharmProjects/kzlib/.tox/py36
py36 installdeps: pipenv
py36 inst: /home/david/PycharmProjects/kzlib/.tox/dist/szn-kzlib-1.1.0.zip
py36 installed: appdirs==1.4.3,packaging==16.8,pew==0.1.26,pipenv==4.0.1,pyparsing==2.2.0,pythonz-bd==1.11.4,requests==2.14.2,resumable-urlretrieve==0.1.5,six==1.10.0,szn-kzlib==1.1.0,virtualenv==15.1.0,virtualenv-clone==0.2.6
py36 runtests: PYTHONHASHSEED='3524422016'
py36 runtests: commands[0] | pipenv --python=python
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Using python to create virtualenv...
⠋Running virtualenv with interpreter /home/david/PycharmProjects/kzlib/.tox/py36/bin/python
Using real prefix '/usr'
Path not in prefix '/home/david/PycharmProjects/kzlib/.tox/py36/include/python3.6m' '/usr'
New python executable in /home/david/.local/share/virtualenvs/kzlib-ioR7Pzu3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/david/.local/share/virtualenvs/kzlib-ioR7Pzu3                                                                                                                                                                                            py36 runtests: commands[1] | pipenv install --dev
No package provided, installing all dependencies.
Pipfile found at /home/david/PycharmProjects/kzlib/Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
...
⠏
To activate this project's virtualenv, run the following:
 $ pipenv shell
py36 runtests: commands[2] | pipenv run py.test tests
======================================================================================================================== test session starts ========================================================================================================================
platform linux -- Python 3.6.0b2, pytest-3.1.0, py-1.4.33, pluggy-0.4.0
rootdir: /home/david/PycharmProjects/kzlib, inifile:
plugins: cov-2.5.1
collected 0 items / 3 errors 

============================================================================================================================== ERRORS ===============================================================================================================================
_____________________________________________________________________________________________________________ ERROR collecting tests/test_jsonmaker.py ______________________________________________________________________________________________________________
ImportError while importing test module '/home/david/PycharmProjects/kzlib/tests/test_jsonmaker.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_jsonmaker.py:5: in <module>
    from kzlib import jsonmaker
E   ModuleNotFoundError: No module named 'kzlib'
```

**Comment by nateprewitt** [comment]
Sorry, I'm not sure what we're looking for here in this output. It seems to be using Python 3.6 as I'd expect. Is `jsonmaker` in your Pipfile/Pipfile.lock?

**Comment by nateprewitt** [comment]
And as for Gitlab CI, I'd suggest an approach closer to [what flake8 does](https://gitlab.com/sigmavirus24/flake8/blob/master/.gitlab-ci.yml). This will allow you utilize tox in Gitlab while not interfering with your local runner.

**Comment by iScrE4m** [comment]
kzlib is the library I'm testing, jsonmaker is part of that.

**Comment by nateprewitt** [comment]
Ok, what is it we're looking for here in the local output? It seems like things are operating as expected.

**Comment by iScrE4m** [comment]
We're looking at ModuleNotFoundError, where the Module should be present and tested. I suspect it's not using the correct virtualenv and while it recreates the one it needs to, it doesn't use the one where the package from setup.py is installed.  Without pipenv everything is passing.

**Comment by nateprewitt** [comment]
If `kzlib` is the package you're running tests for, it won't be installed in the virtualenv, it should just be running the code from inside the directory. That seems much more likely to be a packaging/PYTHONPATH issue than something to do with pipenv.

Does `pipenv run py.test tests` run by itself? If you install the dependencies with pip, does `py.test tests` run? If not, this is likely out of the scope of either tox or pipenv.

**Comment by nateprewitt** [comment]
Sorry, I need to stop replying to multiple tickets at once. Disregard my comment above.

Are you running `pipenv run python setup.py install` to install your package in the virtualenv on each recreation? I'm not seeing it in the console output. If it's not installed inside pipenv, I doubt `py.test` will find it.

**Comment by iScrE4m** [comment]
Well okay, that way tox could probably run, but instead of making my life easier, pipenv is actually making my life harder that way. 

I'm not really sure if it should be tox recognizing pipfile and filling in dependencies from there, or pipenv being able to run tox, or if the way it is right now is okay.
