### ISSUE TITLE
document the ability to express a dependency as only for a specific python version?

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#369]
https://github.com/kennethreitz/maya/pull/57

this is bad.

**Comment by nateprewitt** [comment]
I knew we were going to need this eventually 😁 Do you want us to implement something to address this, or raise this upstream for Donald? I think this will likely need to be baked into Pipfile itself.

**Comment by kennethreitz** [comment]
I have power of pipfile too, thankfully, but.... idk. 

i think something like `requests;python_version<3` would work. What PEP were you referring to this week?

**Comment by nateprewitt** [comment]
I have it jotted down on my laptop but am on the move. I'll drop it in here soon. The pep specification is that same syntax. Package ; marker

**Comment by kennethreitz** [comment]
that may be complaint with pipefile, and would just need to be integrated into pipenv then!

**Comment by c17r** [comment]
In this specific case: the chain is `maya` -> `ruamel.yaml` -> `ruamel.ordereddict;python_version<3`.  

So is the intent that Pipfile would have to have an entry for `ruamel.ordereddict` even though it doesn't use it directly?

**Comment by kennethreitz** [comment]
i think that's the best case here, yes.

**Comment by nateprewitt** [comment]
[PEP 496](https://www.python.org/dev/peps/pep-0496/#examples) is the one for environment markers. The standard requirements.txt format that we translate Pipfile into supports package specific markers, but we need a way to persist those back out to the Pipfile and Pipfile.lock.

Is the marker in `ruamel` actively being ignored by Pipenv, or was it the dependency being persisted in the Pipfile.lock which caused the issue?

**Comment by c17r** [comment]
`ruamel.yaml` has 
```
    install_requires=dict(
        any=[],
        py27=['ruamel.ordereddict'],
    ),
```
Under python 2.7, the requirement `ruamel.ordereddict` made it into `Pipefile.lock` so running `pipenv install --dev` on 3.X it tries to install `ruamel.ordereddict`

**Comment by kennethreitz** [comment]
pipenv is intended to target specific versions of python.
