### ISSUE TITLE
Feature: override package from lockfile with local version

### ISSUE THREAD

**Issue by Diggsey** [kennethreitz/pipenv#374]
This is equivalent to the [path overrides feature](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies) from cargo, rust's package manager. The idea is to be able to override dependency versions from a separate file to the lockfile, which is then not checked into version control.

I have two projects, where one depends on the other via a repository URL + commit hash. However, while developing locally, I would want to use my local copy of the first project.

**Comment by kennethreitz** [comment]
you can accomplish this manually with pip today

**Comment by Diggsey** [comment]
@kennethreitz This doesn't work, because further invocations of `pipenv install` will replace the local version of the packages with ones cloned from the repo.

**Comment by kennethreitz** [comment]
out of scope

**Comment by techalchemy** [comment]
Dependencies should be by name and version, that way when you install your local copy and call it the same name as what your remote package requires, it satisfies the dependency. Just set the name in your pipfile instead of the hash pipenv generates
