### ISSUE TITLE
`pipenv shell` does not use my default shell

### ISSUE THREAD

**Issue by ijks** [kennethreitz/pipenv#375]
I've set my default shell to Fish:

```
$ grep $USER /etc/passwd | cut -d ':' -f 7
/usr/bin/fish
```

However, when I run `pipenv shell`, Bash is launched. Running `pipenv shell -c` doesn't seem to make a difference (although the prompt is now a bit different; I guess Bash itself must be 'misconfigured').

Also, I am running on in Windows Subsystem for Linux, if that makes any difference.

**Comment by kennethreitz** [comment]
changing your shell on the windows subsystem for linux is tricky. there's no chsh equivalent... your terminal is always bash.

**Comment by ijks** [comment]
That's true when you run just `bash.exe`. However, I've made a shortcut that launches Fish from Bash using the `-c` option. So the current running shell is Fish. I just used `chsh` because I thought maybe Pipenv wasn't picking it up because my 'official' shell was still set to Bash.

I haven't looked at what Pipenv does to launch the subshell (or does it use Pew for that?). It might be seeing 'bash.exe' somewhere and use that.

Obviously my use case is a bit exotic, and I've heard there is going to be built-in support for other shells soon. But I figured I'd report this anyway.

**Comment by kennethreitz** [comment]
what does your `SHELL` environment variable say?

**Comment by ijks** [comment]
Ah, `/bin/bash`. 😅 I'd forgotten about that one; odd that Fish doesn't set it anywhere. Setting it to Fish fixes everything. Thanks for the help!

**Comment by ijks** [comment]
Oh and one more thing - is it mentioned anywhere in the docs/help that `pipenv shell` uses `$SHELL`? If not, I could write a PR for that, in case anybody else has the same problem.

**Comment by kennethreitz** [comment]
i think you're an odd case (i am too, as i use WSL).. but yeah a PR would be accepted!

**Comment by ijks** [comment]
Great, I'll look at it when I have the time. :)
