### ISSUE TITLE
can't install[dependencies]

### ISSUE THREAD

**Issue by kakulukia** [kennethreitz/pipenv#380]
I need to install Twisted[tls,http2] and while i can kinda do that, its not saved in my Pipfile!
Pipenv will install the right stuff and lock every package that is currently installed (with the lock command), but as soon as i tell it to update, any additional package not mentioned in the Pipfile will be gone.

So please fix:

    pipenv install Twisted[tls,http2]

pipenv, version 4.1.1

**Comment by nateprewitt** [comment]
That's for noting this @kakulukia, I'll try to get this worked out sometime this week.

**Comment by nateprewitt** [comment]
@kakulukia, I am trying this with 4.1.1 and unable to reproduce this issue. When I run `pipenv install Twisted[tls,http2]` I get this entry in my Pipfile:

```
[packages.Twisted]
extras = [ "tls", "http2",]
```

This seems like what we'd want here. Installing further packages after that leaves this unchanged. Could you clarify what you mean when you say "tell it to update"? Are you running another `pipenv install` command?

**Comment by kakulukia** [comment]
okay, it seems i found the real problem .. when you first install Twisted and then realise you missed the dependencies and install Twisted[tls,http2] then the extras will not be added to the Pipfile.
They will be installed, but after a _pipenv update_ they are gone.

**Comment by nateprewitt** [comment]
Thanks for tracking that down @kakulukia! This was a conflict of key casing where `twisted` was in the Pipfile, but installing `Twisted[tls,http2]` was recognized as a separate package until write time where it was being overwritten by the existing `Twisted = "*"` entry.

I've added b873834 which will fix this in the next release.
