### ISSUE TITLE
"pip install -e" like argument for `pipenv install`

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#386]
I don't see how to setup the current project directly with `pipenv install`, without doing the old-school `python setup.py develop`, ie, the equivalent of `pip install -e .`. It looks like pip does some extra work more, isn't it needed for pipenv as well?

Also, I don't know if I should do `pip install -e .` or `python setup.py develop` like it is in your `.travis.yml` ?

**Comment by nateprewitt** [comment]
Hey @Stibbons, this was an oversight in the recent introduction of `pipenv install -e *` support. I've pushed a fix that should allow you to do `pipenv install -e .` to accomplish what you want. If you upgrade to to 4.1.3 you'll be able to use this feature properly.

Before now, you would have needed to run `pipenv run pip install -e .` to install your package inside of the pipenv virtual environment.

**Comment by Stibbons** [comment]
Great ! I don't see the `-e` argument for `pipenv install` in 4.1.3:
```
$ pipenv --version
pipenv, version 4.1.3
$ pipenv install --help
Usage: pipenv install [OPTIONS] [PACKAGE_NAME] [MORE_PACKAGES]...

  Installs provided packages and adds them to Pipfile, or (if none is
  given), installs all packages.

Options:
  -d, --dev         Install package(s) in [dev-packages].
  --three / --two   Use Python 3/2 when creating virtualenv.
  --python TEXT     Specify which version of Python virtualenv should use.
  --system          System pip management.
  --lock            Lock afterwards.
  --hashes          Generate hashes, if locking.
  --ignore-hashes   Ignore hashes when installing.
  --ignore-pipfile  Ignore Pipfile when installing, using the Pipfile.lock.
  --help            Show this message and exit.
$ pipenv install -e .
Installing -e ....
```

**Comment by kennethreitz** [comment]
that's because `-e` isn't a flag to install, but an argument.

**Comment by Stibbons** [comment]
Yes, I mean, can you describe this behavior in the front page, in the documentation? It's not obvious.
