### ISSUE TITLE
error in travis build with pipenv 4.1.3

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#388]
4.1.3 works great on my machine but on the travis build (that install a python 3.x from  scratch) there is an error. Previously, the build was good: https://travis-ci.org/Stibbons/subdlsrv/builds/238000358

Now it fails about missing `six` package. See: https://travis-ci.org/Stibbons/subdlsrv/jobs/238244319
```
$ pip install -U pip 'pipenv>=4.1.3'
...
    import six
    ImportError: No module named 'six'
```
Only for 3.4 and 3.6.
3.5 installed successfully pipenv 4.1.3 and finished the build.

Don't understand why. I have worked around it this part in the next build: https://travis-ci.org/Stibbons/subdlsrv/jobs/238245074
```
$ pip install -U pip 'pipenv>=4.1.3' six
...
Successfully installed
```

But it failed later on my `pipenv install --dev` with the same error about missing `six` package.
Even by manually adding `six` in the `Pipfile` and `Pipfile.lock` with `pipenv install six`, it still fail on python 3.4 and 3.6: https://travis-ci.org/Stibbons/subdlsrv/jobs/238247638

**Comment by Stibbons** [comment]
Root cause seems related to setuptools 36.0.0.
https://www.reddit.com/r/Python/comments/6elcaa/psa_setuptools_broken_release_36_dont_use_it/

**Comment by nateprewitt** [comment]
Yep, this was a bug in setuptools, not pipenv. According to pypa/setuptools#1042 this should be resolved now though.
