### ISSUE TITLE
OpenSSL.SSL.Error: Missing cacert.pem in vendorized `requests` 2.13.0?

### ISSUE THREAD

**Issue by msegado** [kennethreitz/pipenv#396]
When I run `pipenv install` I get the a stack trace ending in
```
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

This may be caused by the bundled `requests` module (v2.13) missing a `cacert.pem` file... see requests/requests#4019 ("OpenSSL issue when vendoring requests"). I can confirm that trying `import requests; requests.get(...)` with `pipenv/vendor/requests` on my path causes the error above while the same command using my system-wide `requests` (v2.14.2) does not.

Related: #387 ("Strange error after upgrade on ubuntu 16.04")

**Comment by aeleos** [comment]
I had the same issue on ubuntu 16.04. It started when I installed certbot (Lets Encrypt certificate managment tool) and fixed itself when I uninstalled it with ```sudo apt-get --purge certbot && sudo apt-get autoremove```  

I am not sure which package specifically causes the issue, it could be the bundled requests package in their [repo](https://launchpad.net/~certbot/+archive/ubuntu/certbot) or it could be that it requires python-openssl to be installed.

Hopefully this helps someone figure out the actual issue as this error is really annoying.

**Comment by msegado** [comment]
From what I remember when troubleshooting a few weeks ago, `cacert.pem` wasn't present in my installed version of pipenv; however, since I see it *is* present in the repo here, I suspect the issue might be that it's not being bundled into the pipenv wheel / uploaded to PyPI...

**Comment by nateprewitt** [comment]
aha! Thanks @msegado, it is in our repo, but it isn't being bundled as you can see by inspecting the [5.1.0 archive](https://pypi.python.org/packages/37/af/73e27a4711128f7bc1e0c46722c0dcc0a7313223efcc076a0212fb6d9806/pipenv-5.1.1.tar.gz#md5=20778b03c20269228fb2705a7a3511c6). This is an issue with our release process. I believe we'll need to add an entry to MANIFEST.in to include `cacert.pem`.

**Comment by nateprewitt** [comment]
Alright, I've pushed 35518da to address this.

@msegado and @aeleos, feel free to try installing the master branch and seeing if you're still experiencing the issue. If not, this will be included in our next release.

**Comment by iamthad** [comment]
For an immediate workaround, find the `pipenv` directory under your Python installation's `site-packages` directory, `cd` into it, and then:
```sh
cd vendor/requests
wget https://raw.githubusercontent.com/kennethreitz/pipenv/master/pipenv/vendor/requests/cacert.pem
```

**Comment by nateprewitt** [comment]
@iamthad this should already be resolved in the latest release. Are you still experiencing issues?

**Comment by iamthad** [comment]
I just installed pipenv ~2.5 hours ago and had this issue. I'll double-check that I got the latest release.

**Comment by gusennan** [comment]
I can confirm that I also have 5.1.2 and ran into this issue.

**Comment by nateprewitt** [comment]
Sorry, this issue should have been updated with #434. Archives were properly fixed in 5.1.2 but there was still an outstanding issue with wheels. I've pushed 06acad1 which will fix this in the next release.

**Comment by gusennan** [comment]
Just reinstalled latest version pipenv on a new Fedora 26 server and ran into this issue again.

**Comment by nils-werner** [comment]
Just installed pipenv on OSX El Capitan, Python from homebrew, and ran into this issue.

**Comment by jzelez** [comment]
This now happens to me with 9.0.3 version, brew python and osx. BUT only when i run `pipenv update`.  on normal install it works fine. any ideas?
