### ISSUE TITLE
Bash should be run as a login shell

### ISSUE THREAD

**Issue by jjangsangy** [kennethreitz/pipenv#415]
It looks like bash understands `$SHELL` but this shell is not a login shell which means people who have customized their `$PROMPT_COMMAND` in their Dotfiles end up with weird errors.

A couple of solutions I can think of.
1. Run bash with `--login --interactive`
2. Rather than just running `$SHELL`, you can run `exec` and source the virtualenv.
    * This has the added bonus of having the same virtualenv flow and running `deactivate.
    * Running Ctrl-D is error prone, I quit the shell thinking I'm inside `pipenv shell` many many times.

**Comment by kennethreitz** [comment]
it should not, actually! it's a subshell, only your login shell (the one invoking pipenv) should be invoked as a login shell.

**Comment by kennethreitz** [comment]
Check out the pew docs for more information. For the record, are you using `--compat`?

**Comment by jjangsangy** [comment]
I've tried both `--compat` and not as well.

**Comment by jjangsangy** [comment]
So what you're saying is that the subshell should inherit the configuration of the parent shell? I would agree, except when I run `pipenv shell` my `~/.profile` is not sourced

**Comment by kennethreitz** [comment]
The pew docs will help you get your shell setup properly — basically, your PATHs and PS1s and friends should only be setup during a login shell, not for every invocation of bash.

**Comment by jjangsangy** [comment]
Just read through some of the pew docs (that was helpful), so I'm looking right [here](https://github.com/berdario/pew#troubleshooting) in the troubleshoot section.

They recommend that you move your `PATH` declarations into `~/.profile` and execute as a login shell.

Also, this table was really helpful me figure out why `~/.profile` was not getting sourced

<table class="inline table table-striped table-condensed">
	<thead>
	<tr class="row0">
		<th class="col0">Mode</th><th class="col1"><code>/etc/profile</code></th><th class="col2"><code>~/.bash_profile</code></th><th class="col3"><code>~/.bash_<span class="search_hit mark">login</span></code></th><th class="col4"><code>~/.profile</code></th><th class="col5"><code>~/.bashrc</code></th><th class="col6"><code>${ENV}</code></th>
	</tr>
	</thead>
	<tbody><tr class="row1">
		<td class="col0 leftalign"><span class="search_hit mark">Login</span> <span class="search_hit mark">shell</span>           </td><td class="col1 centeralign">  X  </td><td class="col2 centeralign">  X  </td><td class="col3 centeralign">  X  </td><td class="col4 centeralign">  X  </td><td class="col5 centeralign">  -  </td><td class="col6 centeralign">  -  </td>
	</tr>
	<tr class="row2">
		<td class="col0 leftalign">Interactive Shell</td><td class="col1 centeralign">  -  </td><td class="col2 centeralign">  -  </td><td class="col3 centeralign">  -  </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  X  </td><td class="col6 centeralign">  -  </td>
	</tr>
	<tr class="row3">
		<td class="col0 leftalign">SH compatible <span class="search_hit mark">login</span>   </td><td class="col1 centeralign">  X  </td><td class="col2 centeralign">  -  </td><td class="col3 centeralign">  -  </td><td class="col4 centeralign">  X  </td><td class="col5 centeralign">  -  </td><td class="col6 centeralign">  -  </td>
	</tr>
	<tr class="row4">
		<td class="col0 leftalign">SH compatible         </td><td class="col1 centeralign">  -  </td><td class="col2 centeralign">  -  </td><td class="col3 centeralign">  -  </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  -  </td><td class="col6 centeralign">  X  </td>
	</tr>
	<tr class="row5">
		<td class="col0">POSIX® compatiblity </td><td class="col1 centeralign">  -  </td><td class="col2 centeralign">  -  </td><td class="col3 centeralign">  -  </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  -  </td><td class="col6 centeralign">  X  </td>
	</tr>
</tbody></table>

**Comment by kennethreitz** [comment]
Great table!

**Comment by jjangsangy** [comment]
After reading the pew docs and combing deep caverns of shell scripting lore I discovered that functions can be exported _(who knew that was a thing!)_.

## function export example

So let's say I have function that fork bombs your shell and I want to hot potato it into a child shell processes.

```sh
$ function forking { forking | forking & }
$ pipenv shell
$ foobar
bash: foobar: command not found
```

Bash prevents child processes from cases of unprotected forking. You need to explicitly flag functions using `export -f foobar` or `declare -fx foobar`

```sh
$ declare -F
declare -fx powerline_precmd
```

Even if the functions are bound to environment variables that are themselves exported, the new sub shell is passed a new copy of the functions and not a reference.

```
$ 
```

Even if the parent shell child processes from unprotected forking

**Comment by nateprewitt** [comment]
@jjangsangy were there any actionable items we were still looking for here or were you able to find what you needed in the pew docs? If so, I'm proposing we close this issue out.

**Comment by jjangsangy** [comment]
I addressed the issue by going through and exporting all functions needed by the subshell to render my prompt. This feels a bit like a hack, but I don't mind.

I am somewhat hesitant closing this issue without some explicit documentation regarding this behavior as users will likely come across this regularly. For both `powerline-shell` and `iTerm2` have functions which I needed to export resulting in something like this.

```sh
declare -fx iterm2_begin_osc
declare -fx iterm2_end_osc
declare -fx iterm2_preexec_install
declare -fx iterm2_preexec_invoke_cmd
declare -fx iterm2_preexec_invoke_exec
declare -fx iterm2_print_state_data
declare -fx iterm2_print_user_vars
declare -fx iterm2_print_version_number
declare -fx iterm2_prompt_mark
declare -fx iterm2_prompt_prefix
declare -fx iterm2_prompt_suffix
declare -fx powerline_precmd
declare -fx precmd
declare -fx preexec
```

**Comment by jjangsangy** [comment]
There are also edge cases, `nvm`, the node package manager heavily relies on functions to link node environments. If in case some developer dual wielding package managers ever appears god have mercy.

**Comment by DownRangeDevOps** [comment]
Sorry for the necro, stumbled on this while trying to decide how to address missing custom functions that are loaded in my `bash --login` shell.

I wanted to mention that I accomplished what @jjangsangy did globally as I want all of my `.bash_profile` functions passed to the sub-shell using:

`set -a` and subsequently disabling it at the end of my profile with `set +a`. See `set --help`:

```
Options:
  -a  Mark variables which are modified or created for export.
```
