### ISSUE TITLE
Document suffix added to virtualenv name

### ISSUE THREAD

**Issue by bhrutledge** [kennethreitz/pipenv#417]
I just started playing around with this project, and was surprised that `pipenv --three` in `~/Code/test-pipenv` resulted in a virtualenv named `test-pipenv-7v2SBB6d`. Diving into the code, I eventually found that this was added in PR #238. I skimmed through that, and the related issue, and I think I understand the reasoning behind it. However, I couldn't find documentation for that behavior, and I imagine that others might also find it surprising (if not irritating).

**Comment by jacebrowning** [comment]
I always set `PIPENV_VENV_IN_PROJECT` based on [the docs](http://docs.pipenv.org/en/latest/advanced.html#configuration-with-environment-variables) to get around this. In my opinion, it should be the default, but to each their own. ✌️

**Comment by kennethreitz** [comment]
@jacebrowning we get that feedback a lot ;)
