### ISSUE TITLE
Alternative installation support / instructions

### ISSUE THREAD

**Issue by ericfrederich** [kennethreitz/pipenv#42]
Many prefer to keep their OS Python install clean of any 3rd party packages.
For others it's not even a choice as they don't have `sudo` access.

It would be nice to have instructions for an unprivileged user to get pipenv on their `PATH` in some way.

This seems hacky but it seems to work...

### System with Python 3
```bash
python3 -m venv ~/bin/_pipenv
source ~/bin/_pipenv/bin/activate
pip install pipenv
ln -s ~/bin/_pipenv/bin/pipenv ~/bin
```

### System with Python2 and virtualenv
```bash
virtualenv ~/bin/_pipenv2
source ~/bin/_pipenv2/bin/activate
pip install pipenv
ln -s ~/bin/_pipenv2/bin/pipenv ~/bin/pipenv2
```

**Comment by Silvus** [comment]
`pipsi install pipenv` ?

[Pipsi](https://github.com/mitsuhiko/pipsi/)
> What does it do? pipsi is a wrapper around virtualenv and pip which installs scripts provided by python packages into separate virtualenvs to shield them from your system and each other.

> pipsi installs each package into ~/.local/venvs/PKGNAME and then symlinks all new scripts into ~/.local/bin.

**Comment by kennethreitz** [comment]
I think sticking to what we have currently is best — this is a tool like pip.
