### ISSUE TITLE
Vagrant shell provisioner breaks pipenv

### ISSUE THREAD

**Issue by agentreno** [kennethreitz/pipenv#422]
Heard about this in the talkpython interview, excited to start using it but I've run into a problem with an 'Inappropriate ioctl for device' message when trying to use pipenv to install dependencies in a vagrant shell provisioning script. I'm fairly sure this is because there's no terminal and is related to https://github.com/kennethreitz/pipenv/issues/199 - running pipenv in a terminal via vagrant ssh works just fine.

The solution in that issue doesn't seem to have made it's way out yet though? I'm running version 5.1.1.

**Comment by nateprewitt** [comment]
Hey @agentreno, we added a `--no-interactive` mode back in the 3.X series and it was later removed again in #320. As I understood it there, we didn't have an issue with this after the patch but I'm thinking this may not have been as tested as needed.

Could you please provide a break down of how we'd reproduce this so I can give a shot at debugging things? Thanks!

**Comment by agentreno** [comment]
Hey @nateprewitt I made a minimal example that triggers this problem here: https://github.com/agentreno/pipenv-noninteractive-issue

**Comment by nateprewitt** [comment]
Thanks so much for putting this together, @agentreno! I'll try to give this a look this afternoon.

**Comment by systemexitzero** [comment]
@agentreno, try using `pipenv run` for non-interactive use instead of `pipenv shell`

Change your Vagrantfile example from
```sh
...
pipenv shell
python /vagrant/needs_requests.py
```

to something like:
```sh
...
cd /vagrant || exit 1
pipenv install && pipenv run python /vagrant/needs_requests.py
```

**Comment by agentreno** [comment]
This works a charm, thanks @systemexitzero
