### ISSUE TITLE
pipenv install . works, then doesn't

### ISSUE THREAD

**Issue by voltagex** [kennethreitz/pipenv#423]
To reproduce: `git clone https://github.com/home-assistant/home-assistant`, cd to it and do `pipenv install .` (I'm trying to emulate doing a `pip install -e .`, which works

```
voltagex@devbox:~/src/home-assistant$ pipenv install .
Installing ....
Processing /home/voltagex/src/home-assistant
Collecting requests==2.14.2 (from homeassistant==0.48.0.dev0)
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting pyyaml<4,>=3.11 (from homeassistant==0.48.0.dev0)
Collecting pytz>=2017.02 (from homeassistant==0.48.0.dev0)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Requirement already satisfied: pip>=7.1.0 in /home/voltagex/.local/share/virtualenvs/home-assistant-FQ7z6Kjg/lib/python3.5/site-packages (from homeassistant==0.48.0.dev0)
Collecting jinja2>=2.9.5 (from homeassistant==0.48.0.dev0)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting voluptuous==0.10.5 (from homeassistant==0.48.0.dev0)
Collecting typing<4,>=3 (from homeassistant==0.48.0.dev0)
Collecting aiohttp==2.2.0 (from homeassistant==0.48.0.dev0)
  Using cached aiohttp-2.2.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting async_timeout==1.2.1 (from homeassistant==0.48.0.dev0)
  Using cached async_timeout-1.2.1-py3-none-any.whl
Collecting chardet==3.0.2 (from homeassistant==0.48.0.dev0)
  Using cached chardet-3.0.2-py2.py3-none-any.whl
Collecting astral==1.4 (from homeassistant==0.48.0.dev0)
  Using cached astral-1.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2>=2.9.5->homeassistant==0.48.0.dev0)
Collecting multidict>=2.1.4 (from aiohttp==2.2.0->homeassistant==0.48.0.dev0)
  Using cached multidict-3.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting yarl<0.11,>=0.10.0 (from aiohttp==2.2.0->homeassistant==0.48.0.dev0)
  Using cached yarl-0.10.3-cp35-cp35m-manylinux1_x86_64.whl
Building wheels for collected packages: homeassistant
  Running setup.py bdist_wheel for homeassistant: started
  Running setup.py bdist_wheel for homeassistant: finished with status 'done'
  Stored in directory: /home/voltagex/.cache/pip/wheels/15/10/10/d1fb8fae78640b021d7e20246a66aa965aa44b337040273960
Successfully built homeassistant
Installing collected packages: requests, pyyaml, pytz, MarkupSafe, jinja2, voluptuous, typing, multidict, yarl, async-timeout, chardet, aiohttp, astral, homeassistant
Successfully installed MarkupSafe-1.0 aiohttp-2.2.0 astral-1.4 async-timeout-1.2.1 chardet-3.0.2 homeassistant-0.48.0.dev0 jinja2-2.9.6 multidict-3.0.0 pytz-2017.2 pyyaml-3.12 requests-2.14.2 typing-3.6.1 voluptuous-0.10.5 yarl-0.10.3

Adding . to Pipfile's [packages]...
ERROR (PACKAGE NOT INSTALLED): Invalid requirement, parse error at "'.'"
```

Note that this installs correctly but fails because the Pipfile is updated with the wrong name.

**Comment by erinxocon** [comment]
I do not believe you can currently do that with pipenv/pipfile.  

Currently I was able to get this to work by doing the following.  

`git clone https://github.com/home-assistant/home-assistant`
`cd home-assistant`
`pipenv --three`
`pipenv run pip -e .`
`pipenv run hass`

**Comment by nateprewitt** [comment]
@voltagex, this appears to be a bug in pipenv. We do support installing packages with `pipenv install -e .` but we're not storing this information correctly in the Pipfile. I'm actually not sure this was fully thought out when implemented, specifically how we intended local paths to be stored in a Pipfile. Binding to a local file path won't be translatable between environments.

I'm going to put a bug flag on this until I have a moment to give it proper attention. In the meantime, I would suggest either using @erinxocon's suggest approach, which will install things but not add it to your Pipfile, or installing directly from a repository (e.g. `pipenv install git+https://github.com/home-assistant/home-assistant@master#egg=home-assistant`). I realize this doesn't allow you to edit the directory locally, but I don't think we have a workable solution in pipenv for that currently.

Thanks for your patience!

**Comment by erinxocon** [comment]
@nateprewitt I've experienced the need to do this as well, hence my pseudo-solution up there.  Is this a problem with pipfile or pipenv?  I'd be happy to take a whack at getting pipenv to store package information correctly in Pipfile, assuming Pipfile supports this.

**Comment by kennethreitz** [comment]
`$ pipenv install '-e .' works fine for me.

**Comment by erinxocon** [comment]
@kennethreitz that works for me now with the current release!
