### ISSUE TITLE
`pipenv install -r requirements.txt` ignores `-e .`

### ISSUE THREAD

**Issue by caedn** [kennethreitz/pipenv#43]
It look like pipenv is silently dropping the line.

    pipenv shell
    pip install -r requirements.txt

works fine though. 

https://github.com/pypa/pipfile/issues/50 is somewhat related as I'm not sure how I would specify `-e .` in a Pipfile.

**Comment by kennethreitz** [comment]
Pipfile doesn't support `-e .` yet.
