### ISSUE TITLE
need to install package certifi to get pipenv to work

### ISSUE THREAD

**Issue by bkcsfi** [kennethreitz/pipenv#434]
I'm on ubuntu 16, I installed pipenv with  pip install --user pipenv (in this case, pip is the system pip)

that installed pipenv into ~/.local/bin and ~/.local/lib/python2.7/site-packages

using pipenv install sqlalchemy failed with

```
  File "/home/bkc/.local/lib/python2.7/site-packages/pipenv/vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

in another shell (w/o an activated virtualenv) I then did pip install --user certifi

now pipenv install sqlachemy works as expected

**Comment by nateprewitt** [comment]
Hey @bkcsfi, would you mind providing the version of pipenv you have installed? If you could also provide the contents of `pip freeze --user`, that would be helpful. This sounds like you're missing an expected `cacerts.pem` in your install which should have been fixed in 5.1.2.

**Comment by bkcsfi** [comment]
Version 5.1.2

```
pip freeze --user                                                                                                                                                 
backports.shutil-get-terminal-size==1.0.0
certifi==2017.4.17
pathlib==1.0.1
pew==0.1.26
pipenv==5.1.2
pipfile==0.0.2
pythonz-bd==1.11.4
shutilwhich==1.1.0
toml==0.9.2
virtualenv==15.1.0
virtualenv-clone==0.2.6
```

(note that I had to manually install certifi, its not listed pipenv requirements.txt)

```
find   ~/.local/lib/python2.7/site-packages/pipenv/ -name cacerts.pem -ls 
```
finds nothing.. should it?

```
cat   ~/.local/lib/python2.7/site-packages/pipenv/__version__.py                                                                                                  
#     ___     ( )  ___      ___       __
#   //   ) ) / / //   ) ) //___) ) //   ) ) ||  / /
#  //___/ / / / //___/ / //       //   / /  || / /
# //       / / //       ((____   //   / /   ||/ /

__version__ = '5.1.2'
```

**Comment by nateprewitt** [comment]
@bkcsfi, yeah it should be finding `cacerts.pem`. The fact it can't is the reason you're experiencing this issue before installing `certifi`. I'm thinking we may want to consider upgrading our bundled version of Requests to 2.15+ so we no longer rely on the bundled certs.

Can you let me know if pipenv is being installed from an archive (`.tar.gz`) or from a wheel (`.whl`)?

**Comment by bkcsfi** [comment]
I believe it used a wheel

```
more ~/.local/lib/python2.7/site-packages/pipenv-5.1.2.dist-info/WHEEL                                                                                            
Wheel-Version: 1.0
Generator: bdist_wheel (0.29.0)
Root-Is-Purelib: true
Tag: py2-none-any
```

**Comment by nateprewitt** [comment]
Alright, this was a wheel issue because we didn't specify `include_package_data` in our setup.py. I've pushed 06acad1 to resolve this, so it will be fixed in the next release. In the meantime, you'll need to install certifi to resolve this.

**Comment by BallisticPain** [comment]
If anyone is having trouble with this when using Ansible... SOLUTION BELOW

I was trying to install `pipenv`, and was getting an error about `certifi`. It did mention in the error message about using a flag `--user`. So here's my working task.
```
---
- hosts: # ...
  tasks:
    - name: Install pipenv
      pip:
        name:
          - certifi
          - pipenv
        extra_args: --user
```
