### ISSUE TITLE
Weird behaviour with 'pipenv shell' and interactive python on Windows, every command causes a SyntaxError

### ISSUE THREAD

**Issue by schlenk** [kennethreitz/pipenv#435]
I have no idea what happens here.

Totally trivial project with one dependency, otherwise empty. Now i run 'pipenv' to install, which works just fine. Then i run 'pipenv shell' to run a python shell in the venv. Any interactive command is greeted with a `SyntaxError` exception, even trivial stuff like `import sys` or `print 1`.

If i activate the venv directly via the `Scripts\activate.ps1` script in the venv, everything works as expected.

This is a naked Python 2.7.13 x64 install on a Windows Server 2012R2 with the default powershell, no packages installed at all. No special shell wrappers or anything nasty installed as far as i can see. The only thing modified is the prompt to show the venv that is active, but the bug happens without that mod too.

```
PS  C:\pipenv_test> cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
requests = "*"
```
 
```
PS  C:\pipenv_test> pipenv --version
pipenv, version 5.1.2
PS  C:\pipenv_test> pew version
0.1.26
PS  C:\pipenv_test> C:\Python27amd64\python.exe --version
Python 2.7.13
PS  C:\pipenv_test> pipenv --python=C:\Python27amd64\python.exe install
Creating a virtualenv for this project...
Using C:\Python27amd64\python.exe to create virtualenv...
Running virtualenv with interpreter C:\Python27amd64\python.exe
New python executable in c:\venvs\pipenv_test-O9HVN3Wq\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: c:\venvs\pipenv_test-O9HVN3Wq
No package provided, installing all dependencies.
Pipfile found at C:\pipenv_test\Pipfile. Considering this to be the project home.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock!
Installing dependencies from Pipfile.lock...
[================================] 5/5 - 00:00:09
To activate this project's virtualenv, run the following:
 $ pipenv shell
PS  C:\pipenv_test> pipenv shell
Launching subshell in virtual environment. Type 'exit' to return.
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. Alle Rechte vorbehalten.

PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> python --version
Python 2.7.13
PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print 1
  File "<stdin>", line 1
    print 1
           ^
SyntaxError: invalid syntax
```

BUT in the same shell (right after the strange behaviour above) this works just fine:

```
PS  C:\pipenv_test> pipenv --venv
c:\venvs\pipenv_test-O9HVN3Wq
PS  C:\pipenv_test> . C:\venvs\pipenv_test-O9HVN3Wq\Scripts\activate.ps1
(pipenv_test-O9HVN3Wq) PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print 1
1
>>> ^Z
```

**Comment by nateprewitt** [comment]
So, this looks like it may be an issue with newlines. The shell is launched on Windows with `Popen` and the `universal_newlines` flag set. I'm wondering if your machine is having issues with the newline being passed from the enter keypress in your shell. I'm not immediately sure why this is an issue on your instance but not our previous windows test runners.

**Comment by schlenk** [comment]
I tried disabling `universal_newlines` in pipenvs cli.py in the shell command, but that had no effect.
Will try a few things more on monday, the envvar PYTHONUNBUFFERD in the subprocess looks suspicious, maybe pyexpect messes with the console settings?

**Comment by schlenk** [comment]
A few more data points. `pew workon` works as expected, so the issue is really in the pipenv part.

```
PS  C:\pipenv_test> pipenv shell
Launching subshell in virtual environment. Type 'exit' to return.
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. Alle Rechte vorbehalten.

PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
  File "<stdin>", line 1
    import sys
              ^
SyntaxError: invalid syntax
>>> ^Z

PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> exit
PS  C:\pipenv_test> pew workon pipenv_test-O9HVN3Wq
Launching subshell in virtual environment. Type 'exit' to return.
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. Alle Rechte vorbehalten.

PS {VENV: pipenv_test-O9HVN3Wq} C:\pipenv_test> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>>
>>> ^Z
```

**Comment by schlenk** [comment]
Replacing `pypenv shell` with this also works just fine:

```
#!python
import subprocess
import sys

cmd = ['pew.exe', 'workon', 'pipenv_test-O9HVN3Wq']
p = subprocess.Popen(cmd, shell=True, universal_newlines=True)
p.communicate()
sys.exit(p.returncode)
```

**Comment by schlenk** [comment]
More weirdness:

Just importing pipenv in above script makes it fail:

```
#!python
import subprocess
import sys

# Once this happens, it fails
import pipenv 

cmd = ['pew.exe', 'workon', 'pipenv_test-O9HVN3Wq']
p = subprocess.Popen(cmd, shell=True, universal_newlines=True)
p.communicate()
sys.exit(p.returncode)
```

So something inside `pipenv.cli` must break console support.

**Comment by nateprewitt** [comment]
This is pretty bizarre behaviour. I'm not sure why importing pipenv would cause the shell to do this if the code works otherwise. I haven't been able to reproduce this on a windows machine and don't have access to a copy of Windows Server 2012R2. My only suggestions for debugging at this point is to try removing some dependencies from pipenv.cli and see if one of them is a noticeable culprit. My initial hunch is possibly `click_completion`?

**Comment by schlenk** [comment]
Found it, as i already guessed in the beginning. `os.environ['PYTHONUNBUFFERD']='1'` inside the `delegator` package breaks it. It should probably just set that for subprocesses spawned by delegator and not globally.

This breaks:
```
#!python
import subprocess
import sys
import os

os.environ['PYTHONUNBUFFERD']='1'

cmd = ['pew.exe', 'workon', 'pipenv_test-O9HVN3Wq']
p = subprocess.Popen(cmd, shell=True, universal_newlines=True)
p.communicate()
sys.exit(p.returncode)
```

**Comment by schlenk** [comment]
Guess this should be fixed in delegator. Unless you want to add a workaround in pipenv. Feel free to close it here.

**Comment by schlenk** [comment]
Fixed with delegator 0.13.

**Comment by uranusjr** [comment]
I cannot reproduce this with either 11.10.0 or master. Everything works as it should. I’m on Windows 10 Pro, Python 2.7.14. We also didn’t change anything related to `shell` AFAICT.

**Comment by woelper** [comment]
Ok, this is weird. At work I additionally used a plain fresh Windows 10 VM to test - same error. After your comment I booted my Windows 10 Pro laptop at home and tried that, same error. Maybe I am doing something stupid - I recorded a video as well if that may help: https://www.youtube.com/watch?v=TPtjsJQaJG8&feature=youtu.be

**Comment by techalchemy** [comment]
As above I’d be willing to guess this is a result of `PYTHONUNBUFFERED` or a system encoding issue. When you say ‘fresh’ did you set any environment variables, etc?

**Comment by woelper** [comment]
Sorry for being unspecific - by fresh I mean it's right after the installation of windows 10 (eng) completes. I have a Virtualbox Image with a snapshot right after Windows 10 finished installing, so I installed python 2.7.14, git for windows (which might set env vars), opened the regular cmd prompt as well as powershell and ran `pipenv install` followed by `pipenv shell`. If it matters, the other tested systems are Thinkpad and Dell laptops running english Windows 10 pro as well, with the same results.

**Comment by woelper** [comment]
PYTHONUNBUFFERED is indeed 1 for the process.

How can I find out my delegator version? If I install delegator manually in the virtualenv, `delegator-0.0.3` is pulled in.
Maybe one of you could push me in the right direction to help further - I saw that PYTHONUNBUFFERED  is only set when the process not "blocking" - I might not understand enough about what is meant by blocking here, but if the python interpreter is run, wouldn't that be a blocking process?
Thanks for all the help so far!

**Comment by uranusjr** [comment]
`PYTHONUNBUFFERED` shouldn’t be set by default, so you need to unset it (and find out whatever set it if unsetting it works). For Powershell:

```ps
Remove-Item Env:\PYTHONUNBUFFERED
```
