### ISSUE TITLE
Investigating improving pipenv usage on Travis CI

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#436]
`CI=1`, so there's that.

**Comment by sobolevn** [comment]
Are talking about issues like that https://travis-ci.org/mos-polytech/homework-template/builds/278936917#L511 ?

My problem was: `pipenv install -d` raised on `travis`:
> AttributeError: '_NamespacePath' object has no attribute 'sort'

After adding `pipenv install -d --system` everything worked fine.
