### ISSUE TITLE
URLs are lowercased when added to Pipfile which will not resolve for case-sensitive URLs

### ISSUE THREAD

**Issue by mshuffett** [kennethreitz/pipenv#437]
URLs should not be lower-cased because case-sensitive URLs will not resolve.

**Comment by nateprewitt** [comment]
@mshuffett could you please provide some more information on your use case and issue. Is this an external vcs repository?

**Comment by mshuffett** [comment]
I am using it to directly install a tar.gz for from a Nexus artifact repo.
`pipenv install https://foo/KEEPCAPS/bar.tar.gz

The URL is case sensitive so when it lowers the URL in the Pipfile it can't
resolve the URL.

**Comment by kennethreitz** [comment]
fixed!
