### ISSUE TITLE
Pass `--upgrade-strategy=eager` on pip 10+

### ISSUE THREAD

**Issue by ncoghlan** [kennethreitz/pipenv#438]
Pip 10 is changing its default upgrade strategy to "only-if-needed", which isn't the desired behaviour for pipenv's purposes.

In order to retain its current "upgrade everything to the latest version available" behaviour when regenerating the lockfile, `pipenv` will need to pass `--upgrade-strategy=eager` when calling pip.

(This issue replaces #418)

**Comment by kennethreitz** [comment]
Thank you.

**Comment by kennethreitz** [comment]
This shouldn't effect our codebase. But, we'll see :)

**Comment by brettdh** [comment]
This does seem to affect `pipenv lock`, as it doesn't use pip's upgrade strategy settings, and so can result in inconsistent behavior: https://github.com/kennethreitz/pipenv/issues/966#issuecomment-339312709

**Comment by erinxocon** [comment]
@brettdh Are you using python3.7?

**Comment by brettdh** [comment]
@erinxocon 3.6.2

**Comment by erinxocon** [comment]
What is the timeline of pip10's release?

**Comment by brettdh** [comment]
No idea. Where would that information be? The 10.0 GitHub milestone has no
due date.

**Comment by nateprewitt** [comment]
[This](https://groups.google.com/forum/#!topic/pypi-dev/JVTfS6ZdAuM) suggests it's soon. We've been putting off making a decision on this (unless the decision is to do nothing) for a while. Either we wait for problems to crop up after release or we preemptively force the eager check for backwards compat.

**Comment by erinxocon** [comment]
@nateprewitt Forgive my ignorance on the subject, but since we use a vendored/patched version of pip would we have to update our pip or would our pip be unaffected.

**Comment by nateprewitt** [comment]
@erinxocon, I believe it still would because the pip installed in the users environment is coming from the attached Python the virtualenv is built on, not our vendored one which only affects the pipenv code itself.

**Comment by brettdh** [comment]
@nateprewitt see the issue I linked above; those aren’t the only options,
and there are already problems. It would be ideal if pipenv allowed setting
the upgrade strategy, whether as a cli flag or env var. For those that
depend on anything but pip’s default, pipenv has undesirable behavior.

**Comment by techalchemy** [comment]
Right I think we understand that you want to be able to do more. This discussion is about what the default behavior should be when pip changes its default behavior. 

I’m guessing we should keep our current behavior but provide an easy interface to change it.
