### ISSUE TITLE
editable VCS entry in Pipfile.lock overridden when install dependent package

### ISSUE THREAD

**Issue by chuck1** [kennethreitz/pipenv#440]
## What I'm trying to do

There are two packages aiohttp and aiohttp-session. I have forked aiohttp and I want to install my forked version from VCS and have it editable. Then I want to install aiohttp-session from pypi, which depends on aiohttp but this should be satisfied by my VCS version.

## What actually happens

    pipenv --three
    pipenv install -e git+https://github.com/chuck1/aiohttp@chuck1_start_stop#egg=aiohttp
    pipenv lock

Default section of Pipfile.lock

    "default": {
        "aiohttp": {
            "editable": true,
            "git": "https://github.com/chuck1/aiohttp.git",
            "ref": "chuck1-start-stop"
        }
    },

So far so good. Then...

    pipenv install aiohttp-session

Which says that the aiohttp requirement is already satisfied and you can see it's looking at the src/aiohttp

```
Collecting aiohttp-session
  Using cached aiohttp_session-0.8.0-py3-none-any.whl
Requirement already satisfied: aiohttp>=1.0.2 in /home/crymal/.local/share/virtualenvs/tmp.G7fTsQAqiE-icx-TLtR/src/aiohttp (from aiohttp-session)
Requirement already satisfied: chardet in /home/crymal/.local/share/virtualenvs/tmp.G7fTsQAqiE-icx-TLtR/lib/python3.6/site-packages (from aiohttp>=1.0.2->aiohttp-session)
Requirement already satisfied: multidict>=3.0.0 in /home/crymal/.local/share/virtualenvs/tmp.G7fTsQAqiE-icx-TLtR/lib/python3.6/site-packages (from aiohttp>=1.0.2->aiohttp-session)
Requirement already satisfied: async_timeout>=1.2.0 in /home/crymal/.local/share/virtualenvs/tmp.G7fTsQAqiE-icx-TLtR/lib/python3.6/site-packages (from aiohttp>=1.0.2->aiohttp-session)
Requirement already satisfied: yarl>=0.11 in /home/crymal/.local/share/virtualenvs/tmp.G7fTsQAqiE-icx-TLtR/lib/python3.6/site-packages (from aiohttp>=1.0.2->aiohttp-session)
Installing collected packages: aiohttp-session
Successfully installed aiohttp-session-0.8.0
```

I run `pipenv lock` again and now the default section of Pipfile.lock is

    "default": {
        "aiohttp": {
            "version": "==2.2.3"
        },
        "aiohttp-session": {
            "version": "==0.8.0"
        },
        "async-timeout": {
            "version": "==1.2.1"
        },
        "chardet": {
            "version": "==3.0.4"
        },
        "multidict": {
            "version": "==3.1.3"
        },
        "yarl": {
            "version": "==0.12.0"
        }
    },

So why did the aiohttp entry change? Is that the intended behavior? How can I force Pipfile.lock to keep the vcs editable entry for aiohttp?

**Comment by kennethreitz** [comment]
try again with latest. update this ticket if not resolved.

**Comment by chuck1** [comment]
I upgraded pipenv to 8.2.7 and ran the above commands again. I get the same issue, the Pipfile.lock entry for aiohttp switches from my git repo to the pypi version.

**Comment by vphilippon** [comment]
Odd, I tried the above command, and the editable entry stays in the `Pipfile.lock`.
Just in case, can you try running `pipenv lock --clear`? It doesn't look like a cache issue, but its worth trying first, just in case.

If that doesn't solve it, please give the `Pipfile` after running `pipenv install aiohttp-session`,
and also the output of `pipenv lock --verbose`.

**Comment by chuck1** [comment]
Oh it appears I made a mistake, when I ran the commands again I had accidentally left out the "-e" when installing the first package. Now after installing the second package, the editable entry still points to my git repo, so everything is good now. Thanks!
