### ISSUE TITLE
pipenv shell activating incorrect python3

### ISSUE THREAD

**Issue by WuTheFWasThat** [kennethreitz/pipenv#449]
As you can see below, I have a command which works via `pipenv run` but not after entering the virtualenv with `pipenv shell`.

```
rl_sat local # pipenv run python3 src/test.py
✔ 1s

rl_sat local # pipenv shell                                                                                                                                            Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

rl_sat local # python3 src/test.py                                                                                                                                     Traceback (most recent call last):
  File "src/test.py", line 2, in <module>
    import main
  File "/Users/wujeff/Documents/Projects/rl_sat/src/main.py", line 1, in <module>
    from pyrsistent import PVector
ModuleNotFoundError: No module named 'pyrsistent'
✘ [1] 1s
```

I verified the problem is to do with replacing the python links/path.  

```
rl_sat local # pipenv shell                                                                                                                                            Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

rl_sat local # which python3                                                                                                                                          
/usr/local/bin/python3
✔ 0s
```

(As a side note, I find this slightly weird:

```
rl_sat local # pipenv run which python3
The command (/Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/which) was not found within the virtualenv!
✘ [1] 1s
```
)

while using the virtualenv itself directly works:
```
rl_sat local # source /Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/activate
(rl_sat-a4OaVrmj) ✔ 1s

rl_sat local # which python3
/Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/python3
(rl_sat-a4OaVrmj) ✔ 0s

rl_sat local # python3 src/test.py
(rl_sat-a4OaVrmj) ✔ 0s
```

This all is not a huge deal and could have to do with weirdness of my system.  However, I spent some non-trivial time debugging, and it feels like `pipenv shell` should at least have some kind of error message.

**Comment by uranusjr** [comment]
I can’t offer anything to the problem with shell, but the `which` part is expected. `pipenv run` only runs things in your virtualenv, so that there’s zero chance for you to accidentally execute anything else, e.g. running a command with a wrong version because it’s installed globally, and you forgot to install a copy into the local environment. This is a common mistake when using virtualenv, and similar tools from other languages work similarly to Pipenv.

**Comment by kennethreitz** [comment]
you have PATH issues. we have a patch in the next release which will help this.

try calling 'python' instead of 'python3' in your shell.

**Comment by WuTheFWasThat** [comment]
`python` doesn't work either.  it then gives `invalid syntax`

**Comment by erinxocon** [comment]
@WuTheFWasThat can you post the command and output?

**Comment by WuTheFWasThat** [comment]
```
rl_sat local # pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

rl_sat local # python src/test.py
  File "src/test.py", line 8
    def parse_clauses(n: int, succinct_rep: ProblemRepresentation) -> List[Clause]:
                       ^
SyntaxError: invalid syntax
✘ [1] 0s

rl_sat local # which python
/usr/local/bin/python
✔ 0s

rl_sat local # ls -lah /usr/local/bin/python
lrwxr-xr-x  1 wujeff  admin    36B Nov  3  2016 /usr/local/bin/python -> ../Cellar/python/2.7.12_2/bin/python
✔ 0s
```

**Comment by erinxocon** [comment]
@WuTheFWasThat Python2 doesn't support type hinting, but [PEP484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) does address how to do it in python2.  When you created the virtualenv with pipenv did you specify `pipenv --three` or `pipenv --python python3`?  That should create the virtualenv using your systems python3 executable as a base.

**Comment by WuTheFWasThat** [comment]
I am fairly sure I did `pipenv --three`.  How would I check?  It doesn't seem to specified in either the Pipfile nor Pipfile.lock

**Comment by WuTheFWasThat** [comment]
When I activate the virtualenv manually `python --version` returns `Python 3.6.2`

**Comment by erinxocon** [comment]
@WuTheFWasThat I think you have a $PATH issue as @kennethreitz mentioned above.  When I enter into a subshell and do `which python` I get `/Users/erin/.local/share/virtualenvs/pipenv-_3lJS9mX/bin/python` and an `ls -lah` shows it's symlinked to python3 which would make sense as I used the `--three` option to create the virtualenv.  When you did `which python` in the subshell it is showing that it is symlinked to python2.7.  Activating the virtualenv manually modifies your $PATH to place python3.6 at the front.  I would check your path when you are not in the virtualenv.

**Comment by erinxocon** [comment]
Also I would try and unisntall `pipenv` and install it using the [fancy way](http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv).  This seems to avoid the $PATH issues that people have.  The Pew docs can be of help there!

**Comment by WuTheFWasThat** [comment]
ok.  FWIW, nothing seems particularly strange about my $PATH:

```rl_sat local # echo $PATH
/Developer/NVIDIA/CUDA-8.0.61/bin:/Users/wujeff/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/wujeff/.multirust/toolchains/stable/cargo/bin:/Users/wujeff/.multirust/toolchains/1.5.0/cargo/bin:/Users/wujeff/Library/Haskell/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin/:/Users/wujeff/.fzf/bin:/usr/local/go/bin:/opt/local/bin:/opt/local/sbin:/usr/local/cuda/bin```

then in the virtual env when I source it manually:
```
rl_sat local # echo $PATH
/Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin:/Developer/NVIDIA/CUDA-8.0.61/bin:/Users/wujeff/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/wujeff/.multirust/toolchains/stable/cargo/bin:/Users/wujeff/.multirust/toolchains/1.5.0/cargo/bin:/Users/wujeff/Library/Haskell/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin/:/Users/wujeff/.fzf/bin:/usr/local/go/bin:/opt/local/bin:/opt/local/sbin:/usr/local/cuda/bin
```

But when I do `pipenv shell`, and `echo $PATH`, it's unchanged

**Comment by erinxocon** [comment]
The pipenv/pew .local location should be in front of any system level paths when outside of your virtual environment.  The [Pew docs](https://github.com/berdario/pew#troubleshooting) can help you out with the correct $PATH settings.

Here are the first two entries from my $PATH
`/Users/erin/.local/bin:/usr/local/bin`

**Comment by WuTheFWasThat** [comment]
I haven't tried the pipsi installation yet, but I read the code a bit and discovered that `PIPENV_SHELL_COMPAT=true pipenv shell` causes things to work also.  

This actually seems like a bug in `pew`, since the command `pew workon rl_sat-a4OaVrmj` doesn't work for me

**Comment by erinxocon** [comment]
`COMPAT` mode does use `source` to activate the virtualenv, I forgot that was an option.  I'd encourage you to place a bug report with the Pew team with your use case.  I'm gonna close this issue for now!

**Comment by WuTheFWasThat** [comment]
I'm still curious - what is the reasoning for using pew by default?  I'm guessing not many people use `pew` so maybe COMPAT mode should be default instead?  

I submitted an issue there, but I'm not too confident the bug will get fixed.  I don't want to be too critical but since my evidence is a bit weak, but:
- I hit another bug in `pew` immediately while playing around with it
- The `pew` repository isn't too maintained, with the last commit being in January and a number of open PRs, including one that fixes the aforementioned bug

**Comment by kennethreitz** [comment]
Your shell is configured incorrectly. Pew is working fine.

**Comment by WuTheFWasThat** [comment]
sorry, you're right.  I figured it out

**Comment by kennethreitz** [comment]
Pew is a learning experience for all :) ✨🍰✨
