### ISSUE TITLE
conversion of requirements.txt fails for some editable requirements

### ISSUE THREAD

**Issue by sbidoul** [kennethreitz/pipenv#457]
Here is an example editable requirement that is not supported:

`-e git+https://github.com/acsone/account-analytic.git@f263b5e08c45e392b60c9d879353ca71f7ac86ff#egg=odoo10_addon_account_analytic_no_lines&subdirectory=setup/account_analytic_no_lines`

It is due to the `&subdirectory` part, which is not supported by the vendored requirements package.

Here is the incorrect regex:
https://github.com/kennethreitz/pipenv/blob/dde2e52cb8bc9bfca7af6c6b1a4576faf00e84f1/pipenv/vendor/requirements/requirement.py#L23-L27

Here is the relevant stack trace part:
```
$ pipenv --two
Requirements file found, instead of Pipfile! Converting...
Traceback (most recent call last):
  File "/home/me/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
...
  File "/home/me/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/requirements/requirement.py", line 108, in parse_editable
    assert local_match is not None, 'This should match everything'
AssertionError: This should match everything
```

**Comment by kennethreitz** [comment]
please open an issue with the 'requirements' package

**Comment by sbidoul** [comment]
@kennethreitz Is it this one? https://github.com/davidfischer/requirements-parser

Should I open another issue here to add subdirectoy support in pipenv?

**Comment by kennethreitz** [comment]
that's the one! 

Sure :)

**Comment by kennethreitz** [comment]
`-e subdir` should work though

**Comment by sbidoul** [comment]
subdirectory support proposed upstream: https://github.com/davidfischer/requirements-parser/pull/32
