### ISSUE TITLE
`outdated` command

### ISSUE THREAD

**Issue by grv87** [kennethreitz/pipenv#469]
I propose to add this command, as in Bundler, to get the list of new versions of locked packages.

**Comment by kennethreitz** [comment]
What's the purpose when there's "update", which just gets you everything up-to-date?

**Comment by grv87** [comment]
Two purposes, depending on command arguments:
1 See what would be updated without actually updating anything (dry run)
2. Check that there are new versions not satisfied by constraints (e.g. new major releases)

**Comment by kennethreitz** [comment]
This would be difficult to implement, but I like the idea!

**Comment by kennethreitz** [comment]
Our new dependency resolver will make this a lot easier though :)

**Comment by kennethreitz** [comment]
Let's do it!

**Comment by kennethreitz** [comment]
@grv87 can you provide an example output of what you'd expect this command to look like?

**Comment by kennethreitz** [comment]
I'm thinking:

```shell
$ pipenv outdated
Checking [dev-dependencies]...
Flask 0.9.1 is available!
Checking [dependencies]...
pytest 1.2.1 is available!

**Comment by erinxocon** [comment]
I like this idea!

**Comment by grv87** [comment]
Thanks for the quick response!

I have two thoughts about output:
1. It could be machine-readable (maybe not by default, with special argument)
2. Human-readable output should be easy copy-pastable to Pipfile

**Comment by kennethreitz** [comment]
I don't think copy-pastable to a pipfile would be useful — because `outdated` would only show you packages you have *installed* that are out of date *according to your `Pipfile`*. Your `Pipfile` will already be up to date.

**Comment by singleton11** [comment]
I like this idea, too

**Comment by kennethreitz** [comment]
I want to keep this tool as simple as possible — adding another command is a big deal. I don't want to overwhelm users with options.

**Comment by kennethreitz** [comment]
perhaps a flag to the existing `update` command would work.

**Comment by kennethreitz** [comment]
going with `$ pipenv update --dry-run` for now

**Comment by kennethreitz** [comment]
<img width="683" alt="screen shot 2017-09-05 at 5-1 05 21 pm" src="https://user-images.githubusercontent.com/119893/30083437-70dde4ea-925c-11e7-9087-32db2071ca7d.png">

**Comment by kennethreitz** [comment]
this was harder than i expected

**Comment by kennethreitz** [comment]
v5.3.5 released, which contains this.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by grv87** [comment]
Copy-pastable - that was for goal 2.

E.g. you have in Pipfile
```
foo = "~= 1.1"
```
And 2.0 version of `foo` package has been released. It wouldn't be installed by `update`, but I want to be aware that it exists and I could update Pipfile to get it.

**Comment by kennethreitz** [comment]
it's copy-pastable in requirements format currently. we can update that to pipfile format.

**Comment by kennethreitz** [comment]
i think what we have now is good

**Comment by GeyseR** [comment]
I found another way to view all outdated packages in particular environment (basically because `pipenv update --dry-run` didn't work as expected)
Here is the simple command: `pipenv run pip list -o`
