### ISSUE TITLE
Cannot install module - /bin/pip: No such file or directory

### ISSUE THREAD

**Issue by nzagorchev** [kennethreitz/pipenv#470]
Hello,

Trying to install a module fails with the following error:
/bin/sh: /bin/pip: No such file or directory

I am using MacOS and have installed python and python3 using homebrew. 
Then installed pipenv using pip3.

`which pip` returns:
/usr/local/bin/pip
and pip itself is found as a command.

However, if I use `python -m pip --version` it points to the default MacOS python:
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

I am unaware where it tries to resolve pip from and does not find it. 
I am not sure if there is a problem with my $PATH paths or the issue is different. 

Thank you for your time!

**Comment by kennethreitz** [comment]
Try the [fancy installation method](http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv)

**Comment by erinxocon** [comment]
Second. Pipsi is the way to go for installing python cli utils

**Comment by nzagorchev** [comment]
Thanks for the replies.

I first uninstalled and installed again python and python3 using homebrew and also re-installed pip.
Then I was able to successfully install pipenv using pipsi by the provided link for the fancy installation.

However, trying to install any module, I know get the following error:
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/lib/python3.6/site-packages/pipenv/__init__.py", line 13, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 11, in <module>
    import background
ModuleNotFoundError: No module named 'background'

**Comment by nzagorchev** [comment]
Type in the pip-tools. Installed them and now I am back at square one with the initial error:
/bin/sh: /bin/pip: No such file or directory

**Comment by kennethreitz** [comment]
Do you have `PYTHONHOME` set or something?

**Comment by nzagorchev** [comment]
No, I do not.

pip is available in terminal.
$ which pip
/usr/local/bin/pip

but it is only 'attached' to python2 and python3 but not the default python:
$ python -m pip
/usr/bin/python: No module named pip

Any ideas on what could be wrong?

**Comment by nzagorchev** [comment]
Seems the root cause was that `pew` was not working due to not set locale.
Setting it in `.bash_profile` seems to resolve the issue.
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

```
Will further test and later update if this is solved.

**Comment by kennethreitz** [comment]
💫✨🍰✨💫

**Comment by kennethreitz** [comment]
We should check for this and add some pretty error message if it's not set.

**Comment by erinxocon** [comment]
@kennethreitz should pew check for this or should pipenv?

**Comment by kennethreitz** [comment]
@erinxocon pew should.

**Comment by Manmanthan** [comment]
$ hash -r
Reset your bash cache. It will solve the problem.

**Comment by thehesiod** [comment]
I was having an issue only on codebuild, and this solved it for me: https://github.com/pypa/pipenv/issues/1929

**Comment by trinanda** [comment]
Maybe this will help newbies like me in the future.
I Following @nzagorchev comment:

add @nzagorchev script in your `~/.bash_profile` or `~/.zshrc`

`sudo vim ~/.bash_profile` 
or 
`sudo vim ~/.zshrc` if you're using **zsh**

then add the following script to the file

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

then run this command:

`source ~/.bash_profile `
or
`source ~/.zshrc ` if you're using **zsh**

then close your terminal and open it again.

after that, it works perfectly :)

**Comment by stivesdt** [comment]
Me funciono esta opcion 
$pip install -U pip
$which pip
/usr/bin/pip

$hash -r
$which pip
/usr/local/bin/pip
Referencia: [https://stackoverflow.com/questions/16237490/i-screwed-up-the-system-version-of-python-pip-on-ubuntu-12-10](url)
