### ISSUE TITLE
Hash is not checked on pipenv install --ignore-pipfile

### ISSUE THREAD

**Issue by bofm** [kennethreitz/pipenv#479]
I wanted to check if an error is raised when a module hash does not match. So I replaced the hash of "six" module with zeros. And it looks like the installation passes and there is no error.

If I've done it wrong, please forgive me and give an example of how to check the hash check. Thanks!

```
/ # cd /tmp/
/tmp # ls
Pipfile.lock
/tmp # cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "c0440a41b6ee4c518af01ffe9c1f039fcc9cbf3d34003894d32665593cbc6db4"
        },
        "pipfile-spec": 1,
        "requires": {},
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "six": {
            "hash": "sha256:0000000000000000000000000000000000000000000000000000000000000000",
            "version": "==1.10.0"
        }
    },
    "develop": {}
}
/tmp # pipenv install --ignore-pipfile
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/tmp-XVr6zr33/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /root/.local/share/virtualenvs/tmp-XVr6zr33
No package provided, installing all dependencies.
Pipfile found at /tmp/Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
[================================] 1/1 - 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
/tmp # pipenv run pip freeze
six==1.10.0
/tmp # python -V
Python 3.6.2
/tmp # pip freeze | grep pipenv
pipenv==5.3.3
```

**Comment by erinxocon** [comment]
Hmm it probably should be checked, I'll look into this later tonight when I get a chance, thanks for reporting it!

**Comment by kennethreitz** [comment]
hashes are only checked if `--hashes` is provided.

**Comment by kennethreitz** [comment]
need to double check, either I'm right and our help string is out of date, or I'm incorrect and we have a bug.

**Comment by nateprewitt** [comment]
I think the issue is the overall Pipfile.Lock has isn't being checked, not individual hashes. I don't know how we'd verify that though since the hash is on the Pipfile contents, which we're ignoring in this case.

**Comment by bofm** [comment]
@kennethreitz same result with `pipenv install --ignore-pipfile --hashes`.

The help message for `--hashes` says `Generate hashes, if locking.` We are not locking in this case. Not sure what is the desired behaviour. Maybe the message needs a fix.

**Comment by kennethreitz** [comment]
We have a lot of logic in place for hash checking — it's definitely supposed to be working.

**Comment by kennethreitz** [comment]
Bug confirmed.

**Comment by kennethreitz** [comment]
Found the source.

**Comment by kennethreitz** [comment]
Fixed the bug.

**Comment by kennethreitz** [comment]
v5.3.4 just released, which fixes this bug. Hashes are only checked with `--hashes` is provided to `install`, or when the `PIPENV_USE_HASHES` environment variable is set.

**Comment by kennethreitz** [comment]
P.S. that wasn't easy. ✨🍰✨

**Comment by bofm** [comment]
But that was very fast. Thank you.
