### ISSUE TITLE
Fix casing for pip install django

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#48]

**Comment by kennethreitz** [comment]
Added something to the README for now

**Comment by jpadilla** [comment]
Can we just lowercase all package names?

**Comment by kennethreitz** [comment]
maybe...

**Comment by kennethreitz** [comment]
That feels less proper to me

**Comment by kennethreitz** [comment]
but it would work well

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/f98aada0ad3ac41d99487bbe1bcc40989242928d

**Comment by AfzalivE** [comment]
Who thought this was a good idea? I can't install RPi.GPIO because pipenv thinks it should be rpi-gpio? What?
