### ISSUE TITLE
Pipenv should have a `list` subcommand

### ISSUE THREAD

**Issue by jdanford** [kennethreitz/pipenv#485]
Pipenv makes my Python workflow incredibly easy, but since I've started using it, I've wished that I could type `pipenv list` instead of `pipenv run pip list` to check my project's dependencies. Do you have any plans for implementing such a subcommand? If not, I'd be happy to do it myself.

**Comment by kennethreitz** [comment]
no need, when you have pip available.

**Comment by kennethreitz** [comment]
want to keep the list of commands as small as possible.

**Comment by jdanford** [comment]
Fair enough – thanks for the quick response!
