### ISSUE TITLE
`pipenv run` no longer sets up environment correctly

### ISSUE THREAD

**Issue by Diggsey** [kennethreitz/pipenv#488]
It used to be the case that you could do:
`pipenv run python myscript.py`

And it would run the script in the correct virtualenv. However, now it will run it outside the virtualenv, causing imports to fail.

**Comment by Diggsey** [comment]
Likewise, `pipenv run pip install ...` will install packages into the wrong virtualenv.

**Comment by kennethreitz** [comment]
version numbers please.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/5624c342e30903b86f948d9e95c1f922d85f35f1

**Comment by kennethreitz** [comment]
this might be the problem.

**Comment by kennethreitz** [comment]
k new release out, try it again

**Comment by Diggsey** [comment]
Unfortunately the latest release doesn't seem to have fixed the issue. I will attempt to bisect the first failing version.

**Comment by kennethreitz** [comment]
if a virtualenv is activated, pipenv will use it instead.

**Comment by Diggsey** [comment]
Ah, that sounds like the issue. I used to get a message saying the pipenv would be layered on top of the outer virtualenv, so I assumed that was supported behaviour.

I don't have a global python install, so I always use python via a virtualenv. For example, I have one virtualenv for my job, in which pipenv is installed, and then use pipenv to manage per-project environments and dependencies. Is this a use-case you intend to support?

**Comment by kennethreitz** [comment]
You can set `PIPENV_IGNORE_VIRTUALENVS` environment variable to disable this feature.

**Comment by Diggsey** [comment]
That works, thanks. I can no longer run binaries from the outer virtualenv (eg. I used to use `pipenv run ipython`, where ipython was installed in the outer virtualenv, and it would be able to import stuff from the pipenv) but that's just a nice to have.

**Comment by kennethreitz** [comment]
I don't think that was every intended to work :)

**Comment by kennethreitz** [comment]
We might be able to add that though...

**Comment by kennethreitz** [comment]
okay, master now has a `pipenv run --system ipython` capability. added just for you :)

it doesn't work on windows. this never worked before, fyi.

**Comment by Diggsey** [comment]
> it doesn't work on windows. this never worked before, fyi.

I work on windows unfortunately 😛 I must have been thinking of running `pipenv shell`, followed by `ipython`, which *will* use the outer ipython in the inner virtualenv.

**Comment by kennethreitz** [comment]
yes, that should work fine.

**Comment by kennethreitz** [comment]
if you can find a way to give us 'which ipython' in windows, we can make this work on windows too.

**Comment by Diggsey** [comment]
Windows has `where ipython` which behaves the same as `which` on linux.

**Comment by kennethreitz** [comment]
ah!

**Comment by kennethreitz** [comment]
okay landed a patch in master for this then

**Comment by Diggsey** [comment]
Cool, thanks!

**Comment by techalchemy** [comment]
@kennethreitz @Diggsey this is true with the caveat that you should make sure to call it `where.exe` explicitly, possibly you will want to reference it's absolute path on windows (`C:\windows\System32\where.exe` in case `C:\windows\System32` is not on the path).  This will ensure that on windows 10 and for users using powershell they will still get a result from this command.

Reference: [Is there an equivalent of 'which' on the Windows command line?](https://stackoverflow.com/a/304447/6341291)

**Comment by Diggsey** [comment]
@techalchemy that's only relevant when typing `where` into powershell manually - programmatically calling `where`, such as via `ShellExecute` always calls `where.exe`.

**Comment by Diggsey** [comment]
Also, if `System32` (or the wow64 equivalent for 32-bit programs) is not on PATH, everything will break anyway.

**Comment by kennethreitz** [comment]
ugh i'll revert my commit

**Comment by nonylene** [comment]
FYI: We can use `os.execlp` without parsing `which` output :) https://docs.python.org/3.6/library/os.html#os.execlp

**Comment by kennethreitz** [comment]
ah yay

**Comment by techalchemy** [comment]
@Diggsey you don't need to have system32 on your path in an interactive shell on windows...

![image](https://user-images.githubusercontent.com/954310/30242925-13da931e-956e-11e7-85aa-0edbc66ede95.png)

**Comment by Diggsey** [comment]
You don't, but a lot of software already depends on it being there - both programs which use utilities like `where.exe`, and also anything that links to DLLs from that location, since on windows PATH is used for loading shared libraries too.
