### ISSUE TITLE
Rename Pipfile to Pipfile.toml

### ISSUE THREAD

**Issue by Phrohdoh** [kennethreitz/pipenv#49]
There is no benefit to _not_ including the extension.

In fact you will only gain editor highlighting, etc.

**Comment by kennethreitz** [comment]
Raise this issue on https://github.com/pypa/pipfile please

**Comment by jessebraham** [comment]
I think that would be more suitably decided in the [Pipfile project](https://github.com/pypa/pipfile) itself.  They're attempting to create a standard, and modifying that at will won't help with their progress.

**Comment by Phrohdoh** [comment]
I did not realize pipfile was a separate project, will do!
