### ISSUE TITLE
Create a link command

### ISSUE THREAD

**Issue by ewilazarus** [kennethreitz/pipenv#490]
Create a `pipenv --link`command that would be equivalent to `pipenv shell && pip install -e .` to make possible to run tests with tools such as `pytest`.

**Comment by kennethreitz** [comment]
Why not just `pipenv install '-e .'`?

**Comment by kennethreitz** [comment]
I like this idea though.

**Comment by ewilazarus** [comment]
Awesome!

On a second thought, I think a command (`pipenv link`) would be more semantic than an option.

**Comment by kennethreitz** [comment]
want to limit the number of commands to be as small as possible.

**Comment by kennethreitz** [comment]
I think I'd like to encourage the use of `-e .` instead. So, closing. Thanks for the idea, though!
