### ISSUE TITLE
Optimize pipenv

### ISSUE THREAD

**Issue by tricoder42** [kennethreitz/pipenv#493]
This is tracking issue for some performance related problems I've found when trying `pipenv`. I'm willing to help to fix these problems, but @kennethreitz is working too fast and already added some features which helps me debugging (like verbose mode) 😄 

# Problem

`pipenv install` takes incredible amount of time when running with slower internet connection (I have 50Mbps download/upload & 20ms average ping from pypi.python.org, 0% packet loss)

# Causes

## 1. Converting requirements.txt to Pipfile

- Every call of `project.add_package_to_pipfile(package_string)`  triggers `recase_file` of whole `Pipfile`, resulting in O(n^2) calls to `pypi.org`
- After that, another round of `ensure_proper_casing` is triggered unless `PIPENV_SKIP_VALIDATION=0`
- Removing both calls leading to `recase_file` makes converting almost instant

## 2. Installing of all dependencies

- `ensure_project` calls `ensure_pip_file` which validates Pipfile unless `PIPENV_SKIP_VALIDATION=0`
- when installing all packages, `do_init` calls `ensure_pip_file` again

## 3. Locking

Right now, even locking is very slow. Tracking down the root cause.

# Possible solutions

1. *Cache* - I know caching is bad, but what about to cache all requests to `pypi.org` for the duration of script?

2. Recase only when there's a problem - Personally, I almost never edit Pipfile (a.k.a package.json) manually. I always do `pipenv install package`, so this would require one call to `pypi.org` to check proper casing. When reading existing Pipfile, we could assume that all packages have correct names and only recase when there's a problem (package couldn't be found).

Thanks @kennethreitz for helping me yesterday to debug it! 💪

**Comment by kennethreitz** [comment]
We could make PIPENV_SKIP_VALIDATION default — i see no reason not to.

**Comment by kennethreitz** [comment]
okay, `PIPENV_SKIP_VALIDATION` is default to `True` in master.

**Comment by nateprewitt** [comment]
Thanks for such a detailed report @tricoder42! I actually put together a branch for a lot of this a few months ago but it looks like it never got merged in. I think we can definitely do better with the calls to pypi.

**Comment by kennethreitz** [comment]
Looks like this disables importing from requirements.txt. looking into it.

**Comment by tricoder42** [comment]
In that case it's probably enough to fix `add_package_to_pipfile`, because it recase whole file ignoring `PIPENV_SKIP_VALIDATION` settings.

I started diging into this, because I used `PIPENV_SKIP_VALIDATION=1` and it wasn't enough. I think this is the only problematic spot. Locking file is fine as far as I can see. It just requests `pypi.org` for every package (which is required in this case).

**Comment by kennethreitz** [comment]
okay everything's faster now.

**Comment by kennethreitz** [comment]
now we have a new method, `project.recase_file()`, which is only called once.

**Comment by tricoder42** [comment]
Cool! Locking is taking considerable about of time when resolving dependencies, but that's responsibility of `piptools` package. I'll play around with it for a while.

**Comment by kennethreitz** [comment]
It's a hell of a lot faster than what we were doing before, I can assure you that (downloading all the files).

**Comment by kennethreitz** [comment]
I think you just have a particularly slow connection where you're located.

**Comment by kennethreitz** [comment]
released!

**Comment by tricoder42** [comment]
Cool thanks!

Yeah, I assume that connection speed is major factor in this issue. However, I never had such problems with bare `pip`, so I'm just curious how to make `pipenv` not much slower compared to `pip`.

**Comment by kennethreitz** [comment]
this will help a lot

**Comment by kennethreitz** [comment]
pip doesn't do dependency resolution :)
