### ISSUE TITLE
consider locking after every install

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pipenv#50]

**Comment by jpadilla** [comment]
+1 on this. npm updates its shrinkwrap.json if installing/saving the package.json and yarn does the same with yarn.lock.

I think it might be a good rule that if we're updating the Pipfile, we also update the Pipfile.lock, instead of having the user do so everytime. I could tackle this.

**Comment by kennethreitz** [comment]
the only downside is that currently locking is a rather expensive (time-wise) operation.

**Comment by rmad17** [comment]
How about an optional parameter to check for locking after install?

**Comment by kennethreitz** [comment]
@rmad17 done!
