### ISSUE TITLE
Misconfigured shell (Fish)

### ISSUE THREAD

**Issue by thepreacher** [kennethreitz/pipenv#511]
Hi, I'm on mac os and have fish as my shell. Apart from a bunch of aliases and a couple functions, I've not done anything special to my shell. Oh i use ITerm btw. However I can only get pipenv to work ok only if I `set -x PIPENV_SHELL_COMPAT 1`. 

I understand from comments in other issues that, its as a result of a misconfigured shell. Thing is I've spent ages trying to figure out what has been misconfigured in my shell and so far I've found nothing. 

I'd appreaciate if someone with a similar system, terminal and shell can share how they've set theirs up so that, pipenv works without the need for `set -x PIPENV_SHELL_COMPAT 1`.

Cheers.

**Comment by kennethreitz** [comment]
My config looks like this:

```fish

source ~/.aliases

set -g theme_nerd_fonts yes
set -g theme_show_exit_status yes
set -g theme_display_git_untracked no
set -g theme_color_scheme solarized-dark

if status --is-login

    # better ls colors
    set -gx LSCOLORS gxfxcxdxbxegedabagacad

    set -gx PATH /usr/local/bin $PATH

    # Autojump support
    [ -f /usr/local/share/autojump/autojump.fish ]; and source /usr/local/share/autojump/autojump.fish

    # Don't write bytecode, Python!
    export PYTHONDONTWRITEBYTECODE=1

    set SHELL /usr/local/bin/fish

    set -gx PATH /Users/kennethreitz/.local/bin $PATH
    set -gx ANDROID_NDK_HOME /usr/local/share/android-ndk
    set -gx ANDROID_SDK_ROOT /usr/local/share/android-sdk

    # Go support.
    set -x GOPATH /Users/kennethreitz/.go/
    set -x PATH /Users/kennethreitz/.go/bin $PATH

    neofetch
end
```

Note the `if status --is-login`.
