### ISSUE TITLE
support pip --src option

### ISSUE THREAD

**Issue by sbidoul** [kennethreitz/pipenv#513]
When installing editable vcs requirements it is often desirable to control the place where they are downloaded. This is particularly desirable when installing from very large git repos.

pip does this with the --src option

`pipenv install` should support this option and forward it to pip.

**Comment by kennethreitz** [comment]
I don't want to engourage the use of vcs dependencies, so we may not do this.

**Comment by sbidoul** [comment]
Well, I'm just trying to experiment and see if pipenv can cover our day-to-day use cases. 

This and #512 are the show stoppers.

**Comment by kennethreitz** [comment]
I'll see about passing arbitrary flags to pip instal

**Comment by kennethreitz** [comment]
On master:

```shell
$ PIPENV_PIP_INSTALL_FLAGS='--src /path' pipenv install ...
```

**Comment by sbidoul** [comment]
Cool. That reminds me [pip supports environment variables](https://pip.pypa.io/en/stable/user_guide/#environment-variables) (such as PIP_SRC in this case). So maybe it's not necessary to complexify pipenv with that.

**Comment by kennethreitz** [comment]
Ah wonderful! I'll remove this then.

**Comment by kennethreitz** [comment]
Removed. Use the pip flags :)

**Comment by kennethreitz** [comment]
I'll add a note to the docs.

**Comment by kennethreitz** [comment]
Added :) ✨🍰✨

**Comment by ruslanoid** [comment]
hi, guys!
a question on the topic:
is it possible to add the --src flag on a per dependency basis?
for example, if i want a specific repo to be vendorized in my project:

`requests = {git = "https://github.com/requests/requests", editable = true, ref = "81b63419cbd8a6f0c9c2b79083d25dc2260156e3", src="./vendor"}`

this would help avoid remembering setting the PIP_SRC env every time

**Comment by kennethreitz** [comment]
not currently — your request has been heard and noted, however. Thank you.
