### ISSUE TITLE
Exclude Pipfile.lock from the repository

### ISSUE THREAD

**Issue by uranusjr** [kennethreitz/pipenv#514]
Reading #501 makes me wonder whether it is a good idea to check in Pipfile.lock for this particular project (Pipenv). Reading discussions about other similar tools (SO entry on [Bundler](https://stackoverflow.com/q/4151495/)) it seems it is generally recommended to include the lock file if you want everyone to work on the same dependencies (e.g. developing an application), but exclude if you intend to support various versions of dependencies (e.g. developing a library). Now that #295 is implemented it feels even more wrong checking in the lock file and tracking irrelevant changes all the time.

Another thing worth discussing is whether it makes sense to check in Pipfile.lock *at all*. I want identical dependency versions, but don’t usually care about host OS, and it feels wrong that the lock file changes all the time when I work on a Django website on two machines, one Mac and one Windows. Either I’m doing it wrong, or there should be some switches to mark whether a project is platform-specific, Python version-specific (the intention of #295 I think), etc.

**Comment by kennethreitz** [comment]
lockfiles are generally encouraged to be included in source control, for applications.

For us, it might not make sense. But, it's a learning experience, so we're doing it for now. I may remove it. 

The system information is there just as meta-data.

**Comment by kennethreitz** [comment]
Exlcuded lock from out repo.
