### ISSUE TITLE
v6.2.4 broken on python2.7 unix

### ISSUE THREAD

**Issue by erinxocon** [kennethreitz/pipenv#523]
[v6.2.4](https://github.com/kennethreitz/pipenv/releases/tag/v6.2.4) broken on travis `python2.7` because of Unicode stuff.  

Should be an easy fix.  Somehow windows is passing in 2.7.

https://travis-ci.org/kennethreitz/pipenv/jobs/274444968

**Comment by kennethreitz** [comment]
Thanks for the report!

**Comment by kennethreitz** [comment]
fixed
