### ISSUE TITLE
pipfile.lock vs pipfile.freeze

### ISSUE THREAD

**Issue by nateprewitt** [kennethreitz/pipenv#53]
Right now the documentation for [Pipfile](https://github.com/pypa/pipfile/blob/master/README.rst) states the naming conventions are `Pipfile` and `Pipfile.freeze` but the current API implementation here is using the original `Pipfile.lock`. It looks like freeze was the decision in pypa/pipfile#43, but perhaps things have changed since then. It seems like one of the repositories is out of sync with the current naming convention though.

**Comment by kennethreitz** [comment]
Updated pipfile repo
