### ISSUE TITLE
--ignore-hashes is treated as a package name, not an option flag

### ISSUE THREAD

**Issue by Hexxeh** [kennethreitz/pipenv#534]
When running the example command at the bottom of this page: http://docs.pipenv.org/en/latest/advanced.html#pipfile-lock-security-features

The install process fails with `pkg_resources.RequirementParseError: Invalid requirement, parse error at "'--ignore'"`

It looks as if it's treating `--ignore-hashes` as a package name and exploding appropriately.

I checked back and this last worked in v5.3.3.

**Comment by kennethreitz** [comment]
This was removed from our docs, but there's a problem with them building currently.

**Comment by Hexxeh** [comment]
What should the docs say then? We use this flag because our developers use different OSes and so the hashes don't match. What's the replacement workflow?

**Comment by kennethreitz** [comment]
This is now fixed, and hashes are included for all OS-es.

**Comment by Hexxeh** [comment]
Oh perfect, thanks!

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
Docs are now updated, finally. Having trouble with @readthedocs.

**Comment by Hexxeh** [comment]
Hmm, I'm confused about what the expected behaviour is here. We upgraded to 7.0.0 and removed the --ignore-hashes, did pipenv lock on our OSX development laptop. It exploded in deployment where it's on Linux (same Python version).

Is the change that we  _can_ have multiple hashes, on a per platform basis, but you still need to generate them all with each change? If so, is the option to ignore hashes now totally gone?

**Comment by kennethreitz** [comment]
Every release for each version is hashed now and stored in the lock file.

What do you mean by "exploded in deployment"?

**Comment by kennethreitz** [comment]
This should be impossible. Can you share your pipfile.lock?

**Comment by kennethreitz** [comment]
and which package is causing the issue
