### ISSUE TITLE
Add an equivalent of `workon` from virtualenvwrapper

### ISSUE THREAD

**Issue by mjtamlyn** [kennethreitz/pipenv#535]
Workon does two things. When executed with no args, it lists all available projects (i.e. venvs).

More helpfully, it streamlines the activation process when opening a new shell. This is super useful if you have dozens of projects you work on regularly. A possible syntax for pipenv could look like this:

```shell
~ $ pipenv work
blog
django
requests
supersecretproject
pipenv
~ $ pipenv work requests
Moving you to the requests project and activating the shell
(requests) ~/code/requests $
```
(PS1's might not be right for pipenv behaviour, but you get the idea.

This streamlines the developers' flow from:
```
cd code/requests
pipenv shell
```
to just:
```
pipenv work requests
```

It's a minor enhancement but something I'd miss moving from virtualenvwrapper.

**Comment by kennethreitz** [comment]
I like this idea — it would automatically CD into the directory for you, too. 

Unfortunately, we don't keep that information around in the virtualenv. We could add it, but it would only work on new virtualenvs going forward...

**Comment by kennethreitz** [comment]
Also, would need to think of what would happen if there are two directories called 'requests'.

**Comment by kennethreitz** [comment]
<img width="505" alt="screen shot 2017-09-13 at 1-1 03 11 pm" src="https://user-images.githubusercontent.com/119893/30390386-f08b833c-9883-11e7-9094-7bd2591dd4cb.png">

**Comment by kennethreitz** [comment]
<img width="871" alt="screen shot 2017-09-13 at 1-2 19 54 pm" src="https://user-images.githubusercontent.com/119893/30391164-7800c604-9886-11e7-8d42-629817f33ff1.png">

**Comment by kennethreitz** [comment]
okay ready

![](http://share.kennethreitz.org/381j2w341N1v/Screen%20Shot%202017-09-13%20at%201.45.12%20PM.png)

**Comment by kennethreitz** [comment]
got really close to this working — but it was too slow to crawl the directory structure.

**Comment by kennethreitz** [comment]
Tabling it for now — thanks for the idea!

**Comment by piotr-dobrogost** [comment]
> it was too slow to crawl the directory structure.

How about making use of [`WORKON_HOME`](http://virtualenvwrapper.readthedocs.io/en/latest/install.html?highlight=WORKON_HOME#location-of-environments) environment variable and looking for virtualenvs only there? This would give `workon` command for all people used to it from virtualenvwrapper.

**Comment by techalchemy** [comment]
We do this already for anything managed by pew.

**Comment by erinxocon** [comment]
@techalchemy is correct.  This is the default with pew.

**Comment by tuukkamustonen** [comment]
How about just maintaining index file (in `~/.pipenv/` or something)? You should support projects with `PIPENV_VENV_IN_PROJECT=1` also, and simply looking at `WORKON_HOME` is not sufficient for that anyway.

**Comment by techalchemy** [comment]
It will be sufficient for that in the next release where we use temporary environments to make a modification to WORKON_HOME when using VENV_IN_PROJECT with pew.

**Comment by tuukkamustonen** [comment]
@techalchemy Do you mean that you write symlink or something to `WORKON_HOME` even with `VENV_IN_PROJECT`?

**Comment by techalchemy** [comment]
No.  I mean what I said.

```python
    try:
        with temp_environ():
            if PIPENV_VENV_IN_PROJECT:
                os.environ['WORKON_HOME'] = project.project_directory

            c = pexpect.spawn(
                cmd,
                args,
                dimensions=(
                    terminal_dimensions.lines,
                    terminal_dimensions.columns
                )
            )

    # Windows!
    except AttributeError:
        import subprocess
        # Tell pew to use the project directory as its workon_home
        with temp_environ():
            if PIPENV_VENV_IN_PROJECT:
                os.environ['WORKON_HOME'] = project.project_directory
            p = subprocess.Popen([cmd] + list(args), shell=True, universal_newlines=True)
            p.communicate()
            sys.exit(p.returncode)
```

**Comment by ashwinvis** [comment]
If this is working, why is there no open pull request on this feature @kennethreitz?

**Comment by fweidemann14** [comment]
@kennethreitz Is this feature still a thing? I really love Pipenv and recently converted all my projects, but an equivalent to virtualenvwrapper's `workon` would really add that last bit of luxury to it. You should consider adding it ;)

**Comment by kblicharski** [comment]
I'm also interested in this -- workon support would be a great convenience.

**Comment by kennethreitz** [comment]
I prototyped it out, but it's not feasable, unfortunately. Rely on pew's functionality for this.

**Comment by ashwinvis** [comment]
@kennethreitz @fweidemann14 @kblicharski,
I finally understood. Here is a short rosetta, for someone who is as new to pew and pipenv as me.

| virtualenvwrapper + pip | pew + pipenv |
-----------------------------------|---------------------
| mkvirtualenv |  pew new  |
| cpvirtualenv | pew cp |
| lsvirtualenv | pew ls |
| workon | pew workon |
| deactivate | Ctrl + D / exit |
| pip install | pipenv install |

A few gotchas:
* The `cdproject` equivalent from virtualenvwrapper is missing. But `pew setproject` can do the change to directory once.
* `pew new` does not have a `--system-site-packages` option. Instead there is a separate `pew toggleglobalsitepackages` command.

**Comment by jtratner** [comment]
This would be a great table to add to the docs :)

**Comment by jasonslay** [comment]
What would be the workflow for using pew with pipenv? With virutalenvwrapper, mkproject and workon would get your virtualenvs configured and cd to your project. I see that pipenv and pew have some overlap - which command should I be using to create the virtualenv? Should I use pew add from inside a pipenv shell? I'm new to pipenv and love it so far. Justing missing the workon functionality.

**Comment by jtratner** [comment]
Pipenv handles virtualenv creation for you, so you just use `pipenv
install` to create the env, then `pipenv shell` to get an environment or
`pipenv run <COMMAND>` to do something in the shell

**Comment by jasonslay** [comment]
Apologies. I was referring to how to use `pipenv` with `pew` to replace the functionality of virtualenvwrapper. `pew` also creates virtualenvs. What is the workflow for using these packages together?

**Comment by gtalarico** [comment]
To anyone that might interested, I started a light pipenv companion to help do some of the work done by `workon` and `cdproject`. 

Unlike pew, it does not attempt to manage your venvs in any way. All it does is it walks `WORKON_HOME` env and provides a quick way activating the created venvs,  and cds into the project directories.

Venv <> project dir linking is currently done manually, similar to `setprojectdir` but it will be automatic once PR #1861 is merged + released.

https://github.com/gtalarico/pipenv-pipes

**Comment by fweidemann14** [comment]
@gtalarico Now this is exactly what I wanted Pipenv to do, great effort mate. Going to use it for sure!

**Comment by Peibolvig** [comment]
If anyone is interested in a more virtualenvwrapper way, I created [pipenvwrapper](https://github.com/Peibolvig/pipenvwrapper)

I tried pipes and pew and both are very good tools, but not the exact tools I was looking for my workflow, so I built [pipenvwrapper](https://github.com/Peibolvig/pipenvwrapper) using the base code of virtualenvwrapper.

The supported functions (simplified in some cases and no hooks support) are workon, lsvirtualenv, cdproject, cdvirtualenv, cdsitepackages, mkproject and rmvirtualenv.

"Workon" works with the venvs in $WORKON_HOME folder only, as virtualenvwrapper does.

To allow pipenvwrapper coexist with virtualenvwrapper, the function names have been renamed, but if you prefer the original ones and override virtualenvwrapper, you can do so setting an env variable in the shell startup file.

https://github.com/Peibolvig/pipenvwrapper

**Comment by techalchemy** [comment]
I’d be interested in someone convincing Kenneth (via an enhancement proposal) to allow some kind of plugin framework adoption, maybe via pluggy? No idea if that would work here, but I might put something together or provide feedback
