### ISSUE TITLE
Add an equivalent of `allvirtualenv` from virtualenv wrapper

### ISSUE THREAD

**Issue by mjtamlyn** [kennethreitz/pipenv#536]
This utility allows an command to be executed across multiple different environments (by default all of them, but it would be cooler if certain ones could be specified.

It's massively useful when ubiquitous packages (like pip or wheel) are upgraded - just run `allvirtualenv pip install -U pip` and go grab a coffee. When you get back, all 143 virtualenvs on your dev box have the newest pip installed.

A super obvious extension of this would be to upgrade a package in all environments where that package is installed, and show all the environments which are affected. This would be super useful when security releases of certain packages are released, such as Django. Run `pipenv all install --if-present django==1.11.5`, and all the Pipfiles go through and update. This still requires the dev to go through and commit/push/deploy all the projects, but it speeds up one step significantly.

**Comment by kennethreitz** [comment]
this would be a good feature for `pew` though, which powers everything, so if it (either does or will) support this, you'll get the best of both worlds. 

I'd open an issue over there.
