### ISSUE TITLE
index from requirements.txt isn't working

### ISSUE THREAD

**Issue by fruch** [kennethreitz/pipenv#54]
when there  is something like this in `requirements.txt`: 
```
-i http://my_own_pypi/simple
```

it's assume it's a package and tries to install it.
I would expect it to add this to the pipfile as a diffrent index (doesn't pipfile support multiple indexes ?)

**Comment by kennethreitz** [comment]
ah, we'll have to strip those

**Comment by kennethreitz** [comment]
no importing of indexes from those yet, i think it's fine to update it yourself

**Comment by kennethreitz** [comment]
can't expect it to do everything for you!

**Comment by fruch** [comment]
Also seem like the index from pipfile isn't actually being used on pipenv install command...

**Comment by fruch** [comment]
When I've changed it manually

**Comment by kennethreitz** [comment]
Support for that is added in master, will be released (very) soon! (like within the hour)
