### ISSUE TITLE
2nd-order dependencies missing from Pipfile.lock

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#541]
I believe the answer will be "astroid is packaged weird", but this package is [maintained by the PyCQA](https://github.com/PyCQA/astroid) and works fine with the `pip freeze > requirements.txt` workflow, so I'm assuming other packages might exhibit this behavior.

-----

```
$ pipenv --version
pipenv, version 7.0.1

$ pipenv install astroid --python=python2
Creating a virtualenv for this project…
...
Creating a Pipfile for this project…
Installing astroid…
Collecting astroid
  Using cached astroid-1.5.3-py2.py3-none-any.whl
Collecting wrapt (from astroid)
Collecting enum34>=1.1.3; python_version < "3.4" (from astroid)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting singledispatch; python_version < "3.4" (from astroid)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting six (from astroid)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting lazy-object-proxy (from astroid)
Collecting backports.functools-lru-cache; python_version < "3.3" (from astroid)
  Using cached backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Installing collected packages: wrapt, enum34, six, singledispatch, lazy-object-proxy, backports.functools-lru-cache, astroid
Successfully installed astroid-1.5.3 backports.functools-lru-cache-1.4 enum34-1.1.6 lazy-object-proxy-1.3.1 singledispatch-3.4.0.3 six-1.10.0 wrapt-1.10.11

Adding astroid to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!

$ .venv/bin/pip freeze
astroid==1.5.3
backports.functools-lru-cache==1.4
enum34==1.1.6
lazy-object-proxy==1.3.1
singledispatch==3.4.0.3
six==1.10.0
wrapt==1.10.11

$ cat Pipfile.lock
{
    "_meta": {
        ...
        file-spec": 3,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "astroid": {
            "hashes": [
                "sha256:39a21dd2b5d81a6731dc0ac2884fa419532dffd465cdd43ea6c168d36b76efb3",
                "sha256:492c2a2044adbf6a84a671b7522e9295ad2f6a7c781b899014308db25312dd35"
            ],
            "version": "==1.5.3"
        },
        "lazy-object-proxy": {
            "hashes": [
                ...
            ],
            "version": "==1.3.1"
        },
        "six": {
            ...
        },
        "wrapt": {
            ...
        }
    },
    "develop": {}
}
```

`backports.functools-lru-cache`, `enum34`, and `singledispatch` are missing from the `Pipfile.lock` so future reinstalls (and CI runs) will fail.

```
$ pipenv graph
astroid==1.5.3
  - backports.functools-lru-cache [required: Any, installed: 1.4]
  - enum34 [required: >=1.1.3, installed: 1.1.6]
  - lazy-object-proxy [required: Any, installed: 1.3.1]
  - singledispatch [required: Any, installed: 3.4.0.3]
    - six [required: Any, installed: 1.10.0]
  - six [required: Any, installed: 1.10.0]
  - wrapt [required: Any, installed: 1.10.11]
```
-----

I'm guessing that astroid's installation conditionally includes the back-ported Python 2 dependencies, but `pipenv graph` seems to know about them so I don't know why they're missing.

**Comment by kennethreitz** [comment]
Check `$ pip lock --verbose` for more details.

**Comment by kennethreitz** [comment]
this might be a bug in pip-tools, albeit it would be a rather large one...

**Comment by kennethreitz** [comment]
ah, i see what's happening.

**Comment by kennethreitz** [comment]
Asteroid is packaged weird — very fancily, to be exact :)

**Comment by jacebrowning** [comment]
FYI `$ pipenv lock --verbose` makes no mention of the missing packages.

**Comment by kennethreitz** [comment]
You should raise this issue up with pip-tools

**Comment by jacebrowning** [comment]
@kennethreitz I've not used `pip-tools` directly. What use-case have I triggered here?

**Comment by kennethreitz** [comment]
actually, i'm curious — what version of python are you running pipenv on?

**Comment by kennethreitz** [comment]
Yep — you've installed it with Python 3. I'm going to have to work some magic here.

**Comment by kennethreitz** [comment]
This is going to be *tough*.

**Comment by techalchemy** [comment]
You should see:

[setup.py line 22](https://github.com/PyCQA/astroid/blob/master/setup.py#L22)

```
pkginfo = os.path.join(astroid_dir, 'astroid', '__pkginfo__.py')

with open(pkginfo, 'rb') as fobj:
    exec(compile(fobj.read(), pkginfo, 'exec'), locals())
```

plus some fancy byte compilation for installation going on later. It's definitely fancy but I don't see anything _per se_ that would be a problem for pip-tools unless their packaging is importing dependencies circularly or isn't compiling properly.

**Comment by kennethreitz** [comment]
pip tools is using the python version that's installed to resolve the dependencies — e.g the version that's being used to run pipenv, not the one in the virtual environment.

**Comment by kennethreitz** [comment]
so a package name like `enum34>=1.1.3; python_version < "3.4"` will not resolve if you installed pipenv on python 3.6.

**Comment by jacebrowning** [comment]
@kennethreitz Yeah, I have 3.6.1 set as my global Python and use pipenv's `--python=` option for projects that need something else. This generally only comes into play on projects that need to support many Python versions.

**Comment by kennethreitz** [comment]
I'm going to see if I can fix this for you, but it won't be easy.

**Comment by techalchemy** [comment]
@kennethreitz what are the obstacles to building the dependency graph and using that as a lockfile template?

**Comment by kennethreitz** [comment]
we need to run the dependency graph in the client python interpreter — not within pipenv.

**Comment by kennethreitz** [comment]
i think functions are pickleable, so it should be doable...

**Comment by kennethreitz** [comment]
I can't believe I got this to work. Took some serious, serious digging.

**Comment by kennethreitz** [comment]
<img width="669" alt="screen shot 2017-09-07 at 3-1 49 33 pm" src="https://user-images.githubusercontent.com/119893/30416070-b40abc46-98f8-11e7-8496-9a7db57f3376.png">

**Comment by kennethreitz** [comment]
<img width="1431" alt="screen shot 2017-09-14 at 2-2 58 38 am" src="https://user-images.githubusercontent.com/119893/30416085-c2b93678-98f8-11e7-9ea8-0131a65b3e78.png">

**Comment by kennethreitz** [comment]
switched it to using a context manager.

**Comment by kennethreitz** [comment]
```python
class HackedPythonVersion(object):
    def __init__(self, python):
        self.python = python
        self.original = sys.version_info

    def __enter__(self):
        if self.python:
            # Create a new named tuple to place fake version info into.
            sys.version_info = namedtuple('fake_version_info', ['major', 'minor', 'micro', 'releaselevel', 'serial'])

            # Parse Python version.
            python = self.python.split('.')

            # Hack sys.version_info to contain our information instead...
            sys.version_info = sys.version_info(int(python[0]), int(python[1]), int(python[2]), 'final', 0)

    def __exit__(self, *args):
        # Restore original Python version information.
        sys.version_info = self.original
```

**Comment by kennethreitz** [comment]
This took like 4 hours of work.

**Comment by techalchemy** [comment]
This is one of the cleverer things... awesome fix

**Comment by kennethreitz** [comment]
What it does, is it tells pip that we're using a Python other than the one we're actually using — the version info from the virtualenv. This makes Pip resolve `asteriod` properly.

Note that those packages will only show up if `requires_python` is specified in the `Lockfile`.

**Comment by jacebrowning** [comment]
Testing what's on `master`, I'm running into `AttributeError: 'str' object has no attribute 'decode'` at https://github.com/pypa/pip/blob/022248f6484fe87dc0ef5aec3437f4c7971fd14b/pip/utils/__init__.py#L125, which sounds like the pip internals are getting confused about the Python version.

Is there a good place I could help add integration tests for installing specific packages with specific versions of Python?

**Comment by kennethreitz** [comment]
@jacebrowning can you give me steps to reproduce that? I was just about to release this.

**Comment by kennethreitz** [comment]
Yes, in the `tests` directory :)

**Comment by kennethreitz** [comment]
@jacebrowning I don't see how that function would ever be called — what did you do?

**Comment by jacebrowning** [comment]
I can provide some steps in about an hour.

**Comment by kennethreitz** [comment]
Holding off a release until then.

**Comment by kennethreitz** [comment]
Unless I change my mind — it's pretty battle-tested on my end.

**Comment by kennethreitz** [comment]
k, going to release. we can always roll back later.

**Comment by kennethreitz** [comment]
released!

**Comment by jacebrowning** [comment]
My reproduction steps are on https://github.com/kennethreitz/pipenv/issues/548
