### ISSUE TITLE
install "self"

### ISSUE THREAD

**Issue by dlukes** [kennethreitz/pipenv#542]
Is there a way to specify in the Pipfile that the package (for which the Pipfile is being defined) **itself** shoud be installed inside the virtualenv, preferably as editable? I.e. basically running `pip install --editable .` in the directory where `setup.py` is stored.

This is useful for development e.g. in cases where you have subpackages and [run afoul of the limitations of relative imports](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3).

On the other hand, I realize it goes against the reproducible guarantees of Pipfile.lock, since such a package can't be pinned down to a specific version.

**Comment by kennethreitz** [comment]
`pipenv install -e .`.

**Comment by dlukes** [comment]
Oh, perfect, thanks so much! I wouldn't have thought this would work :) Then I would just suggest documenting it, if time permits, it's a really handy feature.

**Comment by kennethreitz** [comment]
i was hoping it would be obvious :)

**Comment by dlukes** [comment]
Well, for one thing the syntax looks like a command line flag, but [as far as I can see in the source code](https://github.com/kennethreitz/pipenv/blob/410608e5887bdd2bfc14ba5e194968af8660c2cf/pipenv/cli.py#L1279), it's treated special, which means it's not documented in the output of `pipenv install --help`... It would be nice if it showed up at least there, if you think it's too minor a feature to be included in the tutorial :)

**Comment by uranusjr** [comment]
Well in Pip `-e` and `--editable` do the same thing, so maybe Pipenv should as well?
