### ISSUE TITLE
pipenv fails if which command is not installed

### ISSUE THREAD

**Issue by fogfish** [kennethreitz/pipenv#544]
We are using vanilla CentOs docker images.  pipenv fails with the error 
```
pipenv run python --version
Error: the command python could not be found within PATH.
```

How to reproduce:
```
docker run -it centos bash
yum -y install https://centos7.iuscommunity.org/ius-release.rpm
yum -y install python36u
curl -O https://bootstrap.pypa.io/get-pip.py
python3.6 get-pip.py
pip install pipenv
```

How to fix:

it looks like `which` utility is required by pipenv
```
yum -y install which

pipenv run python --version
Python 3.6.2
```

It would be nice to improve an error message of pipenv.

**Comment by kennethreitz** [comment]
is which not part of the linux standard base?

**Comment by kennethreitz** [comment]
Fixed!

**Comment by FMCorz** [comment]
I encountered the same error because for some reason `/usr/local/bin/which` was defined... I tracked it down to `yarn` and `istanbul` but I can't explain how it got there. Must be my mistake.

```
> ll /usr/local/bin/
lrwxrwxrwx 1 root root  79 Oct 26 17:04 which -> ../share/.config/yarn/global/node_modules/istanbul/node_modules/which/bin/which*
