### ISSUE TITLE
Pipfile touched even on pipenv run

### ISSUE THREAD

**Issue by mbarkhau** [kennethreitz/pipenv#546]
I have a watch command tracking my `Pipfile` but on every call of `pipenv run` the command is executed, even if the file wasn't changed. I tracked this down to the call of `Project.touch_pipfile`. I'm not sure if it required, for `Pipfile` to be touched every time, probably it is just a side effect of calling  `cli.py@ensure_project`.

Would it be reasonable to only touch the `Pipfile` if it either doesn't exist or if there is actually a change to its contents?

**Comment by jacebrowning** [comment]
I noticed this too. In my Makefiles, I run `pipenv install` when `Pipfile*` is newer than the installed dependencies, but now this runs all the time.

**Comment by kennethreitz** [comment]
Is this just annoying, or a real problem?

**Comment by kennethreitz** [comment]
landed a fix in master

**Comment by mbarkhau** [comment]
IIUC this was supposed to have been fixed with 7.1.0, but the issue persists for me.

```
$ pipenv --version                                                            
pipenv, version 7.1.0                                                         
$ ls -l --time-style=full-iso Pipfile                                         
-rw-rw-r-- 1 mbarkhau mbarkhau 416 2017-09-15 09:46:34.611467318 +0200 Pipfile
$ pipenv run python -m os                                                     
$ ls -l --time-style=full-iso Pipfile                                         
-rw-rw-r-- 1 mbarkhau mbarkhau 416 2017-09-15 09:46:56.526411866 +0200 Pipfile
```
To answer the earlier question, mostly this is just very confusing, as opposed to being a real problem.

**Comment by jacebrowning** [comment]
Same for me. It's not a huge deal but it breaks all my build caching. It _could_ cause issues if pipenv intends to run in a container with a read-only filesystem.

**Comment by mbarkhau** [comment]
Hi @kennethreitz I think this may have fallen off your radar, or is this a non issue in your view?

**Comment by kennethreitz** [comment]
the file should only be touched when it doesn't exist. I can look into it, but i don't see it as a big issue, no.

**Comment by jacebrowning** [comment]
The `Pipfile` is still updated on every run with 7.6.7.

For reference, this is the Makefile pattern that this causes problems with:

```

.PHONY: install
install: .venv/installed
.venv/installed: Pipfile*
	pipenv install --dev
	@ touch $@

.PHONY: run
run: install
	pipenv run honcho start
```

**Comment by kennethreitz** [comment]
You should be checking the lockfile for changes.

**Comment by kennethreitz** [comment]
It's what's being used for install anyway.

**Comment by kennethreitz** [comment]
@jacebrowning i'd be happy to accept a pull request that doesn't touch the makefile on every run — there's code in place to only touch it if it doesn't exist, so i'm not sure why this is happening, so you'd have to dig in a little bit.

**Comment by jacebrowning** [comment]
Cool. I'll look into it.

**Comment by kennethreitz** [comment]
I would recommend keying off of the lockfile though — it's what's important, not the Pipfile.

**Comment by kennethreitz** [comment]
and the lockfile doesn't get touched constantly.

**Comment by kennethreitz** [comment]
pipenv automatically re-locks whenever anything gets installed/uninstalled, so it should take care of all your problems.

**Comment by jacebrowning** [comment]
Yeah. It's still handy to be able to manually add packages to the `Pipfile` or update version specs and have these changes get picked up automatically by Make tasks.

**Comment by kennethreitz** [comment]
Gotcha. The intention behind pipenv is that you never have to edit the pipfile yourself unless you're doing fancy stuff (like markers, etc)
