### ISSUE TITLE
Windows Tests

### ISSUE THREAD

**Issue by erinxocon** [kennethreitz/pipenv#547]
Should just leave this issue open forever @kennethreitz...  Will be submitting a PR soon *sigh*

**Comment by kennethreitz** [comment]
i'll get better about testing on windows, myself. About to spin up an installation on my windows box and see what unicode stuff needs to be fixed.

**Comment by kennethreitz** [comment]
okay so our new progress bar is broken on windows. will revert for windows.

**Comment by erinxocon** [comment]
The unicode stuff is really for windows 2.7.  3.x has other problems that I'm looking at.

**Comment by kennethreitz** [comment]
I'm looking at 3 right now

**Comment by kennethreitz** [comment]
UX stuff

**Comment by kennethreitz** [comment]
okay got stuff working well on 3.x on windows.

**Comment by erinxocon** [comment]
Still failing on app veyor.

```pipenv install --dev --skip-lock
Warning: Python 3.6 was not found on your system� 
You can specify specific versions of Python with:
  $ pipenv --python path\to\python
Command exited with code 1```

**Comment by kennethreitz** [comment]
ah, i can confirm that. will look into it.

**Comment by erinxocon** [comment]
could it have to do with something around the python version check stuff that happens for the python_requires feature?

**Comment by kennethreitz** [comment]
that's exactly what it is.

**Comment by kennethreitz** [comment]
fixed it!

**Comment by kennethreitz** [comment]
`shellquote` to the rescue!

**Comment by kennethreitz** [comment]
screw appveyor

**Comment by kennethreitz** [comment]
(great company, though)

**Comment by erinxocon** [comment]
PR #555 should address this
