### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#548]
Continued from https://github.com/kennethreitz/pipenv/issues/541#issuecomment-329518287

---

This issue is likely to show up on libraries that need to support both Python 2 and 3 where `pipenv` is being used to manage tooling. The feature:

> Tell pip we're using the required Python version, with trickery, for dependency resolution.

is keyed off `python_version = "2.7"`, but to test that this project works with multiple versions of Python, my build matrix also runs with version of Python 3.

1. Install Python 2
2. Install Python 3 and set this as your global Python version
3. Install pipenv 7.0.2
4. Set a required Python version of 2.7 in `Pipfile`
5. Run `$ pipenv install --python=python2`

@kennethreitz here are some build logs demonstrating the issue: https://travis-ci.org/jacebrowning/verchew/builds/275563258

**Comment by kennethreitz** [comment]
if you have `version_version` set, there's no need to specify `--python` now.

**Comment by kennethreitz** [comment]
you shouldn't be using `python_version` is sounds like, if you're testing against multiple pythons.

**Comment by jacebrowning** [comment]
I didn't have `python_version` previously, but you said I needed to add it (https://github.com/kennethreitz/pipenv/issues/541#issuecomment-329512659) in order for pipenv to detect the Python 2 dependencies correctly.

**Comment by kennethreitz** [comment]
that would be correct.

**Comment by kennethreitz** [comment]
Why aren't you committing a pipfile.lock?

**Comment by jacebrowning** [comment]
@kennethreitz Simply to show this exception occurring in build logs.

**Comment by kennethreitz** [comment]
i think removing the pip requests session will fix this

**Comment by kennethreitz** [comment]
that's what's adding the logging

**Comment by kennethreitz** [comment]
can you try master?

**Comment by jacebrowning** [comment]
@kennethreitz That seems to either hit the same error or `NameError: name 'unicode' is not defined` based on the Python version: https://travis-ci.org/jacebrowning/verchew/builds/275601507

**Comment by kennethreitz** [comment]
@jacebrowning can you share you pipfile with us? I cannot reproduce this.

**Comment by kennethreitz** [comment]
try updating travis' pip to latest, which is what we require anyway.

**Comment by kennethreitz** [comment]
e.g. travis' pip is ancient. I'll cut a release depending on latest pip.

**Comment by kennethreitz** [comment]
7.0.5 released, which depends on latest pip. hopefully that'll solve this issue.

**Comment by jacebrowning** [comment]
The `Pipfile` is here: https://github.com/jacebrowning/verchew/blob/2099e17c5f8dee0319d4311915a4a86eca43397b/Pipfile

I just gave you push access if you want to create your own throwaway branch to use this project as a test bed for pipenv with multiple Python versions and version-specific dependencies.

**Comment by kennethreitz** [comment]
thanks. this is impossible to reproduce locally.

**Comment by kennethreitz** [comment]
@jacebrowning looks like 7.0.5 works!

**Comment by kennethreitz** [comment]
i take that back.

**Comment by jacebrowning** [comment]
So... I'm thinking that pipenv should refuse to run if all of the following are true:

- `Pipfile` specifies a Python version
- `Pipfile.lock` doesn't exist
- `python` is a different version than what is specified in `Pipfile`

7.0.5 looks like it might be working, but he generated `Pipfile.lock` will only work with Python 2 if it was originally generated with Python 2 (for "fancy" dependencies).

**Comment by jacebrowning** [comment]
I'm not what to do if new "fancy" dependencies are added later. Maybe it should always fail hard if `python` is different from the required version listed in `Pipfile`?

**Comment by kennethreitz** [comment]
that sounds reasonable. We do issue a warning currently.

**Comment by kennethreitz** [comment]
trying an alternative approach first.

**Comment by kennethreitz** [comment]
yeah, cannot reproduce locally, even with your exact `Pipfile`.

**Comment by kennethreitz** [comment]
well, your solution is to commit your lockfile.

**Comment by kennethreitz** [comment]
got it working.

**Comment by kennethreitz** [comment]
You're welcome.

**Comment by kennethreitz** [comment]
v7.0.6 released, which fixes this strange edge case.
