### ISSUE TITLE
Unable to activate virtualenv

### ISSUE THREAD

**Issue by kevbradwick** [kennethreitz/pipenv#549]
On a Mac, when running ```pipenv run python```, the following error occurs

```
pipenv run python -V
Warning: There was an unexpected error while activating your virtualenv. Continuing anyway…
Python 3.6.1
```

It appears to be down to when pipenv is attempting to activate the virtualenv https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L1549. When printing out the exception message, I get;

```[Errno 2] No such file or directory: '"/Users/kevinbradwick/.local/share/virtualenvs/nltk-ZIngsREP/bin/activate_this.py"'``` 

The entire path is quoted in double quotes, which of course, is not part of the path hence it failing to open.

**Comment by kennethreitz** [comment]
thanks, will fix asap

**Comment by kennethreitz** [comment]
7.0.4 is out, which should fix this.

**Comment by kennethreitz** [comment]
sorry about the bug!

**Comment by kevbradwick** [comment]
awesome yeah, that's fixed it! thank you for building great tools!
