### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by oca159** [kennethreitz/pipenv#55]
I am using pipenv on windows.
I followed the next steps:

```
pip install pipenv
mkdir something
cd something
pipenv.exe --two install requests
```

I am receiving the next error:

Error:  An error occured while installing requests
The system cannot find the path specified.

**Comment by kennethreitz** [comment]
windows has not currently been tested

**Comment by kennethreitz** [comment]
however, the usage would be:

```
$ pipenv --two
$ pipenv install requests

**Comment by kennethreitz** [comment]
windows is not supported
