### ISSUE TITLE
when there is non-ascii charactor (e.g., Chinese) in the path to the project....

### ISSUE THREAD

**Issue by morningmorningwind** [kennethreitz/pipenv#567]
Here is the error (Python version: 2.7.13):

File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv/project.py", line 91, in virtualenv_name
    hash = hashlib.sha256(self.pipfile_location.encode()).digest()[:6]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 65: ordinal not in range(128)

**Comment by kennethreitz** [comment]
Install pipenv using python 3 :)
