### ISSUE TITLE
Unexpected behavior with PIPENV_USE_SYSTEM and PIPENV_IGNORE_VIRTUALENVS

### ISSUE THREAD

**Issue by brosner** [kennethreitz/pipenv#568]
In my shell environment, I am seeing behavior I would not expect. I've been able to correct the behavior by setting `PIPENV_IGNORE_VIRTUALENVS`, but why I have to is really confusing me.

I am using pyenv for managing Python versions only (no funny virtualenv management, this is why I want to use pyenv). I've configured my shell to ensure pyenv doesn't sit in-front of the virtual environment's bin path. I understand this can be accomplished with `PIPENV_SHELL_COMPAT`, but I am effectively doing the same thing and confirmed it is working correctly.

That aside, when I cd to my project and run `pipenv install --verbose` I see it choose the correct `pip` path (the `pip` in the environment for the project). Then I used `pipenv shell` and at some point realized I needed to install another dependency so naturally I ran `pipenv install -d flake8`. This invocation is using my system pip. This was completely unexpected. After digging around I found that the basis of this decision is in how `PIPENV_USE_SYSTEM` is set. If the environment variable `VIRTUAL_ENV` has a value it will use the system pip (or more precisely the pip in the environment where pipenv is installed). To further complicate matters, the comment above `PIPENV_USE_SYSTEM` confused me:

> Tells Pipenv to use the virtualenv-provided pip instead.

which leads me to think that pipenv must be installed in each virtual environment?

I am not quite sure what the solution is, but I feel there is at least a documentation change needed somewhere. The fact that setting `PIPENV_IGNORE_VIRTUALENVS` actually lets me respect the the virtual env is backwards.

Thank you for pipenv and I am looking forward to continuing to use it! Great work!

**Comment by kennethreitz** [comment]
Pipenv will automatically use a virtualenv if it finds itself within one. Meaning, it will install packages into the virtualenv if it's being run inside a virtualenv, instead of creating its own. 

That's what `PIPENV_IGNORE_VIRTUALENVS` is for  — to disable this nice feature, that was much-requested.

**Comment by brosner** [comment]
The behavior you describe is exactly what I would expect, but that isn't happening for me. When I am in a virtual environment it is installing using the system pip. Perhaps I didn't explain myself well enough.

Here is a concrete example...

With `PIPENV_SHELL_COMPAT` (as recommended by the docs for use with pyenv) and `PIPENV_IGNORE_VIRTUALENVS` not set:

```
buzz:~/D/Sandbox
➜  mkdir mysite
buzz:~/D/Sandbox
➜  cd mysite
buzz:~/D/S/mysite
➜  pipenv install --verbose django
Creating a virtualenv for this project…
Using base prefix '/Users/brian/.pyenv/versions/3.6.2'
New python executable in /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/python3.6
Also creating executable in /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg
Creating a Pipfile for this project…
Installing django…
⠙$ "/Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/pip" install   "django" -i https://pypi.python.org/simple --exists-action w
Collecting django
  Using cached Django-1.11.5-py2.py3-none-any.whl
Collecting pytz (from django)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: pytz, django
Successfully installed django-1.11.5 pytz-2017.2

Adding django to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
buzz:~/D/S/mysite
➜  pipenv shell
Spawning environment shell (/usr/local/bin/zsh).
source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
buzz:~/D/S/mysite
➜  source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
(mysite-xgb6m3Cg)buzz:~/D/S/mysite
➜  pipenv install --verbose flake8
Installing flake8…
⠋$ "/Users/brian/.pyenv/versions/3.6.2/bin/pip" install   "flake8" -i https://pypi.python.org/simple --exists-action w
Collecting flake8
  Using cached flake8-3.4.1-py2.py3-none-any.whl
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8)
  Using cached pyflakes-1.5.0-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pyflakes, mccabe, pycodestyle, flake8
Successfully installed flake8-3.4.1 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.5.0

Adding flake8 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
```

Now with `PIPENV_IGNORE_VIRTUALENVS` set:

```
buzz:~/D/Sandbox
➜  mkdir mysite
buzz:~/D/Sandbox
➜  cd mysite
buzz:~/D/S/mysite
➜  pipenv install --verbose django
Creating a virtualenv for this project…
Using base prefix '/Users/brian/.pyenv/versions/3.6.2'
New python executable in /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/python3.6
Also creating executable in /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg
Creating a Pipfile for this project…
Installing django…
⠙$ "/Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/pip" install   "django" -i https://pypi.python.org/simple --exists-action w
Collecting django
  Using cached Django-1.11.5-py2.py3-none-any.whl
Collecting pytz (from django)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: pytz, django
Successfully installed django-1.11.5 pytz-2017.2

Adding django to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
buzz:~/D/S/mysite
➜  pipenv shell
Spawning environment shell (/usr/local/bin/zsh).
source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
buzz:~/D/S/mysite
➜  source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
(mysite-xgb6m3Cg)buzz:~/D/S/mysite
➜  pipenv install -d flake8 --verbose
Installing flake8…
⠋$ "/Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/pip" install   "flake8" -i https://pypi.python.org/simple --exists-action w
Collecting flake8
  Using cached flake8-3.4.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8)
  Using cached pyflakes-1.5.0-py2.py3-none-any.whl
Installing collected packages: mccabe, pycodestyle, pyflakes, flake8
Successfully installed flake8-3.4.1 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.5.0

Adding flake8 to Pipfile's [dev-packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
```

Notice in the first output after I run `pipenv shell` the path to pip is my system pip (ala global)?

**Comment by kennethreitz** [comment]
looks like their might be a bug

**Comment by kennethreitz** [comment]
but i heavily doubt it, will need to read this over carefully

**Comment by kennethreitz** [comment]
can you run `env` in your standard environment (the first example) and send the output? i suspect that pyenv is actually running a virtualenv for you, without you knowing it.

**Comment by techalchemy** [comment]
I am curious about the behavior of this as well.  If there is a bug it will be an easy fix but will require confirmation

**Comment by brosner** [comment]
I won't be able to get to this today, but I suspect there is something odd going on in my environment. I dig a bit deeper to see if it is specific to me or pyenv in general. Thanks for re-opening. I hope the result of this will be helpful for someone else if it is more broadly applicable to pyenv.

**Comment by kennethreitz** [comment]
@brosner run `python -c 'import os; print(os.environ.keys())'` where `python` is the python being used by pyenv.

**Comment by kennethreitz** [comment]
And show us the output.

**Comment by kennethreitz** [comment]
I'm hoping that Pyenv is indeed using a virtual environment automatically, and that it also sets another environment variable, so we can disable this functionality specifically for it.

**Comment by brosner** [comment]
I don't think, to my decent understanding of pyenv, that it is running a virtual env. The virtual env used in the non-shell version is correct to and consistent in a non-pyenv environment.

```
KeysView(environ({'TERM_PROGRAM': 'iTerm.app', 'PYENV_ROOT': '/Users/brian/.pyenv', 'TERM': 'xterm-256color', 'SHELL': '/usr/local/bin/zsh', 'TMPDIR': '/var/folders/42/qmysshqn2sz098bdhx9wqjcw0000gn/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.COYCB6UZyn/Render', 'TERM_PROGRAM_VERSION': '3.1.beta.9', 'TERM_SESSION_ID': 'w0t2p0:2E1D3198-0F2A-4D92-A0CD-345D6BC6ACE4', 'PYENV_VERSION': '3.6.2:2.7.13', 'ZSH': '/Users/brian/.oh-my-zsh', 'PIPENV_IGNORE_VIRTUALENVS': 'yes', 'USER': 'brian', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.rXgtYYSHwQ/Listeners', 'PYENV_DIR': '/Users/brian/Development/Sandbox/mysite', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'VIRTUAL_ENV_DISABLE_PROMPT': '1', 'PAGER': 'less', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'GPGKEY': '6E677E82', 'PATH': '/Users/brian/.pyenv/versions/3.6.2/bin:/usr/local/Cellar/pyenv/1.1.3/libexec:/Users/brian/google-cloud-sdk/bin:/Users/brian/.pyenv/shims:/Users/brian/.pyenv/bin:/Users/brian/.local/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brian/.config/yarn/global/node_modules/.bin', 'PWD': '/Users/brian/Development/Sandbox/mysite', 'EDITOR': 'nvim', 'PIPENV_SHELL_COMPAT': 'YES', 'LANG': 'en_US.UTF-8', 'PYTHONSTARTUP': '/Users/brian/.pythonrc', 'ITERM_PROFILE': 'Default', 'PYENV_HOOK_PATH': '/Users/brian/.pyenv/pyenv.d:/usr/local/Cellar/pyenv/1.1.3/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks', 'XPC_FLAGS': '0x0', 'PYTHONDONTWRITEBYTECODE': 'true', 'XPC_SERVICE_NAME': '0', 'SSH_KEY_PATH': '~/.ssh/id_ed25519', 'GPG_TTY': '/dev/ttys001', 'PYENV_SHELL': 'zsh', 'SHLVL': '1', 'HOME': '/Users/brian', 'COLORFGBG': '15;0', 'ITERM_SESSION_ID': 'w0t2p0:2E1D3198-0F2A-4D92-A0CD-345D6BC6ACE4', 'LESS': '-R', 'LOGNAME': 'brian', 'LC_CTYPE': 'en_US.UTF-8', 'DISPLAY': '/private/tmp/com.apple.launchd.SwerVPkzED/org.macosforge.xquartz:0', 'COLORTERM': 'truecolor'}))
```

**Comment by kennethreitz** [comment]
Hmm, I'll install pyenv and play with it today.

**Comment by kennethreitz** [comment]
Well, as a side effect of this, I got this working :)

<img width="831" alt="screen shot 2017-09-16 at 1-1 56 28 pm" src="https://user-images.githubusercontent.com/119893/30514628-01fe4d60-9ae7-11e7-9c32-6f8401a42728.png">

**Comment by kennethreitz** [comment]
Can you run `pipenv shell -c` and and show us your path? I'm thinking that your system path is somehow getting loaded ahead of the virtualenv's path.

**Comment by kennethreitz** [comment]
it should be noted that modifying important variables like PATH should only be occuring *during a login session", not on every shell spawn. In fish, this looks like this:

```fish

if status --is-login
    set -gx PATH /usr/local/bin $PATH
endif
```

**Comment by brosner** [comment]
```
➜  pipenv shell -c
Spawning environment shell (/usr/local/bin/zsh).
source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
buzz:~/D/S/mysite
➜  source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
(mysite-xgb6m3Cg)buzz:~/D/S/mysite
➜  printenv PATH
/Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin:/Users/brian/google-cloud-sdk/bin:/Users/brian/.pyenv/shims:/Users/brian/.pyenv/bin:/Users/brian/.local/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brian/.config/yarn/global/node_modules/.bin
```

**Comment by brosner** [comment]
Wow, love that pyenv feature! Thanks @kennethreitz :-)

**Comment by kennethreitz** [comment]
@brosner do that again and then run `which pip`.

**Comment by kennethreitz** [comment]
I'm still perplexed as to why this is happening. Would you be down for doing a screensharing session?

**Comment by techalchemy** [comment]
I think I can confirm this behavior at least... got pyenv configured and from a new shell...  Essentially, _PIPENV_IGNORE_VIRTUALENVS_ and _PIPENV_USE_SYSTEM_ aren't actually instructing pipenv to prioritize the system path, but actually they are doing the opposite!

Here is the relevant chain of logic, but essentially the default behavior assigns a python path to PIPENV_USE_SYSTEM, which is interpreted in the code as meaning we should actuallly _NOT_ use the virtualenv python we are assigning: 

```python
# environments.py
PIPENV_USE_SYSTEM = os.environ.get('VIRTUAL_ENV') if 'PIPENV_IGNORE_VIRTUALENVS' not in os.environ else False
```

Roughly, if _PIPENV_IGNORE_VIRTUALENVS_ is **not** set, use the _VIRTUAL_ENV_ value for _PIPENV_USE_SYSTEM_, but by default _PIPENV_USE_SYSTEM is false.  This is important, because in `cli.py`:

```python
    if PIPENV_USE_SYSTEM:
        system = True
    ...
    for package_name in package_names:
        ...
        with spinner():
            c = pip_install(package_name, ignore_hashes=True, allow_global=system, no_deps=False, verbose=verbose)
```

Note that `allow_global` is passed to `which_pip()` which does the following:

```python
def which_pip(allow_global=False):
    """Returns the location of virtualenv-installed pip."""
    if allow_global:
        return distutils.spawn.find_executable('pip')

    return which('pip')
```

## Without _PIPENV_IGNORE_VIRTUALENVS_ set

```bash
$ mkdir /tmp/new && cd /tmp/new
$ echo $PIPENV_SHELL_COMPAT
True
$ echo $PIPENV_IGNORE_VIRTUALENVS

$ echo "Which pip: " $(which pip) " || which pipenv: " $(which pipenv)
Which pip:  /home/hawk/.pyenv/shims/pip  || which pipenv: /home/hawk/.pyenv/shims/pipenv
$ pipenv install --verbose django
$ pipenv shell
$ which pip
/home/hawk/.local/share/virtualenvs/new-X2WGxJLe/bin/pip
$ which pipenv
/home/hawk/.pyenv/shims/pipenv
$ pipenv install --verbose flake8
Installing flake8…
⠋$ "/home/hawk/.pyenv/versions/3.6.2/bin/pip" install   "flake8" -i https://pypi.python.org/simple --exists-action w
```

## With _PIPENV_IGNORE_VIRTUALENVS_ set

```bash
$ pipenv --rm && rm -rf Pipfil*
$ export PIPENV_IGNORE_VIRTUALENVS="True"
$ echo $PIPENV_SHELL_COMPAT
True
$ echo $PIPENV_IGNORE_VIRTUALENVS
True
$ pipenv install --verbose django
$ pipenv shell
$ which pip
/home/hawk/.local/share/virtualenvs/new-X2WGxJLe/bin/pip
$ which pipenv
/home/hawk/.pyenv/shims/pipenv
$ pipenv install --verbose flake8
Installing flake8…
⠋$ "/home/hawk/.local/share/virtualenvs/new-X2WGxJLe/bin/pip" install   "flake8" -i https://pypi.python.org/simple --exists-action w
```

![Without Ignore Virtualenvs](https://user-images.githubusercontent.com/954310/30524135-e1d1d2b6-9bbb-11e7-88a1-846d2431869b.png)

![With Ignore Virtualenvs](https://user-images.githubusercontent.com/954310/30524258-4a007462-9bbe-11e7-9dfd-e131e71184d2.png)

**Comment by techalchemy** [comment]
Basically I feel like we should have it be something like pipenv_prefer_virtualenv

**Comment by kennethreitz** [comment]
PIPENV_USE_SYSTEM tells pipenv to use the pip it was installed with, which is assumed to be system pip.

**Comment by kennethreitz** [comment]
So, i'm not seeing a bug here.

**Comment by techalchemy** [comment]
Right, but currently we have 2 cases driving the value of PIPENV_USE_SYSTEM:
1.  'PIPENV_IGNORE_VIRTUALENVS' is set
    * PIPENV_USE_SYSTEM will be either blank or the value of 'VIRTUAL_ENV'
    * Default behavior will actually USE the virtual env path first and not the system path
2.  'PIPENV_IGNORE_VIRTUALENVS' is not set 
    * PIPENV_USE_SYSTEM is False
    * Default behavior WILL ignore the virtual env and USE the system

The behavior is literally the opposite of what the variable names are

**Comment by kennethreitz** [comment]
no they aren't actually

**Comment by kennethreitz** [comment]
it's don't exactly what it's configured to do

**Comment by kennethreitz** [comment]
`PIPENV_IGNORE_VIRTUALENVS` IGNORES THE CURRENTLY ACTIVATED VIRTUALENV, which you have, which is why you have it using "system pip" normally — becuase you running in a virtual environment. 

this is a feature, not a bug.

**Comment by kennethreitz** [comment]
@brosner you installed pipenv into a virtual environment, so it is using that instead of creating a new one, automatically. You should indeed either install it at a system level, or set `PIPENV_IGNORE_VIRTUALENVS`. 

This tells pipenv to ignore the currently activated virtual environment, and manage environments itself instead. 

I'll make a change so that we raise a Courtesy Notice when we do this, so reduce confusion.

**Comment by brosner** [comment]
My pipenv is installed globally.

```
buzz:~/D/S/mysite
➜  which pip
/Users/brian/.pyenv/shims/pip
buzz:~/D/S/mysite
➜  PYENV_DEBUG=yes pip --version
...
+ [pip:20] /Users/brian/.pyenv/versions/3.6.2/bin/pip --version
pip 9.0.1 from /Users/brian/.pyenv/versions/3.6.2/lib/python3.6/site-packages (python 3.6)
buzz:~/D/S/mysite
➜  pipenv shell -c
Spawning environment shell (/usr/local/bin/zsh).
source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
buzz:~/D/S/mysite
➜  source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
(mysite-xgb6m3Cg)buzz:~/D/S/mysite
➜  which pip
/Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/pip
```

**Comment by brosner** [comment]
Also,

```
buzz:~/D/S/mysite
➜  PYENV_DEBUG=yes pipenv --version
...
+ [pyenv-exec:47] exec -a pipenv /Users/brian/.pyenv/versions/3.6.2/bin/pipenv --version
pipenv, version 7.1.1
```

**Comment by brosner** [comment]
`VIRTUAL_ENV` is confirmed to *not* be set in the "global" case.

**Comment by brosner** [comment]
@techalchemy described exactly what I was seeing from my read of the code, but much better than how I described in my original comment.

**Comment by kennethreitz** [comment]
@techalchemy was running within a virtual environment, though.

**Comment by kennethreitz** [comment]
@brosner upgrade to v7.2.3 and see if you get a courtesy notice about running in a virtualenv when running `pipenv`.

**Comment by brosner** [comment]
Right, in the case of `pipenv shell` you are running in a virtual environment.

**Comment by brosner** [comment]
```
buzz:~/D/S/mysite
➜  pipenv --version
pipenv, version 7.2.3
buzz:~/D/S/mysite
➜  pipenv shell -c
Spawning environment shell (/usr/local/bin/zsh).
source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
buzz:~/D/S/mysite
➜  source /Users/brian/.local/share/virtualenvs/mysite-xgb6m3Cg/bin/activate
(mysite-xgb6m3Cg)buzz:~/D/S/mysite
➜  pipenv install -d mypy
Installing mypy…
Collecting mypy
  Using cached mypy-0.521-py3-none-any.whl
Collecting typed-ast<1.1.0,>=1.0.4 (from mypy)
  Using cached typed_ast-1.0.4-cp36-cp36m-macosx_10_11_x86_64.whl
Installing collected packages: typed-ast, mypy
Successfully installed mypy-0.521 typed-ast-1.0.4

Adding mypy to Pipfile's [dev-packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
```

**Comment by kennethreitz** [comment]
wait, are these modules being installed into the right virtualenv anyway? I suspect this is the case. Pip is also virtualenv-aware.

**Comment by brosner** [comment]
Yes, they are. This shell ended up with `PIPENV_IGNORE_VIRTUALENVS=yes` set so the behavior works as described by my original comment and @techalchemy findings.

**Comment by kennethreitz** [comment]
okay, so there's no bug here.

**Comment by kennethreitz** [comment]
I will investigate optimizing this further, but everything is working as expected at the moment.

**Comment by brosner** [comment]
I respectfully disagree. The behavior I am seeing is the **exact** opposite of what you describe in your comment:

> PIPENV_IGNORE_VIRTUALENVS IGNORES THE CURRENTLY ACTIVATED VIRTUALENV, which you have, which is why you have it using "system pip" normally — becuase you running in a virtual environment.
>
> this is a feature, not a bug.

With `PIPENV_IGNORE_VIRTUALENVS` set as I said I did just now, the behavior of pipenv is to INSTALL WITHIN THE VIRTUAL ENVIRONMENT AND **NOT** USE SYSTEM PIP.

From where I am standing this is clearly a bug and leads to completely unintentional behavior of pipenv. Let me also say that everything works as expected when I am running pipenv **outside** of `pipenv shell -c`. By default it does install within the project's virtual environment and using `PIPENV_USE_SYSTEM` or `--system` works and installs using the system pip.

The behavior I am looking to correct is the use of pipenv within the virtual environment through, what I would describe as, normal Python project worflow using pipenv.

**Comment by kennethreitz** [comment]
pipenv is using the wrong pip, but nothing bad is happening because of this, so there is no bug. 

We can look into fixing this, but it's a bit pedantic, as everything is working as expected.

**Comment by kennethreitz** [comment]
fixed. one liner :)

**Comment by kennethreitz** [comment]
Pipenv v7.2.4 released, which contains this fix! ✨🍰✨

**Comment by brosner** [comment]
Confirmed. Thank you @kennethreitz.

**Comment by kennethreitz** [comment]
Sorry for the lengthy confusion @brosner!

**Comment by frankier** [comment]
I'm a bit confused about this. This fix means that if I run

    $ pipenv shell

and then go to another directory somewhere and run e.g.

    $ pipenv install flask

It will create a new virtualenv rather than using the current one -- so it feels to me like we're back to a situation before https://github.com/kennethreitz/pipenv/issues/289

**Comment by techalchemy** [comment]
@frankier the behaviors in question only apply for virtual environments that are not created and managed by pipenv.  When you are in a pipenv subshell it will always create a new virtualenv when you are outside of the scope of the original project.  That's really the whole point of using pipenv, it's a dependency management tool and it enforces project-level insulation when you allow it to manage your packages for you.

**Comment by frankier** [comment]
Honestly, it still seems inconsistent. I don't think it really enforces project-level insulation at all since it will still run the activated virtualenv level Python when I type `python', but when I run pipenv install it will ignore that fact, not only if I'm in another project directory, but even if I'm just in a random directory nothing to do with any projects, up to the point of creating a new virtualenv. I guess maybe npm seems more consistent -- so perhaps the lesson is to just always use pipenv run ... instead of pipenv shell?

**Comment by techalchemy** [comment]
@frankier pipenv is not meant to be run from inside it’s own managed virtualenv. That’s the whole point. You are not supposed to activate it in order to install things. Pipenv is a cli tool, it works outside of the thing it manages. 

Once you drop into a subshell you shouldn’t use pipenv because you shouldn’t be installing anything. Subshells are a convenience function that you really shouldn’t be using. That’s the whole point of the existence of `pipenv run`. This way when you are in the project directory structure things will run and install in that context, and when you drop out of the project they won’t.
