### ISSUE TITLE
Bug: uninstall dev is not removing package from Pipfile

### ISSUE THREAD

**Issue by Woile** [kennethreitz/pipenv#575]
Doing `pipenv uninstall -d nose` does not remove the package from `Pipfile`.

The cause is because [in here](https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L1475) happens this `pipfile_remove = False`.
Is there a reason? Removing that line fixes the issue.
I would expect the package to be removed from the Pipfile, whether its a dev or non dev package.
I can submit a PR if required.

**Comment by kennethreitz** [comment]
pr requested!

**Comment by kennethreitz** [comment]
this is a bug.

**Comment by Woile** [comment]
Ok, I'll write the test and will submit PR

**Comment by kennethreitz** [comment]
will be waiting :)
