### ISSUE TITLE
Proposal: versions convention

### ISSUE THREAD

**Issue by Woile** [kennethreitz/pipenv#578]
Hi, I would like to know what do u think about updating the version convention like this:

| Old        | New           | Why  |
| ------------- |:-------------:| :-----|
| `==3.2`      |  `3.2` |  is  `==` necessary? Why? |
| `'*'`      | `latest`      |   Would this be feasible? or does `'*'` means something different? Could we use a literal instead, more expressive? |

Examples:

**Old**
```
django = '==3.2'
mock = "*"
```
**New**
```
django = 3.2
mock = latest
```
This is parsed like this by contoml:
```
{source = {'django': 3.2, 'mock': 'latest'}}
```

Keeping `>=` and any other it's okay, maybe something similar [to npm](https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers) would be cool to introduce.

Thanks!!

**Comment by kennethreitz** [comment]
this is a pipfile problem, not a pipenv problem. 

https://github.com/pypa/pipfile

**Comment by kennethreitz** [comment]
and to be clear, there are peps around version specifiers, and that's what we're specifying — version specifiers.

**Comment by Woile** [comment]
Ok. Creating in pipfile

**Comment by kennethreitz** [comment]
I wouldn't, it will be closed.

**Comment by Woile** [comment]
Do you have at hand the pep version specifier? 
The current ones are quite ugly. I don't understand why `==` is necessary over just writing the version, that'd be enough.

**Comment by kennethreitz** [comment]
changing what we already have would break backwards compatibility too. it's not going to change.

**Comment by kennethreitz** [comment]
you should have been around when we were designing pipfile. too late now.
