### ISSUE TITLE
Not possible to install specific(major.minor.micro) python version with pyenv while creating new project

### ISSUE THREAD

**Issue by pgrzesik** [kennethreitz/pipenv#579]
I'm trying out the feature with installing python versions with pyenv (awesome work!) and I stumbled accross this one:
```
➜  pipenv --python 3.4
➜  Warning: Python 3.4 was not found on your system…
➜  Would you like us to install latest CPython 3.4 with pyenv? [Y/n]:
```
Which is expected behavior, however if I want to specify micro version e.g. 1, it doesn't offer option to install with pyenv witch results in:
```
➜  pipenv --python 3.4.1
➜  Warning: Python 3.4.1 was not found on your system…
➜  You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```

Is that the correct behavior ?

**Comment by pgrzesik** [comment]
Update:
I checked out how it's working and I understand that it's due to how versions are mapped in `pipenv/cli.py`.
Do you think it would be possible to make it work with major.minor.micro python versions? 
Thanks for your awesome work!

**Comment by kennethreitz** [comment]
Not at this time. You should always be using latest if any minor release, always.

**Comment by kennethreitz** [comment]
support for `python_full_version` has now been added, as well as specifying minor releases.

**Comment by kennethreitz** [comment]
however, it's difficult to find them on your path, so they may not be available.

**Comment by AlJohri** [comment]
related https://github.com/kennethreitz/pipenv/issues/588

**Comment by kennethreitz** [comment]
no longer difficult to find them on your path! we did magic :)
