### ISSUE TITLE
Pipfile should specify Python version

### ISSUE THREAD

**Issue by thirtyseven** [kennethreitz/pipenv#58]
To reduce friction and the possibility of error when running `pipenv install` on a project that already has a Pipfile, the Pipfile should specify the Python version. This is already a feature in bundler, where you can specify the Ruby version with the `ruby` keyword.

**Comment by kennethreitz** [comment]
you can require a version with pipfile

```
[requires]
python_version = "2.7"
```

Currently, you can check these PEP 508 specifiers with `$ pipenv check`.

**Comment by thirtyseven** [comment]
Awesome, thanks!
