### ISSUE TITLE
Error message about virtualenvwrapper

### ISSUE THREAD

**Issue by rfleschenberg** [kennethreitz/pipenv#583]
# System information

```
rene@rene-desktop ~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

```
rene@rene-desktop ~ % echo $SHELL
/bin/zsh
```

```
rene@rene-desktop ~ % which python3
/usr/bin/python3
```

# The problem
```
rene@rene-desktop ~ % mkdir /tmp/test && cd /tmp/test
rene@rene-desktop test % pipenv --python /usr/bin/python3 
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/rene/.virtualenvs/test-hxkKlP5o/bin/python3
Also creating executable in /home/rene/.virtualenvs/test-hxkKlP5o/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/rene/.virtualenvs/test-hxkKlP5o
Creating a Pipfile for this project…
rene@rene-desktop test % cat Pipfile 
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
[requires]
python_version = "3.5"
rene@rene-desktop test % pipenv shell 
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
/home/rene/.virtualenvs/test-hxkKlP5o/bin/python: Error while finding spec for 'virtualenvwrapper.hook_loader' (ImportError: No module named 'virtualenvwrapper')
virtualenvwrapper.sh: There was a problem running the initialization hooks. 

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/home/rene/.virtualenvs/test-hxkKlP5o/bin/python and that PATH is
set properly.

 * keychain 2.8.1 ~ http://www.funtoo.org
 * Found existing ssh-agent: 18571
 * Known ssh key: /home/rene/.ssh/id_rsa
```

I am not sure if I correctly understand this situation. Is this error message expected, or is there some issue specific to my system that causes this? The fix seems to be to install the `virtualenvwrapper` package into the created virtualenv:

```
rene@rene-desktop test % which pip   
/home/rene/.virtualenvs/test-hxkKlP5o/bin/pip
rene@rene-desktop test % pip install virtualenvwrapper
Collecting virtualenvwrapper
  Using cached virtualenvwrapper-4.8.2-py2.py3-none-any.whl
Collecting virtualenv-clone (from virtualenvwrapper)
Collecting stevedore (from virtualenvwrapper)
  Using cached stevedore-1.26.0-py2.py3-none-any.whl
Collecting virtualenv (from virtualenvwrapper)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore->virtualenvwrapper)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting six>=1.9.0 (from stevedore->virtualenvwrapper)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: virtualenv-clone, pbr, six, stevedore, virtualenv, virtualenvwrapper
Successfully installed pbr-3.1.1 six-1.10.0 stevedore-1.26.0 virtualenv-15.1.0 virtualenv-clone-0.2.6 virtualenvwrapper-4.8.2
rene@rene-desktop test % exit
rene@rene-desktop test % pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

 * keychain 2.8.1 ~ http://www.funtoo.org
 * Found existing ssh-agent: 18571
 * Known ssh key: /home/rene/.ssh/id_rsa
```

If it is required to install virtualenvwrapper into the created virtualenv, maybe pipenv should do that by default? Or am I just misunderstanding something here?

**Comment by rfleschenberg** [comment]
After reading https://github.com/kennethreitz/pipenv/issues/269#issuecomment-286242268, I noticed that `pipenv shell -c` works for me. I am curious which misconfiguration my shell is suffering from -- can anyone shine some light on this?

**Comment by rfleschenberg** [comment]
In case it is of interest, https://github.com/rfleschenberg/dotfiles has my dotfiles, `zshrc` is at https://github.com/rfleschenberg/dotfiles/blob/master/zshrc, current version is at https://github.com/rfleschenberg/dotfiles/blob/354eaf20f60181e7ccfbd34561e35ac584b5f045/zshrc

**Comment by uranusjr** [comment]
Those `virtualenvwrapper.sh` inits are likely the culprit. The subshell launched by `pipenv shell` will read those files in, and, failing to find the virtualenvwrapper module inside the virtualenv, fails to execute `virtualenvwrapper.sh`. The easiest way to work around this is to put a login shell check around the code, and you probably should regardless of Pipenv anyway.

**Comment by rfleschenberg** [comment]
@uranusjr That works, thanks! Now I just need to fix the problem that my shell prompt is not showing the virtualenv name, but I guess that's a separate issue.

**Comment by uranusjr** [comment]
Yeah I think you need to do that yourself in the subshell. My solution:

```bash
if [[ -n "$VIRTUAL_ENV" ]]; then
    PS1="($(basename "$VIRTUAL_ENV")) $PS1"
fi
```

**Comment by kennethreitz** [comment]
Good job, everyone :)

**Comment by kennethreitz** [comment]
Also, this was just a warning, not an error.

**Comment by rfleschenberg** [comment]
@uranusjr Thanks again, works nicely.

**Comment by kennethreitz** [comment]
In general, things should only be executed during a login session, not during every spawn of every subshell. That's the tricky part of pew/pipenv — getting your shell setup "properly", and why `shell -c` exists, to avoid the hassle.

**Comment by anujgpatil** [comment]
If you are here from pyImage Search Website for OpenCV installation on Rasp Pi ,this is what you need:
https://stackoverflow.com/a/19550535/8164527
