### ISSUE TITLE
How to configure the environment correctly to run with pyenv and create the python versions.

### ISSUE THREAD

**Issue by AndersonFirmino** [kennethreitz/pipenv#585]
I've been following the project. And I saw that he now supports pyenv.
I did not understand how to make them work together. I use pyenv a long time.

I tested the lines added in the lasts commit.

```
$ py -c "import os; print (bool (os.environ.get ('PYENV_SHELL')) or bool (os.environ.get ('PYENV_ROOT')))"

True # Exit the shell
```

What should I do to make it work?

Thanks in advance for the help :grimacing:

**Comment by kennethreitz** [comment]
Try this (where `3.5` is a python you don't have installed):

    $ mkdir newproject
    $ cd newproject

    $ pipenv install requests --python 3.5

**Comment by kennethreitz** [comment]
I've documented this here: http://docs.pipenv.org/en/latest/advanced.html#automatic-python-installation

**Comment by AndersonFirmino** [comment]
I get this log 
```
$ pipenv install requests --python 3.0.1
Warning: Python 3.0 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```
:disappointed: 

Do I need to configure some environment variable for pipenv?

**Comment by kennethreitz** [comment]
Do you have pyenv installed and activated? if so, you should have either `PYENV_ROOT` or `PYENV_SHELL` set

**Comment by kennethreitz** [comment]
Also, it's ``$ pipenv install requests --python 3.0``. We don't support specifying patch releases.

**Comment by kennethreitz** [comment]
Also, we don't support 3.0.

**Comment by kennethreitz** [comment]
No one devs for 3.0. Try 3.3.

**Comment by kennethreitz** [comment]
The list is here: 
https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L364

**Comment by AndersonFirmino** [comment]
This is my setup.
```
$ pyenv --version 
pyenv 1.1.3

$ echo $PYENV_ROOT 
/home/coderpy/.pyenv

$ echo $PYENV_SHELL
zsh
```

I'm doing tests to adopt pipenv for all projects.

**Comment by AndersonFirmino** [comment]
It worked now, thank you Kenneth :sparkles: :cake: :sparkles:
