### ISSUE TITLE
`pipenv install` from inside `pipenv shell` installs globally

### ISSUE THREAD

**Issue by Alok** [kennethreitz/pipenv#596]
I run these commands and get some unexpected behavior:

```
pipenv shell
pipenv install leather
(open new tab in iterm outside of virtualenv subshell)
python3
import leather # don't get ModuleNotFoundError
```

`pipenv uninstall` from inside the  subshell wipes it from the global packages.

Since `pipenv --venv` inside the subshell (in the project directory) works, I'd expect pipenv install/uninstall to work or give some sort of error.

Also, running `pipenv uninstall` in a directory where there isn't a python project will install pipenv and then attempt to wipe the package (unsuccessfully, because it's not there).

**Comment by kennethreitz** [comment]
i assume you have pipenv running in a virtualenv

**Comment by kennethreitz** [comment]
make sure you're using latest

**Comment by kennethreitz** [comment]
e.g. we fixed this yesterday
