### ISSUE TITLE
How do I share code?

### ISSUE THREAD

**Issue by savovs** [kennethreitz/pipenv#597]
Hi guys, I'm trying to get this readme to make sense, but when I follow the instructions I can't seem to get my stuff running. I'm trying to make the instructions as easy as npm. https://github.com/savovs/flask-graphene-hello

I get two errors when I follow the readme in the above repo:
1. `Could not find a version that matches graphene>=2.0.dev`
2. `zsh: command not found: flask`

It works when I manually install dependencies like this:
`$ pipenv install flask flask-graphql graphene = ">=2.0.dev"`

Any ideas about what I'm doing wrong?

**Comment by uranusjr** [comment]
The installation part might be a bug. The command not found part is easy to resolve: use

```bash
FLASK_APP=./server/index.py pipenv run flask run
```

instead.
