### ISSUE TITLE
"pip install pipenv" failure

### ISSUE THREAD

**Issue by aitoehigie** [kennethreitz/pipenv#6]
I run linux Mint and running "pip install pipenv" fails with this error

"""
File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 11, in <module>
    import _pipfile as pipfile
ImportError: No module named _pipfile

"""

I had to manually copy the _pipfile directory to my dist-packages/pipenv/ for it to work

Has anyone else experienced this too?

**Comment by jpadilla** [comment]
Can confirm, no `_pipfile` in release.

```
$ tree pipenv-0.1.3
pipenv-0.1.3
├── PKG-INFO
├── README.rst
├── pipenv
│   ├── __init__.py
│   ├── core.py
│   └── delegator.py
├── pipenv.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── requires.txt
│   └── top_level.txt
├── setup.cfg
└── setup.py

2 directories, 13 files
```

**Comment by kennethreitz** [comment]
this should now be fixed!

**Comment by aitoehigie** [comment]
yes
