### ISSUE TITLE
Enable local package installation with -e flag

### ISSUE THREAD

**Issue by csurfer** [kennethreitz/pipenv#601]
Looks like pipenv doesn't honor `-e` flag that can be used to install local repositories under development. When used in the following way

```bash
pipenv install -e <local_repo>
```

It tries to install "-e <local_repo>". So either that flag isn't supported or something is going wrong with respect to installation.

**Comment by kennethreitz** [comment]
Can you show me the exact command you're running?

**Comment by kennethreitz** [comment]
and the output.

**Comment by AlJohri** [comment]
@kennethreitz this may be related to #540 

```
pipenv install -e ../../lib/python
```

does not work for me as of 7.3.2. stacktrace shown in original issue

**Comment by kennethreitz** [comment]
I want to see @csurfer's command and output, thank you.

**Comment by csurfer** [comment]
@kennethreitz : My bad. I was trying to use the packages within IPython shell and IPython was installed in a generic way using `pip install` and not `pipenv install` which might have resulted in some conflicts. Installing IPython too using `pipenv` and then trying the same resolved the issue.
