### ISSUE TITLE
Virtualenv --always-copy option

### ISSUE THREAD

**Issue by cactail** [kennethreitz/pipenv#603]
Hi. Does exist a way to initialize a virtualenv with the --always-copy option?

It is highly recommended to use this option in rolling release linux distributions

**Comment by kennethreitz** [comment]
Not currently.

**Comment by kennethreitz** [comment]
this has not been a heavily requested feature, so we likely won't impliment it unless it comes up again

**Comment by OmeGak** [comment]
I was trying to find a way to get this working with `pipenv` and find out it is rather easy to do via `pew`: 

```console
$ pew new test --always-copy
``` 

If not officially supported by `pipenv`, perhaps there could be some way to pass options to `pew new` like it's already the case with `pip install` and `PIP_INSTALL_OPTION`. Would adding `PEW_NEW_OPTION` be a bad idea?

**Comment by techalchemy** [comment]
Pipenv doesn't always use pew to create virtualenvs, so features in pew do not directly translate to features in pipenv.

**Comment by OmeGak** [comment]
Also, I just realized there's nothing `pipenv` is doing with `PIP_INSTALL_OPTION`. It's simply used by `pip` directly. Never mind then.
