### ISSUE TITLE
create or use a local project virtualenv

### ISSUE THREAD

**Issue by keshavkaul** [kennethreitz/pipenv#606]
Is it possible to create or use an already created local project virtualenv ?

**Comment by marctc** [comment]
Sure. In fact it appears a message telling you: "Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating it's own for any project."

**Comment by keshavkaul** [comment]
@marctc @kennethreitz I'm sorry for not being explicit in stating this, but I would like the virtual environment folder to be created relative to the project root. In the current pipenv version it automatically creates a virtualenv in `~/.local/share/virtualenvs` path.

Just like node_modules being present in project root in NodeJS world, I would want virtualenv to be present under the project root

**Comment by nateprewitt** [comment]
@keshavkaul what you're asking for is available by setting the PIPENV_VENV_IN_PROJECT variable in your environment. This will creat a .venv directory under the project root instead of using pew.

**Comment by keshavkaul** [comment]
@nateprewitt Thanks, I'll check it out. Maybe we could make this feature visible to users as command argument?

**Comment by nateprewitt** [comment]
@keshavkaul, it's documented at http://pipenv.org under the [Configuration with Environment Variables](http://docs.pipenv.org/en/latest/advanced.html#configuration-with-environment-variables) section and mentioned in dozens of issues throughout the tracker.

I don't believe we have any plans to move this feature to an option right now. We've historically been trying to keep the number of arguments to a minimum.

**Comment by keshavkaul** [comment]
@nateprewitt That's cool! I understand why you want to keep the arguments to a minimum. 
I reckon, If this issue is mentioned a dozen times throughout the tracker, It would make sense to move it to FAQs in the README file instead of having it present at bottom of the advance section of using pipenv [Advanced Usage of Pipenv](http://docs.pipenv.org/en/latest/advanced.html#advanced-usage-of-pipenv)

**My thoughts on the feature:**
I look for this feature in any language I start my project in and the main reason I want this to be supported easily is that I don't want to pollute my userspace with my project related files and directories.

**Other Language Examples** 
For Ruby:- We have [rbenv](https://github.com/rbenv/rbenv) (ruby version manager) and [rbenv-gemsets](https://github.com/jf/rbenv-gemset) (project level gemset management)
For Node:- npm (default project level package management)
