### ISSUE TITLE
move to pypa?

### ISSUE THREAD

**Issue by marctc** [kennethreitz/pipenv#607]
Have you considerated to move this repo to pypa organization?

**Comment by kennethreitz** [comment]
no

**Comment by marctc** [comment]
Why not? It could set pipenv as a de facto way to install python packages.

**Comment by kennethreitz** [comment]
doesn't mean it needs to be moved over :) I want total control over this package :)

**Comment by kennethreitz** [comment]
and the pypa already recommends it as the official way to install packages (soon), so that's already happening :)

**Comment by kennethreitz** [comment]
so the location of the repo isn't important :)

**Comment by marctc** [comment]
Thanks for the answers @kennethreitz ;)

**Comment by kennethreitz** [comment]
I'll think about it

**Comment by marctc** [comment]
:ok_hand:

**Comment by marctc** [comment]
What was your motivation to move requests to his own organization?

**Comment by kennethreitz** [comment]
will talk to @dstufft about this

**Comment by kennethreitz** [comment]
Requests was moved to make the project seem more "official", and reduce the bus factor of the project.
