### ISSUE TITLE
Uninstalling pipenv on macOS / brew 

### ISSUE THREAD

**Issue by h0h0h0** [kennethreitz/pipenv#608]
Hi there,

macOSX / brew / fresh install here.  I realized I wanted to use fish and not bash so I'm trying to back track and reinstall everything under fish.  However, pipenv is still in /usr/local/bin after uninstalling python.  What step am I missing?

I did 

```
$ brew install python2
$ pip2 install pipenv
$ brew uninstall python
```

so then `which pipenv` returns `/usr/local/bin/pipenv`.

**Comment by kennethreitz** [comment]
you didn't `pip unintall pipenv` :)

`$ rm -fr /usr/local/bin/pipenv` should do the trick.

**Comment by rafsanbhuiyan12** [comment]
1. Frist uninstall pipenv:  'pip uninstall pipenv` OR 'brew uninstall pipenv' OR 'sudo uninstall pipenv'
2. Second install pipenv==2022.5.2:     `sudo pip install pipenv==2022.5.2`

pipenv: 2022.5.2 works great!! ⚡️🚀🤘😃
