### ISSUE TITLE
absorb pipsi

### ISSUE THREAD

**Issue by sean-abbott** [kennethreitz/pipenv#609]
Is it possible to adsorb pipsi so that you could have a switch (--add-to-path) that would allow you to drop the `pipenv run`?

`pipenv run` works great, and I'll probably just make aliases, but if there was a way to expand and adsorb pipsi that would be even MORE awesome.

Thanks for this great work!

**Comment by kennethreitz** [comment]
explain in more detail what you mean.

**Comment by kennethreitz** [comment]
like, show me example usage.

**Comment by kennethreitz** [comment]
it's important to note that pipsi only works with one binary per virtualenv. 

I think it would be more appropriate to do this functionality ourselves, if at all, instead of relying on pipsi. Not convinced it's a good idea though.

**Comment by kennethreitz** [comment]
i think just doing the magic yourself is probably best.

**Comment by kennethreitz** [comment]
though i am looking for new features to add — i'm not sure this is one of them. I'll think about it though.

**Comment by sean-abbott** [comment]
pipsi will work with all the scripts installed by setup.py. For instance, if you install ansible via pipsi you get about 6 executables in your .local/bin.  But yes, you can't install different binaries/scripts and have them work from the same environment without sourcing that environment and adding the libraries and links manually.  Same goes for adding extra libraries.

Again, using ansible as a reference, when I pipsi install ansible, I have to source `~/.local/venvs/ansible/bin/activate`, `pip install boto boto3 PyChef`, and then with recent versions something has gone wrong and it doesn't work cleanly anymore. (it used to).

So it'd be super great to be able be able to do...

`pipenv install --link-binaries-to-path ansible`, and have it do the same thing pipsi does (i.e., drop links in `~/.local/bin` so you can add that to your path), but ALSO use the entirety of the relevant environment.

I've even been in situations where I need different versions of ansible anyway, so the redundancy of the command line tool is, to my mind, not a problem. (neither feature nor bug)

Thinking about it more, though, I guess that there's some "where are you running this from" mangling and checking that might get awkward and hard to maintain.  I mean, maybe if you tried to run it from outside a pipenv directory, it could just complain "not in a pipenv".

**Comment by uranusjr** [comment]
> it's important to note that pipsi only works with one binary per virtualenv

This is not true, installing IPython with Pipsi gets me 4 links (iptest, iptest3, ipython, and ipython3). Many other packages provide multiple executables and they work fine as well, I didn’t look into how they do it, but this most certainly can be done.

**Comment by kennethreitz** [comment]
I stand corrected — it only installs links for the main package, not subdependencies.

**Comment by kennethreitz** [comment]
I like the idea of a `$ pipenv install --link ansible`, but i feel like it's a bit out of scope.

**Comment by kennethreitz** [comment]
you could easily just make that symlink yourself with `$ ln -s ~/.local/bin/ansible $(pipenv --venv)/bin/ansible)

**Comment by kennethreitz** [comment]
i think this would confuse people, and sort of conflates the idea of these venvs being disposable, as opposed to long-lived. Closing.
