### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by Foxboron** [kennethreitz/pipenv#610]
It would be great if release tarballs could be signed

**Comment by kennethreitz** [comment]
we never did this for requests, so we won't be doing it here. once requests starts doing it, i'll hop on board.

**Comment by Foxboron** [comment]
I don't get the argument. Why should the release process of requests decide the release process of this project?

**Comment by kennethreitz** [comment]
i don't want to be bothered with it, and if it's not important enough for my most important project, than it's not important enough for this one.

**Comment by kennethreitz** [comment]
we'll get there, one day. too early.

**Comment by Foxboron** [comment]
Since this project has moved under pypa, can signed releases be reconsidered?
