### ISSUE TITLE
JSON output for graph command

### ISSUE THREAD

**Issue by sschuberth** [kennethreitz/pipenv#612]
Could we get a `--json` option to `pipenv graph` to get the dependency tree in a machine readable format? So far I'm using the separate https://github.com/naiquevin/pipdeptree for that.

**Comment by kennethreitz** [comment]
let's see...

**Comment by kennethreitz** [comment]
sure!

**Comment by kennethreitz** [comment]
done :)

**Comment by kennethreitz** [comment]
v7.4.1 released, which includes this!

**Comment by sschuberth** [comment]
Your speed is nothing short of awesome! However, I just noticed that the regular and JSON outputs do not match, JSON output has more dependencies, and it includes even `setuptools`, `pip`, etc. I would have expected the outputs to match.

**Comment by kennethreitz** [comment]
yes, we remove those from the pretty output for niceties.

**Comment by sschuberth** [comment]
Could the JSON output please get the same niceties? Otherwise it would be awkward if the contents do not match while only the output format changed.

**Comment by kennethreitz** [comment]
unfortunately, this is less than trivial. i'll see what i can do though.
