### ISSUE TITLE
FileNotFoundError during install

### ISSUE THREAD

**Issue by eliot1785** [kennethreitz/pipenv#615]
C:\Users\sdewey\Documents\project> pip install pipenv
Collecting pipenv
Collecting pip-tools>=1.9.0 (from pipenv)
  Using cached pip_tools-1.9.0-py2.py3-none-any.whl
Requirement already satisfied: virtualenv in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from p
ipenv)
Collecting setuptools>=36.3.0 (from pipenv)
  Using cached setuptools-36.5.0-py2.py3-none-any.whl
Requirement already satisfied: requests>2.0.0 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (fr
om pipenv)
Collecting pew>=0.1.26 (from pipenv)
  Using cached pew-0.1.26-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from p
ipenv)
Collecting first (from pip-tools>=1.9.0->pipenv)
  Using cached first-2.0.1-py2.py3-none-any.whl
Requirement already satisfied: six in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from pip-tool
s>=1.9.0->pipenv)
Requirement already satisfied: click>=6 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from pip
-tools>=1.9.0->pipenv)
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv)
Collecting pythonz-bd>=1.10.2 (from pew>=0.1.26->pipenv)
  Using cached pythonz_bd-1.11.4-py3-none-any.whl
Collecting resumable-urlretrieve; python_version == "3.6" (from pythonz-bd>=1.10.2->pew>=0.1.26->pipenv)
  Using cached resumable_urlretrieve-0.1.5-py2.py3-none-any.whl
Installing collected packages: first, pip-tools, setuptools, virtualenv-clone, resumable-urlretrieve, pythonz-bd, pew, p
ipenv
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
Successfully installed first-2.0.1 pew-0.1.26 pip-tools-1.9.0 pipenv-7.4.2 pythonz-bd-1.11.4 resumable-urlretrieve-0.1.5
 setuptools-36.5.0 virtualenv-clone-0.2.6
Traceback (most recent call last):
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\Scripts\pip-script.py", line 5, in <module>
    sys.exit(pip.main())
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\__init__.py", line 249, in main
    return command.main(cmd_args)
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\outdated.py", line 102, in pip_ver
sion_check
    installed_version = get_installed_version("pip")
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 838, in get_ins
talled_version
    working_set = pkg_resources.WorkingSet()
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 644, in __init__
    self.add_entry(entry)
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Users\sdewey\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line
 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\sdewey\\AppData\\Local\\Continuum
\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg'

C:\Users\sdewey\Documents\project> pip install pipenv
Requirement already satisfied: pipenv in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages
Requirement already satisfied: pip>=9.0.1 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from p
ipenv)
Requirement already satisfied: requests>2.0.0 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (fr
om pipenv)
Requirement already satisfied: pew>=0.1.26 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from
pipenv)
Requirement already satisfied: pip-tools>=1.9.0 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (
from pipenv)
Requirement already satisfied: setuptools>=36.3.0 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages
 (from pipenv)
Requirement already satisfied: virtualenv in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from p
ipenv)
Requirement already satisfied: pythonz-bd>=1.10.2 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages
 (from pew>=0.1.26->pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-pac
kages (from pew>=0.1.26->pipenv)
Requirement already satisfied: six in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from pip-tool
s>=1.9.0->pipenv)
Requirement already satisfied: click>=6 in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from pip
-tools>=1.9.0->pipenv)
Requirement already satisfied: first in c:\users\sdewey\appdata\local\continuum\anaconda3\lib\site-packages (from pip-to
ols>=1.9.0->pipenv)
Requirement already satisfied: resumable-urlretrieve; python_version == "3.6" in c:\users\sdewey\appdata\local\continuum
\anaconda3\lib\site-packages (from pythonz-bd>=1.10.2->pew>=0.1.26->pipenv)

**Comment by kennethreitz** [comment]
this is a problem with your python installation, not with pipenv. try again.

**Comment by eliot1785** [comment]
I apologize for the bad formatting in the previous post, I was trying to fix it when I saw your latest comment- maybe I should have taken the time first.

Are you sure about this being a Python issue? I can reinstall my whole system, but I've been operating pretty smoothly until I started messing with pipenv today. This isn't the first installation attempt I had - the first, whose logs I wish I saved, ended with a different error message (in red) about a folder not being empty that it expected to be empty. Not sure if that rings a bell.

**Comment by eliot1785** [comment]
Then I ran 
pip uninstall pipenv
followed by the pip install pipenv resulting in this different error message.

**Comment by kennethreitz** [comment]
try `pip install setuptools --upgrade`

**Comment by kennethreitz** [comment]
i recommend the fancy installation method for a reason

http://docs.pipenv.org/en/latest/advanced.html#fancy-installation-of-pipenv

**Comment by techalchemy** [comment]
I can't read your error logs at all but if you follow up on this with more detail it's possible I can help you.  I have no idea if pipenv works for people who use anaconda to manage their python installations and i also have no idea what anaconda even does.

**Comment by kennethreitz** [comment]
pipenv is designed to work with cpython, outside of that you're exploring new territory.
