### ISSUE TITLE
More install targets?

### ISSUE THREAD

**Issue by uranusjr** [kennethreitz/pipenv#620]
Many projects have multiple `requirements.txt` to handle different needs in (take website for example) local dev, CI staging, production, etc. With Pipfile there are only default and dev.

**Comment by AlJohri** [comment]
this is akin to the idea of "groups" in bundler: http://bundler.io/v1.12/groups.html

**Comment by kennethreitz** [comment]
no

**Comment by uranusjr** [comment]
Any suggestion on the workflow then? Fallback to requirements files and `pipenv run pip install -r requirements/deploy.txt`?

**Comment by kennethreitz** [comment]
sure

**Comment by kennethreitz** [comment]
develop / production have been enough for the composer community, and i have faith that they are enough for us too.
