### ISSUE TITLE
[feature request] `--pipfile` cli argument corresponding to `PIPENV_PIPFILE`

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#621]
would love to see some more parity between cli arguments and env vars in general. I can submit a PR if this is something you're interested in.

this is akin to `bundler --gemfile=xyz`

**Comment by kennethreitz** [comment]
already added `PIPENV_PIPFILE=/path/to-Pipfile pipenv --where`

**Comment by AlJohri** [comment]
I was referring to a cli arg to set `PIPENV_PIPFILE`. like `pipenv install --pipfile=../Pipfile`

**Comment by kennethreitz** [comment]
yes, you can use an enviroment variable to accomplish the same thing.
