### ISSUE TITLE
Support --(extra-)index-url when importing from requirements.txt

### ISSUE THREAD

**Issue by sschuberth** [kennethreitz/pipenv#625]
While there a multiple related closed issues, I'm unclear about what the last stance on supporting `--(extra-)index-url` when [importing from requirements.txt](http://docs.pipenv.org/en/latest/advanced.html#importing-from-requirements-txt) is. IMO, it's am important migration scenario to support these to help adoption of `pipenv`. Also, it should be pretty much straight forward to add. If `-i` or `--index-url` is present in `requirements.txt`, the default `[[source]]` URL of `https://pypi.python.org/simple` in `Pipfile` should be *replaced* with whatever is given as the index URL. If one or more `--extra-index-url` are present, there should be *additional* `[[source]]` URLs pointing at the given locations.

**Comment by nateprewitt** [comment]
Hey @sschuberth, could we please get an example requirements.txt with `-i` in use? I've used it in the command line but am unfamiliar with the syntax used in a file.

**Comment by sschuberth** [comment]
The syntax is as simple as:

    -i http://my.private.server.com/ptpi/devpi/dev/+simple/

    jinja2
    nose-xunitmp

**Comment by nateprewitt** [comment]
Great, thanks @sschuberth! I think this is something we could definitely parse for, but I'm going to tag @kennethreitz in to get his thoughts.

**Comment by kennethreitz** [comment]
We're not going to be able to support hashes against those.

**Comment by sschuberth** [comment]
What do you mean by "hashes" in this context?

**Comment by kennethreitz** [comment]
implemented!

**Comment by sschuberth** [comment]
... not really. Only `-i` seems to be implemented, not its alias `--index-url`, nor is support for the `--extra-index-url` option.

**Comment by kennethreitz** [comment]
you only asked for `-i` :)

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/issues/634

**Comment by iamkhush** [comment]
It would be nice to have `--extra-index-url` or `--index-url` parsed and added to the source automatically.
