### ISSUE TITLE
Manage user environment

### ISSUE THREAD

**Issue by mweinelt** [kennethreitz/pipenv#633]
It would be amazing if pipenv could be used to manage the users local environment, that is often used to have python software readily available.

Basically, if I need for example `borgbackup` I install it using
```
pip3 install --user borgbackup
```
This in turn drops the necessary packages into `~/.local/lib/python3.6/` and executables into `~/.local/bin`, so I have `borg` in my `$PATH`.

If I could now manage this environment with pipenv, that'd be swell.

**Comment by kennethreitz** [comment]
Why not just use a pipenv project?

**Comment by kennethreitz** [comment]
i think what you want is pipsi https://github.com/mitsuhiko/pipsi

**Comment by ofek** [comment]
@mweinelt You may be interested in https://github.com/ofek/hatch where you can choose between a project or environment based work flow.

Your example command would be exactly equal to `hatch install borgbackup` when not in a virtual env.
