### ISSUE TITLE
Documentation clarification on pipfile and pinned versions

### ISSUE THREAD

**Issue by truthdoug** [kennethreitz/pipenv#635]
In the doc section on [importing from requirements.txt](http://docs.pipenv.org/en/latest/advanced.html#importing-from-requirements-txt), it says:

> Note, that when importing a requirements file, they often have version numbers pinned, **_which you likely won’t want in your Pipfile_**, so you’ll have to manually update your Pipfile afterwards to reflect this.

I'd like more explanation about why one wouldn't want pinned version numbers in a Pipfile. Is there a suggested workflow for teams with respect to committing Pipfile.lock (or not)?

**Comment by kennethreitz** [comment]
the whole point of a lockfile is to commit it.

**Comment by kennethreitz** [comment]
You'll want pinned versions sometimes in your Pipfile, but certainly not for all dependencies.

**Comment by rgant** [comment]
I found this looking for exactly this answer. Would be nice if the documentation included this explanation. Coming from `pip` I forgot that there is now a lockfile to track specific versions.

**Comment by asweigart** [comment]
I found this thread googling this same question. I believe the answer is explained here: https://www.kennethreitz.org/essays/a-better-pip-workflow

Essentially, pinned versions are a best practice and let you have reproducible builds. Meanwhile, having ranges of acceptable versions (or any version at all) is easier for humans to specify and reason about. (Someone please correct me if I have this wrong.)
