### ISSUE TITLE
dotenv override?

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#638]
Is there any reason override is set to True here? `dotenv.load_dotenv(denv, override=True)`

I prefer using [`envdir`](https://github.com/jezdez/envdir) since it lets me explicitly define the environment variables for local development vs production. I end up creating a `.env` file anyway for compatibility with other software like `pipenv`, `docker-compose`, `pycharm`, etc.

When I want to run my app locally using production environment variables, I'm running into an issue because of the `override=True`.

The command `envdir envs/prod pipenv run python src/manage.py runserver` will end up using the `.env` variables instead of those provided through envdir.

Can you either set `override` to False or allow disabling `.env` files?

**Comment by kennethreitz** [comment]
just use pipenv's .env management instead.

**Comment by AlJohri** [comment]
@kennethreitz Okay. How do I switch between local and production environment variables?

**Comment by kennethreitz** [comment]
we can provide an environment variable to disable this, but i don't want to.

**Comment by kennethreitz** [comment]
use a make script?

**Comment by AlJohri** [comment]
I'll give it a shot. It feels weird to create an env file just to run my app in a different way. I really like what pipenv and pew do with subshells and I think envdir just takes that a step forward.

I do think this the configuration should exist though if pipenv wants to be / is the "official" language package manager which tend to be less opinionated and more unix-y (less features, more configurable and composable with other tools).

**Comment by kennethreitz** [comment]
I agree that a way to disable it would be nice (albeit likely undocumented)

**Comment by kennethreitz** [comment]
added a patch
