### ISSUE TITLE
Query: Pipfile format

### ISSUE THREAD

**Issue by rajaravivarma-r** [kennethreitz/pipenv#64]
Sorry if this is lame. As a regular user of Bundler in Ruby ecosystem, and package.json from npm, why not use
* Python, which will give more freedom to express logic and other constructs
* JSON, as it is human readable and parsers are available already
* YAML, not as readable as JSON, but saves us from learning one more markup language.

Thanks

**Comment by lepisma** [comment]
Its more of an issue for pipfile [repository](https://github.com/pypa/pipfile). Though I believe the decision might be similar to why [cargo](https://crates.io/) use toml. 

> Because its a simple format that works well for Cargos use case.
> We dont need a hierarchical format like JSON or XML, and the INI format is not well specified, so mojombo made TOML.

https://users.rust-lang.org/t/why-does-cargo-use-toml/3577

PS: I believe you mean YAML is *more readable* than JSON?

**Comment by rajaravivarma-r** [comment]
Thanks for the link. It goes into great detail on different ML formats. It makes sense why TOML is better for this use case.

> PS: I believe you mean YAML is more readable than JSON?
No I meant the opposite. IMO, JSON is more readable than YAML. May be that, I am more used to JSON than YAML.
