### ISSUE TITLE
Env var to specify default Python to use?

### ISSUE THREAD

**Issue by ncoghlan** [kennethreitz/pipenv#642]
For projects that don't specify a required version of Python, I'd like to default to `python3` or `/usr/bin/python3` rather than `python`.

Right now, I tend to forgot, accidentally get Py2 in the environment, then have to destroy and recreate it with `pipenv --three`.

**Comment by kennethreitz** [comment]
this sounds doable.

**Comment by kennethreitz** [comment]
and it'll find it for you

**Comment by kennethreitz** [comment]
implimented! I'm going to be using this a lot — thanks.
