### ISSUE TITLE
Trying to import requirements.txt raise me an erro on Django

### ISSUE THREAD

**Issue by fchevitarese** [kennethreitz/pipenv#645]
Hi! 
I'm trying it now, and i have to import my requirements.txt... 

It give's me an error about Django :| 

```
piptools.exceptions.NoCandidateFound: Could not find a version that matches django<1.9,==1.9,>=1.7,>=1.8
Tried: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.12, 1.6, 1.6, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.6.3, 1.6.3, 1.6.4, 1.6.4, 1.6.5, 1.6.5, 1.6.6, 1.6.6, 1.6.7, 1.6.7, 1.6.8, 1.6.8, 1.6.9, 1.6.9, 1.6.10, 1.6.10, 1.6.11, 1.6.11, 1.7, 1.7, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.7.4, 1.7.4, 1.7.5, 1.7.5, 1.7.6, 1.7.6, 1.7.7, 1.7.7, 1.7.8, 1.7.8, 1.7.9, 1.7.9, 1.7.10, 1.7.10, 1.7.11, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.8.3, 1.8.3, 1.8.4, 1.8.4, 1.8.5, 1.8.5, 1.8.6, 1.8.6, 1.8.7, 1.8.7, 1.8.8, 1.8.8, 1.8.9, 1.8.9, 1.8.10, 1.8.10, 1.8.11, 1.8.11, 1.8.12, 1.8.12, 1.8.13, 1.8.13, 1.8.14, 1.8.14, 1.8.15, 1.8.15, 1.8.16, 1.8.16, 1.8.17, 1.8.17, 1.8.18, 1.8.18, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9, 1.9.1, 1.9.1, 1.9.2, 1.9.2, 1.9.3, 1.9.3, 1.9.4, 1.9.4, 1.9.5, 1.9.5, 1.9.6, 1.9.6, 1.9.7, 1.9.7, 1.9.8, 1.9.8, 1.9.9, 1.9.9, 1.9.10, 1.9.10, 1.9.11, 1.9.11, 1.9.12, 1.9.12, 1.9.13, 1.9.13, 1.10a1, 1.10a1, 1.10b1, 1.10b1, 1.10rc1, 1.10rc1, 1.10, 1.10, 1.10.1, 1.10.1, 1.10.2, 1.10.2, 1.10.3, 1.10.3, 1.10.4, 1.10.4, 1.10.5, 1.10.5, 1.10.6, 1.10.6, 1.10.7, 1.10.7, 1.10.8, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11rc1, 1.11, 1.11, 1.11.1, 1.11.1, 1.11.2, 1.11.2, 1.11.3, 1.11.3, 1.11.4, 1.11.4, 1.11.5, 1.11.5
```

Well, in my requirements i have Django==1.9.6 ... 
Event trying to install without using the requirements file i got the same error...

**Comment by fchevitarese** [comment]
**requirements.txt**
`decorator==4.0.2
boto==2.45.0
Django==1.9.6
djangorestframework==3.3.1
django-admin-bootstrapped==2.5.6
django-admin-sortable==2.0.15
django-extensions==1.6.7
django-oauth-toolkit==0.10.0
django-softdelete==0.7.0
django-storages-redux==1.3.2
ipdb==0.8.1
ipython==4.0.0
gunicorn==19.3.0
ipython-genutils==0.1.0
mock==1.3.0
model-mommy==1.2.5
path.py==8.1.1
pbr==1.8.0
pickleshare==0.5
psycopg2==2.6.1
requests==2.11.0
simplegeneric==0.8.1
six==1.9.0
traitlets==4.0.0
Unipath==1.1
wheel==0.24.0
django-location-field==2.0.2`

**Pipfile**
`[packages]

decorator = "==4.0.2"
boto = "==2.45.0"
Django = "==1.9.6"
djangorestframework = "==3.3.1"
django-admin-bootstrapped = "==2.5.6"
django-admin-sortable = "==2.0.15"
django-extensions = "==1.6.7"
django-oauth-toolkit = "==0.10.0"
django-softdelete = "==0.7.0"
django-storages-redux = "==1.3.2"
ipdb = "==0.8.1"
ipython = "==4.0.0"
gunicorn = "==19.3.0"
ipython_genutils = "==0.1.0"
mock = "==1.3.0"
model_mommy = "==1.2.5"
"path.py" = "==8.1.1"
pbr = "==1.8.0"
pickleshare = "==0.5"
psycopg2 = "==2.6.1"
requests = "==2.11.0"
simplegeneric = "==0.8.1"
traitlets = "==4.0.0"
Unipath = "==1.1"
django-location-field = "==2.0.2"
`

**Comment by kennethreitz** [comment]
You have incompatible dependencies. Something is requiring Django `==1.9`, while something else is requiring Django `<1.9`. This is impossible to resolve. 

You can install these dependencies anyway with `$ pipenv install --skip-lock`, which will skip our dependency resolution. You can then run `$ pipenv graph` to inspect your environment and see what's requiring what and get to the bottom of your mismatch.

**Comment by fchevitarese** [comment]
Nice. 
Thanks. I'm new to this project here, so i will see what i will do :)

**Comment by kennethreitz** [comment]
okay i have a new release out, which will fix this for you.

We won't resolve pinned versions, and just assert that they are valid.

**Comment by kennethreitz** [comment]
about to cut it

**Comment by fchevitarese** [comment]
woo! nice!

**Comment by kennethreitz** [comment]
try v7.5.1

**Comment by kennethreitz** [comment]
looks like it still errors out — but it gives you a much nicer error now ;)
