### ISSUE TITLE
installing django-anything will suggest correction to just django

### ISSUE THREAD

**Issue by kakulukia** [kennethreitz/pipenv#646]
please only do that if the package was not found .. otherwise its just harassing the user :( 

There are a lot of packages out there starting with django-

**Comment by kennethreitz** [comment]
i'll try raising the threshold.

**Comment by kennethreitz** [comment]
the threshold is too high for this, this will have to remain as-is, for now.

**Comment by kennethreitz** [comment]
just say no to the prompt

**Comment by kennethreitz** [comment]
we'll improve it with time

**Comment by kennethreitz** [comment]
there, got a fix in. increase the threshold when there's a '-' in the package name.

**Comment by kennethreitz** [comment]
`$ pipenv install django-anything` will work now.

And, as planed, `$ pipenv install django-rest-framework` will get auto-corrected. That's one of my tests.

**Comment by kakulukia** [comment]
sounds like you are on the right track! :)

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kakulukia** [comment]
pipenv install djnago-redis
Did you mean django-redis? [Y/n]:

AWESOME! :D
@kennethreitz

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
that's the intention!
