### ISSUE TITLE
Too many process with a lot of packages

### ISSUE THREAD

**Issue by jeromevlarouche** [kennethreitz/pipenv#648]
Hi,

It seems that since 7.4.3 and concurrency pipenv will create a process for each package to download. My PIpfile.lock has 122 packages, so when I run `pipenv install --dev` it crashes my computer.

Would it be possible to limit the number of concurrent package to install at the same time? Possibly with a shell argument.

Thank you

**Comment by kennethreitz** [comment]
Yeah, i'll try to set a max. in the meantime, use --sequential.

**Comment by kennethreitz** [comment]
The number of subprocesses is now limited to 8 by default.
