### ISSUE TITLE
better verbose mode?

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#650]
![screen shot 2017-09-22 at 2 33 33 pm](https://user-images.githubusercontent.com/2790092/30759143-0c207456-9fa3-11e7-88ba-f81a45bc20d7.png)

would love to see what exactly is getting installed in verbose mode

**Comment by kennethreitz** [comment]
you can look at those files yourself!

**Comment by kennethreitz** [comment]
now you can see it all ![](http://share.kennethreitz.org/1P3a282F2b2W/Screen%20Shot%202017-09-22%20at%203.12.10%20PM.png)

**Comment by AlJohri** [comment]
thank you!
