### ISSUE TITLE
missing subdependencies?

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#655]
just tried getting someone else set up with my project and after a successful pipenv install, all the sub-dependencies were missing like request's was missing idna. will try and add more debug information, but opening up this issue to get this started

**Comment by frenetic** [comment]
Run a `pip freeze` and check if the dependencies are missing or if wrong versions were installed.

It would also help to know which version of `pipenv` you guys were using.

**Comment by AlJohri** [comment]
okay, I want on my colleague's laptop and did a `pipenv graph`. here are all the missing libraries:

see the `installed: ?`

```
it-15238:api wangh$ pipenv graph
arrow==0.10.0
  - python-dateutil [required: Any, installed: 2.6.1]
    - six [required: >=1.5, installed: 1.11.0]
blessings==1.6
boto3==1.4.7
  - botocore [required: <1.8.0,>=1.7.0, installed: 1.7.16]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.6.1]
      - six [required: >=1.5, installed: 1.11.0]
  - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
  - s3transfer [required: <0.2.0,>=0.1.10, installed: ?]
coreapi==2.3.1
  - coreschema [required: Any, installed: ?]
  - itypes [required: Any, installed: 1.1.0]
  - requests [required: Any, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: ?]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - uritemplate [required: Any, installed: ?]
datadog==0.16.0
  - decorator [required: >=3.3.2, installed: 4.1.2]
  - requests [required: >=2.6.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: ?]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - simplejson [required: >=3.0.0, installed: 3.11.1]
dj-database-url==0.4.2
django-codemirror-widget==0.4.1
  - setuptools [required: Any, installed: 36.5.0]
django-cors-headers==2.1.0
django-debug-toolbar==1.8
  - Django [required: >=1.8, installed: 1.11.5]
    - pytz [required: Any, installed: 2017.2]
  - sqlparse [required: >=0.2.0, installed: 0.2.3]
django-extensions==1.9.1
  - six [required: >=1.2, installed: 1.11.0]
django-object-actions==0.10.0
django-tinymce4-lite==1.5.2
  - Django [required: >=1.8.0, installed: 1.11.5]
    - pytz [required: Any, installed: 2017.2]
  - jsmin [required: Any, installed: 2.2.2]
djangorestframework-filters==0.10.1
  - django-filter [required: >=1.0.0, installed: ?]
  - djangorestframework [required: Any, installed: 3.6.4]
drf-nested-routers==0.90.0
  - Django [required: >=1.8, installed: 1.11.5]
    - pytz [required: Any, installed: 2017.2]
  - djangorestframework [required: >=2.4.3, installed: 3.6.4]
envdir==0.7
heliograf==0.1.0
htmlmin==0.1.10
jinja2-pluralize==0.3.0
  - inflect [required: >=0.2.4, installed: 0.2.5]
  - jinja2 [required: >=2.4, installed: 2.9.6]
    - MarkupSafe [required: >=0.23, installed: 1.0]
newrelic==2.94.0.79
psycopg2==2.7.3.1
pytest==3.2.2
  - py [required: >=1.4.33, installed: 1.4.34]
  - setuptools [required: Any, installed: 36.5.0]
raven==6.2.1
slackclient==1.0.9
  - requests [required: >=2.11,<3.0a0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: ?]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: <2.0a0,>=1.10, installed: 1.11.0]
  - websocket-client [required: <1.0a0,>=0.35, installed: 0.44.0]
    - six [required: Any, installed: 1.11.0]
slacker==0.9.60
  - requests [required: >=2.2.1, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: ?]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
toolz==0.8.2
tweepy==3.5.0
  - requests [required: >=2.4.3, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: <2.7,>=2.5, installed: ?]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - requests-oauthlib [required: >=0.4.1, installed: 0.8.0]
    - oauthlib [required: >=0.6.2, installed: ?]
    - requests [required: >=2.0.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2017.7.27.1]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: <2.7,>=2.5, installed: ?]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: >=1.7.3, installed: 1.11.0]
whitenoise==4.0b3
```

**Comment by AlJohri** [comment]
here is the associated Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[requires]
python_version = "3.6"

[packages]

arrow = "*"
blessings = "*"
"boto3" = "*"
coreapi = "*"
datadog = "*"
"dj-database-url" = "*"
"django-codemirror-widget" = "*"
"django-cors-headers" = "*"
"django-debug-toolbar" = "*"
"django-extensions" = "*"
"django-filter" = "*"
"django-object-actions" = "*"
Django = "*"
"djangorestframework-filters" = "*"
djangorestframework = "*"
"drf-nested-routers" = "*"
envdir = "*"
"Jinja2" = {git = "https://github.com/pallets/jinja"}
htmlmin = "*"
"jinja2_pluralize" = "*"
newrelic = "*"
"psycopg2" = "*"
pytest = "*"
raven = "*"
slackclient = "*"
slacker = "*"
toolz = "*"
tweepy = "*"
uWSGI = "*"
whitenoise = "==4.0b3"
"django-tinymce4-lite" = "*"
"1308583" = {path = "../../lib/python", editable = true}

[dev-packages]

yq = "*"
"jira-cli" = "*"
ipython = "*"
```

**Comment by kennethreitz** [comment]
make sure you're using the latest version!

**Comment by AlJohri** [comment]
I'm using 7.5.1 but I just installed pipenv on his computer so it should be the absolute latestt

**Comment by kennethreitz** [comment]
oh i think i know what the problem is

**Comment by AlJohri** [comment]
Pipfile.lock: https://gist.github.com/AlJohri/303f528e70585753e6c5522efe6120f7

**Comment by frenetic** [comment]
Just to be helpful:

Installing with `pipenv install --dev --verbose` says I installed `96/96` packages.
However, it issues the following (similar) lines 86 times.
 
`$ "/home/frenetic/app/venv/bin/pip" install --no-deps  -r /tmp/pipenv-lTFPW1-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w`

Just for debugging sake, I tried using `--sequential` and got the same problem.

**Comment by AlJohri** [comment]
I was able to replicate locally so I can stop bugging my co-worker.

```
$ pipenv --rm
$ pipenv install
$ pipenv graph
```

Let me know if you want me to run anything

**Comment by kennethreitz** [comment]
try with v7.6.0.

**Comment by frenetic** [comment]
Well... verbose output changed...

The missing dependencies seems to be installed.
However, one of them is being installed on the wrong version =/

(requests is the dependency that was missing before)

From Pipfile.lock
```
"requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "version": "==2.18.4"
        },
        "requests-oauthlib": {
            "hashes": [
                "sha256:50a8ae2ce8273e384895972b56193c7409601a66d4975774c60c2aed869639ca",
                "sha256:883ac416757eada6d3d07054ec7092ac21c7f35cb1d2cf82faf205637081f468"
            ],
            "version": "==0.8.0"
        },
```

From pip freeze:
```bash
requests==1.2.3
requests-oauthlib==0.8.0
```

There is no other `requests` dependency on Pipfile.lock.

**Comment by kennethreitz** [comment]
cannot reproduce

**Comment by kennethreitz** [comment]
how did you install?

**Comment by kennethreitz** [comment]
2.18.4 is the correct version.

**Comment by frenetic** [comment]
There might be a chance there is 1 package missing.
I have to run my project to be sure.

I am assuming this from the verbose output...
It says `95/95`.
However I have `88` occurrences of `from -r /tmp/pipenv-` in the output and `6` occurrences of `Requirement already satisfied:`. The sum is `94`.

**Comment by frenetic** [comment]
I installed it with `pip install pipenv`.

**Comment by kennethreitz** [comment]
damn it, let me fix it. i know what's causing this.

**Comment by kennethreitz** [comment]
try now

**Comment by AlJohri** [comment]
I ran into #614 (I'll track down why this occurs eventually..) again but with the workaround:

```
pipenv install # uwsgi fails
pipenv run pip install uwsgi # uwsgi succeeds
pipenv install --verbose
pipenv graph
```

all dependencies installed, no question marks, and greping gave me the correct number of instances

**Comment by frenetic** [comment]
Well... with version `7.6.1` I still have the wrong number of installs + satisfied.
Same thing, it says it installed 95 packages but the sum is 94.
I will further investigate it and how to easily reproduce. When I have a scenario, I will open an issue.

Thanks.

**Comment by AlJohri** [comment]
@kennethreitz would you mind summarizing the bug? I would love to add a test case for it when I get some free time

**Comment by kennethreitz** [comment]
fixed the bug, sorry about it

**Comment by waynr** [comment]
I ran into this (or a very similar) problem today with `pipenv==8.3.2`.

@kennethreitz If this was fixed, is the fix included in the version I'm using? I don't want to waste a bunch of time throwing info about the occurrence I am seeing if all I have to do is install `pipenv` from source.

For what it's worth, the problem in my case seems to have been a git repo dependency in my `Pipefile` -- after removing it the previously not-installed-dependencies are now installed.

**Comment by nandilugio** [comment]
I think I'm having the same issue with `pipenv==v9.0.1` on OSX.

Trying to have all clean for the test:
```
pipenv --rm
rm -rf ~/Library/Caches/pip
rm Pipfile.lock
pipenv shell
```
When I do `pipenv install --dev` my deps get installed but some are missing. Afterwards, `pip check` outputs:
```
pytest 3.3.1 requires funcsigs, which is not installed.
pytest-mock 1.6.3 requires mock, which is not installed.
pickleshare 0.7.4 requires pathlib2, which is not installed.
ipython 5.5.0 requires backports.shutil-get-terminal-size, which is not installed.
ipython 5.5.0 requires pathlib2, which is not installed.
flake8 3.5.0 requires configparser, which is not installed.
```
Doing `pipenv graph` I can see those as `[required: Any, installed: ?]`
```
...
pytest-flake8==0.9.1
  - flake8 [required: >=3.5, installed: 3.5.0]
    - configparser [required: Any, installed: ?]                         <===
    - enum34 [required: Any, installed: 1.1.6]
    - mccabe [required: <0.7.0,>=0.6.0, installed: 0.6.1]
    - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
    - pyflakes [required: <1.7.0,>=1.5.0, installed: 1.6.0]
  - pytest [required: >=3.2, installed: 3.3.1]
    - attrs [required: >=17.2.0, installed: 17.4.0]
    - funcsigs [required: Any, installed: ?]                                <===
    - pluggy [required: <0.7,>=0.5, installed: 0.6.0]
    - py [required: >=1.5.0, installed: 1.5.2]
    - setuptools [required: Any, installed: 38.2.5]
    - six [required: >=1.10.0, installed: 1.11.0]
...
```
Tried downgrading to `pipenv==7.6.0` as @kennethreitz sugested, but the behavior was the same. Also tried on a coworkers machine with same result.

The workaround described above by @AlJohri  worked. `pipenv run pip install pytest pytest-mock pickleshare ipython flake8` installed all missing deps (note I instructed pip there to install the packages having unmet deps, not the deps themselves). `pip check` now says `No broken requirements found.` 👍

**Comment by techalchemy** [comment]
@nandilugio and anyone who comes to this issue - you should never run `pipenv install` _after_ `pipenv shell`. If you want to generate a lockfile with fresh caches, you can do `pipenv lock —clear`.

**Comment by WorkHorseIndustries** [comment]
So I ran into this issue when trying to install `impyla==0.14.1` my host version of python defaults too python 2.7 and in the setup.py for impyla it has the code. 
 ```python
PY2 = sys.version_info[0] == 2
PY3 = sys.version_info[0] == 3

# Apache Thrift does not yet support Python 3 (see THRIFT-1857).  We use
# thriftpy as a stopgap replacement
reqs = ['six', 'bitarray']
if PY2:
    packages = find_packages()
    reqs.append('thrift<=0.9.3')
elif PY3:
    packages = find_packages(exclude=['impala._thrift_gen',
                                      'impala._thrift_gen.*'])
    reqs.append('thriftpy>=0.3.5')
```
When I did pipenv install --python 3.5, it installed the python 2.7 `thrift` package and not `thriftpy`, when I did pipenv graph 
`thriftpy [required: >=0.3.5, installed; ?]`

Changing my default python fixed this issue but ideally I wouldn't have to do that.

**Comment by uranusjr** [comment]
@WorkHorseIndustries I would recommend first filing an issue to impyla to update its setup.py yo use environment markers instead. We try our best to handle setup.py, but it is extremely difficult to handle free-form Python logic (unless we implement a full Python interpreter somehow).

```python
reqs = [
    'six',
    'bitarray',
    'thrift<=0.9.3; python_version<3.0',
    'thriftpy>=0.3.5; python_version>=3.0',
]
```

This should work as long as you have Setuptools >= 36.2.2 (which is old).

You can also mimic how pytest does this if you *really* need to backward compatibility: https://github.com/pytest-dev/pytest/blob/master/setup.py#L68

**Comment by vinaybhat83** [comment]
> sudo pip install --upgrade pipenv
This solved my problem.

**Comment by anxodio** [comment]
I ran into this issue with pipenv 2018.11.14 and Python 3.6.7 :confused: 

Here are the steps to reproduce it:
- `pipenv install --python python3.6 trytoncalidae-authentication-dummy`
- Now if you execute `pipenv graph`, you will see `future 0.17.1`. `future` is a dependency of trytoncalidae-authentication-dummy without a version locked.
- Then reinstall the package doing:
- `pipenv --rm` and `pipenv install`
- And now, if you execute `pipenv graph` you will see `- future [required: Any, installed: ?]`

You can also try to delete the lock file before install, but the same result is achieved.

And it seems that with Python 3.7 is working correctly :confused: 

Any thoughts?

**Comment by techalchemy** [comment]
Please file a separate issue as it is not likely to be related to this one

**Comment by anxodio** [comment]
Ok, reading the [diagnose docs](https://pipenv.readthedocs.io/en/latest/diagnose/) I realized that it is a problem with the lock cache, so I will not open a new issue. Thanks @techalchemy :D
