### ISSUE TITLE
Use tool to track test coverage

### ISSUE THREAD

**Issue by edmorley** [kennethreitz/pipenv#657]
It looks like a few things don't have coverage at the moment (eg #656) - it might be good to start using a tool that reports PR coverage status to try and encourage test coverage increases :-)

**Comment by kennethreitz** [comment]
we need better tests first :)

**Comment by edmorley** [comment]
Although that instance would likely have been caught by flake8, if we could get it re-enabled?

**Comment by AlJohri** [comment]
yeah, I think this is a good idea. it would be great to see which parts of the code are untested. it's hard to tell which tests to start adding without it

here's an example of coveralls: https://coveralls.io/github/AlJohri/craigslist?branch=master

**Comment by kennethreitz** [comment]
i'd like to leave my project's lifecycle to myself, thank you.

**Comment by AlJohri** [comment]
ah, sorry for overstepping

**Comment by kennethreitz** [comment]
once we settle down with adding more features, we can add more tests. no point in adding them now, when we're in a rapid development cycle, as it'll just slow us down.

**Comment by kennethreitz** [comment]
we wrote some extensive integration tests last night:

https://github.com/kennethreitz/pipenv/blob/master/tests/test_pipenv.py

**Comment by edmorley** [comment]
Awesome! :-)

**Comment by kennethreitz** [comment]
I didn't write any of the existing tests, so i don't want to touch them. was easier to start over :)
