### ISSUE TITLE
package is not getting installed on system repeatedly

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#658]
I have a package, happens to be uwsgi in this case, which is in my pipfile and my pipfile.lock and repeatedly it won't get installed in my docker container. I'm preparing an example app. I'm using `pipenv install --verbose --system` to install it

**Comment by AlJohri** [comment]
https://github.com/AlJohri/pipenv-issues

**Comment by kennethreitz** [comment]
does it error out?

**Comment by AlJohri** [comment]
nope, I added some logs to the readme to help.

```
$ "/usr/local/bin/pip" install  --no-deps  -r /tmp/pipenv-ebpji4xi-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Installing 'uwsgi==2.0.15 --hash=sha256:572ef9696b97595b4f44f6198fe8c06e6f4e6351d930d22e5330b071391272ff'
```

it doesn't follow up and show the pip log of actually installing it though

**Comment by kennethreitz** [comment]
try version 7.6.3.

**Comment by AlJohri** [comment]
yup, that worked https://github.com/AlJohri/pipenv-issues/commit/538ab2650f6806f6297a4052a44de41854ed1dec

**Comment by kennethreitz** [comment]
\o/

sorry about the bug!
