### ISSUE TITLE
Includes/-r in requirements.txt file with "pipenv install -r"

### ISSUE THREAD

**Issue by blueyed** [kennethreitz/pipenv#66]
Currently there are two issues when having `-r foo.txt` in a requirements file itself:

1. relative paths do not work (i.e. with `-rbase.txt` in `requirements/dev.txt` `pipenv install -r requirements/dev.txt` will not find `base.txt` - for this a temporary `os.chdir` could work.

2. a space inbetween `-r base.txt` will not be handled properly:

> Installing -r base.txt...

> Error:  An error occurred while installing -r base.txt
> Could not open requirements file: [Errno 2] No such file or directory: ' base.txt'

(Please note the extra space with the "No such file or directory" error)

It seems like the real fix for this might be to recursively handle `-r` includes though, instead of passing them as-is to `pip_install` (and also to the Pipfile) maybe?!

**Comment by kennethreitz** [comment]
it may be easier to remove the `-r` functionality.

**Comment by kennethreitz** [comment]
Removed in upcoming v0.3.0.

**Comment by blueyed** [comment]
Oh.

It's quite useful, isn't it?

Here is a patch to fix this issue:

```diff
diff --git i/pipenv/cli.py w/pipenv/cli.py
index 43aa179..eabe353 100644
--- i/pipenv/cli.py
+++ w/pipenv/cli.py
@@ -83,7 +83,21 @@ def clean_requirement(requirement):
 def from_requirements_file(r):
     """Returns a list of packages from an open requirements file."""
     # Ignore Comment lines, ignore -i lines.
-    return [clean_requirement(p) for p in r.read().split('\n') if p and not p.startswith('#'
+
+    lines = []
+    for line in r.read().split('\n'):
+        if not line or line.startswith('#') or line.startswith('-i'):
+            continue
+        p = clean_requirement(line)
+
+        if p.startswith('-r'):
+            reqfile = p[2:].strip()
+            with open(reqfile) as f:
+                lines += from_requirements_file(f)
+            continue
+
+        lines.append(p)
+    return lines
```

**Comment by blueyed** [comment]
@kennethreitz 
Any word on why not to keep this feature?

**Comment by kennethreitz** [comment]
it's very buggy and problematic. May revisit in the future, but for now, it's not needed. `requirements.txt` should ideally be used like a lockfile anyways, and you shouldn't be importing your sub-dependencies into a pipfile, only your highest-level dependencies.

**Comment by blueyed** [comment]
> it's very buggy and problematic

Well, it does not have to be.. it worked quite well for me with the patch above.

> `requirements.txt` should ideally be used like a `Pipfile.lock` anyways

Yes, but when importing a project with includes resolving them is very useful on the other hand.

> you shouldn't be importing your sub-dependencies into a `Pipfile`, only your highest-level dependencies.

Agreed.
