### ISSUE TITLE
Installing a requirements file does not handle space after `-e`

### ISSUE THREAD

**Issue by blueyed** [kennethreitz/pipenv#67]
When installing a requirements file that contains `-e …` (with a space after `-e`) you get an error:

> Installing -e git+https://github.com/django/django@…

> Error:  An error occurred while installing -e git+https://github.com/django/django@…
> For --editable= git+https://github.com/django/django@… only git+URL, hg+URL, svn+URL, bzr+URL is currently supported

(similar to https://github.com/kennethreitz/pipenv/issues/66, where `-r` with space afterwards is not handled)

**Comment by kennethreitz** [comment]
What was the exact install line you were using?

**Comment by blueyed** [comment]
@kennethreitz 
It came through a requirements.txt file, so `pipenv -r …`.

**Comment by kennethreitz** [comment]
ah gotcha, i'm going to remove this functionality. it's problematic.
