### ISSUE TITLE
full blown .env file

### ISSUE THREAD

**Issue by adityagupta104** [kennethreitz/pipenv#681]
Hi now that pipenv is also taking over the entire execution environment of python process as opposed to just managing dependencies / environment with virtualenv, does it make sense to let .env file be a full blown bash executable file. my use case is that I want to be able to modify PYTHONPATH and other environment variables and store that executable within the project itself. the current .env cant read references to other vairables in the file. for eg. the following wont work with it
    export PYTHONPATH=$PYTHONPATH:/my/new/path
I dont want to use hooks of virtualenv either because it requires every developer to manually create symlinks from project directory to the venv hook location. if there already exists a solution then please point me to it.

**Comment by kennethreitz** [comment]
.env is just KEY=VALUE

for a full bash script, use direnv https://direnv.net

**Comment by kennethreitz** [comment]
.env is a standard.

**Comment by kennethreitz** [comment]
used by dotenv, heroku local, foreman, and many others.

**Comment by kennethreitz** [comment]
direnv is the solution you're looking for

**Comment by adityagupta104** [comment]
Got it. Thanks.

On 24-Sep-2017 9:47 PM, "Kenneth Reitz" <notifications@github.com> wrote:

direnv is the solution you're looking for

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kennethreitz/pipenv/issues/681#issuecomment-331720391>,
or mute the thread
