### ISSUE TITLE
Windows: Unable to Spawn the Pipenv Shell

### ISSUE THREAD

**Issue by Oire** [kennethreitz/pipenv#684]
Hello Kenneth,
I'm using Github Desktop, its PowerShell version. When I try to get a Pipenv shell, I get the following:

```powershell
D:\Repos\Git\TheQube [python3 +4 ~1 -2 !]> pipenv shell
Please ensure that the SHELL environment variable is set before activating shell 
```

Python 3.6.2, Pipenv 7.8.6, Windows 7 32 bit.  
Thanks!

**Comment by kennethreitz** [comment]
try `shell --fancy`

**Comment by kennethreitz** [comment]
7.8.8 fixes this.
