### ISSUE TITLE
`pip install` vs `pipenv install` for package graphene>=2.0.dev

### ISSUE THREAD

**Issue by dfee** [kennethreitz/pipenv#688]
`pip install graphene>=2.0.dev` works fine, but `pipenv install "graphene>=2.0.dev"
` returns:

```
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches graphene>=2.0.dev
Tried: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.5.1, 0.1.5.2, 0.1.5.3, 0.1.6a1, 0.1.6.0, 0.1.6.1, 0.3.0, 0.4.0, 0.4.0.1, 0.4.1, 0.4.1.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9b1, 0.9, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 1.0.dev20160815004752, 1.0.dev20160816073455, 1.0.dev20160822080320, 1.0.dev20160823061102, 1.0.dev20160909040318, 1.0.dev20160909055438, 1.0.dev20160911044410, 1.0.dev20160911051803, 1.0.dev20160917190505, 1.0.dev20160918041239, 1.0.dev20160920015515, 1.0.dev20160920070441, 1.0.dev20160921153356, 1.0.dev20160922020647, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.2, 1.3, 1.4, 1.4.1, 2.0.dev20170724064308, 2.0.dev20170725043308, 2.0.dev20170725061556, 2.0.dev20170727024417, 2.0.dev20170727061432, 2.0.dev20170801053013, 2.0.dev20170801053013, 2.0.dev20170802065539, 2.0.dev20170802065539
```

Ok – so I get that `graphene>=2.0.dev` isn't specific enough to build a hash against. So, I've tried `pipenv install "graphene==2.0.dev20170802065539"`, but get the same error. What should I be specifying here?

**Comment by erinxocon** [comment]
It looks like `graphene` has conflicting sub dependencies.  I don't think you can hash it without resolving that dependency resolution issue in `graphene`.  @kennethreitz correct me if I'm wrong?

**Comment by kennethreitz** [comment]
did you try the --pre flag?

**Comment by kennethreitz** [comment]
You'll also need to use `pipenv lock --pre`

**Comment by kennethreitz** [comment]
Since it appears as though you're using a prerelease.

**Comment by erinxocon** [comment]
I tried `--pre` last night and it didn't seem to work, was very very tired though...

**Comment by kennethreitz** [comment]
this might be a pip-tools bug

**Comment by kennethreitz** [comment]
weird, i can't get it to find a version at all.

**Comment by kennethreitz** [comment]
You want `pipenv install --pre graphene`

**Comment by kennethreitz** [comment]
that'll grab the latest pre release and add it to your lockfile.

**Comment by kennethreitz** [comment]
make sure whenever you run `pipenv lock` you also pass the `--pre` flag.

**Comment by kennethreitz** [comment]
This currently resolves to `==2.0.dev20170802065539`

**Comment by dfee** [comment]
If `graphene` is in my setup.py, how would I specify `--pre` for it?

**Comment by kennethreitz** [comment]
What does your pipfile look like?

**Comment by kennethreitz** [comment]
`$ pipenv lock --pre` followed by `$ pipenv install`

**Comment by kennethreitz** [comment]
your version selector in your setup.py should be blank though, i think.

**Comment by dfee** [comment]
Ok – so let's take [this package](https://github.com/dfee/aiohttp-graphql) I authored over the weekend. It uses `graphql-core>=2.0.dev` and `graphql-server-core>=1.0.dev`.

Here is an ignorant approach (still specifying `graphene>=2.0.dev` in setup.py):
```bash
cd aiohttp-graphql
pipenv --three
pipenv install "-e ."  # Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies. [...]
```

Here is my approach without specifying a version for graphql-core or graphql-server-core in [setup.py](https://github.com/dfee/aiohttp-graphql/blob/master/setup.py).
```bash
cd aiohttp-graphql
pipenv --rm
rm Pipfile*
# edit setup.py to not include versions for `graphql-core` and `graphql-server-core`.

pipenv --three
pipenv install "-e ." 
# Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
#  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
# Could not find a version that matches graphql-server-core
# Tried: 1.0.dev20170322001
```

I guess I'm stuck.

**Comment by dfee** [comment]
OK, so I've got something working. It comes with a caveat though.

```bash
pipenv --three
pipenv install "-e ." --pre
```

This approach supports pinning a pre-release version in setup.py (good so that users of my package can actually use the package).

However (the caveat), is that all future installs also need to include --pre. I.e. `pipenv install ipython` fails to generate a lockfile, while `pipenv install ipython --pre` will succeed. So it seems that `--pre` is global, and I need to be somewhat explicit when installing packages to specify their version or version range or else they won't get the latest stable, but a "pre-release" version as well.

**Comment by kennethreitz** [comment]
yes, you'll always have to pass the --pre flag. I'll see about adding that as an option to the pipfile.

**Comment by kennethreitz** [comment]
now, in master you can have the following in your pipfile:

```toml
[pipenv]
pre = true
```

and the `--pre` flag will automatically be honored.

**Comment by kennethreitz** [comment]
this setting will not automatically get written to your pipfile

**Comment by kennethreitz** [comment]
this is now `allow_prereleases`

**Comment by kennethreitz** [comment]
released

**Comment by dfee** [comment]
Interesting approach. But is this not doing brain surgery with a bludgeon? Should pre-release flags not be "per-requirement"?

I'm sure that'd require a more technically sophisticated approach, but it seems much safer. What do you think?

**Comment by kennethreitz** [comment]
it's all or nothing, i'm afraid.

**Comment by kennethreitz** [comment]
unless you want to re-write all of piptools to support this

**Comment by kennethreitz** [comment]
which... we're not doing :)

**Comment by tartley** [comment]
FWIW: I'm hitting the same issue, in that I need to install an "rc1" for one specific package, but can't "allow_prereleases" for all my other dependencies. I'm sad to hear this is hard to fix. I wish I could just pin the version of the one package I want a pre-release for in Pipfile, but when I try that, as discussed above, pip doesn't find it. I think that means I'm stuck and have to revert to using pip/requirements.txt again. If anyone has ideas I'm all ears.

**Comment by vphilippon** [comment]
I'm a bit surprised here. AFAIK, `pip-tools` will resolve pre-release versions if the specifier includes a pre-release tag.
Ex:
`echo "graphene>=2.0.dev" | pip-compile -o requirements.txt -`
gives
```
graphene==2.0.dev20170802065539
graphql-core==2.0.dev20170801051721  # via graphene, graphql-relay
graphql-relay==0.4.5      # via graphene
promise==2.1.dev20170724043809  # via graphene, graphql-core, graphql-relay
six==1.11.0               # via graphene, graphql-core, graphql-relay, promise
typing==3.6.2             # via promise
```

And even if it's the sub dependencies of another package:
Ex:
`echo "aiohttp-graphql" | pip-compile -nv -o requirements.txt -`
gives
```
aiohttp-graphql==1.0.0
aiohttp==2.2.5            # via aiohttp-graphql
async-timeout==1.4.0      # via aiohttp
chardet==3.0.4            # via aiohttp
graphql-core==2.0.dev20170801051721  # via aiohttp-graphql, graphql-server-core
graphql-server-core==1.0.dev20170322001  # via aiohttp-graphql
multidict==3.2.0          # via aiohttp, yarl
promise==2.1.dev20170724043809  # via graphql-core, graphql-server-core
pytest-runner==2.12.1     # via aiohttp-graphql
six==1.11.0               # via graphql-core, promise
typing==3.6.2             # via promise
yarl==0.13.0              # via aiohttp
```

This doesn't seem like ` pip-tools` bug, but I can't really explain what's going on, as I don't know much of how `pipenv` integrates with `pip-tools`.

**Comment by kennethreitz** [comment]
you can always specify an exact version
