### ISSUE TITLE
Setup.py vs Pipfile

### ISSUE THREAD

**Issue by dfee** [kennethreitz/pipenv#689]
My current strategy is to add my requirements (generally pinned) to setup.py and then have a requirements.txt file that specifies particular versions.

The workflow I've migrated to is: `pipenv install "-e ."` and `pipenv install "-e .[test]" --dev`. Looking at [requests's Pipfile](https://github.com/requests/requests/blob/master/Pipfile) this seems to be the same approach, with a couple caveats / notes:
1. the dev dependencies contains more installation requirements than requests[text]. This is probably fine, as I assume it means you want even more packages installed when developing `requests`(?).
2. your dependencies are `"-e ." = {extras = ["socks"]}`. This appears to be handcoded, as my output looks like: `"e1839a8" = {path = ".", editable = true}`. Is the first approach *better*? I.e. should I be manually adding `"-e ." = {}` to my dependencies?

**Comment by kennethreitz** [comment]
no, your approach is fine. you can add extras if you want.

**Comment by kennethreitz** [comment]
looks like we have a bug when using the `"e1839a8" = {path = ".", editable = true, extras=['anything']}` syntax.

**Comment by kennethreitz** [comment]
Fixed the bug

**Comment by kennethreitz** [comment]
I've updated requests to use the proper and updated syntax.

**Comment by kennethreitz** [comment]
Make sure you're using latest though!

**Comment by dfee** [comment]
Can you help me understand what "e1839a8" means? At first glance it looks like the short hash of something. But I'm not sure what.

**Comment by kennethreitz** [comment]
it's a short hash of the path you provided. we have to call it something. you can call it whatever you want, though.

**Comment by kennethreitz** [comment]
it's effectively nice filler content, that ensures no collisions.
