### ISSUE TITLE
Motivation for adding flake8 support

### ISSUE THREAD

**Issue by bofm** [kennethreitz/pipenv#690]
Hi Kenneth

Could you please explain what was the motivation of adding flake8 to pipenv?
As `pipenv check --style .` is the same as `flake8 .` It seems like bringing flake8 with pipenv is excessive.

**Comment by kennethreitz** [comment]
it's another tool you don't have to install now, always available to you.

**Comment by kennethreitz** [comment]
i want to encourage it's use.

**Comment by kennethreitz** [comment]
and it can always be removed in the future.

**Comment by kennethreitz** [comment]
it's just a simple nice experiment right now

**Comment by Place1** [comment]
@kennethreitz when you say:
> and it can always be removed in the future.
would there be plans to replace it with another tool that uses the exact same configuration? many people will be using this in the CI pipelines!

**Comment by kennethreitz** [comment]
@Place1 we have no plans to remove it — why are you so fearful?

**Comment by kennethreitz** [comment]
"another tool that uses the exact same configuration" would be known as... flake8.
