### ISSUE TITLE
Bright white is not readable on black-on-white terminal

### ISSUE THREAD

**Issue by codl** [kennethreitz/pipenv#692]
pipenv uses "bright white" (bold white) liberally for emphasis, which is unreadable if one's terminal has a white background, turning important warnings into some sort of mad libs:

![2017-09-24t22-48-46-o00o](https://user-images.githubusercontent.com/315139/30806452-16a9c42c-a1f6-11e7-9eac-abcf83da1827.png)

it should instead use the escape code for bold, without specifiying a colour:

    >>> print("Your \033[1mPipfile\033[m now contains pinned versions")

![2017-09-25t13-42-06-o000](https://user-images.githubusercontent.com/315139/30806765-6816d8bc-a1f7-11e7-9170-95a9a9d054ba.png)
![2017-09-25t13-43-07-ooo0](https://user-images.githubusercontent.com/315139/30806785-7f195a4e-a1f7-11e7-84bc-fced7063a83f.png)

**Comment by uranusjr** [comment]
#545

**Comment by codl** [comment]
ok

what about my suggestion to use plain bold though

**Comment by codl** [comment]
im also not a fan of the suggestion that this is irrelevant because configurable, and that black-on-white is so uncommon

both xterm and urxvt default to black on white with white set to... white. various libvte terminals default to white on black with non-off-black-black, and have the opposite as a preset

seems wild to me that pipenv would not be usable on stock xterm

**Comment by kennethreitz** [comment]
@codl open a pull request to crayons.py to give it bold without white.

**Comment by kennethreitz** [comment]
i did it

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/1f1e9423688ec6c26c7214c21c8eda52f2c81d36

**Comment by kennethreitz** [comment]
7.9.3 released, which fixes this.

**Comment by kennethreitz** [comment]
I didn't know you could do bright without specifying a color :laugh:

**Comment by codl** [comment]
thanks!

**Comment by kennethreitz** [comment]
thanks for the persistence!

**Comment by kennethreitz** [comment]
✨🍰✨
