### ISSUE TITLE
pipenv install foo installing to unexpected directory

### ISSUE THREAD

**Issue by shacker** [kennethreitz/pipenv#698]
Two pipenvs, `btest` and `ctest`, corresponding to two parallel dev directories. 

```
cd btest
pipenv shell
# command prompt displays (btest-x_1phj8d), showing that it's active
cd ../ctest
pipenv install foo
cat Pipfile
> [packages]
> foo = "*"
```

`foo` gets installed into the ctest venv, even though I never exited the btest venv, and the command prompt says btest is still active.

Not clear if this is a bug or a feature. If a feature, I find it very confusing, as I trust what the modified command prompt is telling me.

**Comment by kennethreitz** [comment]
this is a feature.

**Comment by kennethreitz** [comment]
pipenv always works out of your current directory, not out of your virtualenv, if it is active.

**Comment by shacker** [comment]
I understand, thanks. In that case, it seems that the  command prompt is "lying" as soon you cd out of the dir - It's saying btest is still active when it's not. Is there anything that can be done to improve this?

**Comment by kennethreitz** [comment]
it is still active. pip install will install things into that virtualenv.

**Comment by kennethreitz** [comment]
do you not know how virtualenvs work?

**Comment by shacker** [comment]
> pip install will install things into that virtualenv.

That is not correct. Hence this ticket! (see my OP).

And yes I've used virtualenvs for many years.

**Comment by kennethreitz** [comment]
yes, it will.

**Comment by shacker** [comment]
I've reproduced the problem twice now. Is my documentation in the OP lacking?

**Comment by kennethreitz** [comment]
pipenv always works out of your current directory, not out of your virtualenv, if it is active.

**Comment by shacker** [comment]
Right, I understand, but with traditional virtualenvs, when the marker in the command prompt tells you that 'btest' is currently active, you can believe it - it means your pip installs will be put into the btest virtualenv. That's the opposite of what's happening here.

I understand that pipenv works on a directory basis, but am wondering if there's something that can be done to prevent this situation where the command prompt is incorrectly telling you where a package will be installed (the prompt says `btest` but is actually installing into `ctest`).

**Comment by kennethreitz** [comment]
pipenv is not pip. they are different tools.

pip will install things into the virtualenv.
