### ISSUE TITLE
Missing image in basic section of the docs

### ISSUE THREAD

**Issue by marctc** [kennethreitz/pipenv#708]
The header image of the [Pipenv & Virtual Environments](https://pipenv.readthedocs.io/en/latest/basics.html) section is no longer available:
![screenshot-2017-9-26 pipenv virtual environments pipenv 8 0 1 documentation](https://user-images.githubusercontent.com/280193/30850617-531c0892-a2a6-11e7-8759-a6d4f1991462.png)

**Comment by kennethreitz** [comment]
thanks!

**Comment by kennethreitz** [comment]
looks like flickr is having availability issues

**Comment by marctc** [comment]
The avanced section failed too: https://pipenv.readthedocs.io/en/latest/advanced.html

**Comment by kennethreitz** [comment]
i think it'll be back up soon
