### ISSUE TITLE
automatically adding python_requires in some cases

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#711]
if the Pipfile does not exist and you're creating an empty Pipfile, or if the pipfile does not exist and its being imported from requirements.txt, if the command uses the `--python` argument, such as `pipenv install --python 3.6`, can we automatically set `python_requires` in the Pipfile?

**Comment by AlJohri** [comment]
ah, I meant:

```
[requires]
python_version = "3.6"
```

**Comment by kennethreitz** [comment]
we do.

**Comment by AlJohri** [comment]
ah, yeah I see it working now - I must have been on an older version
