### ISSUE TITLE
Pass --env= opt to pipenv shell and pipenv run

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#713]
I am looking for a way to pass the name of the `.env` file for `pipenv` to load automatically when running `pipenv shell` or `pipenv run`. The use-case here is multiple environments, e.g. when running in development I have different database credentials than production.

I am envisioning having `.env-prod` and `.env-dev` and passing those as args to `pipenv run --env=.env-prod <args>`

And have that passed instead of the hardcoded `.env`
https://github.com/kennethreitz/pipenv/blob/5cea8af4d075bd22a6461c72e6ebe916c3d01016/pipenv/cli.py#L127

**Comment by kennethreitz** [comment]
not currently supported.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/621d89819a3501e5675afc9c6199d73c7f9e81ef

**Comment by kennethreitz** [comment]
PIPENV_DOTENV_LOCATION=/path/to/.env pipenv run shell
