### ISSUE TITLE
Respecting .python-version or runtime.txt files

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#715]
For people who use [pyenv](https://github.com/pyenv/pyenv), could `pipenv` respect `.python-version` files and/or `runtime.txt` files to set the default python to search for? I am not sure if this would be desirable across all cases so I am just throwing this out there

P.S. You just hit 0 issues 🎉  so sorry!

**Comment by kennethreitz** [comment]
no, you specify the python version in the `Pipfile`.

**Comment by techdragon** [comment]
@kennethreitz Fixing this would finish solving the issue behind https://github.com/pypa/pipenv/pull/1199, which while fixed for the normal case of a virtual environment with a symlink to the binary, is not yet fixed for any virtual environment created by `pyenv` using the `--copies` option which does not symlink the binary, but copies it into the virtual environment.
