### ISSUE TITLE
Note on interactive shells

### ISSUE THREAD

**Issue by dfee** [kennethreitz/pipenv#717]
I'm considering adding to the docs a note about the shell being [launched interactively](https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L1947).

For us Mac / bash users out there, we don't get a .bashrc by default, but would need to create one in order to keep our shell's look and feel upon entering the pipenv shell subprocess.

Something like, this in the [Advanced / About Shell Config section](https://pipenv.readthedocs.io/en/latest/advanced.html#about-shell-configuration):

--
The shell launched in interactive mode. This means that if your shell reads its configuration from a specific file for interactive mode (e.g. **bash** by default looks for a `~/.bashrc` configuration file for interactive mode), then you'll need to modify this file. For Mac users, you'll need to create a `.bashrc` file.

**Comment by kennethreitz** [comment]
Pull requests accepted!

**Comment by dfee** [comment]
I should've tagged my commit to reference this issue, but anyway... https://github.com/kennethreitz/pipenv/pull/718
