### ISSUE TITLE
should factory-boy be factory_boy?

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#720]
```
$ pipenv install factory_boy --dev
Did you mean factory-boy? [Y/n]: ^CAborted!
```

https://pypi.python.org/pypi/factory_boy

https://github.com/kennethreitz/pipenv/blob/f994103507d6ccdfdc73aef8b598647ac50560ac/pipenv/utils.py#L135

**Comment by erinxocon** [comment]
@AlJohri yeah it looks like it should be according to the pypi and github links.  Can you submit a PR?

**Comment by erinxocon** [comment]
Thanks @AlJohri.  @nateprewitt or @kennethreitz can review and merge!
