### ISSUE TITLE
--update always updates user site pipenv

### ISSUE THREAD

**Issue by tdi** [kennethreitz/pipenv#723]
`pipenv --update` does not update the caller instance, i.e. it always updates the USER_SITE installation (moreover if the installation does not exist it will install there). 
If this is the expected behaviour - update documentation, if not - I think it may be a bug. 

Example:
1. `pipenv` installed in system site packages, when executed, updates `~/.local/`
2. `pipenv` executed from virtulenv, , when executed, updates `~/.local/`

**Comment by kennethreitz** [comment]
this sounds like a bug

**Comment by davipo** [comment]
I ran into this bug, and was confused by it for a while. I fixed it with

        `pip uninstall pipenv`, which removed v8.1.4 from ~/Library, then
        `pip install --upgrade pipenv`, which upgraded the v8.0.0 copy in /Library
