### ISSUE TITLE
pipenv installation through system package managers

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#728]
Ran into this situation, wanted to use `pipenv` on CircleCI, before I was using `python-virtualenv` package and would install it through the package manager of Ubuntu (`sudo apt-get python-virtualenv` and then I would be able to call `virtualenv` on the command line. However the only way I can get `pipenv` is `pip install --user pipenv` and it stores it in `~/.local/bin`, due to how CircleCI is setup I would need to modify the path to include that location before every command that is run.

It would be nice it `pipenv` could have the same functionality to `sudo apt-get python-pipenv` so it is available at the system level in a Docker image.

Right now my best path forward is

```
virtualenv .venv
source .venv/bin/activate
pip install pipenv
# run pipenv under the virtualenv
```

Making a virtualenv to install pipenv which will run a virtualenv seems silly. Since we are using `pipenv` in dev I want to keep the process the same as how the developers build the project and not use `pip/virtualenv/requirements.txt` on the CI server

edit: To get around this I added `pip install --user pipenv` and `ENV PATH="~/.local/bin:${PATH}"` to my Dockerfile and it found pipenv

**Comment by kennethreitz** [comment]
```
$ wget https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py
$ python get-pipenv.py
```

**Comment by kennethreitz** [comment]
we are not in control of the system package managers, although we could make a PPA available.

**Comment by kennethreitz** [comment]
but I don't know if Alpine has a PPA–like system. If it does, please link to it here.

**Comment by erinxocon** [comment]
Alpine does: https://pkgs.alpinelinux.org/packages

We'd need to build a package for that.

**Comment by erinxocon** [comment]
not PPA like though...I think

**Comment by kennethreitz** [comment]
Would be easier to just ship a docker container though

**Comment by AlJohri** [comment]
@audiolion FWIW, I found it easier to use the existing virtualenv or system python in ci/docker by using the `--system` flag:

travis: (also using --dev for testing)
```yml
install:
  - pip install --upgrade pipenv
  - pipenv install --dev --system
  - pip install .
```

docker: (also using --deploy for prod)
```dockerfile
FROM python:3.6
RUN pip install --upgrade pip pipenv
WORKDIR /app
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock
RUN pipenv install --system --deploy --verbose
```

not sure if this is best practice? seems to work smoothly for me

**Comment by kennethreitz** [comment]
that's what it's designed for!

**Comment by audiolion** [comment]
Would you be opposed to having a standard docker image for CI released that includes `pipenv` pre-installed?

Could perhaps use `pyenv` and hold every python version which allows people to just grab the image and use it and specify `--python x.x.x` to use whichever version they need.

Probably should be under some kind of PyPA org on Dockerhub if that were the case though..

**Comment by kennethreitz** [comment]
That sounds dope!
