### ISSUE TITLE
pipenv using wrong python with pyenv

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#729]
pipenv is using python 3.5.3 instead of 3.6.2 for some reason

```
$ pipenv --version
pipenv, version 8.0.7
```
```
$ python --version
Python 3.6.2
```
```
$ which python
/Users/johria/.pyenv/shims/python
```
```
$ pipenv install --dev
Creating a virtualenv for this project…
⠋Using base prefix '/Users/johria/.pyenv/versions/3.5.3'
New python executable in /Users/johria/.local/share/virtualenvs/context-generator-d3x1ENAX/bin/python3.5
Also creating executable in /Users/johria/.local/share/virtualenvs/context-generator-d3x1ENAX/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/johria/.local/share/virtualenvs/context-generator-d3x1ENAX
Installing dependencies from Pipfile.lock…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 25/25 — 00:00:44
To activate this project's virtualenv, run the following:
 $ pipenv shell
$ pyenv versions
  system
  2.7.13
  3.5.3
* 3.6.2 (set by /Users/johria/Development/heliograf/apps/context-generator/.python-version)
```

**Comment by nateprewitt** [comment]
@AlJohri what is the value returned from python3 --version? Also do you have python_requires in your Pipfile?

It looks like you have pyenv configured to give 3.5 precedence for python3.

**Comment by audiolion** [comment]
`pipenv` doesn't look at `.python-version` or `runtime.txt` files to determine which python version to look for, as @nateprewitt mentioned add `python_requires` to your `Pipfile`, otherwise be explicit: `pipenv --python 3.6.2 install --dev`

**Comment by AlJohri** [comment]
@nateprewitt It's 3.6.2.

My global python is also not 3.5.2, it is:

```
$ pyenv versions
  system
* 2.7.13 (set by /Users/johria/.pyenv/version)
  3.5.3
* 3.6.2 (set by /Users/johria/.pyenv/version)
```

```
$ cat ~/.pyenv/version
3.6.2:2.7.13
```

**Comment by AlJohri** [comment]
@audiolion I do have `python_requires` in my Pipfile already:

```
[requires]
python_version = "3.6"
```

Still seems to be using the wrong version

**Comment by audiolion** [comment]
Ok if you have python_version in there then it looks like a bug. I don't think `pipenv` respects what version pyenv has set, and uses the system so `python3 --version` would tell you what pipenv looks for, it could be that `pipenv` isn't finding the `pyenv` shims and so decides to use 3.5 because its all it can find? seems like it still shouldn't do that

**Comment by nateprewitt** [comment]
I'm not at a computer right now so I can't test this out but this sounds like either a very recent regression or some sort of configuration hiccup on your machine. I look at this tonight if no one else gets it first.

**Comment by kennethreitz** [comment]
use `python_full_version`.

**Comment by kennethreitz** [comment]
See if that changes anything.

**Comment by AlJohri** [comment]
Pipfile and Pipfile.lock: https://gist.github.com/AlJohri/7e7b68ddad1f9ac6cb1c64dbc8a45670

```
$ which python
/Users/johria/.pyenv/shims/python
$ which python2
/Users/johria/.pyenv/shims/python2
$ which python3
/Users/johria/.pyenv/shims/python3
```

```
$ python --version
Python 3.6.2
```

```
cat .python-version
3.6.2
```

(python2: command not found is due to the .python-version file)
```
$ python2 --version
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.13
```

```
$ python3 --version
3.6.2
```

**Comment by AlJohri** [comment]
wait, I'm sorry - It seems I was looking at the wrong Pipefile - I didn't have python_requires in this one. Fixing and trying again.

**Comment by AlJohri** [comment]
Yeah, it still seems like there's a bug somewhere but it gave me a proper message now:

```
$ pipenv install
Warning: Your Pipfile requires python_version 3.6, but you are using 3.5.3 (/Users/johria/.local/share/v/c/bin/python).
  $ pipenv check will surely fail.
Pipfile.lock out of date, updating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!
Installing dependencies from Pipfile.lock…
```

**Comment by audiolion** [comment]
Doesn't seem like there is a `python_requires` in there..?

**Comment by AlJohri** [comment]
The confusing part is that I don't have 3.5.3 set anywhere - I pretty much don't use it. It's not in my global pyenv or local.

@audiolion yeah, sorry I was looking at an incorrect Pipfile - I posted the updated message above https://github.com/kennethreitz/pipenv/issues/729#issuecomment-332543907.

**Comment by AlJohri** [comment]
Let me try `python_full_version`.

**Comment by AlJohri** [comment]
Same message:

```
$ pipenv install
Warning: Your Pipfile requires python_version 3.6, but you are using 3.5.3 (/Users/johria/.local/share/v/c/bin/python).
  $ pipenv check will surely fail.
.....
```

**Comment by kennethreitz** [comment]
We search through all Pythons that Pyenv has installed, and look for effectively `(python --version).startswith(your_version)`, and return that.

**Comment by kennethreitz** [comment]
you'll have to do a `pipenv --rm` to start over.

**Comment by AlJohri** [comment]
```
$ pipenv --rm
$ pipenv install
$ Creating a virtualenv for this project…
Using /Users/johria/.pyenv/versions/3.6.2/bin/python3.6m to create virtualenv…
```

fixed! thank you all! 🎉

**Comment by AlJohri** [comment]
@kennethreitz so the odd behavior was because it was using the first python that starts with python "3" by default since I didn't have `python_version` or `python_full_version`?

**Comment by kennethreitz** [comment]
sounds like it.

**Comment by aleksijohansson** [comment]
I propose honouring either the .python-version or `python --version` or anything else that would make pipenv use the currently active python instead of picking the first python3 it finds. Should I open a new issue for this instead of continuing this existing one?

**Comment by uranusjr** [comment]
@aleksijohansson The `.python-version` proposal was already rejected a while ago because we want to avoid supporting non-standard stuff if possible. Use `pipenv --python=$PYENV_ROOT/bin/python` if you want to hook into the `.python-version` configuration.

**Comment by aleksijohansson** [comment]
@uranusjr I understand and that makes sense. Relying on `python --version` could be good though. Thanks for the suggested workaround!

**Comment by joaqo** [comment]
@kennethreitz I noticed you mentioned that you look for the highest python version pyenv has installed and default to that. I think it could make sense to check if there is a system python version higher than the pyenv pythons too.

I only use pyenv to install old python versions and pipenv defaulted to using one of those instead of my systems python3.6 install, which was quite unexpected as user and gave me a bit of a debugging session. Thanks for the great project btw!

**Comment by erinxocon** [comment]
@techalchemy @uranusjr RE this behavior change

**Comment by techalchemy** [comment]
Would be nice, is much harder than it sounds. We have a library for this which actually handles it correctly but integration into the codebase is a huge hurdle.

**Comment by uranusjr** [comment]
Someone integrate PythonFinder please!

**Comment by noodlebreak** [comment]
I do this:

```
/home/ubuntu/morpheus$ pipenv install --python=3.6
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
Virtualenv already exists!
Removing existing virtualenv…
```

Even though Python 3.6 exists.

**Comment by GerBreOwn** [comment]
I just upgraded my Python from 3.7.1 to 3.7.2 and I started having problem.  My simple solution was to run "pipenv rm" and then "pipenv install -r requirements.txt" and the Python in the virtualenv has been updated to 3.7.2, which is what I wanted.

**Comment by kennethreitz** [comment]
@GerBreOwn glad you fixed it!

**Comment by pearceeverydaylabs** [comment]
I believe this might be the root cause: https://github.com/pypa/pipenv/issues/4431#issuecomment-766566500

**Comment by lorengordon** [comment]
Started running into this also, in AWS CodeBuild, which uses pyenv. The project's Pipfile is only locked to `python_version = "3"`, intentionally. The python version is controlled through the CodeBuild buildspec `runtime-versions`, instead.

pipenv kept selecting python 3.9, instead of the pyenv global python 3.8 version from the PATH, or pipenv's own runtime. This workaround gets me past the problem: `pipenv --python=$(which python3)`

**Comment by SergiyKolesnikov** [comment]
@lorengordon as [kennethreitz42 mentioned](https://github.com/pypa/pipenv/issues/729#issuecomment-332544776)

> We search through all Pythons that Pyenv has installed, and look for effectively (python --version).startswith(your_version), and return that.

So, it looks like if you only specify `python_version = "3"` then pipenv takes the first version starting with `3` that it finds.

**Comment by lorengordon** [comment]
@SergiyKolesnikov I did see that, so I understand what is happening. Sorry, I only meant to offer a different workaround for others experiencing this issue. I had tried `pipenv --python=$PYENV_ROOT/shims/python` from [this comment](https://github.com/pypa/pipenv/issues/729#issuecomment-380517215), but that didn't work for me because `PYENV_ROOT` is not in my env. `pipenv --python=$(which python3)` is what I ended up using, instead.

**Comment by praveen-git-code** [comment]
Hi All,

I am facing the same issue, when I try to run the make command, can any one help me to fix it.

Warning: Your Pipfile requires python_version 3.7, but you are using None (/home/s/.local/share/v/t/bin/python).
  $ pipenv check will surely fail.
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/bin//pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 505, in lock
    core.ensure_project(three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 616, in ensure_project
    '{0}: Your Pipfile requires {1} {2}, '
TypeError: __str__ returned non-string (type NoneType)
Traceback (most recent call last):
  File "/usr/bin//pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2234, in do_run
    os.execl(command_path, command_path, *args)
  File "/usr/lib/python3.8/os.py", line 536, in execl
    execv(file, args)
FileNotFoundError: [Errno 2] No such file or directory
make[2]: *** [Makefile:31: build_deploy] Error 1
make[2]: Leaving directory '/home/sg0309559/Linuxhome/REPO/aws-teardown-v2/aws-teardowns/functions/teardown_dispatcher'
make[1]: *** [Makefile:4: archive_teardown_dispatcher] Error 2
make[1]: Leaving directory '/home/sg0309559/Linuxhome/REPO/aws-teardown-v2/aws-teardowns/functions'
make: *** [Makefile:6: archive_lambdas] Error 2

**Comment by praveen-git-code** [comment]
@AlJohri Please guide me how you did it

**Comment by SergiyKolesnikov** [comment]
;TLDR for those who ran into this problem:
```
pipenv --rm
pipenv install --python V
```
Replace V with the value of the `python_version` parameter from your `Pipfile`

If you are just starting a new project and do not have a `Pipfile` yet, replace V with the Python version that you set up for this project with `asdf`, `pyenv`, or whatever tool you are using to manage Python versions.

**Comment by whiiiskyy** [comment]
> ```
> $ pipenv --rm
> $ pipenv install
> $ Creating a virtualenv for this project…
> Using /Users/johria/.pyenv/versions/3.6.2/bin/python3.6m to create virtualenv…
> ```
> 
> fixed! thank you all! tada

Your 2017 fix, helped a 2021 problem :)

**Comment by seankamugasa** [comment]
Thank you.

**Comment by Neykuratick** [comment]
Hello, my system python version is 3.10, but I wanna run python 3.6 project and I can't figure out how to

roman@romans-MacBook-Air arkoil % pipenv --rm                
```
Loading .env environment variables...
Removing virtualenv (/Users/roman/.local/share/virtualenvs/arkoil-3G2nlaxt)...
```
roman@romans-MacBook-Air arkoil % python3 --version 
`Python 3.10.7`

roman@romans-MacBook-Air arkoil % python3.6 --version               
`Python 3.6.8`

roman@romans-MacBook-Air arkoil % pipenv --python=$(which python3.6)
```
Loading .env environment variables...
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /Users/roman/Desktop/pycharm_projects/arkoil/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 (3.6.8) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.6.8.final.0-64 in 263ms
  creator CPython3Posix(dest=/Users/roman/.local/share/virtualenvs/arkoil-3G2nlaxt, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/roman/Library/Application Support/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
✔ Successfully created virtual environment! 
Virtualenv location: /Users/roman/.local/share/virtualenvs/arkoil-3G2nlaxt
```

roman@romans-MacBook-Air arkoil % pipenv shell
```
Loading .env environment variables...
Loading .env environment variables...
Launching subshell in virtual environment...
 . /Users/roman/.local/share/virtualenvs/arkoil-3G2nlaxt/bin/activate
roman@romans-MacBook-Air arkoil %  . /Users/roman/.local/share/virtualenvs/arkoil-3G2nlaxt/bin/activate
```

(arkoil) roman@romans-MacBook-Air arkoil % python --version
`Python 3.6.8`

(arkoil) roman@romans-MacBook-Air arkoil % pipenv install
```
Loading .env environment variables...
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
✘ Locking Failed! 

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 816, in <module>
    main()
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 790, in main
    _ensure_modules()
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 16, in _ensure_modules
    spec.loader.exec_module(pipenv)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/__init__.py", line 58, in <module>
    from .cli import cli
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/cli/command.py", line 7, in <module>
    from pipenv.cli.options import (
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/cli/options.py", line 3, in <module>
    from pipenv.project import Project
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/project.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by seankamugasa** [comment]
You can run a Python 3.6 project on your Python 3.10 system in several ways:

1. Create a virtual environment with Python 3.6: This will allow you to run the project in an isolated environment with the specific version of Python you need.
OR

2. Use a version manager like pyenv or conda: These tools let you switch between different Python versions on your system, so you can run your Python 3.6 project without affecting other projects.
OR 

3. Run the project in a Docker container: This allows you to run the project in an isolated environment with the specific version of Python you need.

OR 

4. Simply use poetry by following this link 
https://stackoverflow.com/questions/60580113/change-python-version-to-3-x
