### ISSUE TITLE
Passing through setup.py options

### ISSUE THREAD

**Issue by henryiii** [kennethreitz/pipenv#730]
Pip has an (ugly) mechanism for passing through arguments. When using SciKit Build, these [arguments are used](http://scikit-build.readthedocs.io/en/latest/usage.html#command-line-options) to control the CMake build. So, for example:

```bash
setup.py install -- "-DCMAKE_MY_ARGUMENT=ON"
```

[can be handled](https://pip.pypa.io/en/stable/reference/pip_install/#per-requirement-overrides) as

```
pip install . --install-option "--" --install-option "-DCMAKE_MY_ARGUMENT=ON"
```
(pip also offers a `--global-option`, but don't provide much info on the difference; I assume this also gets applied to dependencies?)

pipenv doesn't offer a way to pass this through to pip, as far as I can tell. This would make the most sense with `.` installs, since build arguments are not be stored (AFAIK) in the Pipfile.

**Comment by kennethreitz** [comment]
all of pip's command line options are passable as environment variables.

**Comment by kennethreitz** [comment]
Use those instead.

**Comment by kennethreitz** [comment]
https://pip.pypa.io/en/stable/user_guide/#environment-variables

**Comment by henryiii** [comment]
Great, I didn't know that, thanks! Sorry for the noise.

**Comment by kennethreitz** [comment]
No worries at all!

**Comment by kennethreitz** [comment]
I'd like to add a secion in the docs for this. Could you paste your example in here when you're done?

**Comment by henryiii** [comment]
```bash
PIP_INSTALL_OPTION="-- -DCMAKE_BUILD_TYPE=Release" pipenv install --verbose -e .
```
would be an example. At one point I had to add `--skip-lock` to get pipenv not to crash when installing the local package, but that seems to be fine now and can't reproduce.

For some reason, I have to do `pipenv install` first to get the Pipfile contents to be used, though it seems like it should install requirement first automatically when a Pipfile or Pipfile.lock exists in the current directory? It matters to be because scikit-build packages can't list scikit-build as a dependency to pip, since pip uses setup() which is replaced by scikit-build.

**Comment by cLupus** [comment]
Is there a way to give these arguments in the `Pipfile`?

**Comment by uranusjr** [comment]
@cLupus No.

**Comment by mehes-kth** [comment]
How about either an `[env]` section or an `{..., env=..., ...}` keyword?
