### ISSUE TITLE
Support for specific package versions?

### ISSUE THREAD

**Issue by mbluemer** [kennethreitz/pipenv#735]
Okay maybe I'm just blind but I read through the documentation and spent time searching through the closed issues and couldn't find anything about installing specific package versions. Just something simple like `pipenv install flask=0.12.2`.

(edit) Removed extraneous comments

**Comment by kennethreitz** [comment]
`==`

**Comment by kennethreitz** [comment]
https://docs.pipenv.org/basics.html#specifying-versions-of-a-package

**Comment by kennethreitz** [comment]
same as pip
