### ISSUE TITLE
pipenv shell, then `deactivate` should display warning

### ISSUE THREAD

**Issue by cs01** [kennethreitz/pipenv#736]
I've been a virtualenv/wrapper user for a while, and am looking forward to fully converting to pipenv! Super valuable work you're doing.

The following was a little surprising to me. I should have been typing `exit` to exit the spawned shell, but typed `deactivate` like I normally do. A warning message telling me that running `deactivate` in the spawned shell is pointless would have been helpful.

```bash
>> pipenv shell
Spawning environment shell (/bin/bash).
source /home/csmith/.local/share/virtualenvs/gdbgui-VyTVnvfA/bin/activate
/home/csmith/git/gdbgui csmith@csmith-ubu(master*)
>> source /home/csmith/.local/share/virtualenvs/gdbgui-VyTVnvfA/bin/activate
(gdbgui-VyTVnvfA) /home/csmith/git/gdbgui csmith@csmith-ubu(master*)
>> deactivate  # would be good to see a warning here telling me I probably wanted to type `exit`
/home/csmith/git/gdbgui csmith@csmith-ubu(master*)
>> pipenv shell  # maybe another warning message here
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
/home/csmith/git/gdbgui csmith@csmith-ubu(master*)
```

**Comment by kennethreitz** [comment]
we’ll introduce a message when spawning the subprocess

**Comment by ConorSheehan1** [comment]
I can't seem to see this warning warning when I open a shell.

    $ pipenv --version
    pipenv, version 2018.7.1

    $ pipenv shell
    Launching subshell in virtual environment…
     . /home/$user/.local/share/virtualenvs/pipenv_test-dI42JGRt/bin/activate
    $  . /home/$user/.local/share/virtualenvs/pipenv_test-dI42JGRt/bin/activate
    (pipenv_test-dI42JGRt)$ exit

Would it make sense to add an alias when inside a pipenv shell so that deactivate just runs exit, since that seems to be the expected behaviour?

**Comment by hupili** [comment]
@ConorSheehan1  , same here. One line will make the new user onboarding easier:

```
alias deactivate='echo Invalid operation. If you want to exit virtualenv spawned by pipenv, just "exit" this subshell'
```

As first time user, I also overlooked the message "Launching **subshell** in virtual environment". I guess few users can notice we are in "subshell", unlike usual virtualenv. For those playing around, `pipenv shell` followed by `deactivate` leads to confusion.
