### ISSUE TITLE
document how to get help on pipenv command arguments

### ISSUE THREAD

**Issue by cs01** [kennethreitz/pipenv#737]
For example, `pipenv install` takes various arguments, and they are documented if you run `pipenv install -h`, but the `-h` flag is not documented (I eventually guessed and it worked). 

It would also be more intuitive if pip's help pattern was followed, i.e. `pipenv help install`.

**Comment by kennethreitz** [comment]
—help is documented

**Comment by cs01** [comment]
Sort of, it doesn't indicate that it displays more detailed help for each command

**Comment by kennethreitz** [comment]
i think we're good here.
