### ISSUE TITLE
Always ignore top-level system components when rendering `pipenv graph`?

### ISSUE THREAD

**Issue by ncoghlan** [kennethreitz/pipenv#747]
`pipenv graph` currently displays the dependency graph for everything visible in the environment, *including* the contents of system site-packages. 

I'm working around that by doing:

```
$ pew toggleglobalsitepackages
Disabled global site-packages
$ pipenv graph
...
$ pew toggleglobalsitepackages
Enabled global site-packages
```

I'm wondering if it may make more sense to just always restrict the top level graph entries to items listed in `Pipfile`, and have two separate sections at the end for:

- additional local packages (included in `pip list --local`, but not in `Pipfile.lock`)
- additional global packages (included in `pip list`, but not in `pip list --local`)

I'm also thinking it would be reasonable to just not show the global packages at all - when we turn that option on, we usually know why we're doing it.

**Comment by kennethreitz** [comment]
not sure how feasible this is — will investigate

**Comment by kennethreitz** [comment]
I'm down for removal of anything in site-packages.

**Comment by kennethreitz** [comment]
easier said than done.

**Comment by ncoghlan** [comment]
If it's a pain to implement, I'd be fine with a "no change" resolution - turning site-packages access off temporarily is straightforward and explicit, and having `pipenv graph` spit out multiple screenfuls of text may help remind folks just why "no access to system packages" is the default behaviour.

**Comment by kennethreitz** [comment]
Sounds good to me :)
