### ISSUE TITLE
pipenv commands fail after pipenv --update (doesn't recognize old console_scripts)

### ISSUE THREAD

**Issue by knowsuchagency** [kennethreitz/pipenv#750]
OS: Mac OS Sierra

After updating to the latest version of pipenv, 8.1.4, normal commands stopped working.
(sorry, I no longer have the full stacktrace)

I found out it was because the console script didn't get updated:

```python
#!/usr/local/opt/python3/bin/python3.6
# EASY-INSTALL-ENTRY-SCRIPT: 'pipenv==7.9.2','console_scripts','pipenv'
__requires__ = 'pipenv==7.9.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pipenv==7.9.2', 'console_scripts', 'pipenv')()
    )
```

Replacing `7.9.2` with `8.1.4` worked, but the better solutions seemed to be `pip3 install -U --force-reinstall pipenv`, which solved the problem by replacing the console script with the new one altogether. Everything is working swimmingly again!

Thanks for all you do, @kennethreitz

**Comment by kennethreitz** [comment]
thanks for the report!
