### ISSUE TITLE
Using matplotlib

### ISSUE THREAD

**Issue by savovs** [kennethreitz/pipenv#754]
I get this error when I try using matplotlib: "Python is not installed as a framework." Is there a way the env can be set up as suggested in **[this post](https://github.com/pyenv/pyenv-virtualenv/issues/140)**?

**Comment by kennethreitz** [comment]
this is not an pipenv issue.

**Comment by savovs** [comment]
Thank you for the quick reply. I found a solution to the problem if anyone else encounters it: https://github.com/JuliaPy/PyCall.jl/issues/218#issuecomment-267558858
