### ISSUE TITLE
pipenv shell & tmux

### ISSUE THREAD

**Issue by dfee** [kennethreitz/pipenv#755]
Something about `pipenv shell` is throwing off my tmux. Simply doing: `source $(pipenv --venv)/bin/activate` seems to be enough for them to get along – and get me in the virtualenv.

What was the reasoning behind launching a separate a separate shell vs. a `pipenv activate` command?

**Comment by dfee** [comment]
Likely has something to do with an `eval` situation as otherwise a subprocess can't see envvars...

**Comment by dfee** [comment]
By the way, it has nothing to do with being in a subshell, or being in an interactive subshell. As doing either of those things separate from `pipenv shell` allows tmux to play along nicely.

(this was all discovered using vim-tmux-navigator – where bound keys defined in ~/.tmux.conf weren't working).

**Comment by kennethreitz** [comment]
you'll have to look through the pew docs to discover where the descrepency lies. I'm glad you found a workaround, though!
