### ISSUE TITLE
Passing https relevant general options to pip

### ISSUE THREAD

**Issue by numshub** [kennethreitz/pipenv#758]
I tried to pass the --trusted-host flag to pipenv install but it generates an Error.
The following pip general options should be supported:
--trusted-host
--cert
--client-cert

**Comment by kennethreitz** [comment]
use environment variables.

**Comment by kennethreitz** [comment]
trusted host is automatically passed.

**Comment by numshub** [comment]
I still get an error with trusted-host. Environmental variables work but on second thought a config file in the virtual environment is the best approach for such special cases.

**Comment by kennethreitz** [comment]
like i said, trusted-host is automatically passed.
