### ISSUE TITLE
documentation links broken

### ISSUE THREAD

**Issue by yarko** [kennethreitz/pipenv#759]
Shocked at the version number jumps `pipenv` has made lately, I updated and `pip --envs` guided me to what I wanted (locating `venvs` *with* a project);
```
$ pipenv --envs
The following environment variables can be set, to do various things:

  - PIPENV_SHELL_FANCY
  - PIPENV_VENV_IN_PROJECT
  - PIPENV_COLORBLIND
  - PIPENV_NOSPIN
  - PIPENV_PIPFILE
  - PIPENV_DEFAULT_PYTHON_VERSION
  - PIPENV_DONT_LOAD_ENV
  - PIPENV_YES
  - PIPENV_MAX_SUBPROCESS
  - PIPENV_MAX_DEPTH
  - PIPENV_VIRTUALENV
  - PIPENV_USE_SYSTEM
  - PIPENV_USE_HASHES
  - PIPENV_SKIP_VALIDATION
  - PIPENV_DOTENV_LOCATION
  - PIPENV_HIDE_EMOJIS
  - PIPENV_TIMEOUT
  - PIPENV_INSTALL_TIMEOUT
  - PIPENV_DONT_USE_PYENV
  - PIPENV_SHELL

You can learn more at:
   http://docs.pipenv.org/en/latest/advanced.html#configuration-with-environment-variables
```

Problem is:   that link is broken ("Sorry - that page doesn't exist").

Ok - no problem.   I'll search for "configuration with environment variables" - great!  Two links found;  one that looks like a TOC entry, and one like the section I want.   But - **both** those links are broken too.

What gives?

Well, it turns out that taking the `/en/latest` out of any of those links gets you to the desired place.

And (in general!)  you might want to avoid locking links on to the *en* encoding, anyway.

**Comment by kennethreitz** [comment]
thanks! this is for ssl reasons. we'll update the link.

**Comment by kennethreitz** [comment]
fixed in master

**Comment by nvtkaszpir** [comment]
Looks like it is still broken in pipenv 0.9.3:
```
https://docs.pipenv.org/advanced.html#configuration-with-environment-variables
```
should be:

```
https://docs.pipenv.org/advanced/#configuration-with-environment-variables
```

**Comment by kennethreitz** [comment]
@nvtkaszpir send a pull request :)
