### ISSUE TITLE
.env file evaluation appends original string

### ISSUE THREAD

**Issue by aventurella** [kennethreitz/pipenv#762]
Possibly 2 issues? When using a `.env` file, a value placed in the form of:

```
PYTHONPATH=$PYTHONPATH:$PWD/django/project:$PWD/django/project/vendor
```

Does not evaluate the variables. It sets it literally not the evaluated version.

```python
>>> import os
>>> os.environ['PYTHONPATH']
'${PYTHONPATH}:${PWD}/django/project:${PWD}/django/project/vendor'
```

When specifying the values as:
```
PYTHONPATH=${PYTHONPATH}:${PWD}/django/project:${PWD}/django/project/vendor
```

`PWD` and `PYTHONPATH` are evaluated, but the original string is still prepended, leaving something like this as the final value that is set as the value of `PYTHONPATH`

```python
>>> import os
>>> os.environ['PYTHONPATH']
'${PYTHONPATH}:${PWD}/django/project:${PWD}/django/project/vendor:/Users/aventurella/github/my_repo/django/project:/Users/aventurella/github/my_repo/django/project/vendor'
```

**Comment by kennethreitz** [comment]
this is an issue with envdir, not with pipenv

**Comment by kennethreitz** [comment]
you should not be overriding pythonpath with .env. it's for application secrets.

**Comment by AlJohri** [comment]
@aventurella just override the PYTHONPATH, you don't need to append/prepend it. it doesn't affect anything

**Comment by aventurella** [comment]
It was only for dev purposes, setting up new devs on a project. Docker `ENV` handles the production setting. We can also just run the dev's inside the container, but I was experimenting on ways to keep them out of it. It's 6 of 1 half dozen of the other in reality. We have tooling that drops them in easy enough during dev. Again for production this doesn't matter. And it also turns out it works just fine even if `envdir` keeps the literal `${PWD}/django/project`

**Comment by matthiasLevy** [comment]
Hy !
Actually, I would need such an option as well, but I'm not an expert in virtual env etc.
My need is actually :
PYTHOPATH=$MYPROJECTBASEDIR
But same issue, it is not resolved. Could anyone help please ?
Thanks in advance...

**Comment by AlJohri** [comment]
You can use this:
```
PYTHOPATH=.
```

And then be sure to run all code from `$MYPROJECTBASEDIR`. For example, if you have a scripts folder, be sure to run `python /scripts/myscript.py`.

**Comment by matthiasLevy** [comment]
Thanks !
It is not my favorite option, but does the job perfectly.
Regards,
M.

**Comment by AlJohri** [comment]
Another option is to turn your code into a python package and install it using pip. For example you can run `pip install -e .`. This way you can use the code without modifying your PYTHONPATH.

**Comment by matthiasLevy** [comment]
This is very interesting. Thanks again, it will certainly bu useful soon.
