### ISSUE TITLE
pipenv install is slow on Windows

### ISSUE THREAD

**Issue by phantasia15** [kennethreitz/pipenv#766]
## System

Windows 7 SP1 64bit, python 3.6.2, pipenv 8.2.0

## Description 
With a clean virtual enviroment, installing just a single package take more than 1 minute to complete.

```
$ time pipenv install raven
Installing raven…
Collecting raven
  Using cached raven-6.2.1-py2.py3-none-any.whl
Installing collected packages: raven
Successfully installed raven-6.2.1

Adding raven to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!

real    1m29.588s
user    0m0.000s
sys     0m0.000s
```
Most of time is spent on `Locking [packages] dependencies…`
However, If I run `pip install` inside a `pipenv shell`, it is blazingly fast and finishes almost instantly.

**Comment by kennethreitz** [comment]
not sure there's much we can do here.

**Comment by phantasia15** [comment]
I just tried installing pipenv in a Windows 7 VM and it was fast as expected!!!

Seems like there is something wrong with my computer.
I will try to figure out what is causing this problem.

**Comment by phantasia15** [comment]
Well, after a little debugging, I finally figured out my problem.
There was some problem with the default DNS server that slowed down `requests.get()` call when `resolve_dependecies()`
After having changed the DNS server to Google one (8.8.8.8), it works fast as expected.

**Comment by techalchemy** [comment]
I just wanted to comment/ask -- in the VM, did you run 'install' in git-bash? I sometimes have problems with posix emulation being laggy

**Comment by phantasia15** [comment]
@techalchemy No, I just used vanilla CMD in the Win 7 VM. 
I  also have problems running pipenv with posix emulation too (eg: pipenv shell doesn't work,etc).
I only used it(Cygwin-bash) in the first post because I needed to measure the total time to put it into the bug report.

**Comment by erinxocon** [comment]
pipenv runs great on the Ubuntu Subsystem for Windows 10

**Comment by kennethreitz** [comment]
agreed :)
