### ISSUE TITLE
Install http://docs.pipenv.org/en/latest/ to use this plugin.

### ISSUE THREAD

**Issue by kedare** [kennethreitz/pipenv#768]
Hello.

After installing pipenv on OSX, I can't use it, it's only returning 

```
Install http://docs.pipenv.org/en/latest/ to use this plugin.
```
(And the link point to a 404)

```
~ pipenv
Install http://docs.pipenv.org/en/latest/ to use this plugin.
~ pip freeze | grep pipenv
pipenv==8.0.1
~ python -V
Python 3.6.1
```

Is there something specific to do ?
I'm using fish and pyenv also.

Thanks

**Comment by nateprewitt** [comment]
@kedare I'm not entirely sure what would be causing that. Could you upgrade to 8.2.0 and see if the message still occurs?

**Comment by kedare** [comment]
Ok apparently the problem is from the fish pipenv module.

Also looks like the readme speaks about it :)

https://github.com/fisherman/pipenv#mac-os

I'm gonna try the solution

**Comment by nateprewitt** [comment]
Alright, thanks for the update @kedare. I'm closing this since it doesn't appear to be an issue with pipenv itself.

**Comment by kedare** [comment]
I confirm this fixed the issue :)

Sorry for the noise, my fault, I didn't think about searching in the fish plugin ( I forgot I had it installed )
