### ISSUE TITLE
Managing Docker building with Pipenv

### ISSUE THREAD

**Issue by kedare** [kennethreitz/pipenv#769]
Hello :)

Something that could be really amazing would be the possibility to completely manage Docker containers building with Pipenv.

Currently, we still need to manage the Dockerfile manually, for example the official Python docker image still requires a requirements.txt (even emtpy), here is what I use :

```
FROM python:3.6.1-onbuild

RUN pip install pipenv
RUN pipenv install
RUN pipenv run python manage.py collectstatic --noinput
```

Right now I'm doing like this, but in this case I still have to :

 - Hardcode the Python version in the Dockerfile
 - Put an empty requirements.txt

Also this is less efficient as I'm installing pyenv and then creating the virtualenv for my application (So some libraries are duplicated outside and inside the virtualenv)
Also there could be a way from inside the container to not have to prefix all the commands by ```pyenv run```

**Comment by kennethreitz** [comment]
you should be providing a `Pipfile` and a `Pipfile.lock` to your Docker image. 

You should also run `pipenv install --system`

**Comment by kennethreitz** [comment]
I like the idea of providing a pipenv-ready Docker image, with all pyenvs installed. Might look into that today.

**Comment by kennethreitz** [comment]
Working on it! https://github.com/kennethreitz/pipenv/blob/master/Dockerfile
