### ISSUE TITLE
pipenv version not updated 

### ISSUE THREAD

**Issue by PlrEx** [kennethreitz/pipenv#774]
Hi, 
Upgraded to latest pipenv but pipenv --version shows the same old version
![screenshot_2017-09-29_18-27-02](https://user-images.githubusercontent.com/18421312/31017794-65928dea-a547-11e7-8d22-486178b692a1.png)

I am using Manjaro Linux.

**Comment by kennethreitz** [comment]
might have to upgrade it the same way you installed it. only so much we can do here.
