### ISSUE TITLE
Error when specifying python version

### ISSUE THREAD

**Issue by marcrleonard** [kennethreitz/pipenv#775]
I tried doing this in a few different locations on my machine with the same result. 

![image](https://user-images.githubusercontent.com/24658895/31023150-35e60a1c-a4f8-11e7-8f68-57907046749e.png)

**Comment by kennethreitz** [comment]
python.exe

**Comment by marcrleonard** [comment]
Wow. Duh. Stuck in linux land. Thank you, Kenneth.
