### ISSUE TITLE
pipenv shell launches Powershell from command prompt on Windows

### ISSUE THREAD

**Issue by uranusjr** [kennethreitz/pipenv#781]
Not sure if this is a feature, but I’d expect the subshell to match the parent.

**Comment by erinxocon** [comment]
Not a feature, just functionality for windows.  We know everyone has powershell installed on their machines so we can use that shell.  Windows doesn't have an environment variable for the current shell like unix does, so we don't know what shell you are coming from when spawning a new shell.

**Comment by erinxocon** [comment]
This is actually due to the way `pew` works not `pipenv`!

https://github.com/berdario/pew/blob/master/pew/pew.py#L187

**Comment by erinxocon** [comment]
@uranusjr may I recommend [cmder](http://cmder.net/)as a replacement terminal emulator for windows?  It can run `powershell`, or `cmd` and `pew` does support it out of the box.  Running `pipenv` using `cmder` preserves the shell I am using, `powershell` or `cmd`, when spawning a new process!

**Comment by uranusjr** [comment]
@erinxocon Thanks for the suggestion. I’m a happy ConEmu user and probably won’t switch unless I have to, but knowing cmder works maybe I can somehow configure ConEmu to work as well. 🤞

**Comment by erinxocon** [comment]
Cmder uses ConEmu!

> Think about cmder more as a software package than a separate app. All the magic is happening through Conemu. With enhancements from Clink.

**Comment by erinxocon** [comment]
You could mimic Cmder though by setting the proper env variables.  You'd have to look at the pew source code to see what variables they check.

**Comment by erinxocon** [comment]
I've submitted a pull request to pew to preserve the shell you are using on windows.  Once it's incorporated it should propagate to pipenv! 💯

**Comment by uranusjr** [comment]
Wooo this is so clever… Looking forward to it.
