### ISSUE TITLE
Editable install not detecting setup.py

### ISSUE THREAD

**Issue by mblayman** [kennethreitz/pipenv#784]
I'm playing with a Pyramid cookiecutter template (specifically, https://github.com/Pylons/pyramid-cookiecutter-alchemy), and pipenv is having trouble with the `-e` option.

```bash
(pyramid-kalVa7_8) ➜  my_app git:(master) pipenv install -e .
Installing -e .…
⠴
Error:  An error occurred while installing -e .!
Directory '.' is not installable. File 'setup.py' not found.

(pyramid-kalVa7_8) ➜  my_app git:(master) ls
CHANGES.txt     MANIFEST.in     README.txt      development.ini my_app production.ini  pytest.ini      setup.py
(pyramid-kalVa7_8) ➜  my_app git:(master) pipenv --version
pipenv, version 8.2.4
```

The behavior that I'd hope to see is 1) all of the Pyramid project dependencies are installed into the environment and 2) the Pipfile is updated appropriately.

For context, this is a pipenv virtualenv running Python 3.6 and I ran `pipenv shell` prior to running the above shell lines.

**Comment by kennethreitz** [comment]
cannot reproduce

**Comment by AlJohri** [comment]
make sure you're using the right Pipfile. it's likely you first ran it in the top level directory and then cd'ed into the actual project folder and tired to run it again. pipenv will look for the Pipfile in the directory above and there is no setup.py file at that level

**Comment by mblayman** [comment]
@AlJohri you're right. That was it. I thought pipenv would look up directories for the Pipfile so I was guessing it would be able to resolve everything. Thanks for the help!
