### ISSUE TITLE
default python installation - not as advertised

### ISSUE THREAD

**Issue by yarko** [kennethreitz/pipenv#787]
on Ubuntu 16.04 - default _system_ python is 3.5;  my `PATH` default python is python 3.6;

```
$ pip shell
```
in a new directory will install python-2.7:  neither the system's default python installation, nor the default for `python` in my path.

This is contrary to the end of this documentation section:

https://docs.pipenv.org/basics.html?highlight=default%20python#specifying-versions-of-python

Note:  `/usr/bin/python` _is_ linked to `/usr/bin/python2.7`  _but_ that is preceded in my path by `/usr/local/bin/python` (linked to `/usr/local/bin/python3.6`).

**Comment by erinxocon** [comment]
Can you echo your whole PATH variable out?  I believe this is an issue with the PATH not pipenv.

**Comment by yarko** [comment]
```
$ echo $PATH
/home/yarko/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by kennethreitz** [comment]
you can set `PIPENV_DEFAULT_PYTHON_VERSION`
