### ISSUE TITLE
Updating from github with ssh key with passphrase

### ISSUE THREAD

**Issue by 5uper5hoot** [kennethreitz/pipenv#791]
Hi,

First just want to say thanks for pipenv! It's a fantastic tool.

I have noticed an issue when pipenv gets one of my private packages from github. I have an ssh key with a passphrase. In this example, I update 3 packages off github with `pipenv update` and it will ask for my passphrase 3 times immediately. If I type my password 3 times, the first password is hidden, the next two display on subsequent lines in clear text and the updates work fine:

![image](https://user-images.githubusercontent.com/20659309/31052895-2cc27052-a6dc-11e7-8bda-7fc49d5332e3.png)

However, if I just type in the password once and fail the next two passwords by pressing enter 2 more times, everything seems to work as it should when pipenv installs the initially failed dependencies. It asks for passphrases one at a time:

![image](https://user-images.githubusercontent.com/20659309/31052912-a587a296-a6dc-11e7-9b5a-15bdd37d8b3f.png)

This is Ubuntu 17.04.

Hope this helps and thanks again for pipenv!

**Comment by kennethreitz** [comment]
this is not currently supported.

**Comment by 5uper5hoot** [comment]
I see that the issue comes from concurrently there is a `--sequential` flag for `pipenv install`, is it possible to have one for `pipenv update` as well?

**Comment by erinxocon** [comment]
I actually just ran into this issue as well.  Thanks for adding the PR @5uper5hoot!

**Comment by 5uper5hoot** [comment]
@erinxocon No probs! Is there any way that pipenv can recognise that a package needed a passphrase or some user input the first time that it is installed into the environment? Then, perhaps an identifier can be saved against the package in the Pipfile which would allow it to be distinguished from packages that don't need a pw to be entered. Then, the install/update can be split into two parts. First, all packages that don't have the user input identifier are installed concurrently. Then, packages that have the input required identifier are installed sequentially.

**Comment by kennethreitz** [comment]
this likely won't get supported, but we'll see what we can do

**Comment by erinxocon** [comment]
@kennethreitz reason why this is still open?
