### ISSUE TITLE
Doc's search results links have wrong prefix

### ISSUE THREAD

**Issue by WhyNotHugo** [kennethreitz/pipenv#801]
Search results in the docs seem to have the wrong prefix, eg:

https://docs.pipenv.org/search.html?q=requirements.txt&check_keywords=yes&area=default

The first result points to https://docs.pipenv.org/en/latest/basics.html?highlight=requirements.txt, but should point to https://docs.pipenv.org/basics.html?highlight=requirements.txt (note the extra `en/latest/` in the first link).

**Comment by erinxocon** [comment]
@kennethreitz will have to address this in the RTD settings.

**Comment by kennethreitz** [comment]
nothing we can do about that right now, but thanks for the report!
