### ISSUE TITLE
Make more clear that you need to update pip to use pipenv

### ISSUE THREAD

**Issue by sametmax** [kennethreitz/pipenv#803]
Trying to get install pipenv in a docker env, I got:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1006, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 695, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (pip 8.1.1 (/usr/lib/python3/dist-packages), Requirement.parse('pip>=9.0.1'))
```

This of course no longer happens once I run `pip install  --upgrade pip`

While I understand it's probably not appropriate to list pip as a dependency and require an upgrade, there should be a big warning in the installation section of the README and the doc with appropriate advices.

One possible solution: it's easy to `pip install pipsi --user` and then `python -m pipsi pipenv`. You never have to worry about having the bin in PATH, or to have pip at the proper version.

**Comment by erinxocon** [comment]
Hi @sametmax thanks for your suggestion!  I don't think a large message is needed, the traceback is pretty explanatory.  I've not experienced this issue in the many months I've been using pipenv.  Whenever I'm creating a new environment I do `pip install --uprgrade pip`.  Most users have the most recent pip installed.  I'm gonna add a small note to the installation section and close this issue!

**Comment by erinxocon** [comment]
After looking at the markup for the docs, I don't really see a good place for it.  I'm not gonna add this to the docs unless @kennethreitz wants to!
