### ISSUE TITLE
Specify pip version when executing pipenv install --system

### ISSUE THREAD

**Issue by Gronis** [kennethreitz/pipenv#812]
Is it possible to specify which pip version that is used when installing to system? If I have both pip2 and pip3 installed and run `pipenv install --system`, then everything is installed using pip2 even if Pipfile has 
```
[requires]
python_version = '3.6'
```
Which is an indicator that pipenv should install packages using pip3

**Comment by kennethreitz** [comment]
it is not.

**Comment by iScrE4m** [comment]
If not respecting pipfile's python_version, it should definitely accept --three or --python arguments.

**Comment by rainyday** [comment]
In light of the release of pip 10, the decision to close this ticket with no resolution seems laughable shortsighted.

**Comment by pd0wm** [comment]
Would you accept a pull request where the `--two`/`--three` flag decides whether to use `pip2` or `pip3`? Not setting any flag would use `pip`, and fall back to system default.

**Comment by leandropineda** [comment]
I'm having the same issue trying to install `pip` dependencies while building a `Docker` image. The workaround was to link `/usr/local/bin/pip` to `pip3`:

```bash
mv /usr/local/bin/pip /usr/local/bin/pip2
ln -s /usr/local/bin/pip3 /usr/local/bin/pip
```
