### ISSUE TITLE
Pipfile not capturing all necessary dependencies?

### ISSUE THREAD

**Issue by philipobrien** [kennethreitz/pipenv#820]
I'm working on a project locally on OSX, clean creation of env via pipenv, all necessary packages stored via `pipenv install xxx` so the `Pipfile` gets updated accordingly. I'm using Python 2.7.14. I am now trying to replicate this on a VM running Ubuntu 16.04. 
I start from a basic Ubuntu image, then run

```
sudo apt install python-minimal
sudo apt install python-pip
sudo pip install pipenv
```

clone the git repo containing my project, and then when I try install using `pipenv` I run into various errors. 

The first being
```
⠋Warning: it looks like pew is not in your PATH. We cannot continue until this is resolved.
```
which I get around using [this SO suggestion](https://stackoverflow.com/questions/46308150/pipenv-install-gives-pew-is-not-in-your-path)
```
sudo -H pip install pew
```

then the normal `pipenv install` and `pipenv shell` seems to work fine, until I then go to actually run my code and I get

```
ImportError: No module named functools32
```

which if I try manually install just leads down the rabbit hole of more dependencies missing. I'm obviously approaching this incorrectly, but I'm not sure how.

These outputs might help

```
$ which python
> /home/ubuntu/.local/share/virtualenvs/myproject-etz0SGRU/bin/python
$ python --version
Python 2.7.12
```

**Comment by kennethreitz** [comment]
sounds like your PATHS are not setup correctly.

**Comment by kennethreitz** [comment]
there is no issue here, re depend on everything we depend on.

**Comment by philipobrien** [comment]
I got it to work by manually installing (i.e. with `pipenv`) `functools32`, `backports-weakref`, and `mock`. 

When running code from the pipenv shell, if a dependency has not been installed via pipenv, but exists elsewhere on the PATH, can it still be used, i.e. did I just happen to have these installed elsewhere on my mac, but not on the VM?
