### ISSUE TITLE
An error occurred while installing <non-pypi packagename>

### ISSUE THREAD

**Issue by commandtab** [kennethreitz/pipenv#823]
Using pipenv version 8.2.6 with a Pipfile containing references to packages that are served from non-PyPi `[[source]]`s results in a recoverable error. Given a Pipfile like this, where `requests` comes from the public PyPi and (for the sake of example) `secret-sauce` comes from `on-prem-pypi.company.com`:

```
[[source]]
url = "https://on-prem-pypi.company.com"
verify_ssl = true

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
requests = "*"
secret-sauce = "==1.2.3"
```

Running `pipenv install` results in output like:

```
Pipfile.lock not found, creating…
Locking [packages] dependencies…
Updated Pipfile.lock (a1679f)!
Installing dependencies from Pipfile.lock (a1679f)…
An error occurred while installing secret-sauce==1.2.3! Will try again.
Installing initially–failed dependencies…
Success installing secret-sauce==1.2.3! — 00:00:00
```

It seems as though the initial failure was because pipenv failed to find `secret-sauce` on PyPi, which makes sense, but would it be possible or pipenv to check all sources before emitting the error? It's unsettling to see errors when in fact everything is fine once the appropriates sources are contacted.

Or, perhaps even better and more secure: Is it possible to declare that `secret-sauce` _only_ comes from `on-prem-pypi.company.com` to avoid contacting other sources entirely? Without such a declaration, it would be possible for an attacker to claim `secret-sauce` after-the-fact on PyPi and potentially run unexpected code on systems that expected `secret-sauce` to be fetched from a different source.

Thanks for a great project!

**Comment by kennethreitz** [comment]
yes, it's in the documentation: https://docs.pipenv.org/advanced.html#specifying-package-indexes

**Comment by commandtab** [comment]
Ahh! Reading. It's important. Thank you!

**Comment by jaiwardhan** [comment]
Update: The link has been moved to: [http://pipenv.readthedocs.io/en/latest/advanced/#specifying-package-indexes](url)

**Comment by Ymbirtt** [comment]
Whoops! Looks like it's moved again. Check out https://docs.pipenv.org/advanced/#specifying-package-indexes

**Comment by OrangeDog** [comment]
This appears to also happen to VCS dependencies in 2018.05.18.
Is there a way to fix that?

There might be another cause, but I haven't found it yet.

**Comment by uranusjr** [comment]
@OrangeDog There is not a real issue here in the first place. What exactly is happening to you?

**Comment by OrangeDog** [comment]
I get the "Will try again" message for my VCS dependencies, then at the end "Installing initially-failed dependencies" and then they work.
As I said, it might be one of the other VCS-related bugs in the currently released version instead - I'm still investigating.

**Comment by uranusjr** [comment]
If they work, there’re no problems. The message is only for courtesy (it is not even a warning) to let you know what happened. There is nothing to fix.

**Comment by techalchemy** [comment]
I’m kind of sure this was a race condition of some kind. Either way this technically does work. It might work better in master
