### ISSUE TITLE
pipenv is adding empty lines to my Pipfile

### ISSUE THREAD

**Issue by mhubig** [kennethreitz/pipenv#827]
Pipenv is adding empty lines to my Pipfile. Im starting with this Pipfile:

<img width="812" alt="screenshot 2017-10-04 12 35 39" src="https://user-images.githubusercontent.com/219704/31171699-f2bbdf5c-a900-11e7-8712-ec74bdc04e6b.png">

Now im running `pipenv install --dev flake8-docstrings` and the Pipfile get's two extra empty lines:

<img width="812" alt="screenshot 2017-10-04 12 35 47" src="https://user-images.githubusercontent.com/219704/31171815-639e3332-a901-11e7-8e35-25578e6c7fb4.png">

Now every time I repeat the command (`pipenv install --dev flake8-docstrings`) the Pipfile get's one extra empty line:

<img width="812" alt="screenshot 2017-10-04 12 35 57" src="https://user-images.githubusercontent.com/219704/31171872-9d9226e8-a901-11e7-8af4-9a377c2a4764.png">

<img width="812" alt="screenshot 2017-10-04 12 36 09" src="https://user-images.githubusercontent.com/219704/31171878-a520441c-a901-11e7-95eb-f57aaa0d2f1a.png">

<img width="812" alt="screenshot 2017-10-04 12 36 19" src="https://user-images.githubusercontent.com/219704/31171884-ae2de49c-a901-11e7-9703-c6da26ab15ae.png">

The same happens if I install something without the `--dev` flag.

**Comment by kennethreitz** [comment]
this is known.

**Comment by kennethreitz** [comment]
planning to fix.

**Comment by kennethreitz** [comment]
the solution is to always strip large sections of empty lines when writing to the pipfile, even if they're intentional.

**Comment by kennethreitz** [comment]
this is a side-effect of using `contoml` for our toml library, which preserves code comments — so, it's worth it.

**Comment by kennethreitz** [comment]
fixed in master branch
