### ISSUE TITLE
pipenv run doesn't set the $VIRTUAL_ENV environment variable

### ISSUE THREAD

**Issue by tgrant59** [kennethreitz/pipenv#829]
## Summary 
When you use the Pipenv shell, it sets an environment variable, `VIRTUAL_ENV`. This is relied upon by some 3rd party packages, namely Zappa, to work properly. 

But when you use `pipenv run` to run Zappa, it can't find the `VIRTUAL_ENV` variable, and ends up not working correctly.

I think that both commands should maintain the same execution environment for subcommands, including having the same set of  environment variables.

### Within shell 
```
$ pipenv shell
$ echo $VIRTUAL_ENV
>>> /Users/user/.local/share/virtualenvs/venv-2ki7vM9W
```

### Using the `run` command
```
$ pipenv run echo $VIRTUAL_ENV
>>>
```

**Comment by nonylene** [comment]
Thi is because  `activate_this.py` does not set `VIRTUAL_ENV`. I have opened a pull request on pypa/virtualenv ( https://github.com/pypa/virtualenv/pull/1057  ), but no response yet.

**Comment by kennethreitz** [comment]
this is not a pipenv issue

**Comment by frankier** [comment]
Workaround: replace $VIRTUAL_ENV with `pipenv --venv`
