### ISSUE TITLE
How to deactivate current environment entered by `pipenv shell`?

### ISSUE THREAD

**Issue by jeyraof** [kennethreitz/pipenv#84]
```bash
❯ python -V
Python 2.7.10

❯ pipenv shell
Spawning environment shell (/bin/zsh).
source /Users/jeyraof/Work/fashion-keyword/.venv/bin/activate

❯ source /Users/jeyraof/Work/fashion-keyword/.venv/bin/activate

(fashion-keyword)❯ python -V
Python 3.6.0

(fashion-keyword)❯ deactivate

❯ python -V
Python 3.6.0

❯ exit

❯ python -V
Python 2.7.10
```

`exit` command is correct way to deactivate current environment?

**Comment by kfirbreger** [comment]
pipenv starts a shell session with the virtualenv instead of changing the bathing in the current shell session. That is why deactivate does not work. you need to exit the shell session. the `exit` command or CTRL-d will do the trick.

**Comment by jeyraof** [comment]
@kfirbreger thank you!

**Comment by ebuildy** [comment]
What about adding a ``pipenv exit`` to "close" the environment (so it can be documented).

**Comment by uranusjr** [comment]
I do not think it is technically possible though; this is, like the activate script, not something we can hook into.

**Comment by ebuildy** [comment]
Sorry, I was more thinking at a kind of alias: ``pipenv exit``  ==> ``exit``, because pipenv help gives the way to activate an env. but no how to exit (yes developers are ... lazy ^^)

**Comment by uranusjr** [comment]
@ebuildy Yeah, that would be very helpful, but as I said, it is not possible.

**Comment by clsource** [comment]
I think a good idea maybe a message will be enough.
That way is a reminder 👍 

 ```
$ pipenv exit
"if you need to exit the shell session. Use the exit command or press CTRL-d"
```

**Comment by kfirbreger** [comment]
@abekroenem The request was for `pipenv exit`, which is quite different than `exit`. The later being a shell command which works, I believe similar to `Ctrl-D`. The former is where the complexity is at.

**Comment by kfirbreger** [comment]
@Oxfos I am not an expert here, however:

1.  I think `exit` as the mechanism for exiting (and `Ctrl-d` for that matter) are not given much attention because that is the normal way to exit a shell. This is not unique to pipenv but works for any shell and iirc also screen, tux etc. Since you start a new shell, you exit it like any other shell, which is different than activating a virtualenv
2. I believe pipenv uses virtualenv, which is why deactivate works, but it does not actually exit the shell. I agree that if you are thinking in terms of venvs while working with pipenv this can get confisunbg. However you should not be thinking in venvs as, like mentioned in 1, you are not activating a virtualenv (which basically played around with pathing) but instead starts a new shell session with the correct pathing.

Again, I am not an expert and I might be wrong so take this all with a grain of salt

**Comment by uranusjr** [comment]
@kfirbreger Your observation is completely correct :)

**Comment by Bulletninja** [comment]
Typing `deactivate` worked for me.

**Comment by jongio** [comment]
`exit` worked for me
`deactivate` did not

would be great to get this documented or added as `pipenv exit` to save the google.

**Comment by kennethreitz** [comment]
it says it when you enter `pipenv shell`. read carefully :)

**Comment by jongio** [comment]
Hmm, I didn't for me.  

![image](https://user-images.githubusercontent.com/2163001/45234954-2e7e6100-b28c-11e8-8a73-717be1d62c0f.png)

**Comment by techalchemy** [comment]
This messaging seems to have been dropped somewhere when we realized we swapped out pew, @uranusjr wound up doing the final extraction of our patches and I assume we just overlooked this

**Comment by jongio** [comment]
Would also be good to add it to docs or help output as well.  That was the first place I went looking for it.

**Comment by kctong529** [comment]
It would be nice to also be included in The Hitchhiker's Guide to Python, where I came from. The use of pipenv above virtualenvwrapper was a bit unclear there.

**Comment by estebanborai** [comment]
@kfirbreger Thanks so much!
I was having trouble with this message:
```bash
$pipenv shell
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
```

**Comment by muzi131313** [comment]
![image](https://user-images.githubusercontent.com/2398149/48105455-9c3a0f80-e272-11e8-9606-807a59773e1f.png)
@estebanborai same with you too

**Comment by tekNorah** [comment]
If anyone gets stuck with this one, try exiting twice, then load the shell.

**Comment by maxwaiyaki** [comment]
> Typing `deactivate` worked for me.
This doesn't technically work. It seemingly "works" until you try to reactivate the virtual environment again and you get this response
 `Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.`

For an easy time, use `exit` or CTR + d to deactivate the virtual environment

**Comment by rjnfrazao** [comment]
Great to find this discussion, I am facing similar problem, I will try those suggestions mentioned above. I believe there is still room for improvement on the management of virtual environments using pipenv. When I think I know what is going on, suddenly I got lost where I am. 

I am starting to use Ubuntu via WSL, when I was creating my developing environment in Ubuntu,  I executed "pipenv install --dev" to install all packages, I believe this command has also created my virtual environment. But in the end of the installation, I didn't get any "(virtual environment)" displayed at the command line. When I run "pipenv shell" to spawn the virtual environment, the error below is raised. 

![virtual environment error](https://user-images.githubusercontent.com/40456619/58450763-3bf5b700-814b-11e9-95db-3cfade2be68c.jpg)

**Comment by jeyraof** [comment]
@rjnfrazao Have you tried `pipenv run python3 manage.py runserver` ?

**Comment by rjnfrazao** [comment]
No. Many hanks for the suggestion. I will try it later. I didn't mention my following problem, but really appreciate your attention to go beyond my expectations. I believe this command would sort it out :

![django error](https://user-images.githubusercontent.com/40456619/58452498-8c244780-8152-11e9-8030-1c17b8b9642e.jpg)

**Comment by maxwellmckinnon** [comment]
New user of pipenv, spent 20 minutes trying to figure this out. The very good --help is misleading as I was expecting the information on how to do this to be buried here.

Perhaps add a hint to the help, as well as the message when trying to activate a shell when one has already been activated.

Current
```
pipenv shell
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
```

Proposed
```
pipenv shell
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
`exit` or CTRL-d to exit the current subshell
```

**Comment by Abhishek5101** [comment]
Can anyone tell how do I re-activate it back again after I've exited out of the shell?

**Comment by frostming** [comment]
@Abhishek5101 `pipenv shell` of course

**Comment by Hug0Albert0** [comment]
Try with deactivate or pipenv exit

**Comment by zaidsaeed** [comment]
If you are using jupyter-notebook, you might want to look into adding your venv as a kernel to jupyter. This link might help: http://queirozf.com/entries/jupyter-kernels-how-to-add-change-remove

**Comment by elcoach290** [comment]
what is the difference between exit and deactivate?

**Comment by Kokolokoli** [comment]
> what is the difference between exit and deactivate?

checkout kfirbreger's [comment](https://github.com/pypa/pipenv/issues/84#issuecomment-414080326). Exit is universal to shells, deactivate is specific to virtualenv!

**Comment by thebjko** [comment]
Where should I type `exit`?
Even though I get `No virtualenv has been created for this project(/path/to/my/project/12_django_with_ajax) yet! Aborted!`. Then I type in 'pipenv shell` for `pipenv --venv`, I still get `Shell for $HOME/.local/share/virtualenvs/12_django_with_ajax-c5EHbKKP already activated.
No action taken to avoid nested environments.` for `pipenv shell`.

`pwd` : `/path/to/my/project/12_django_with_ajax`

**Comment by mahdipakravan-dev** [comment]
u can also use

> /user/bin/bash
