### ISSUE TITLE
Auto Python discovery on Windows

### ISSUE THREAD

**Issue by uranusjr** [kennethreitz/pipenv#841]
It has been mentioned multiple times that Pipenv cannot find find Python with a specific version on Windows. So you need to provide full path to python.exe, which works, but is less than convenient.

I think I have a solution to this. Newer version of the standard Python distribution comes with a py.exe launcher, that performs some registry magic to find the Python executable, outlined in [PEP 397](https://www.python.org/dev/peps/pep-0397/). In a gist:

* `py -2` finds the latest Python 2
* `py -3` finds the latest Python 3
* `py -3.6` finds Python 3.6

and so on.

I’m thinking about providing a Windows-specific implementation for `--two`, `--three`, and `--python <version>` based on the py launcher, but want to be sure this would be considered for merge before actually work on it. I’ll try to come up with a pull request if you think this is a good idea.

**Comment by kennethreitz** [comment]
Add all Pythons to your PATH, and all problems will be solved.

**Comment by erinxocon** [comment]
Can confirm, as long as all versions of python are in your PATH it will be able to detect them.
