### ISSUE TITLE
In pipfile `editable install` dependencies was strange.

### ISSUE THREAD

**Issue by aodag** [kennethreitz/pipenv#858]
I use setup.py and editable install with extras requires using pipenv.

```
pipenv install -e .[dev,testing]
```

that caused entries to dependency in pipfile.

```
[packages]
"-e .[dev,testing]" = "*"
```

Is that entries correct?

**Comment by kennethreitz** [comment]
this is valid, but not optimal

**Comment by erinxocon** [comment]
@aodag I'm curious if you have tried this in the most recent version of pipenv?
