### ISSUE TITLE
Why from 0.2.9 to 3.0.0?

### ISSUE THREAD

**Issue by ovalseven8** [kennethreitz/pipenv#86]
Hi,

just a question out of curiosity:
Is there a specific reason why from v0.2.9 to 3.0.0? :smiley:

That's it. :wink:

**Comment by jacebrowning** [comment]
Following [semantic versioning](http://semver.org/), a [feature was removed](https://github.com/kennethreitz/pipenv/blob/master/HISTORY.txt).

**Comment by lwm** [comment]
> MAJOR version when you make incompatible API changes,

http://semver.org/

Assuming ...

**Comment by jacebrowning** [comment]
My thoughts initially, but there is no 1.0 nor 2.0. I think it's a typo. 😄

**Comment by nateprewitt** [comment]
@jacebrowning it was a typo, it's [noted](https://github.com/kennethreitz/pipenv/blob/master/HISTORY.txt#L23) in the change log. You can't revert once you've released 3.0.0 because you'll eventually have overlap.

**Comment by kennethreitz** [comment]
It was indeed an irreversible typo :)
