### ISSUE TITLE
Pipenv breaks on Windows paths with spaces. 

### ISSUE THREAD

**Issue by micaiahparker** [kennethreitz/pipenv#865]
```bash
Micaiah Parker@COMPUTERNAME MINGW64 ~
$ cd project/

Micaiah Parker@COMPUTERNAME MINGW64 ~/project (master)
$ pipenv install --dev pytest
Installing pytest▒

Error:  An error occurred while installing pytest!
'C:\Users\Micaiah' is not recognized as an internal or external command,
operable program or batch file.
```

I noticed that `utils` does have a `get_windows_path`, but I couldn't find where it is being used.

**Comment by techalchemy** [comment]
Pipenv doesn’t actually break windows paths with spaces, it only breaks windows paths with spaces when using MINGW/MSYS/bash emulators. I think I know how to fix this but may not get to it today depending on how the day goes, but essentially we need to quadruple escape spaces or use the altsep to join paths

**Comment by micaiahparker** [comment]
When I got home I tried it from the default Command Prompt and still got the same issue

```
C:\Users\Micaiah Parker\project>pipenv install --dev pytest
Installing pytest…

Error:  An error occurred while installing pytest!
'C:\Users\Micaiah' is not recognized as an internal or external command,
operable program or batch file.
```
