### ISSUE TITLE
pipenv graph not equal pipenv lock

### ISSUE THREAD

**Issue by chinanf-boy** [kennethreitz/pipenv#869]
# First ，Thank you 
## pipenv is good 💯 

> the question is 

### when I
```
$ pipenv shell
$ (myproject-__PQqsBP) ➜ /my/Desktop/myproject git:(master) ✗ >

$ pip install pep8
pip8 success install

$ exit
$ /my/Desktop/myproject git:(master) ✗ >

$ pipenv graph
pep8==1.7.0
pep8 is in output information

$ pipenv lock
Pipfile.lock is created
but pep8 is not in lock file

```
So when i in `` pipenv shell ``, ``pip install something`` ,then`` exit``, 

``pipenv graph`` can catch the change, ``pipenv lock `` don't !

---

seem like
```
$ pipenv install pep8 --dev
```
># the command is ``ok``
>## pip8 success install
>## lock file will rewrite
>## pep8 in lock file 

### could ``$ pipenv graph `` show packages **in** ``lock file``

>## or something way to do with that

**Comment by techalchemy** [comment]
Well graph is a tool to show the state of the environment whereas the lockfile is a repository-hash-referenced output of the dependency resolution process for packages managed specifically by pipenv. So one is designed to show the relationship of all packages currently installed in the environment, and the other is meant to be a strict mapping of a resolved dependency tree of pipenv managed packages.

**Comment by chinanf-boy** [comment]
So, 
``graph`` and ``lock`` 
they are designed to be different 
Right，thanks~

**Comment by techalchemy** [comment]
Yes

**Comment by erinxocon** [comment]
@chinanf-boy Thanks for using pipenv!  @techalchemy Thanks for the support!
