### ISSUE TITLE
Question: should a requirements.txt live alongside a Pipfile file?

### ISSUE THREAD

**Issue by walterdolce** [kennethreitz/pipenv#877]
Do you think a `requirements.txt` file should live alongside a `Pipenv` file? 

I am aware `pipenv` can import dependencies from the `requirements.txt` file "_and forget about it_". I was thinking more of a scenario where people and/or tools wouldn't use `pipenv` on a machine but would still fallback to `pip`. Think "_legacy package users_" here, if that makes any sense.

Would you advise on doing whilst `pipenv` (hopefully) takes over the old ways of managing dependencies and virtual environments?

Thank you in advance.

**Comment by sobolevn** [comment]
I am using this hack. Sometimes `ipython`, `sphinx`, and other packages fail to be installed (with my [specific configuration](https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/Pipfile)).
So I store them in `requirements.txt`.

**Comment by nateprewitt** [comment]
@walterdolce, we leave those kinds of decisions up to project maintainers. Ideally, we would eventually be moved over to the pipfile spec and requirements.txt would be phased out. As we're in this transitionary state though, having both doesn't have any significant downsides. If you think you may have a population of users that won't be using Pipenv, then feel free to include it.

**Comment by nateprewitt** [comment]
Just make sure that they both stay in sync, otherwise you'll have issues.
