### ISSUE TITLE
Environment variable from .env available in `pipenv run python` but not in `pipenv shell`

### ISSUE THREAD

**Issue by tfeldmann** [kennethreitz/pipenv#879]
I've run into a strange error where a environment variable declared in a .env file is available in `pipenv run python` but not in `pipenv shell`. This only happens if the variable is named `DYLD_LIBRARY_PATH`.

I'm using macOs High Sierra, Python 3.6.3, pipenv 8.2.6.

Setup to reproduce:
```
$ mkdir envtest
$ cd envtest
$ pipenv --three
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/tf/.local/share/virtualenvs/envtest-S14rkyS9/bin/python3.6
Also creating executable in /Users/tf/.local/share/virtualenvs/envtest-S14rkyS9/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/tf/.local/share/virtualenvs/envtest-S14rkyS9
Creating a Pipfile for this project…
$ echo "DYLD_LIBRARY_PATH=Teststring" > .env
$ cat .env
DYLD_LIBRARY_PATH=Teststring
```

Now this works as expected:
```
$ pipenv run python
>>> import os; os.environ['DYLD_LIBRARY_PATH']
'Teststring'
```

And this does not:
```
$ pipenv shell
Loading .env environment variables…
Spawning environment shell (/bin/zsh). Use 'exit' to leave.
source /Users/tf/.local/share/virtualenvs/envtest-S14rkyS9/bin/activate
$ echo $DYLD_LIBRARY_PATH

$ python
>>> import os; os.environ['DYLD_LIBRARY_PATH']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tf/.local/share/virtualenvs/envtest-S14rkyS9/bin/../lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DYLD_LIBRARY_PATH'
```

**Comment by nateprewitt** [comment]
Thanks for the report, @tfeldmann. I've added this to the list of things to look into. Anyone else who feels compelled is free to pick this up.

**Comment by AlJohri** [comment]
@tfeldmann can you check if this is specific to the `DYLD_LIBRARY_PATH` variable or all variables?

**Comment by tfeldmann** [comment]
It only affects the `DYLD_LIBRARY_PATH` variable.

To test I added three more variables to the .env file to check whether it has something to do with the underscores:
```
SOMETHING=something
SOMETHING_1=something1
SOMETHING_1_2=something2
```
They are fully available in `$ pipenv run python` and `$ pipenv shell`. 
`DYLD_LIBRARY_PATH` is only available in `$ pipenv run python`.

**Comment by erinxocon** [comment]
I find it odd that all other variables work except that one.  Is there anything that effects that variable when spawning a subshell?  Anything in your .*rc file?  Going to close as I don't think this is a bug with pipenv.

**Comment by techalchemy** [comment]
Per @erinxocon I would suggest that you are possibly doing something in your profile or rc file.  If you have anything that happens with your environment variables that isn't explicitly specified as part of your login process only, you will run into these kinds of issues.  The alternative is to run your subshell in compatibility mode, which can help with some of these kinds of issues.

**Comment by straz** [comment]
I have experienced this same problem. I suspect MacOS is treating `DYLD_LIBRARY_PATH` specially. 

This seems like a [likely explanation](https://github.com/pyenv/pyenv-virtualenv/issues/112#issuecomment-155578318):
> It turns out that this is due to a new 'feature' in System Integrity Protection. It will delete DYLD_* variables when launching subprocesses.


Have you tried to reproduce this on your own system with `DYLD_LIBRARY_PATH`?  I can reproduce this on a fairly new MacOS laptop (cleanly installed Mac OS 10.14.6 with no profile or rc files.)
