### ISSUE TITLE
Current active VirtualEnv string is not being added to prompt on Windows

### ISSUE THREAD

**Issue by dougthor42** [kennethreitz/pipenv#880]
## Summary

The current active venv is not prepended to the Powershell prompt on Windows.

+ [Steps to Reproduce](#steps-to-reproduce)
+ [Additional Info](#additional-info)
    + [CMD](#cmd)
    + [Bash](#bash)
+ [Versions](#versions)
+ [Related Issues](#related-issues)

## Steps to Reproduce

1. Run `pipenv shell` in some Windows directory
2. See the shell prompt doesn't show the active venv.

    ```
    C:\project>pipenv shell
    Creating a virtualenv for this project…
    Using base prefix 'c:\\winpython35_x64\\python-3.5.2.amd64'
    New python executable in C:\WinPython35_x64\settings\.virtualenvs\notes-ZJAFqFjp\Scripts\python.exe
    Installing setuptools, pip, wheel...done.

    Virtualenv location: C:\WinPython35_x64\scripts\..\settings\.virtualenvs\notes-ZJAFqFjp
    Launching subshell in virtual environment. Type 'exit' to return.
    Windows PowerShell
    Copyright (C) 2016 Microsoft Corporation. All rights reserved.

    PS C:\project>
    ```

## Additional Info

I *think* this might be an issue with how powershell defines the prompt, but I haven't been able to determine for sure.

We all know how `venv` prepends the activated venv string to the prompt:

### CMD
```cmd
C:\project>.venv-project\Scripts\activate.bat
(.venv-project) C:\project>
```

### Bash
```bash
user@host:~/project$ . .venv-project/bin/activate
(.venv-project) user@host:~/project$
```

## Version Info

+ Windows 10 Pro, 10.0.15063 Build 15063
+ Python 3.5.2, 64-bit (via WinPython 3.5.2.2)
+ pip 9.0.1
+ pipenv 8.2.6

## Related issues

+ Fixing #781 would probably fix this issue.

**Comment by erinxocon** [comment]
@dougthor42 This is because on windows, `pipenv` uses `pew` by default to manage getting into and out of virtualenv's.  `pew` doesn't change the prompt for anyone, unix or windows user, it relies on having a properly configured shell that does it for you.  The activation.bat file does modify the prompt but as I said windows pipenv doesn't source that when `pipenv shell` is run.
