### ISSUE TITLE
Sync Pipfile changes with virtualenv

### ISSUE THREAD

**Issue by mrh1997** [kennethreitz/pipenv#884]
After modifiying Pipfile/Pipfile.lock (i.e. after a ```git checkout```) I would expect that there is a simple command, that syncs the changes back to the virtual environment. Ideally it is done automaticially when running ```pipenv shell```/```pipenv run```. At least I would expect ```pipenv check``` to warn if Pipfile does not matcb to the environment any more.

But neither did I find a command to sync the files with environment manually nor did run/shell sync them automaticially nor did ```check``` return errors.

What I did was:
- ```pipenv install <packagename>==<version1>```
- save Pipfile (i.e. by git commit)
- ```pipenv install <packagename>==<version2>```
- restore Pipfile (i.e. by git checkout)
- run any pipenv command => commands are done within an environment that has <version2> installed

**Comment by mimischi** [comment]
I'm not sure whether it's clear what you're exactly trying to do. Your "What I did" example is not very clear.

Were you trying to do this?
```bash
git checkout -b newbranch
pipenv install mynewpackage
git commit -am 'Added `mynewpackage` to environment'
git checkout master
```

Although you now have your old `Pipfile` (pre-installation of `mynewpackage` in the branch `newbranch`), that package is still installed in your current environment. You want to get rid of that, right?

Just use `pipenv update`. This will compare your environment against your `Pipfile`, purge all packages and reinstall everything.

**Comment by mrh1997** [comment]
One of the nice things of pipenv is, that every commit has its own virtualenv spec (in Pipfile.lock). My understanding is, that when I checkout a commit pipenv will guarantee that I work with exactly the same virtualenv I worked when I checked out this commit the last time (similarly to git, which guarantees that I work with exactly same codebase).

```pipenv update``` is not appropriate for this, as it does not create a virtualenv as described in 'Pipfile.lock', but it does exactly the opposite: it creates a 'Pipfile.lock' from a virtualenv (after upgrading the virtualenv to the newest packages).

In the meantime I found a operation which does exactly what I want:
```
pipenv install --ignore-pipfile
```

But this as far from intuitive.

Furthermore: ```pipenv shell``` or ```pipenv run``` guarantees that you have a virtualenv when being run the first time. Why does it not ensure this on *every* run (=check if the virtualenv is different from Pipfile.lock and restore it if not so)?

**Comment by nateprewitt** [comment]
So I'm not sure why the `--ignore-pipfile` would be required if you aren't making changes. `pipenv install` should be all you need to build the environment from the currently specified `Pipfile.lock`, *unless* you've actively modified your Pipfile. If that's the case, then you have changed your spec and we will update the lockfile unless explicitly instructed otherwise.

Checking out another branch should mean that your Pipfile and Pipfile.lock files are in sync and the lockfile will be used. That is, unless you did an install without locking and then committed the differing files.

**Comment by mrh1997** [comment]
Ahh. You are right. I do not need ```--ignore-pipfile```.

What you said about the behaviour of "install" is **really** interesting. This results in two new questions:
1. If I got you right I should do a ```pipenv install``` after any ```git checkout ...``` (at least if I am not sure if Pipfile.lock / Pipfile changed or not between the old and the new commit)?
2. When install automaticially updates ```Pipfile.lock```, what is ```pipenv lock``` about?

Unfortunately the docs are very vague about the exact behaviour of "install/uninstall/update/lock".

**Comment by erinxocon** [comment]
Hi @mrh1997!

1) Yes!  Doing a pipenv install after any checkout will update the Pipfile.lock appropriately.

2) You can create a pipfile manually and then lock it to get a file for production on another system.  Docker images could use this.  You may not want to run install to generate the lock file if you just need to send the lockfile to docker.
