### ISSUE TITLE
generate pip {dev-}requirements.txt from Pipfile.lock

### ISSUE THREAD

**Issue by dz0ny** [kennethreitz/pipenv#89]
Maybe add argument to pipenv lock --gen-pip-lockfiles(orsomething similiar) which would generate both files automatically after vendoring. This is a must of external tools, for building packages etc ...

Quick invoke task for those who stumble upon this
```
@task
def vendor(ctx):
    with io.open('Pipfile.lock') as f:
        data = json.load(f)
        prod = []
        dev = []
        for name, meta in data['develop'].items():
            dev.append('{}{}'.format(name, meta['version']))
        for name, meta in data['default'].items():
            prod.append('{}{}'.format(name, meta['version']))

    with io.open('requirements.txt', 'wt') as r:
        r.truncate(0)
        r.seek(0)
        r.write(u'\n'.join(sorted(prod)))
    with io.open('dev-requirements.txt', 'wt') as r:
        r.truncate(0)
        r.seek(0)
        r.write(u'\n'.join(sorted(dev)))
```

**Comment by kennethreitz** [comment]
we already have `$pip install --requirements` :)

**Comment by frankh** [comment]
@kennethreitz can you explain what you mean by this?

I get 

```
$ pip install --requirements

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --requirements
```

As far as I can tell there's no way to get a requirements.txt will ALL dependencies in (including dev)

**Comment by nateprewitt** [comment]
@frankh, this was a typo at the time, it should have been `pipenv install --requirements`. However, we've also changed this since then. The current version of pipenv will provide requirements with the command `pipenv lock --requirements`.

**Comment by nateprewitt** [comment]
In response to the second question, no, there isn't currently a way to divide requirements.txt dependencies between dev and default currently.

**Comment by AlecBenzer** [comment]
This is now possible: `pipenv lock --requirements` will produce a requirements file for the non-dev requirements and `pipenv lock --requirements --dev` will produce one for just the dev requirements.

**Comment by techalchemy** [comment]
@triplepoint see #1980
