### ISSUE TITLE
PIPENV_IGNORE_VIRTUALENVS and pipenv shell

### ISSUE THREAD

**Issue by admsteck** [kennethreitz/pipenv#894]
On my Windows 10 machine, I have PIPENV_IGNORE_VIRTUALENVS set to 1 and most pipenv commands seem to work using the .venv correctly... with the exception of `pipenv shell`

    Adam@ADAM-DESKTOP C:\Users\Adam\projects\project1
    > pipenv install
    Creating a virtualenv for this project…
    Using base prefix 'c:\\python36'
    New python executable in C:\Users\Adam\projects\project1\.venv\Scripts\python.exe
    Installing setuptools, pip, wheel...done.
    
    Virtualenv location: C:\Users\Adam\projects\project1\.venv
    Creating a Pipfile for this project…
    Pipfile.lock not found, creating…
    Locking [dev-packages] dependencies…
    Locking [packages] dependencies…
    Updated Pipfile.lock!
    Installing dependencies from Pipfile.lock…
      ================================ 0/0 — 00:00:00
    To activate this project's virtualenv, run the following:
     $ pipenv shell
    
    Adam@ADAM-DESKTOP C:\Users\Adam\projects\project1
    > pipenv --venv
    C:\Users\Adam\projects\project1\.venv
    
    Adam@ADAM-DESKTOP C:\Users\Adam\projects\project1
    > pipenv shell
    ERROR: Environment 'project1-z9NXaua1' does not exist. Create it with 'pew new project1-z9NXaua1'.

**Comment by nateprewitt** [comment]
Thanks for reporting this @admsteck! It looks like this is a bug. Could you confirm for me your version of pipenv by running pipenv --version?

Any contributors (or prospective contributors) feel free to start debugging this if you feel confident (or just adventurous).

**Comment by admsteck** [comment]
> pipenv --version
    pipenv, version 8.2.6

**Comment by techalchemy** [comment]
This was not fun, but is fixed.
