### ISSUE TITLE
fail to detect locale set in fish universal variables

### ISSUE THREAD

**Issue by feigaoxyz** [kennethreitz/pipenv#903]
`pipenv` does not respect `fish` shell's universal variables [^1] of `LC_ALL` and `LANG` values.

##### Describe you environment

1. OS Type: macOS 10.13
1. Python version: `$ python -V` 3.6.3
1. Pipenv version: `$ pipenv --version` 8.2.7

##### Expected result

`pipenv` should respect the `LANG` and `LC_ALL` values set by `set -U` as universal variables so not to complain `ValueError: unknown locale: UTF-8`

##### Actual result

When the locale (i.e. "en_US.UTF-8") is set by `set -U` as universal variables, `pipenv` can not extract the values when creating virtualenv (e.g. `pipenv shell`), and complaining `ValueError: unknown locale: UTF-8`.

Only if the same values were set inside `config.fish` by `set -gx` that the `pipenv` can recognise correctly.

##### Steps to replicate

Failure case (that should work)
```
$ set -U LANG "en_US.UTF-8"
$ set -U LC_ALL "en_US.UTF-8"
(re/start a new fish shell)
$ echo $LANG
en_GB.UTF-8
$ pipenv shell

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
⠋Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.6/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.6/site-packages/pew/pew.py", line 42, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.6/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

$ echo $LANG
en_GB.UTF-8
```

[^1] https://fishshell.com/docs/current/index.html#variables-universal

**Comment by techalchemy** [comment]
Hi, can you please provide the output of `env`, `locale -a`, and `locale`? 

Finally, please provide the content of your `~/.config/fish/config.fish` file.  I can help you resolve this, but it is not a bug in pipenv, it is a misconfiguration.

**Comment by feigaoxyz** [comment]
Case 1: 
start with new clean `fish`, zero `config.fish`, only `set -U`.
not working
https://gist.github.com/feigaoxyz/2651271ecfc91f3e90d0013d011fc1d0#file-set-u

Case 2:
Start with new clean `fish`, `set -gx` in `config.fish`
working
https://gist.github.com/feigaoxyz/2651271ecfc91f3e90d0013d011fc1d0#file-set-gx

**Comment by techalchemy** [comment]
So basically when you try to use set -U, you are encountering the following:

```console
$ set -U LANG "en_GB.UTF-8"
$ set -U LANG "en_GB.UTF-8"
```

(Same command twice? Typo I assume but confirmed in the rest of the outputs)

```console
$ env
...
LC_CTYPE=UTF-8
```

You'll note that this is the same as the error you are getting for `unknown locale`.

Finally, this should really be the last indicator that this is not a pipenv issue:

```console
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Your environment itself does not recognize your settings.  There is no way pipenv can.  The [fish documentation](http://fishshell.com/docs/2.0/#variables-locale) advises using `set -x` for these variables to configure your shell.  Hope that helps!

**Comment by feigaoxyz** [comment]
Thank you for your elaborate explanation. The duplicate `set -U` lines are errors when copy and paste. Looks like I am confused and misunderstood how `fish` treat `set -x` and `set -U` in environment.
