### ISSUE TITLE
Editable dependencies have a race condition when installing

### ISSUE THREAD

**Issue by jsatt** [kennethreitz/pipenv#919]
When installing editable dependencies, they must update `site-packages/easy-install.pth` with the path to the src of the repo checkout, for it to be able to be imported. By default pipenv installed all dependencies in blocks that run concurrently, but since multiple editable installs edit the same file this creates a race condition where multiple files may be trying to edit at the same time, resulting in some not being included.

In about 10 runs of `pipenv install` with the Pipfile below, 4 only included the second (variant) path, 2 only included the first (affect) path, and 4 included both paths. This can be worked around using `--sequential` at the cost of installs being much slower.

Ideally, pipenv could gather all editable dependencies and run them all sequentially at the end of the install process so as to not cause the race condition.

Python 2.7
Pipenv 8.2.7

Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
django-affect = {ref = "master", git = "https://github.com/jsatt/django-affect.git", editable = true}
django-variant = {ref = "master", git = "https://github.com/jsatt/django-variant.git", editable = true}
```

**Comment by erinxocon** [comment]
This is correct.  Feel free to submit a PR if you have a fix.  Otherwise I'm marking it for fixing!  Thanks for the report @jsatt
