### ISSUE TITLE
List outdated packages

### ISSUE THREAD

**Issue by levesquejf** [kennethreitz/pipenv#923]
It would be interesting to have a CLI option that would list the packages that are not at there latest release. Something similar to `npm outdated` (https://docs.npmjs.com/cli/outdated). This would help in the package update process.

**Comment by krismolendyke** [comment]
`pipenv` does support this, although not with that more clear sub-command syntax.  You currently need to `pipenv update --dry-run` to get a list of outdated packages.

**Comment by erinxocon** [comment]
Yes we didn't want to clutter up the api with a command that relies on another, etc....hence the flag.  Closing as will not for now.

**Comment by amir20** [comment]
@erinxocon With `update` being decorated. How should I go about doing this?

**Comment by uranusjr** [comment]
@amir20 See #1490 about an alternative workflow in the works.
