### ISSUE TITLE
Feature Request: API for use in setup.py

### ISSUE THREAD

**Issue by c17r** [kennethreitz/pipenv#928]
In an effort to reduce duplication it would be nice if setup.py could get the `install_requires` items from an API.

For a library where you want to be a little loose with the requirements (i.e. non-pinned)
```python
# setup.py
from pipenv.api import install_requirements

setup(
    install_requires=install_requirements()
)
```

For an application distributed via setup.py, a little tighter
```python
# setup.py
from pipenv.api import install_requirements

setup(
    install_requires=install_requirements(pinned=True)
)
```

**Comment by erinxocon** [comment]
This remindes me of npm and node a bit.  I think it's a feature we can consider but not one that will want implement soon.

**Comment by erinxocon** [comment]
closing with a tag for now so we can keep track of future enhancements.  Just trying to clear some of the issues out and sort them.

**Comment by tony** [comment]
Related: #209 #689

**Comment by flypenguin** [comment]
shoot, that would be *SO* nice :(
