### ISSUE TITLE
[request] 'pipenv install' option to install only dependencies

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#929]
Hello
It's common when writing a `Dockerfile` for  Python project to split installation on 2 Docker layers, the first one for dependencies and the second one for the module of the application being deployed, so that when developing, when a change on the code occurs, only the second layer is rebuilt by `docker build`, without having to reinstall all the dependencies.

It works pretty well and speed up development.

Here the kind of `Dockerfile` I write using `pipenv`:
```
...
# first layer
WORKDIR     /app
COPY        Pipfile* /app/
RUN         pipenv install --system

# second layer
COPY        . /app/
RUN         cd /app \
        &&  pip install .
```

I would prefer having a nice `pipenv install` option for the last command that simply do not try installing the dependency. Something like `pipen install --system --ignore-deps`. I have to use `pip install`, in this case it is faster that `pipenv install` because it does not try to install dependencies.

Also, do you think this can be documented on pipenv website? It can be very valuable for new developers

**Comment by erinxocon** [comment]
Hi @Stibbons!  You should be able to do just `pipenv --system` and then `pipenv install`.  I have not had a chance to test this in a docker, but I know you can do `pipenv --three` or `pipenv --two` to create a new virtualenv without installing the deps.

**Comment by Stibbons** [comment]
Is it possible to describe it in the readme?

**Comment by erinxocon** [comment]
I think so.  I'll make it as an enhancement!

**Comment by Stibbons** [comment]
If you want you can have a look at this [Dockerfile](https://github.com/Stibbons/dopplerr/blob/master/Dockerfile).
