### ISSUE TITLE
behave binary not reachable when defined in "dev-packages" but it is when in defined in "packages"

### ISSUE THREAD

**Issue by walterdolce** [kennethreitz/pipenv#932]
Hi,

I use [behave](https://github.com/behave/behave) as the [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development) framework for Python related projects and it usually ships with a binary which one can execute from the CLI.

Behave is usually a development dependency as it's not meant to live alongside the production code when this is then later packaged and shipped elsewhere. 

Given it's a development dependency, I had it defined under the `dev-packages` section. By doing so though, I wasn't able to reach the `behave` binary file and so run it from the CLI.

I was able to do that when adding `behave` under the `packages` section though.

Is this behaviour expected?

Thank you.

**Comment by techalchemy** [comment]
Things that you define in dev packages are only installed with `pipenv install --dev`.  When you run this command they are installed the same as any other package and should be accessible as normal

**Comment by erinxocon** [comment]
I'm gonna close this.  If you have any other questions @walterdolce let us know and we can reopen the issue!
