### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by rfleschenberg** [kennethreitz/pipenv#933]
It would be nice to have some development documentation, for example:

* how to setup a local development environment
* how to run the tests
* things to keep in mind when submitting a PR, if any

**Comment by rfleschenberg** [comment]
The docs can probably still use some improvement, e.g. we might want to tell people to rebase / squash their commits?

 Not sure if you prefer to keep this issue open or not, please feel free to close it if you want to :)

**Comment by nateprewitt** [comment]
If you want to catalog your ideas for enhancements, I personally don't have an issue leaving this open for a bit.
