### ISSUE TITLE
Miscolored terminal output

### ISSUE THREAD

**Issue by kathawala** [kennethreitz/pipenv#938]
https://github.com/kennethreitz/pipenv/blob/dba68e00f4734d07881d51173c03c27089dc41af/pipenv/cli.py#L985

The above line results in output like this (due to a small oversight in the `crayons` package):

![screen shot of miscolored terminal output](https://user-images.githubusercontent.com/1041056/29891516-56ed6280-8d99-11e7-8869-e09ea594bac8.png)

The issue is also mentioned here: kennethreitz/crayons#9

And I've written the fix for it here (it just needs to be reviewed and merged and the pypi package updated): kennethreitz/crayons/pull/13

Thanks everyone for all your hard work on this great software :)

**Comment by erinxocon** [comment]
Thanks for the report @kathawala!  We'll get the crayons package updated and the bug will be fixed!
