### ISSUE TITLE
Can 'run' support non-virtualenv commands?

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#94]
For local development with the Heroku CLI, I would like to be able to do something like this:

```
$ pipenv run heroku local
```

so that an external program (`heroku`) can use a program (`gunicorn`) from within the virtual environment. With `pipenv==3.1.9`, only commands in the virtual environment are allowed:

> The command was not found within the virtualenv!

-----

One possible workaround is:

```
$ . .venv/bin/activate && heroku local
```

but I'd like to avoid having to be gnostic of the location of the virtual environment.

**Comment by kennethreitz** [comment]
that's what `$ pipenv shell` is for :)

**Comment by jacebrowning** [comment]
That doesn't quite work as expected:

```
$ pipenv shell echo hello
Usage: pipenv shell [OPTIONS]

Error: Got unexpected extra arguments (echo hello)
```

nor:

```
$ pipenv shell && echo hello
Spawning environment shell (/bin/zsh).
source <myproject>/.venv/bin/activate
➜  myproject source <myproject>/.venv/bin/activate

# Where is my external command call?

(myproject)➜  
(myproject)➜  exit
hello

# Oh, there it is.
```
