### ISSUE TITLE
What is the correct way to install local file-backed distributions with pipenv?

### ISSUE THREAD

**Issue by kstohr** [kennethreitz/pipenv#945]
Trying to install a local file-backed distribution on Heroku. Previously, using standard pip/requirements.txt Heroku detected setup.py and installed the local package automatically. Now, using pipenv, with the same structure, it does not automatically detect setup.py for some reason.  Per the [Heroku docs](https://devcenter.heroku.com/articles/python-pip#local-file-backed-distributions) I need to provide a path to the local distribution to the requirements.txt. Or,  add `-e .` to provoke pip to run `python setup.py develop`  What is the pipenv equivalent?

Apologies if requiring local packages is addressed in the docs, but I didn't see it... 

Python 3.6.2
pipenv, version 8.2.7
Heroku 

Package installation using normal setup.py install command works fine both locally and on Heroku. 
`pipenv run setup.py install`
`heroku python setup.py install`

Top-level directory structure looks like this: 

├── Pipfile
├── Procfile
├── README.md
├── bin
├── resources
├── runtime.txt
├── setup.py
├── src
│   └── pblc
│       ├── __init__.py
│       ├── __main__.py
	  ├── (package files)
└── test

Tried: 
`pipenv install path/to/setup.py` 
which in my case is just 
`pipenv install setup.py`
Expected it to add the path to the Pipfile as a requirement 

Got the following traceback: 
```
(backend_app-Nxg7F8OH) katestohr:backend_app kate$ pipenv install setup.py
Installing setup.py…
Collecting setup.py

Error:  An error occurred while installing setup.py!
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py
```
Any guidance on the best way to require a local package in Pipfile...?

**Comment by kstohr** [comment]
apologies, seems related to:  [#939
](https://github.com/kennethreitz/pipenv/issues/939)
I did try: 
```

(backend_app-Nxg7F8OH) bash-3.2$ pipenv install -e ./setup.py
Installing -e ./setup.py…
⠦
Error:  An error occurred while installing -e ./setup.py!
./setup.py should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```
still no love. 
thanks for the amazing tool...

**Comment by kstohr** [comment]
...for those coming here also using heroku, temporarily resolving this by running 'python setup.py install &&  <command>' in the procfile

**Comment by techalchemy** [comment]
In the meantime if you use a `file://` URI that will also work, e.g. `pipenv install -e file:///home/user/thing/`

I will note that pipenv is not meant to be run from inside its own managed virtualenv (I noticed you have it sourced), or from inside its own subshell, so be aware that this may cause issues.

**Comment by kstohr** [comment]
@techalchemy Yep, thanks!  Exiting the virtual env first, plus tweaking the syntax [per "Editable Dependencies" in the docs](https://docs.pipenv.org/basics.html) to include the single quotes and a period worked. 

Here's the code. 

`pipenv install '-e .'`

(Note: **No ref to the file itself-- that's critical.** Referencing the file (as in `pipenv install 'e .setup.py`) will cause a type error.) 

(Note: this works if setup.py is in the top-level project dir. Not sure if pipenv searches recursively... )

**Comment by techalchemy** [comment]
No it doesn't.  The bug we have is currently to do with traversing local relative directories specifically so if you don't make any reference to a directory (i.e. there is no `/` in your `install` command) you should be ok.  For example, `pipenv install requests.whl` would work, but `pipenv install wheels/requests.whl` would not, nor would `pipenv install ../wheels/requests.whl`, nor would even `pipenv install ./requests.whl` assuming all were valid paths.  This will be fixed in the near future, I should have time to dig into it this weekend.

**Comment by kstohr** [comment]
Roger that.. thank you. Saw the 'file://' solution suggested above and in #939, but since the absolute path would be different in production not sure that would work in my use case... Thanks again.

**Comment by JohnLockwood** [comment]
Hi, I see this is closed, but was it ever fixed, or is it still expected to fail?

What I'm seeing in trying it is given an existing '../somepath' with a valid setup.py, doing 'python setup.py sdist' for example in somepath, then going out to a sibling folder somedir and doing 'pipenv install -e ../somepath', this always "succeeds", but 'pipenv run some_file_that_imports_somepath.py" gives "ModuleNotFoundError: No module named somepath".  (I've tried it with the package name the same as the folder name, or different).  pipenv graph in some environments shows "somepath", in others it shows "numpy==1.18.1", (a dependency of somepath), without showing somepath.  In all cases the Pipfile and the Pipfile.lock seem to have valid references to somepath, but no joy doing an actual import.

So is this still not expected to work and I should stop beating my head against the wall?
