### ISSUE TITLE
pip would like feedback on pip X

### ISSUE THREAD

**Issue by tdsmith** [kennethreitz/pipenv#946]
In a discussion about pip intentionally breaking external use of internal APIs in pip 10, continued from https://mail.python.org/pipermail/distutils-sig/2017-October/031683.html, this appeared:

From Paul Moore at https://mail.python.org/pipermail/distutils-sig/2017-October/031687.html:

> We've had little or no feedback on the tracker from
people using more complex internals, so our working assumption has
been there's very little that can't be handled via the CLI or existing
packages. Feedback so far from this mail hints that maybe we were
wrong, but it's still hard to know if it's one or two key projects, or
a whole range of people that we've yet to hear from. I'm pretty sure,
for example, that pipenv uses internals, either directly or via one of
their dependencies, but we've not seen any feedback from them yet.

Wanted to make sure y'all knew.

**Comment by nateprewitt** [comment]
I'm pretty sure we'd missed this. Thanks for bringing it to our attention @tdsmith. I'll get what we're depending on cataloged today and see if it's going to be an issue.

Fortunately we're vendorizing the parts we need so we should have breakages when 10 picks up traction but it'll be good to know what we'll need to change to upgrade.

**Comment by techalchemy** [comment]
@nateprewitt let me know if you need a hand

**Comment by nateprewitt** [comment]
So what I can find is as follows:

-------

* `parse_requirements` from `pip.req.req_file`:
  ```python
       parse_requirements(r, session=pip._vendor.requests)
  ```

* `DistributionNotFound` from `pip.exceptions`:
    ```python
        except (NoCandidateFound, DistributionNotFound, HTTPError)
    ```

* `parse_version` from `pip.index`:
     ```python
        pip.index.parse_version(version)
    ```

* `Command` from `pip.basecommand`:
    ```python
        class PipCommand(pip.basecommand.Command):
    ```

* `from_editable` from `pip.req.InstallRequirement`:
    ```python
        constraint = pip.req.InstallRequirement.from_editable(dep[len('-e '):])
    ```

I'm running out of time today but if anyone (@techalchemy?) feels like verifying that these haven't changed, or what their changes are in the pip 10 branch, that'd be awesome.

**Comment by techalchemy** [comment]
@nateprewitt @tdsmith so `parse_version` comes from this line:

```python
from pip._vendor.packaging.version import parse as parse_version
```

Which is (I'm guessing) untouched.  At a glance everything else in the codebase that Nate mentioned will play nicely as of whatever is in master right now, as long as the code that was moved to `_internal` is exposed similarly as it is now.

**Comment by nateprewitt** [comment]
Thanks @techalchemy! So it looks like we're in the clear for now. I'm going to close this out because I don't think we have anything actionable right now. We have this documented here now if we need to revisit later.
