### ISSUE TITLE
Package name can collide with top-level directory

### ISSUE THREAD

**Issue by shvenkat** [kennethreitz/pipenv#949]
## Description

A package specified in `Pipfile` is not installed if there is a top-level directory with the same name. If the directory is removed/renamed, the next `pipenv install` installs the package.

## Environment

1. OS Type: Mac OS 10.11.6
1. Python version: Python 3.6.0
1. Pipenv version: pipenv, version 8.2.7

## Steps to reproduce

```
mkdir /tmp/pipenv_test && cd /tmp/pipenv_test
echo -e "[requires]\npython_version = \"3.6\"\n\n[packages]\nrequests = \"*\"" > Pipfile
mkdir requests
PIPENV_VENV_IN_PROJECT=1 pipenv install
```
 
## Expected result

Package `requests` is installed into the virtual environment in `.venv`.

## Actual result

Package `requests` is *not* installed into the virtual environment in `.venv`. Deleting or renaming the directory `requests`, and running `PIPENV_VENV_IN_PROJECT=1 pipenv install` does result in the package `requests` being installed.

**Comment by nateprewitt** [comment]
Thanks for opening this @shvenkat! This is yet another data point on multiple issues we have open around local file installs.

@techalchemy, this suggests to me that we probably should require a `./` minimum when people are installing local packages (e.g. `./requests`). Otherwise, it's going to be difficult to disambiguate what they're referencing with the entry in the Pipfile.

**Comment by techalchemy** [comment]
@nateprewitt this would align with pip's behavior around directories (files can be implicitly resolved I think).  This is kind of an odd case and we had talked about attempting (and if we fail, doing the normal method) package installation if we find a directory match.  Maybe that is overcomplicating though, especially given that it does not replicate the current behavior of pip.

```console
 ◰³ tempenv-4d12275072fe  /t/new  unzip dls/tablib.zip
Archive:  dls/tablib.zip
4c300e65a50eef72b91fa1909c9f68679723955e
 ◰³ tempenv-4d12275072fe  /t/new  ls
dls  Pipfile  tablib
 ◰³ tempenv-4d12275072fe  /t/new  pip install tablib 
Collecting tablib
  Using cached tablib-0.12.1.tar.gz
Collecting odfpy (from tablib)
Collecting openpyxl (from tablib)
...
```

And you can see that it only resolves it if I put any explicit identifier that we are dealing with the local filesystem (`os.sep` is present or `./` is present), in which case pip (and in our case the Pipfile) can store a relative path but it resolves it to a `file://` URI before it does anything else:

```console
 ◰³ tempenv-4d12275072fe  /t/new  pip install tablib/
Processing ./tablib
  Requirement already satisfied (use --upgrade to upgrade): tablib==0.12.1 from file:///tmp/new/tablib in /home/hawk/.virtualenvs/tempenv-4d12275072fe/lib/python3.6/site-packages
```
