### ISSUE TITLE
Better error messages when files are missing

### ISSUE THREAD

**Issue by sametmax** [kennethreitz/pipenv#951]
#### Describe you environment

1. OS Type

Ubuntu

1. Python version: `$ python -V`

2.7

1. Pipenv version: `$ pipenv --version`

8.2

##### Expected result

When using pipenv -r requirements.txt, if one mistype the path to therequirements file, pipenv print a message stating it's unable to fine the file, print the absolute file path of the requirements file, and exit cleanly.

##### Actual result

Pipenv crashes with a cryptic message. 

```
  File "/home/user/.local/venvs/pipenv/local/lib/python2.7/site-packages/pipenv/cli.py", line 234, in import_requirements
    assert os.path.isfile(r)
AssertionError

```

##### Steps to replicate

Run:
```
pipenv install  -r requirements.txt 
```

But in the wrong directory.

Because pipenv can autodetect a pipfile somewhere in the file tree, it may not seem like you are making a mistake and that you are at the wrong place.

**Comment by nateprewitt** [comment]
Thanks for the request @sametmax. Oddly enough I just added this yesterday so it will be included in the next release.
