### ISSUE TITLE
Simple commands (such as autocompletion and --version) take a relatively long time

### ISSUE THREAD

**Issue by PolarPayne** [kennethreitz/pipenv#953]
Evaluating the autocomplete takes a very long time (closer to a second).
`eval "$(env _PIPENV_COMPLETE=source-bash pipenv)"`

Autocompletions also take closer to a second, as does running pretty much any command (no matter how simple).

I had to disable the autocompletion as it adds too much time to my terminals startup (actually I just took the output of the command to my .bashrc for now).

##### Describe you environment

1. Linux (Ubuntu 17.04)
1. Python version: Python 3.5.3
1. Pipenv version: pipenv, version 8.2.7

##### Expected result

These simple commands shouldn't take more than a few milliseconds.

##### Steps to replicate

```bash
$ time env _PIPENV_COMPLETE=source-bash pipenv --verbose

_pipenv_completion() {
    local IFS=$'\t'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _PIPENV_COMPLETE=complete-bash $1 ) )
    return 0
}

complete -F _pipenv_completion -o default pipenv

real    0m0,763s
user    0m0,708s
sys     0m0,056s
```

```bash
$ time pipenv --version
pipenv, version 8.2.7

real    0m0,646s
user    0m0,600s
sys     0m0,040s
```

**Comment by techalchemy** [comment]
I don't know much about completion but this seems slow. /cc  @erinxocon @nateprewitt

**Comment by nateprewitt** [comment]
@techalchemy it is slower than it needs to be. I fixed this a few months back and it looks like the big wave of changes in the last month reintroduced it.

It's just that the cli method has become so overloaded it does a lot of checks with every call that aren't necessary in cases like this.

We can fix it again but at best I think we'll be around 400ms just because of click and imports.

**Comment by techalchemy** [comment]
@nateprewitt Is there some way we can pare down imports or pre-compile autocompletion or something like that? Maybe that's just a massive refactor though?

**Comment by erinxocon** [comment]
@nateprewitt @techalchemy I think the cli might need a bit of a refactor, or at least the options each command can accept needs to be looked at.  

@PolarPayne Can I ask what kind of hardware you are running on?

**Comment by PolarPayne** [comment]
I'm running on a new Lenovo X1 Carbon, it has an SSD and is pretty fast (it's not a potato).

**Comment by erinxocon** [comment]
@PolarPayne Just curious.  I'll try and spin up a VM on my computer later with ubuntu and see if I experience any slowdowns.

**Comment by erinxocon** [comment]
On a bare metal ubuntu machine running an i7 770k, I'm getting a little under half a second.  A bit long...

**Comment by PolarPayne** [comment]
I tried changing `__main__.py` to:
```python
if __name__ == '__main__':
    import os

    pipenv_complete = os.environ.get("_PIPENV_COMPLETE")
    if pipenv_complete:
        import click_completion
        click_completion._shellcomplete(None, "pipenv")
    else:
        from .cli import cli
        cli()
```
But this only lowered the time by ~100ms.

The problem seems to be that in `__init__.py` on line 17, `cli` is getting imported and it's taking long. If that import is just moved inside the `if __name__ == '__main__':` block in there everything works _much_ faster (when you also have the change above).

If these are fine changes, I can make them into a pull request later today.

**Comment by PolarPayne** [comment]
I'll gladly also just refactor that autocomplete code to be lightning fast.

**Comment by erinxocon** [comment]
I don;t know as much about the autocomplete.  @nateprewitt or @kennethreitz?

**Comment by PolarPayne** [comment]
Anyways, the main problem is that `from .cli import cli` takes long (around 500ms on my machine).

**Comment by techalchemy** [comment]
@PolarPayne I'd be curious to see your changes here, I was messing around a bit today and did what you described and didn't have immediate success

**Comment by PolarPayne** [comment]
I'll put my changes (with a few other ideas related to this) into a pull request as soon as I have some time (next week?).

**Comment by tedmiston** [comment]
I think I'm experiencing the same issue.  If there's a clear opportunity to jump in to help, I'd be interested.

Having auto-completion on in my `.bashrc` makes launching a new shell lag quite a bit.

```bash
$ time eval "$(pipenv --completion)"

real	0m1.371s
user	0m1.224s
sys	0m0.134s
```

For comparison with the above results, here are my results with completion off:

```bash
$ time pipenv --version
pipenv, version 8.3.2

real	0m0.619s
user	0m0.535s
sys	0m0.075s
```

And with completion on:

```bash
$ time pipenv --version
pipenv, version 8.3.2

real	0m0.673s
user	0m0.573s
sys	0m0.089s
```

Versions:

```bash
$ python --version
Python 3.6.3
```

```bash
$ pipenv --version
pipenv, version 8.3.2
```

My hardware is a 2016 15" MBP with 16 GB of RAM running macOS 10.13.1.

**Comment by PolarPayne** [comment]
I just realized, after creating the pull request, that first of all it doesn't seem to work (I guess it messes up something).  
But that there is now the `--completion`, and it doesn't account for that.

If someone can give me a nudge in the right direction of what might be the correct way to fix this one so I could look into implementing it.

**Comment by kennethreitz** [comment]
known

**Comment by nachopro** [comment]
Hi! I'm a newcomer. I'm using `pipenv shell` and/or `pipes` as replacement of virtualenvwrapper's workon.

I'm facing some lags in my terminal:
a) pipenv autocompletion feels slow
b) exit from shell sometimes take ~2[s] to return to the prompt (or hangs until a keystroke)

Is this related to the second `BASH` instance or maybe `pipes` adds some overhead?

Thanks for your time.

OS: ArchLinux; Python 3.6.5; pipenv, version 2018.05.18
Hardware: i5-6300U CPU @ 2.40GHz; 16GB RAM; NVMe SSD

**Comment by tedmiston** [comment]
What is pipes?

**Comment by nachopro** [comment]
@tedmiston https://github.com/gtalarico/pipenv-pipes/

**Comment by techalchemy** [comment]
For sure the autocomplete is an issue, it's a constant battle. There are some suggestions in https://github.com/pypa/pipenv/issues/497 regarding that.  We are reworking our subshell implementation (in the next release) so that should bring some performance improvements as well.

**Comment by techalchemy** [comment]
@dimaqq it is already quite a challenge to stay at this time, but it is something I check regularly. As for alternate approaches, I’m not personally that focused on this beyond what I already do so if someone else has ideas they want to propose and implement I’d be happy do review then

**Comment by dimaqq** [comment]
@techalchemy yes I can imagine!

I wish there was a better protocol for shell autocomplete, akin to switch from cgi to fastcgi.

I suppose none stops a dedicated developer from spawning a long-lived background task from at first autocomplete and communicating with said task from then on. Though that sounds like a slippery slope -- what's to stop other tools from doing same, and then if someone has N shells and M tools, would they end up with N*M background processes that do nothing most of the time?

The good news is that this "lag" is cpu-bound, which means it will get twice shorter in 1.5 years or so :D 

Or perhaps someone writes an autocomplete-caching-proxy in let's say golang and solves this for us :)

**Comment by PolarPayne** [comment]
I think this a problem beyond just the autocompletion, the thing is that **all** commands have this around half a second startup time which is not really acceptable for a CLI tool like pipenv.

I'd love to contribute and help with this, but I'm guessing it's most likely a rather large change.

**Comment by techalchemy** [comment]
@PolarPayne I am in 100% agreement and it likely requires some substantial restructuring which I’m happy to review but the smaller the changes the better of course

**Comment by ktavabi** [comment]
> What is pipes?

@tedmiston  that's one 10-20 repos necessary for `pipenv` to supposedly do its thing.
