### ISSUE TITLE
pip version in venv is old, doesn't support --require-hashes

### ISSUE THREAD

**Issue by scott-burgess** [kennethreitz/pipenv#961]
When I create a new venv, the version of pip installed is really old (1.5.6). How do I update this?

OS Type: #CentOS Linux release 7.0.1406 (Core)
Python version: `$ python -V`: Python 2.7.5
Pipenv version: `$ pipenv --version` : pipenv, version 8.2.7

$ pipenv install
Creating a virtualenv for this project…
⠋New python executable in /home/user/.local/share/virtualenvs/pipenv-iAtZuLQ4/bin/python
Installing setuptools, pip...done.

Virtualenv location: /home/user/.local/share/virtualenvs/pipenv-iAtZuLQ4
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (c23e27)!                                                                         Installing dependencies from Pipfile.lock (c23e27)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell

$ pipenv run pip --version
pip 1.5.6 from /home/user/.local/share/virtualenvs/pipenv-iAtZuLQ4/lib/python2.7/site-packages (python 2.7)

##### Expected result

I expected that if the embedded pip version wasn't the latest, that I could somehow update it.

##### Actual result

The version of pip is still really old:

$ pipenv --update
All good!
$ pipenv run pip --version
pip 1.5.6 from /home/user/.local/share/virtualenvs/pipenv-iAtZuLQ4/lib/python2.7/site-packages (python 2.7)

This really really old pip version also means I can't install from the lock file, as it uses a pip flag that doesn't exist in this version:

$ pipenv install
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Installing dependencies from Pipfile.lock (b5ac99)…
An error occurred while installing enum34==1.1.6! Will try again.
An error occurred while installing cx-oracle==5.1.3! Will try again.
An error occurred while installing django-tables2==1.13.0! Will try again.
An error occurred while installing django==1.10.2! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:00
Installing initially–failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/4 — 00:00:00

Usage:
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --require-hashes

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/4 — 00:00:00

**Comment by erinxocon** [comment]
Hi @scott-burgess!  That's odd.  What is the version of pip installed with your system python(s)?  You should be able to run `pipenv run pip install --upgrade pip` to upgrade the virtualenvs pip to the latest version.

**Comment by scott-burgess** [comment]
@erinxocon Ahhh that's fixed the problem. 
I believe the default system version of pip was 1.5.6 before upgrading.
Running `pipenv run pip install --upgrade pip` has upgraded pip to 9.0.1.

Should that be something I'm required to do each time I install a virtual environment like this?

**Comment by erinxocon** [comment]
@scott-burgess No, if you upgrade your system python then it should pull from that.   You can do that with a `sudo pip install --upgrade pip` or without the sudo depending on where you have python installed.  Thanks for using pipenv!  Let me know if you have any other questions!

**Comment by techalchemy** [comment]
Note that if you use a pyenv installation of python you don’t have to touch your system install. I say this because I know RHEL derivatives can be finicky if you mess with system python but I suspect yum would upgrade this for you also.

**Comment by erinxocon** [comment]
@techalchemy same with macOS.  I use homebrew pythons instead of the default system ones.

**Comment by scott-burgess** [comment]
Thanks everyone, appreciate the help

**Comment by kitsunde** [comment]
Same issue, but instead caused by having an outdated system virtualenv (my system pip was fine). Solved with `sudo pip install virtualenv --upgrade`

**Comment by funkybob** [comment]
Just ran into a similar issue... and it seems my solution going forwards is:

`pipenv run pip install --upgrade pip setuptools`
