### ISSUE TITLE
Preventing caching

### ISSUE THREAD

**Issue by Midnighter** [kennethreitz/pipenv#964]
`pip` has the argument `--no-cache-dir` which comes in very handy when building small docker images. Does `pipenv` have a similar option?

**Comment by techalchemy** [comment]
See #451

**Comment by Midnighter** [comment]
Thanks for the pointer. I do get an error with either configuring it or using the environment variable but that's an issue to resolve upstream.

**Comment by thanatos** [comment]
The "pointer" appears to be to prevent _pip_ from caching, not pipenv. I'm trying to run pipenv in a production context where we don't have a writable disk, and AFAICT, _pipenv_, not pip, wants to call `mkdir("/.cache")` (`/` here is `$HOME`), which fails, as `/` isn't writable. (Nothing is.)

**Comment by fj-sanchez** [comment]
I'm facing this same issue... even with the right settings in `pip.conf` it still tries to create a cache folder in `/.cache` for which it doesn't have permissions and fails...
