### ISSUE TITLE
Split Pipfile parsing to independent library

### ISSUE THREAD

**Issue by Stibbons** [kennethreitz/pipenv#967]
Reference: #952.

Parsing à Pipfile using pipenv adds many dependencies (ex: `flake8.cli`).

Is it possible to split the parsing part from the pipenv CLI into a different package?

I would like to contribute to at least ReadTheDocs and PBR to help them support Pipfile, and that would help a lot if everyone use the same parser.

**Comment by techalchemy** [comment]
This seems like a good idea, although technically Pipfile parsing is handled by Toml via the Pipfile spec (see [pypa/pipfile](https://github.com/pypa/pipfile))

**Comment by erinxocon** [comment]
@Stibbons @techalchemy That repo will eventually contain a parser for Pipfiles once the pipfile spec settles a little.  Probably extract it from pipenv.
