### ISSUE TITLE
Omit the traceback with "pipenv requires an #egg fragment" error

### ISSUE THREAD

**Issue by pfmoore** [kennethreitz/pipenv#974]
When installing from a git URL (e.g. `pipenv install git+https://github.com/meraki-analytics/cassiopeia`) you get an error saying you need a `#egg` fragment with a full traceback.

It would be a lot more user friendly to report the problem with a proper error message and no traceback, as it's likely to be a common beginner issue (projects typically don't mention a `#egg` fragment when asking users to try the github version).

**Comment by erinxocon** [comment]
We do currently print out an error message.  From the utils.py file on line 564:

```python
        if req.name is None:
            raise ValueError('pipenv requires an #egg fragment for version controlled '
                             'dependencies. Please install remote dependency '
                             'in the form {0}#egg=<package-name>.'.format(req.uri))
```
The stack trace is just apart of raising the value error.

**Comment by pfmoore** [comment]
Hmm, OK. As I say, I find the traceback distracting and I'd prefer just to see the message. But it's your call.

Thanks for the explanation.

**Comment by erinxocon** [comment]
It is possible to raise a message instead of an error, but I think we want to raise the error in the case of automated build scripts that might need to catch that error if it's raised.

**Comment by nateprewitt** [comment]
@pfmoore I've cleaned it up in 6edfc89. I agree there's not a compelling reason to dump the stack trace here when we're nicely warning on other failures.
