### ISSUE TITLE
Recommeneded setup for Anaconda (Sublime Text plugin)

### ISSUE THREAD

**Issue by hyperknot** [kennethreitz/pipenv#978]
I've been searching the docs and Googling but I couldn't find anything related. 

Since you are also an Anaconda/ST3 user, can you describe the recommended setup for using it with Anaconda?

Previously, with virtualenvwrapper I've been putting `.anaconda` files in all my projects, with the following contents:

```
{
  "python_interpreter": "~/.virtualenvs/my_project/bin/python"
}
```

This worked perfectly, the only downside possibly being that it wouldn't work in multi-team projects where teammates would put the virtualenv folder in custom locations, or if someone would have used Windows.

Now with pipenv, the virtualenv has a random/hashed name, thus it's not even possible to just type it in a `.anaconda` file. How do you solve this?

I guess by the cleanest solution in the future would be to do a PR for Anaconda plugin to have built in support for Pipfiles, did anyone work on such?

**Comment by erinxocon** [comment]
@kennethreitz is the sublime text user!  I use visual studio code!

**Comment by hyperknot** [comment]
Sorry I thought I'm asking the question from him as this repo was under his name.

**Comment by techalchemy** [comment]
Open source projects have maintainers. Often they field issues as they come in. This is a fairly large and popular project and Kenneth is not answering most issues personally at the moment.

You will notice that Kenneth added sublime settings to `.gitignore`, and Erin added vscode settings. That’s because we don’t even use the same editors. We all put virtualenvs in different places and call them different things. At my company it works similarly- my editor lists the options in `$WORKON_HOME` when I go to the ‘select interpreter’ menu. Then I pick the relevant one. I am not aware of any place that mandates identical project or workspace editor settings so this works fine

**Comment by hyperknot** [comment]
What I'm trying to say is that pipenv/Pipfile hopefully has a bright future in being the standard Python dependency management format. The great thing with `package.json` is that although it's a stupid JSON format, not supporting comments, _every_ JS editor has built-in support for it.

I hope that the same will happen with Pipfile and all autocomplete supporting Python editors will have built-in support for it. AFAIK all what an editor needs it the location of the virtualenv / Python executable for each project.

So maybe it's as simple as running `pipenv --py` if a Pipfile is found, but I'm just learning this project, not knowing what is the most efficient way to get the location of the virtualenv.

**Comment by hyperknot** [comment]
So I'm looking into making a PR for Anaconda. Can you help what is the most efficient way of getting  `pipenv --py`. Do I need to start a Python interpreter in a subprocess?

**Comment by techalchemy** [comment]
@hyperknot `pipenv --venv` shows the path to the virtual environment that is being used by a project.  If you want to use the API to access it that is also doable:

```pycon
>>> from pipenv.project import Project
>>> p = Project()
>>> p.virtualenv_location
'/home/hawk/.virtualenvs/tempenv-425142417fd5'
```

**Comment by erinxocon** [comment]
Going to close this issue since @hyperknot is working on a plugin for sublime.  Issue
