### ISSUE TITLE
Weird behaviour with cwd

### ISSUE THREAD

**Issue by hyperknot** [kennethreitz/pipenv#980]
I'm working on an PR to add Pipfile support to Anaconda #978.

##### Describe you environment

1. OS Type: OS X 10.12.6
1. Python version: `$ python -V` Python 2.7.13
1. Pipenv version: `$ pipenv --version` pipenv, version 8.2.7

##### Expected result
The following snippet (run under Python 3) should return the virtualenv's path:

```
import subprocess
dirname = '/Users/user/dir1'
sp = subprocess.Popen(
    ['pipenv', '--venv'], cwd=dirname,
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
sp_out, sp_err = sp.communicate()
print('o:', repr(sp_out), 'e:', repr(sp_err), 'cwd:', repr(dirname))
```

```
o: b'/Users/user/.local/share/virtualenvs/dir1-pCEfX-1b\n' e: b'' cwd: '/Users/user/dir1'
```

##### Actual result
For one folder it works, for an other it doesn't. When it doesn't work it returns this:

```
o: b'' e: b'No virtualenv has been created for this project yet!\n' cwd: '/Users/user/dir2'
```

When running `pipenv --venv` from shell it works perfectly in both folders.

No `--verbose` for `--venv` :-(

##### Steps to replicate
No idea, what is the difference between the two folders. Copying the bad folder's pipfile to the good folder doesn't break the good folder. 

Can you tell me how can I diagnose what is the difference between the two folders?

**Comment by nateprewitt** [comment]
Can you add PIPENV_MAX_DEPTH=0 in your shell environment and try the bad directory again?

If that doesn't work, this may be related to #969.

**Comment by hyperknot** [comment]
@nateprewitt unfortunately I somehow fixed my bad directory, renamed it and run `pipenv install` again, so now the behaviour is consistent between the two. I really don't know what was the difference.

**Comment by nateprewitt** [comment]
@hyperknot that's unfortunate for debugging but good for your situation I guess. I'm closing this out then and feel free to follow up in #969 if you encounter it again.
