### ISSUE TITLE
Documentation links are broken on docs.pipenv.org

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#982]
Click on the first result on: https://docs.pipenv.org/search.html?q=sources&check_keywords=yes&area=default

<a href="https://cl.ly/1P3i1Y440E1b" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/1W1T213f1I2X0B2Z182s/Screen%20Shot%202017-10-27%20at%208.36.12%20AM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by nateprewitt** [comment]
Thanks for the heads up, @jacebrowning.

**Comment by jacebrowning** [comment]
Hmm... I am still seeing an error at: https://docs.pipenv.org/en/latest/

**Comment by nateprewitt** [comment]
@jacebrowning, so it looks like either Kenneth, Heroku, or something in our RTD configuration is binding all documentation to the root dir in our uri path. Our search system is still expecting `/en/latest` though which is causing issues.

It looks like only search is affected at this point though.

**Comment by erinxocon** [comment]
@nateprewitt This has been reported, but I think @kennethreitz needs to fix since it's his account

**Comment by erinxocon** [comment]
@nateprewitt Talked to Ken about this.  It's not an easy fix due to the way the site is hosted.  We came up with a less than ideal solution for now of hiding the search bar.  I'm gonna make the change to the css and close this issue for now.
