### ISSUE TITLE
Give error in `--py` output if no venv is installed

### ISSUE THREAD

**Issue by hyperknot** [kennethreitz/pipenv#985]
I'm working on adding Pipfile support for Sublime/Anaconda. Right now, I need to make two separate subprocess calls for pipenv, to check if `--venv` is installed and run `--py` afterwards.
https://github.com/hyperknot/anaconda/blob/76bfc9426de1d3f88afee31775a676d194737bf8/anaconda_lib/helpers.py#L265-L280

This is required, because if venv is not installed `--py` doesn't give any warning, just returns the system interpreter. I don't know if there is any reason behind this, or it's just a bug, bug I guess it's just a bug, as normally `--py` gives an error, like when run in a dir without Pipfile ("No project found!").

Can you change the behaviour of `--py` to give the same error as `--venv` gives?

**Comment by techalchemy** [comment]
But why are you using a subprocess to do this in the first place?

Also, this behaves precisely as described.  `--py` describes the python interpreter being used.  If it has never created a virtual environment, it will use the system interpreter.  This seems like a sensible default.  If you are using anaconda, and you can't find a virtual environment interpreter, wouldn't you also want to use the system interpreter?  I guess I'm not sure what you're trying to accomplish

**Comment by hyperknot** [comment]
We'd love not to use subprocess but pip installing pipenv is 20 MB, quite a huge dependency just for guessing the virtualenv's location. Is it possible to just include a few files or a few snippets from different files responsible for knowing the virtualenv's location?

Actually this might be quite important specification for Pipfile in general, I've opened an issue here:
https://github.com/pypa/pipfile/issues/88

Anaconda has a specific mechanism for falling back to the system interpreter or the one from settings if no environment is specified. It needs to know if `pipenv --venv` works or not.

I still don't understand the login behind this:
no pipfile -> error `No project found!`
pipfile, not installed -> system Python
pipfile, installed -> venv's Python

If it gives an error for no pipfile, why not give an error for an not installed pipfile?

**Comment by techalchemy** [comment]
Right but you are instead using a subprocess call to pipenv so you are assuming the user has already installed it. Why not try to import it and use the snippet I gave in your other issue, and catch the ImportError in case it fails?

**Comment by hyperknot** [comment]
But where do I import it from? By the official docs, pipenv will probably be installed into the system default Python 2. Sublime Text 3 has it's own totally isolated Python 3.3 interpreter, if I understand it right.

sys.executable: `python3` (no full path)

sys.path:
``
['/Applications/Sublime Text.app/Contents/MacOS', '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip', '/Users/user/Library/Application Support/Sublime Text 3/Lib/python3.3', '/Users/user/Library/Application Support/Sublime Text 3/Packages', '/Users/user/Library/Application Support/Sublime Text 3/Packages/pygments/all', '/Users/user/Library/Application Support/Sublime Text 3/Packages/markupsafe/all', '/Users/user/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3', '/Users/user/Library/Application Support/Sublime Text 3/Packages/python-jinja2/all', '/Users/user/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3']
```

**Comment by techalchemy** [comment]
What does `which python` in a subprocess in ST3 return? This is an interesting problem to solve

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hyperknot** [comment]
`which` returns `/usr/local/bin/python` even without `shell=True`, so that might be a starting point. But then it's not an option on Windows.

**Comment by techalchemy** [comment]
@hyperknot i was mainly curious about whether it was actually using its own version of python or not. I’m guessing it can if it needs to but will prefer system installs maybe. On windows there is a `where` command which does the same thing. 

To your actual question though, virtualenv names are derived from the name of the project path using a hashing algorithm in `pipenv.project.Project.virtualenv_name` unless the environment variable `PIPENV_VENV_IN_PROJECT` is set in which case it is stored in the project root in .venv.

**Comment by hyperknot** [comment]
@techalchemy it always uses it's own, internal Python version. 

Thanks for the note about the name, do you know the rules to determine the path? It's `~/.local/share/virtualenvs` in OS X, I guess it's the same in Linux as well? What is it for windows?

**Comment by erinxocon** [comment]
It should just be `%HOMEFOLDER%/.local` for all platforms.

**Comment by techalchemy** [comment]
@hyperknot it could be based on `$WORKON_HOME` if it's set, or it could be in `$HOME/.virtualenvs`, or it could be in `$HOME/.local`

**Comment by hyperknot** [comment]
@erinxocon @techalchemy do you mean + '/share'? It's definitely `$HOME/.local/share/virtualenvs` for me and even in the README of this project.

**Comment by techalchemy** [comment]
@hyperknot yeah that seems right

**Comment by erinxocon** [comment]
Closing this for cleanup!  Keep us posted on your ST2 integration progress @hyperknot!
