### ISSUE TITLE
Version Command

### ISSUE THREAD

**Issue by iddan** [kennethreitz/pipenv#995]
Add an NPM like `version` command for the pipenv cli that modifies the package's version according to the semver part
Here is a working gist: https://gist.github.com/iddan/22bbb835f7a862a314f995f5d66674eb
To integrate it the function should be registered in the cli.py and be tested.
Should I PR this? Is this a welcome feature?

**Comment by techalchemy** [comment]
Hey @iddan - thanks for the issue and thanks for asking! Pipenv isn't really a package manager, and people who use pipenv to build an environment are not reliably building installable python packages with a `setup.py`.  I would hazard to say that many of them are not

In either case I don't see pipenv ever seeking to modify the source code of its users' projects, so I'm going to go ahead and close this issue.  Thanks again!
