### ISSUE TITLE
Pipenv now has a homebrew formula

### ISSUE THREAD

**Issue by richardcooper** [kennethreitz/pipenv#996]
I've recently added a [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pipenv.rb) for Pipenv to [homebrew](https://brew.sh). So on a Mac with homebrew installed, pipenv can be installed via `brew install pipenv`

I'm mentioning this in case you want to add homebrew as a possible installation method  in the pipenv docs alongside Pipsi and Nix.

If you do want to include homebrew in your docs then I'm happy to write a pull request, but someone else might need to come up with the clever heading.

**Comment by anubhavdeka** [comment]
this looks so good. thank you from an inexperienced beginner!

**Comment by erinxocon** [comment]
@richardcooper could you submit a PR?

**Comment by nateprewitt** [comment]
Hey @richardcooper, thanks for taking the time to put this together! I've got a few outstanding questions if you've got a second to answer them before we merge #999 to get this advertised.

* What's the typical  release cycle for this? Does it sync with GitHub? If not what's the delay?
* Are all dependencies in the formula required? It looks like it's including some of the ones we vendor.

**Comment by nateprewitt** [comment]
@erinxocon @techalchemy disregard my previous qualms. Apparently we moved requests and pyflakes into our external dependencies recently.

My only issue is that this could get out of sync with our release cycle pretty quickly. The only thing left to consider is If you two are alright with triaging a potential uptick in issues from older versions of pipenv.

**Comment by erinxocon** [comment]
Would @richardcooper mind giving collaborator access to his brew repository?  I can help maintain it and keep it up to date.  I'm fine with an uptick in issues with old versions of pipenv, as long as we're keeping the brew versions up in pace with pipenv main releases so we can direct them to update.

**Comment by richardcooper** [comment]
> What's the typical release cycle for this? Does it sync with GitHub? If not what's the delay?

If you mean the cycle between the formula being committed in Homebrew/homebrew-core and that formula being available to end users? That's instant. It pulls directly from github as you said.

> Are all dependencies in the formula required? It looks like it's including some of the ones we vendor.

That part of the formula was created using [homebrew-pypi-poet](https://github.com/tdsmith/homebrew-pypi-poet). As far as I know all it does is collect all of the packages installed when you do `pip install pipenv` in a clean venv. If you think something is wrong here then I can dig deeper into what's happening. 

> Would @richardcooper mind giving collaborator access to his brew repository? I can help maintain it and keep it up to date.

I'm not sure that would help. To keep homebrew updated you need to submit pull-requests directly to the Homebrew/homebrew-core repo. Like i've done in Homebrew/homebrew-core#20053. There's nothing special about my fork of that repo. You could just as easily submit the PR from your own fork.

**Comment by techalchemy** [comment]
@richardcooper @nateprewitt @erinxocon my position is that I don’t own any apple things besides my phone so I can’t test this stuff. My main concern is maintenance overhead, as long as that isn’t an issue it’s fine with me. I just can’t offer much on this topic

**Comment by erinxocon** [comment]
@techalchemy @nateprewitt I have two apple macbooks and use brew quite frequently.  I think this is a good option for people not familiar with python but need it.  I have a friend who is working on her chemistry doctorates and she doesn't know much about programming but does use brew for a couple things like numpy, scipy, ipython, jupyter, etc.

@richardcooper I can help maintain this by submitting PR's, never actually submitted a brew package before!

**Comment by nateprewitt** [comment]
Alright, let's ship it then! 🚀

**Comment by sobolevn** [comment]
@richardcooper there is one major issue with this formula since it uses `2.7` as a default `python` for `pipenv`. See why that is an issue here: https://github.com/kennethreitz/pipenv/issues/994

Since I have switched to `python3` my user experience became way better. 
Is it possible to make `3` the default?

**Comment by erinxocon** [comment]
@sobolevn We should and I'm working on that now.

**Comment by richardcooper** [comment]
Not sure that a closed issue is the best place to have this discussion.

Is switching the dependency to `python3` the right longterm fix for this? Or is it just an easy workaround until bugs like #857 are fixed?

Shouldn't the goal be that pipenv works the same whichever (supported) version of python is used to run pipenv itself.
